### ISSUE TITLE
[Bug]: Chinese characters not showing correctly

### ISSUE THREAD

**Issue by HarryK4673** [Whisky-App/Whisky#1006]
### Description

Chinese characters are shown like a square. English and Japanese are fine.

### Steps to reproduce

Just install any apps in Chinese and open them. You will see a lot of squares.

### Expected behaviour

Characters are shown correctly.

### Logs

```bash
None
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Install `cjkfonts` in Winetricks.
