### ISSUE TITLE
[Bug]: Can't install Whisky

### ISSUE THREAD

**Issue by ecr228** [Whisky-App/Whisky#1019]
### Description

Each time I try to install a release of Whisky it downloads but when I go to open it it shows: You can’t open the application “Whisky-4” because this application is not supported on this Mac.

I'm running Sonoma 14.5

Tried earlier releases and it says the same thing

### Steps to reproduce

download completes, select it from downloads to open and get the error pop-up

### Expected behaviour

Is there something I'm missing as far as install/set-up requirements

### Logs

```bash
You can’t open the application “Whisky-4” because this application is not supported on this Mac.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You need an Apple Silicon Mac to use Whisky
