### ISSUE TITLE
[Feature]: game porting toolkit 2

### ISSUE THREAD

**Issue by clearluyy** [Whisky-App/Whisky#1021]
### Is your feature request related to a problem?

none

### Describe the solution you'd like

whether the newest game porting toolkit can be adopted to whisky

### Anything else?

If the answers is yes, do I need to upgrade to Sequoia

### Issue Language

- [X] Yes my issue is written in English

**Comment by Spidy123222** [comment]
> If you actually downloaded the kit and read the read me you would already have an answer to this.

doesn't really automatically download it for users but yeah the instructions does get the job done.

**Comment by clearluyy** [comment]
> If you actually downloaded the kit and read the read me you would already have an answer to this.
I’ve tried this, but in this way GPTK’s performance was worse than 1.1 version, so I think it's important that developers officially adapt to the latest GPTK

**Comment by recmo** [comment]
> read the read me

I read the readme in the repo (no answer), and followed the homebrew install commands (no readme). I also searched the repo. Where is this readme you talk about? Could you copy past the relevant part here?

**Comment by dalanmiller** [comment]
@dopeytree - your path is missing the backslash (for those who are confused why your copypasta didn't work). 

```
~/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/external/
```

**Comment by IsaacMarovitz** [comment]
Added in WhiskyWine 2.3.0
