### ISSUE TITLE
[Feature]: Support Game Porting Toolkit 2

### ISSUE THREAD

**Issue by jrapf32** [Whisky-App/Whisky#1028]
### Is your feature request related to a problem?

No not really.

### Describe the solution you'd like

Support it as an option and still let the user choose 1.0

### Anything else?

Nothing else

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
GPTK 2 is included in WhiskyWine 2.3.0+
