### ISSUE TITLE
[Bug]:  Hoyoplay launcher blank screen

### ISSUE THREAD

**Issue by Narukane** [Whisky-App/Whisky#1033]
### Description

Since Hoyoverse created a new launcher for the game and force all user to use it at June 17, the old launcher can no longer be used, and the new launcher shows a blank screen
![image](https://github.com/Whisky-App/Whisky/assets/36229848/9442da98-6a1b-4a15-9384-98befd487e49)

### Steps to reproduce

- Install hoyoplay launcher (https://hoyoplay.hoyoverse.com/)
- Open Hoyoplay launcher

### Expected behaviour

Should not blank and can see list of the games

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-06-17T10:05:45Z
macOS Version: 14.5.0

Bottle Name: Genshin
Bottle URL: /Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8/drive_c/Program Files/HoYoPlay/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8";
}

msync: warning: a previous shm file /wine-9d6ee-msync was not properly removed
msync: bootstrapped mach port on wine-9d6ee-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Narukane** [comment]
Here what i got if using ESYNC
```Whisky Version: 2.3.2
Date: 2024-06-17T10:15:47Z
macOS Version: 14.5.0

Bottle Name: Genshin
Bottle URL: /Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: esync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8/drive_c/Program Files/HoYoPlay/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEPREFIX = "/Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8";
}

01dc:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

**Comment by emaildd5** [comment]
<img width="1440" alt="Screenshot 2024-06-17 at 6 20 45 PM" src="https://github.com/Whisky-App/Whisky/assets/169367113/7af735ee-a3d4-41a1-8489-861eabecce18">


Having the same issue, but also this pop-up shows up.

**Comment by Nashh11-afk** [comment]
hey! have you been able to fix this? I'm facing the same issue, my discord is nash_gn
(contact me pls)

**Comment by Galox64** [comment]
This is something of a whiskey mistake, oh you just can't run it??

Could it be solved in some way?

**Comment by dinneo** [comment]
Same issue here

**Comment by shubs123-cloud** [comment]
same issue, how to fix it?

**Comment by Galox64** [comment]
So far there is no solution regarding using the new laucher in whiskey?

And if there is, what is the way to solve it?

**Comment by crcrworks** [comment]
Using GPTK directly, the log shows what is happening

This is the command
```
MTL_HUD_ENABLED=1 WINEESYNC=1 WINEPREFIX=~/my-game-prefix /usr/local/Cellar/game-porting-toolkit/{version}/bin/wine64 ~/Downloads/ZZZ-Installer.exe
```

This is the log
```
0424:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0424:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
~~
2024-07-07 21:22:54.275 wine64-preloader[16625:7831389] getMetalPluginClassForService: Failed to find bundle for accelerator bundle named: AGXMetalA12 errno: 0
```

Given the black screen, I think the metal error causes the problem.
Sry I have no idea to solve this.

**Comment by crcrworks** [comment]
I didn't realize that whiskey also can show log.
No need to use GPTK directly

**Comment by shubs123-cloud** [comment]
> I didn't realize that whiskey also can show log. No need to use GPTK directly

is there any solution?

**Comment by crcrworks** [comment]
> > I didn't realize that whiskey also can show log. No need to use GPTK directly
> 
> is there any solution?

No...
But if you really want to play such as ZZZ, Open HoYoPlay on windows, install games, and copy generated data to mac.
Then launch .exe file from whiskey, it works well.

This way don't support update because of no launcher, so need to do it again when update patch is released.

I am now waiting for ZZZ to be added to [yet-another-gamelauncher](https://github.com/yaagl/yet-another-anime-game-launcher).

**Comment by Kapy2003** [comment]
There's a fix you if you all are using bottles go to dependencies then search for web-view 2 its ms edge software which is a critical dependency which mihoyo needs for its apps.
Hope it helps all

**Comment by Nashh11-afk** [comment]
> There's a fix you if you all are using bottles go to dependencies then search for web-view 2 its ms edge software which is a critical dependency which mihoyo needs for its apps. Hope it helps all

Hey can you elaborate a little more? Can you send screenshots?

**Comment by Lzyct** [comment]
> There's a fix you if you all are using bottles go to dependencies then search for web-view 2 its ms edge software which is a critical dependency which mihoyo needs for its apps. Hope it helps all

Can you give more details for this step?

**Comment by LY1806620741** [comment]
I get the same problem, any one can solve it?

**Comment by tcapelle** [comment]
> > There's a fix you if you all are using bottles go to dependencies then search for web-view 2 its ms edge software which is a critical dependency which mihoyo needs for its apps. Hope it helps all
> 
> Hey can you elaborate a little more? Can you send screenshots?

I think it is related to installing webview-2.

https://github.com/Winetricks/winetricks/issues/1986

I managed to install webview on the bottle manually, but no able to run hoyo launcher =(

**Comment by reklic** [comment]
> Hey guys, I've figured out, that the only thing that is not working, is the visual presentation. All UI elements are there. I was able to launch Genshin by looking at pictures on the internet which show the placement of the UI elements in the launcher. And clicking at the right places of this blank screen.

can confirm. In addition, if you only have top bar, i.e. without main part (where to click buttons), then hold top bar (like you want to move the window) and shake it and it will appear xD

**Comment by Lzyct** [comment]
> > Hey guys, I've figured out, that the only thing that is not working, is the visual presentation. All UI elements are there. I was able to launch Genshin by looking at pictures on the internet which show the placement of the UI elements in the launcher. And clicking at the right places of this blank screen.
> 
> can confirm. In addition, if you only have top bar, i.e. without main part (where to click buttons), then hold top bar (like you want to move the window) and shake it and it will appear xD

Can you provide the screen record about it?

Thanks

**Comment by Nuanulla** [comment]
https://github.com/Gcenx/WineskinServer/issues/589

For people like me who would prefer to use Hoyoverse's own launcher, Wineskin currently works without any hard issues if you use the 23.7.1-3_rc1 engine.

I simply moved my Hoyoplay and "Genshin Impact game" files from my Whisky bottle to an equivalent C drive directory under my Wineskin wrapper. Just make sure to run vc2022 winetrick before running the game.

If your computer sleeps while the Hoyoplay launcher is updating a game, the window may appear frozen. Just right-click the menu bar icon to reveal the drop-down menu and the window should resume functioning. If that doesn't work, click "Open Main Window", grab the window via the macOS window bar, then shake the window around your desktop.

**Comment by tcapelle** [comment]
> <img alt="Screenshot 2024-07-30 at 9 13 02 AM" width="1276" src="https://private-user-images.githubusercontent.com/38226388/353470650-4a5a991f-b414-4029-a60f-4012faebcc8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTY4OTcsIm5iZiI6MTcyMjUxNjU5NywicGF0aCI6Ii8zODIyNjM4OC8zNTM0NzA2NTAtNGE1YTk5MWYtYjQxNC00MDI5LWE2MGYtNDAxMmZhZWJjYzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEyNDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMWI0NjQ5ODA5ZWM4M2RiNTc2N2U0ODljYjcyMDM4MjkyMGNjNjg0ZTJjY2MwNGRlNDJjNjc1ZGJiOTU5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vYXs2lCcRyNKvIrZjKqT66ECGpryuSycyn7sGOdYbm0">

I am here: 
<img width="797" alt="image" src="https://github.com/user-attachments/assets/a2a31c79-1eca-4f3a-92b4-963a4f8ae0c7">

what else do I need to setup to run the launcher?

**Comment by tcapelle** [comment]
How do I run this? double click?

**Comment by tcapelle** [comment]
nothing happens =(

**Comment by tcapelle** [comment]
What happened to the Issues section on the WineskinServer?!

**Comment by tcapelle** [comment]
Thanks @Gcenx =).

I think that maybe my issue is with the installation of winetricks? I get this log when hitting "Test Run":
HoYoPlay_install_ua_ac98304bb4c8.exe

**Comment by shubs123-cloud** [comment]
> Hey guys, I've figured out, that the only thing that is not working, is the visual presentation. All UI elements are there. I was able to launch Genshin by looking at pictures on the internet which show the placement of the UI elements in the launcher. And clicking at the right places of this blank screen.

hi, just tried it it might work but it opens zzz twitter when i open it, anyway to fix it to genshin?

**Comment by Moonshee5288** [comment]
im so confused so what do i have to do?

**Comment by Wallvon** [comment]
Hi,

I got HoYoPlay to launch after performing the following steps:
- Create a bottle, I just left it on the defaults (so Windows 10 64-bit)
- Install HoYoPlay, and close it when it launches (right-click the icon in the menu bar -> "Exit Program")
- Go to installed programs -> `launcher.exe` and click on the cog icon on the right
    - Add `--in-process-gpu` to the arguments (credits to the user that made [this Reddit comment](https://www.reddit.com/r/macgaming/comments/1dv41nz/comment/ljmuhu5/) for figuring this out)
- Run launcher.exe
![image](https://github.com/user-attachments/assets/9c5d9349-d2ad-4db6-be86-2531f640263f)

The game also runs just fine:
![image](https://github.com/user-attachments/assets/b75f811f-bd5e-4bb3-8f63-a2f5252ca037)

**Comment by Narukane** [comment]
> Hi,
> 
> I got HoYoPlay to launch after performing the following steps:
> 
> * Create a bottle, I just left it on the defaults (so Windows 10 64-bit)
> * Install HoYoPlay, and close it when it launches (right-click the icon in the menu bar -> "Exit Program")
> * Go to installed programs -> `launcher.exe` and click on the cog icon on the right
>   
>   * Add `--in-process-gpu` to the arguments (credits to the user that made [this Reddit comment](https://www.reddit.com/r/macgaming/comments/1dv41nz/comment/ljmuhu5/) for figuring this out)
> * Run launcher.exe
>   ![image](https://private-user-images.githubusercontent.com/42699143/364424562-9c5d9349-d2ad-4db6-be86-2531f640263f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjE4MDMsIm5iZiI6MTcyNzI2MTUwMywicGF0aCI6Ii80MjY5OTE0My8zNjQ0MjQ1NjItOWM1ZDkzNDktZDJhZC00ZGI2LWJlODYtMjUzMWY2NDAyNjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEwNTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZmFlNTU4YjhlZDdkMjQ4MWQ4YjYyNDUzZjJjOTJkNTA5OTRmN2EyNjhjYjQyYWU5MDVkZTVjOTRjYTU0YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NztWSQNu5DhQDu3iX_3he36j4261BvG1k4ImXOod284)
> 
> The game also runs just fine: ![image](https://private-user-images.githubusercontent.com/42699143/364438919-b75f811f-bd5e-4bb3-8f63-a2f5252ca037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjE4MDMsIm5iZiI6MTcyNzI2MTUwMywicGF0aCI6Ii80MjY5OTE0My8zNjQ0Mzg5MTktYjc1ZjgxMWYtYmQ1ZS00YmIzLThmNjMtYTJmNTI1MmNhMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEwNTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOWY3ZmU0MDMzNWQ1NTc1NzhlY2U2ZmIyZDBhMjRiYjVkOGJkZDk5YWQyNzcyYjMxNzhiNzI5MjFiMWQ5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ML-LjFW18wczuVzEcTbzMYN65IwRCDzprYFxiHbg4yY)

Confirmed, Thanks
This workaround solve the issue

**Comment by Moonshee5288** [comment]
when i try to do this i get an error message when trying to get hoyoplay to work on winebottler

###ERROR### Command '/Users/USER/Desktop/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126.
Task returned with status 1.

how do i fix this>

**Comment by Moonshee5288** [comment]
> Hi,
> 
> I got HoYoPlay to launch after performing the following steps:
> 
> * Create a bottle, I just left it on the defaults (so Windows 10 64-bit)
> * Install HoYoPlay, and close it when it launches (right-click the icon in the menu bar -> "Exit Program")
> * Go to installed programs -> `launcher.exe` and click on the cog icon on the right
>   
>   * Add `--in-process-gpu` to the arguments (credits to the user that made [this Reddit comment](https://www.reddit.com/r/macgaming/comments/1dv41nz/comment/ljmuhu5/) for figuring this out)
> * Run launcher.exe
>   ![image](https://github.com/user-attachments/assets/9c5d9349-d2ad-4db6-be86-2531f640263f)
> 
> The game also runs just fine: ![image](https://github.com/user-attachments/assets/b75f811f-bd5e-4bb3-8f63-a2f5252ca037)

when i try to do this i get an error message when trying to get hoyoplay to work on winebottler

###ERROR### Command '/Users/USER/Desktop/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126.
Task returned with status 1.

how do i fix this?

**Comment by Moonshee5288** [comment]
> > when i try to do this i get an error message when trying to get hoyoplay to work on winebottler
> > ###ERROR### Command '/Users/USER/Desktop/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126. Task returned with status 1.
> > how do i fix this?
> 
> [@Moonshee5288](https://github.com/Moonshee5288) we don’t provide help for WineBottler here, plus WineBottler has been dead since macOS Catalina released.

sorry i forgot about that, so in the step where you click installed programs and launcher.exe what if there is no launcher.exe
![Image](https://github.com/user-attachments/assets/15b30f26-09ab-43bc-a9af-ef025b568937)
