### ISSUE TITLE
[Bug]: Bitdefender Antivirus says it's a virus

### ISSUE THREAD

**Issue by ricardodolnl** [Whisky-App/Whisky#1042]
### Description

Bitdefender removes a file from wine because it says it's a virus. It this really true and if so can it run smoothly without that file?

Name: Gen:Variant.Tedy.606532
Location:  /Users/user/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/i386-windows/serialui.dll

### Steps to reproduce

-

### Expected behaviour

-

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-06-22T16:07:17Z
macOS Version: 14.5.0

Bottle Name: Bottle
Bottle URL: /Users/user/Library/Containers/com.isaacmarovitz.Whisky/Bottles/844BDF40-74C4-4EF5-AC01-5D9221CCE443

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: reg add HKCU\Control Panel\Desktop -v LogPixels -t REG_DWORD -d 0 -f

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/user/Library/Containers/com.isaacmarovitz.Whisky/Bottles/844BDF40-74C4-4EF5-AC01-5D9221CCE443";
}

msync: bootstrapped mach port on wine-80b3b84-msync.
msync: up and running.
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
reg: De bewerking is succesvol voltooid
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by nicholashennellfoley** [comment]
I also just noticed this.

**Comment by andrei-zgirvaci** [comment]
Same issue for me. Went ahead and reported those 2 files as false positives on Bitdefender website. Maybe it helps if more people report them too: https://www.bitdefender.com/consumer/support/answer/29358.

**Comment by andrei-zgirvaci** [comment]
Some update from my side regarding this issue. I have reported over the last 2 weeks a few threats found in https://data.getwhisky.app/Wine/Libraries.tar.gz as false positives to Bitdefender and it looks like they removed them as threats, at least for now. Hopefully it stays this way. :)

**Comment by IsaacMarovitz** [comment]
This has happened several times before. Occupational hazard of shipping executables that look a lot like but are not quite Windows system DLLs. I can't do much other than advise not using an antivirus on macOS at all, as it is often more of a hindrance than a help.

Related issues: #565, #465, #141. If you want more info, read those.
