### ISSUE TITLE
[Bug]: Whiskywine is not downloading 

### ISSUE THREAD

**Issue by mansees2** [Whisky-App/Whisky#1065]
### Description

 I really need help my internet is pretty good and i have ethernet and I tried installing different versions but the only one that works is the 2.02 but when I create a bottle nothing shows up I even tried rebooting my pc 3 times and the website for me doesn't work and I use chrome and it still says "zero kb out of zero kb installed"

### Steps to reproduce

![noe](https://github.com/user-attachments/assets/991e798e-7c44-460d-a91a-d6672b5cbdff)

### Expected behaviour

for the whiskywine to download

### Logs

```bash
no logs
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Antonio-Rinaldi** [comment]
i have the same issue

**Comment by SYUMJOBA** [comment]
Same issue

**Comment by mansees2** [comment]
i fixed it my wifi was not allowing it to download
