### ISSUE TITLE
[Bug]: Can not open Destiny 2

### ISSUE THREAD

**Issue by GalaxySciTech** [Whisky-App/Whisky#1068]
### Description

Can not open Destiny 2

### Steps to reproduce

Can not open Destiny 2

### Expected behaviour

Can not open Destiny 2

### Logs

```bash
12:50:55: 启动 BattlEye 服务...
12:50:58: 更新�?..
12:50:59: 无法初始�?BattlEye 服务�?.*hs�?
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by voltagex** [comment]
Well yes, BattleEye isn't going to allow being run under Wine.

**Comment by hahayupgit** [comment]
Due to the anti-cheat used by Destiny 2, WhiskyWine will be unable to run the game. Same reason the game doesn't work on Linux through Proton.
