### ISSUE TITLE
[Feature]: Please 🥺🙏 add AVX to Whisky. I was hoping you all could because of gptk 2. It would make it just a bit better.😁

### ISSUE THREAD

**Issue by topocode22** [Whisky-App/Whisky#1087]
### Is your feature request related to a problem?

I can't play certain games like Persona 5 Royal due to not having AVX support

### Describe the solution you'd like

Add AVX and a toggle to turn it on and off 

### Anything else?

Thank You!😁👍

### Issue Language

- [X] Yes my issue is written in English

**Comment by topocode22** [comment]
Thank You! So we can play Persona 5 Royal right?

**Comment by IsaacMarovitz** [comment]
AVX is dependent on having macOS 15 installed, not GPTK 2. Whisky has been updated to GPTK 2 for months.

**Comment by topocode22** [comment]
Ok, thanks for the clarification.

**Comment by Coulin9** [comment]
That's not true, there is a AVX patch for macOS 14

**Comment by topocode22** [comment]
how do you install it

**Comment by Coulin9** [comment]
[RosettaPatcher.zip](https://github.com/user-attachments/files/16782746/RosettaPatcher.zip)
Try this patch, I got this patch from reddit.

**Comment by topocode22** [comment]
Thanks, I'll check it out!
