### ISSUE TITLE
[Bug]: Whiskey Bottles dissapear upon creation.

### ISSUE THREAD

**Issue by Sarg9-11** [Whisky-App/Whisky#1112]
### Description

So I deleted some files relating to the Steam version for Windows 10, upon doing so Whiskey just makes all my bottles I create disappear. Even when redownloading Whiskey it doesn't prompt me to download the dependancies that it requires, just straight up opens the program.

I have downloaded the latest version that the Website provides.

My Mac is a MacBook Pro TouchBar.

Please don't give me technical jargon since I have no understanding around what coding literally does for any kind of app even if I had to save my life.

I'm also asking this for the people who are expriencing this issue who aren't able to understand technical luagague just as much as I.

### Steps to reproduce

Download Whiskey again - > Open up Whiskey -> Create bottle -> Bottle dissapears upon creation

### Expected behaviour

Bottles aren't accesible.

### Logs

```bash
2024-08-30T13/06/13Z.log
2024-08-30T13/11/53Z.log
2024-08-31T07/05/17Z.log
2024-08-31T07/06/33Z.log
2024-08-31T07/06/50Z.log
2024-08-31T09/29/37Z.log
2024-08-31T09/32/58Z.log
2024-08-31T09/33/01Z.log
2024-08-31T09/33/37Z.log
2024-08-31T09/33/45Z.log
2024-08-31T09/33/54Z.log
2024-08-31T09/34/38Z.log
2024-08-31T09/36/39Z.log
2024-08-31T09/38/32Z.log
2024-08-31T09/38/48Z.log
2024-08-31T13/39/12Z.log
2024-08-31T13/40/51Z.log
2024-08-31T13/41/17Z.log
2024-08-31T13/45/09Z.log
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by jcommaret** [comment]
@Sarg9-11 : can you update to the latest version, I had the same issue and things just work great now (using sequoia)

**Comment by Sarg9-11** [comment]
It works now, thanks! :D.

**Comment by jcommaret** [comment]
@Sarg9-11 : so maybe you can close the bug ;)
