### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Lancelotbronner** [Whisky-App/Whisky#1116]
### Is your feature request related to a problem?

The app seems dead, it doesn't seem to be updating to GPTK 2 and I'm having issues with both Steam and Epic Games, preventing me from installing and playing games on these platforms.

### Describe the solution you'd like

What needs to be done, how can people help?

### Anything else?

Can we have a statement on your intentions?

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Whisky has been updated to GPTK 2 since the day it came out. I've been mostly focusing on other projects but Whisky is certainly not dead. If there is a clear upgrade or a breaking change, I will work to keep the app up-to-date.

**Comment by Lancelotbronner** [comment]
Could wine be updated? Manually running the latest version of wine fixes the issue with Steam but Epic Games is still broken

**Comment by Lancelotbronner** [comment]
Fait enough, thank you for your time and answers!
