### ISSUE TITLE
[Bug]: Sequoia + Satisfactory: computer reboots on game launch

### ISSUE THREAD

**Issue by canada-geek** [Whisky-App/Whisky#1126]
### Description

Recenly updated to macOS 15.0 (Sequoia).
MacBook Pro 16-inch, 2021 (Apple M1 Max chipset)

Also upgraded Whisky to latest.

Game worked OK before upgrade (occasionally the computer would reboot, but this was a relatively rare occurrence...call it once every ~4-6 hours of game play).

NOTE: The dropdown/pickers below don't let me choose the actual version I'm using...
- Whisky version: 2.3.3 (41)
- macOS version: 15.0 (Sequoia)

Also note: I did not see any statement on the repo indicating whether Sequoia was supported or not; but given that I see commits from yesterday, presumably we're either there or almost there.

### Steps to reproduce

1. Launch steam
2. Attempt to launch Satisfactory
3. At the welcome screen, click on "Continue" to resume existing game
4. Watch the computer reboot.

### Expected behaviour

Game should play and the computer should not reboot.

### Logs

```bash
Whisky Version: 2.3.3
Date: 2024-09-20T21:19:05Z
macOS Version: 15.0.0

Bottle Name: Winnie
Bottle URL: /Users/<userid>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/A34380D5-92AA-4E7D-803F-5BC2449AB343

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/<userid>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/A34380D5-92AA-4E7D-803F-5BC2449AB343/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/<userid>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/A34380D5-92AA-4E7D-803F-5BC2449AB343";
}

msync: bootstrapped mach port on wine-3ef68dd-msync.
msync: up and running.
.dylib
  Reason: tried: '/Users/<userid>/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/libssh.4.dylib' (no such file), '/usr/local/lib/libssh.4.dylib' (no such file), '/usr/lib/libssh.4.dylib' (no such file, not in dyld cache)Library not loaded: @loader_path/libdav1d.7.dylib
  Referenced from: <3DAB6F40-87F5-3578-BE53-45D3C6D37C34> /Users/<userid>/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/libavcodec.61.dylib
  Reason: tried: '/Users/<userid>/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/libdav1d.7.dylib' (no such file), '/usr/local/lib/libdav1d.7.dylib' (no such file), '/usr/lib/libdav1d.7.dylib' (no such file, not in dyld cache)
02ec:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Sep 2024 04:46:00 UTC"
00c4:err:ole:com_get_class_object class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
012c:err:ole:com_get_class_object class {aa509086-5ca9-4c25-8f95-589d3c07b48a} not registered
0108:err:wininet:HTTP_ParseRfc1123Date unexpected time zone L"UTC"
0108:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Sep 2024 01:33:00 UTC"
0108:err:wininet:HTTP_ParseDate unexpected date format L"Thu, 19 Sep 2024 01:33:00 UTC"
```

### What version of Whisky are you using?

2.3.3 (41) [manually edited]

### What version of macOS are you using?

Sequoia (macOS 15) [manually edited]

### Issue Language

- [X] Yes my issue is written in English

**Comment by MacGamer2020** [comment]
I have this same problem.  I was able to play Satisfactory quite well prior to Sequoia but now it reboots almost every time I try to play the game.  I also have a 16" 2021 M1 Max.

**Comment by kahnakha** [comment]
Yesterday I experienced a system reboot while trying to launch Ori And The Blind Forest from steam.
When you first launch it after the initial download/install is complete you are getting the loading screen, and immediately after it, the system rebooted.
I also submitted a but report about an unexpected system reboot, so something's definitely off.

**Comment by IsaacMarovitz** [comment]
I am assuming that some kernel panic is occurring, which should not usually be triggerable by userspace applications. Either way, I can't diagnose this further without a full kernel panic log.

**Comment by canada-geek** [comment]
@IsaacMarovitz thanks for your response. I'm happy to reproduce the issue and collect what you need.

Can you:
- let me know how best to generate the information after the crash?
- where can I place the information? I'd rather not attach it here, as there might be some PII in it

Thanks.

**Comment by brunoformagio** [comment]
The kernel panic issues stopped here after I installed an app to manually control the cooling fans, as they weren't switching on properly during gameplay (Cyberpunk 2077). I suspected in my case it might be a heating issue, but I'm not sure yet if that was just a coincidence... I have the same machine as you (MBP M1 MAX 2021, 16-inch)

**Comment by kahnakha** [comment]
> The kernel panic issues stopped here after I installed an app to manually control the cooling fans, as they weren't switching on properly during gameplay (Cyberpunk 2077). I suspected in my case it might be a heating issue, but I'm not sure yet if that was just a coincidence... I have the same machine as you (MBP M1 MAX 2021, 16-inch)

I disagree, simply because the reboots are not every time you launch a particular game for example, but there's a high chance that it will reboot, and then on the next attempt it runs fine for hours, and hours of gameplay without any issues.
It's just the initial 1st boot of the game that sometimes triggers a kernel panic, and the system reboot, but after the reboot, if you go ahead and try again, I guarantee that the game will start just fine and you can play for hours without any issues.
At least that's what my experience have been, so this kind of defeats the statement of a high temperature as the cause of it.

**Comment by canada-geek** [comment]
@kahnakha, my experience was a bit different... I tried launching Satisfactory 3 times in a row, and it rebooted every time.

The computer wasn't 'hot' at the time (at all), I had just pulled it out of my bag after it sat there asleep overnight. 3 consecutive attempts to launch Satisfactory triggered a reboot of the computer.

In the interest of being more precise, here is exactly what I experienced (all 3 times):

1. Launch `Whisky` -> `Steam` -> `Satisfactory` (whichever need launching)
2. The 'Satisfactory' pre-load banner appears, then the "Coffee Stain" logo
3. The loading screen appears where we can select 'new game' or 'continue'
4. I chose 'continue' all 3 times
5. Watch the show as the computer goes completely dark and reboots

I haven't tried starting a new game, to see if it's somehow related to my save game. I plan to try again today, so I'll try that to see if it's any better.

FOLKS: If any of you know what I should collect for a kernel panic, let me know. I did find some files under `/Library/Logs/DiagnosticReports`, but I'm not sure which (and how many) I should collect. Also, since these will contain PII, I can't just post them here, I need to know where to supply them.

**Comment by canada-geek** [comment]
OK so of course you show your TV to the person doing repairs, and it works perfectly :-)

I just tried again (with 'continue'), this time the game launched.

There _was_ an update to Whisky (which still shows 2.3.3 (41), though I _did_ do an install; so I have no idea what the new version should be). Not sure whether that's what did it.

In any case I'll use it for a while, let's see how it goes.

**Comment by kahnakha** [comment]
> OK so of course you show your TV to the person doing repairs, and it works perfectly :-)
> 
> I just tried again (with 'continue'), this time the game launched.
> 
> There _was_ an update to Whisky (which still shows 2.3.3 (41), though I _did_ do an install; so I have no idea what the new version should be). Not sure whether that's what did it.
> 
> In any case I'll use it for a while, let's see how it goes.

Well of course that it will work when you try to show your mechanic how something in your car was not working for the past few months...
Anyways, glad to see that it works now without some weird workarounds with other 3rd party apps, etc. etc.
Kernel panic logs can be collected if you go to your "System Settings>General>System Report..." then scroll down a bit to find the "Logs" and look for "Kernel log" for a type of logs you want to see, there you will find the exact path and logs needed, if such logs or any other logs are requested.

**Comment by IsaacMarovitz** [comment]
Thermals has nothing to do with it. It's an issue with D3DM's caching. There is no way to resolve this without Apple fixing their broken driver.

**Comment by Yrouel** [comment]
Commenting to report that on Sequoia 15.0.1 (MacBook Air M2 8GB) with Whisky 2.3.3 and Satisfactory 1.0.0.3 Build 368883 it just works, no crashes or reboots.
I'm adding this also as a reference for anyone else that, like me, might find this bug report and be discouraged to try like I initially was.

The performances on my specific machine aren't great but at least for now it's playable using low settings.


I used this guide as a general reference to install it https://gamefeedbacks.com/satisfactory-how-to-play-on-mac-full-guide/

And since the driver warning was annoying I looked for a way to disable it and I found this https://www.reddit.com/r/SatisfactoryGame/comments/1fechhb/guide_how_to_disable_the_warning_known_issues/

I'm attaching screenshots of both just in case the links die or something:

![Image](https://github.com/user-attachments/assets/5a7c2643-4e2a-44b1-9cea-19bd217b2749)
![Image](https://github.com/user-attachments/assets/d80e5b14-adfe-431b-a6f4-159fd7aaceca)

**Comment by asweet** [comment]
@Yrouel The file that that guide asks you to install and run is all kinds of suspicious. If you downloaded and ran it I would delete and re-create your bottle if I were you, to be safe.

**Comment by Yrouel** [comment]
> [@Yrouel](https://github.com/Yrouel) The file that that guide asks you to install and run is all kinds of suspicious. If you downloaded and ran it I would delete and re-create your bottle if I were you, to be safe.

It links directly to Microsoft. It's not malware

**Comment by asweet** [comment]
Ah, my mistake, I was a bit overzealous when looking at the microsoftonline domain that it redirects to which _looked_ like a common phishing domain and I didn't dig deeper than that. Sorry about that.

**Comment by canada-geek** [comment]
FWIW I'm still getting reboot with macOS 15.0.1. Whisky seems to be at latest.

**Comment by MacGamer2020** [comment]
> FWIW I'm still getting reboot with macOS 15.0.1. Whisky seems to be at latest.

I managed to get it to work ocassionally if I set all the graphics options to the bare minimum, however, it still reboots about 40% of the time.  Sure wish we could figure out what Apple's new OS did to break this.

**Comment by rmejia64** [comment]
> > FWIW I'm still getting reboot with macOS 15.0.1. Whisky seems to be at latest.
> 
> I managed to get it to work ocassionally if I set all the graphics options to the bare minimum, however, it still reboots about 40% of the time.  Sure wish we could figure out what Apple's new OS did to break this. 

I'm experiencing the same problem right now with The Forest. This is the error message and call stack:

panic(cpu 3 caller 0xfffffe003110c410): DCP PANIC - IOMFB int_handler_gated: failure: axi_rd_err [0x40300034]
 - iomfb_driver(11)
IOMFB int_handler_gated: failure: axi_rd_err [0x40300034]

Faulting task  11 Call Stack: 0x00000000002648f0 0x00000000002642b0 0x00000000002640c4 0x0000000000267494 0x00000000004ee204 0x00000000004ed760 0x00000000003d8534 0x0000000000264d44 0x0000000000257f14
RTKit Task List:
   name                    | pri     | stack use | status     | resource | warning
 0 rtk_background          | 007     |   848/2048  | SEMWAIT    | 0xca86f0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

 1 rtk_ep_work             | 057     |   920/2048  | SEMWAIT    | 0xca4d00 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

 2 log_tx                  | 007     |   544/2048  | SEMWAIT    | 0xc91840 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

 3 log_flush               | 015     |   160/4096  | SEMWAIT    | 0xc90be0 | 
      0x0000000000257380 0x00000000002583d4 0x000000000026ba28 0x0000000000257f14

 4 tracekit_work           | 007     |   576/4096  | SEMWAIT    | 0xc8e710 | 
      0x00000000002573c8 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

 5 power                   | 000     |  1472/65536 | RUNNABLE   | 0xa73d38 | 
      0x0000000000257380 0x0000000000263ab0 0x0000000000263794 0x0000000000257f14

 6 Terminator              | 015     |   240/2048  | SEMWAIT    | 0xc7cde0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

 7 main                    | 015     |  6848/40960 | SEMWAIT    | 0xc78170 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000251c54 0x000000000025403c

 8 dcpexpert               | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c011f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

 9 AFKMailboxEndpoint      | 015     |   688/16368 | SEMWAIT    | 0xffffffff0c031f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

10 rtkitpmgr               | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c051f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

11 iomfb_driver            | 016     |  5872/16384 | RUNNABLE   | 0 | [Faulting task]

12 iomfb_low               | 009     |  2720/16384 | SEMWAIT    | 0xffffffff410e09f0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

13 iomfb_driver_low        | 008     |   240/16384 | SEMWAIT    | 0xffffffff410d1470 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

14 iomfb_cdfd              | 014     |  3808/16384 | SEMWAIT    | 0xffffffff410b2a70 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

15 iomfb_dcp_disp_serv     | 016     |  1104/4096  | SEMWAIT    | 0xffffffff410a2410 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

16 iomfb_ap_link           | 016     |  1296/4096  | SEMWAIT    | 0xffffffff410a0f00 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

17 iomfb_ap_caller_0       | 016     |   240/512   | SEMWAIT    | 0xffffffff4109f9c0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

18 iomfb_ap_caller_1       | 016     |   240/512   | SEMWAIT    | 0xffffffff4109f390 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

19 iomfb_ap_caller_2       | 016     |   240/512   | SEMWAIT    | 0xffffffff4109ed20 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

20 iomfb_ap_caller_3       | 016     |   240/512   | SEMWAIT    | 0xffffffff4109e6a0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

21 iomfb_ap_callee_0       | 016     |  6992/16384 | SEMWAIT    | 0xffffffff4109e030 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

22 iomfb_ap_callee_1       | 016     |  5632/16384 | SEMWAIT    | 0xffffffff41099bb0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

23 iomfb_ap_callee_2       | 016     |  1616/16384 | SEMWAIT    | 0xffffffff41095740 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

24 iomfb_ap_callee_3       | 016     |   240/16384 | SEMWAIT    | 0xffffffff410912c0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

25 iosurface_tracker_timer | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c071f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

26 AUCWorkLoop             | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c091f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

27 auc_dcp_queue           | 015     |   288/16368 | WAITING    | 0xffffffff41081c20 | 
      0x0000000000257380 0x0000000000257b6c 0x0000000000256928 0x0000000000265400 0x0000000000386f24 0x0000000000257f14

28 dcpav                   | 015     |   688/16368 | SEMWAIT    | 0xffffffff0c0d1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

29 cpCapsThread            | 015     |  1360/16368 | SEMWAIT    | 0xffffffff0c0f1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

30 additionThread          | 015     |  5648/16368 | SEMWAIT    | 0xffffffff0c111f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

31 removalThread           | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c131f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

32 dcpav-power-epic        | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c151f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

33 config                  | 015     |   736/16368 | WAITING    | 0xffffffff4105aed0 | 
      0x0000000000257380 0x0000000000257b6c 0x0000000000256928 0x0000000000265400 0x0000000000386f24 0x0000000000257f14

34 dcpdptx-hdcp-interface  | 015     |  3008/16368 | SEMWAIT    | 0xffffffff0c191f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

35 dcpav-controller-epic   | 015     |  3008/16368 | SEMWAIT    | 0xffffffff0c1b1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

36 dcpdp-controller-epic   | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c1d1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

37 sac-controller          | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c1f1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

38 setDisplayAsync         | 015     |  3824/16368 | SEMWAIT    | 0xffffffff0c211f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

39 dcpav-sac-epic          | 015     |  3008/16368 | SEMWAIT    | 0xffffffff0c231f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

40 endpointWL              | 015     |  2248/8192  | SEMWAIT    | 0xffffffff41030980 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

41 md-manager              | 015     |  3664/8192  | SEMWAIT    | 0xffffffff4102d8e0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

42 AFKGlobalDispatch       | 015     |  8912/16368 | WAITING    | 0xffffffff410256b0 | 
      0x0000000000257380 0x0000000000257b6c 0x0000000000256928 0x0000000000265400 0x0000000000386f24 0x0000000000257f14

43 iomfb_alss              | 016     |   240/4096  | SEMWAIT    | 0xffffffff40fae260 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

44 iomfb_pdc               | 008     |   240/4096  | SEMWAIT    | 0xffffffff40f9c740 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

45 iomfb_backlight         | 016     |   240/4096  | SEMWAIT    | 0xffffffff40f7a940 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

46 iomfb_mailbox           | 018     |  1312/16384 | SEMWAIT    | 0xffffffff40f78bc0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

47 iomfb_mailbox_async     | 018     |  1568/16384 | SEMWAIT    | 0xffffffff40f69520 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

48 iomfb_mailbox           | 018     |   384/16384 | SEMWAIT    | 0xffffffff40f646a0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

49 iomfb_mailbox_async     | 018     |   240/16384 | SEMWAIT    | 0xffffffff40f55000 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

50 iomfb_reg_stream        | 016     |   240/4096  | SEMWAIT    | 0xffffffff40f4c360 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

51 iomfb_mailbox           | 018     |   240/16384 | SEMWAIT    | 0xffffffff40f46640 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

52 iomfb_mailbox_async     | 018     |   240/16384 | SEMWAIT    | 0xffffffff40f370b0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

53 iomfb_video_async       | 016     |  2080/16384 | SEMWAIT    | 0xffffffff40f27420 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

54 iomfb_video_if          | 016     |   240/4096  | SEMWAIT    | 0xffffffff40f22e30 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

55 iomfb_video_async       | 016     |   240/16384 | SEMWAIT    | 0xffffffff40f16450 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

56 iomfb_video_if_stub     | 016     |   240/4096  | SEMWAIT    | 0xffffffff40f11eb0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

57 cp                      | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c271f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

58 dcpav-device-epic       | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c291f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

59 poweroff                | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c2b1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

60 cpsrc                   | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c2d1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

61 restartIntfc            | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c2f1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

62 hdmiErrorMonitor        | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c311f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

63 hdmiErrorInject         | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c331f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

64 sinkCount               | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c351f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

65 linkStatus              | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c371f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

66 cpIrq                   | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c391f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

67 dpIrq                   | 015     |  5136/16368 | SEMWAIT    | 0xffffffff0c3b1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

68 edpAggressor            | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c3d1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

69 cdiAggressor            | 015     |  2048/16368 | SEMWAIT    | 0xffffffff0c3f1f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

70 dcpav-service-epic      | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c411f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

71 dcpdp-service-epic      | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c431f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

72 dcpdp-device-epic       | 015     |  3008/16368 | SEMWAIT    | 0xffffffff0c451f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

73 aup                     | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c471f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

74 dcpav-video-interface-e | 015     |   240/16368 | SEMWAIT    | 0xffffffff0c491f40 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

75 termination             | 015     |  1392/16368 | WAITING    | 0xffffffff40ea1c48 | 
      0x0000000000257380 0x0000000000257b6c 0x0000000000256928 0x0000000000265400 0x0000000000386f24 0x0000000000257f14

76 iomfb_ca                | 016     |  1648/4096  | SEMWAIT    | 0xffffffff40e687b0 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

77 iomfb_mailbox           | 018     |   656/16384 | SEMWAIT    | 0xffffffff40e67430 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

78 iomfb_mailbox_async     | 018     |  6400/16384 | SEMWAIT    | 0xffffffff40e58050 | 
      0x0000000000257380 0x00000000002583d4 0x0000000000264cd8 0x0000000000257f14

**Comment by Yrouel** [comment]
I don't know what to tell you, I've been playing regularly since my post and I only had one instance where my machine suddenly rebooted.

My only real issues are occasional lockups (I have to force quit it) and a general slow down over time especially after any kind of reload/respawn or as I explore new areas.
The latter might also be related to my machine simply struggling to keep up since it has been worsening the more stuff I build.

I do play with everything set to potato quality but for performance reasons

**Comment by MacGamer2020** [comment]
Same here.  Starting Steam and the game via Whisky and modifying all graphics settings to minimum, I can play the game off and on about 50% of the time.  Sometimes, I’ve had the game running for over 4 hours but then there are times it won’t start after multiple attempts to load.  This is really frustrating and it started only after MacOS Sequoia.
