### ISSUE TITLE
[Bug]: Audio mutes sometimes when trying to switch macOS Sound Output

### ISSUE THREAD

**Issue by mattmaniak** [Whisky-App/Whisky#1127]
### Description

It is impossible to change a macOS Sound Output for an application running using Whisky. There are three cases possible after changing this when a Wine process is already running:

1. Sound mutes for the Wine process after Sound Output change.
  1a. Sound is restored when switching to the Sound Output that was active on the Wine process launch.
2. Wine process uses the same Sound Output even if it is changed.

This makes changing audio output when playing impossible. The only possible way to change Sound Output is to turn off and on an application under Whisky.

I am using macOS 15.0 and Whisky 2.3.2 but it also happened for macOS 14.6.1.

### Steps to reproduce

Tested with using DX11 version The Witcher 3 Wild Hunt GOTY v4.0.4 without any Whisky and Winetricks adjustments. It is reproducible with any other title most likely as I have noticed it in about dozen of them.

1. Check what Sound Output is already set:
![Screenshot 2024-09-21 at 17 20 01](https://github.com/user-attachments/assets/f22b5cfa-322b-4495-91ad-1a463e25c111)
2. Launch the app using Whisky.
3. Sound occurs on the selected Sound Output.
4. Change the Sound Output.
5. Audio is muted or audio is played using the same audio device even if it is different in the Sound Output settings.
6. Revert back to the originally selected Sound Output.
7. Audio is back on the original device if it was missing on point number five.

### Expected behaviour

It is expected for audio devices to be changed accordingly to the Sound Output settings and play sound respectively to the settings without muting audio completely.

### Logs

Currently my Xcode 16.0 prevents me from listing process. As soon as I will connect to the process successfully I will provide logs.

```bash
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sequoia (macOS 15)

### Issue Language

- [X] Yes my issue is written in English

**Comment by aske-cph** [comment]
Yes this an issue especially annoying when playing with earphones which must be many people?

I wonder if you can somehow change via terminal while running.

Also this has been an issue for a year, it's not just in Seqouia.

**Comment by IsaacMarovitz** [comment]
This is a long-standing issue in Wine that currently does not have a solution. As far as I know, it still occurs in the latest version of CrossOver and has no fix in upstream Wine either.

**Comment by Trebor-Huang** [comment]
Is there a link that documents this in wine?
