### ISSUE TITLE
[Bug]: whisky is using user's computer for mining bitcoin

### ISSUE THREAD

**Issue by lazywhite** [Whisky-App/Whisky#1141]
### Description

# whisky using much more CPU/GPU resource than CrossOver
## 1. game run with whisky
![image](https://github.com/user-attachments/assets/ee919f68-7efe-4437-9959-ec773b2f8c0a)
## 2. same game run with crossover
![image](https://github.com/user-attachments/assets/57257a73-60e6-4201-9eaa-3036aa9608ea)

## question
There is a "Whisky" process takes 100% cpu, if we force quit it , running game won't get affected at all, so this 
process is totally unnecessary
## conclusion
Whisky is using user's computer to do BitCoin Mining!!!

### Steps to reproduce

run same game with crossover and whisky

### Expected behaviour

Whisky CPU/GPU resource consumed should be  same level with CrossOver

### Logs

```bash
no...
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Not even gonna give this a reasonable or technical response because this is an unreasonable report. Please don't even joke about Whisky being malware.

**Comment by Crd5** [comment]
> There is a "Whisky" process takes 100% cpu

Do you know that 100% CPU load means full usage of 1 core? And GPU is used for mining, not CPU.
# Whisky is open source.
If you do not trust @IsaacMarovitz 's builds, you can build Whisky yourself.

**Comment by lazywhite** [comment]
why "whisky" process is taking 100% cpu? fix this bug please.
