### ISSUE TITLE
[Bug]: No controllers found after today's WhiskyWine update

### ISSUE THREAD

**Issue by Mateus109** [Whisky-App/Whisky#1142]
### Description

No game controllers found after today's WhiskyWine update
<img width="612" alt="image" src="https://github.com/user-attachments/assets/c260f1e0-4e46-4e78-b7ca-248862110b77">

### Steps to reproduce

Check 'Game Controllers' in Control Panel

### Expected behaviour

Controllers are automatically found and work perfectly

### Logs

```bash
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
```

### What version of Whisky are you using?

2.3.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I made a mistake in the new build script. It should be resolved when the latest version deploys shortly.

**Comment by Mateus109** [comment]
Thanks. Does "shortly" mean days or hours?

**Comment by SubhranilRaha** [comment]
How do you reinstall whiskywine?
