### ISSUE TITLE
Just doesn't open on M3 Sequoia

### ISSUE THREAD

**Issue by cauediademi** [Whisky-App/Whisky#1165]
### Description

I open the app, it crashes and I receive the error log below.

This is when i run it from terminal:

cd Whisky.app/Contents/MacOS/
./Whisky
[1]    47776 segmentation fault  ./Whisky

The option wasn't available, but my SO is Sequoia 15 beta 2

### Steps to reproduce

I run the application, app crashes.

### Expected behaviour

App insta crashes on new version, it shouldn't

### Logs

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Whisky [47115]
Path:                  /Applications/Whisky.app/Contents/MacOS/Whisky
Identifier:            com.isaacmarovitz.Whisky
Version:               2.3.3 (41)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-09 22:12:41.0337 -0300
OS Version:            macOS 15.0 (24A5298h)
Report Version:        12
Anonymous UUID:        027BF917-F246-3628-2416-A12E201C843E

Time Awake Since Boot: 98000 seconds

System Integrity Protection: disabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000004
Exception Codes:       0x0000000000000001, 0x0000000000000004

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [47115]

VM Region Info: 0x4 is not in any region.  Bytes before following region: 4364599292
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104268000-10436c000    [ 1040K] r-x/r-x SM=COW  /Applications/Whisky.app/Contents/MacOS/Whisky

Thread 0:
0   libsystem_kernel.dylib        	       0x1807b3574 getattrlistbulk + 8
1   CoreServicesInternal          	       0x18421d24c NextEntryFromParent + 184
2   CoreServicesInternal          	       0x18421cfdc DirEnumRead + 412
3   CoreServicesInternal          	       0x18421cdbc _GetDirectoryURLs(_CFURLEnumerator*) + 1276
4   CoreServicesInternal          	       0x18421b5a8 _URLEnumeratorGetNextURL + 140
5   Foundation                    	       0x181a74b94 -[NSFileManager contentsOfDirectoryAtURL:includingPropertiesForKeys:options:error:] + 208
6   Whisky                        	       0x1042e8c48 0x104268000 + 527432
7   Whisky                        	       0x1042e3b50 0x104268000 + 506704
8   Whisky                        	       0x104279e21 0x104268000 + 73249
9   Whisky                        	       0x1042ea055 0x104268000 + 532565
10  Whisky                        	       0x104279e21 0x104268000 + 73249
11  libswift_Concurrency.dylib    	       0x25a1628a5 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 1 Crashed:
0   Whisky                        	       0x10433269c 0x104268000 + 829084
1   Whisky                        	       0x104272d05 0x104268000 + 44293
2   Whisky                        	       0x1042788e5 0x104268000 + 67813
3   Whisky                        	       0x1042e77f9 0x104268000 + 522233
4   Whisky                        	       0x104279e21 0x104268000 + 73249
5   libswift_Concurrency.dylib    	       0x25a1628a5 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 2:
0   libsystem_pthread.dylib       	       0x1807ec0e8 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1807ec0e8 start_wqthread + 0

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1807afe34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1807c25d0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1807b89d8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x1807b017c mach_msg + 24
4   CoreFoundation                	       0x1808da73c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1808d8fec __CFRunLoopRun + 1212
6   CoreFoundation                	       0x1808d84b4 CFRunLoopRunSpecific + 572
7   AppKit                        	       0x1845414f8 _NSEventThread + 148
8   libsystem_pthread.dylib       	       0x1807f12e4 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x1807ec0fc thread_start + 8

Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000001   x1: 0x0000000000000001   x2: 0x000000018049bb68   x3: 0x00000001e663fa28
    x4: 0x0000000000000002   x5: 0x0000000000000012   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x1ebc6fb64eea00ec  x10: 0x000000016bc1ed6c  x11: 0x0000000000000001
   x12: 0x0000000000000007  x13: 0x000000015d81a260  x14: 0x01000001e57e1939  x15: 0x00000001e57e1938
   x16: 0xdafc0001e663fa28  x17: 0x0000000000000238  x18: 0x0000000000000000  x19: 0x000000015d818b80
   x20: 0x000000015d818a00  x21: 0x000000015d818b80  x22: 0x000000015d818940  x23: 0xd000000000000011
   x24: 0x00000001e6aece28  x25: 0x0000000000000004  x26: 0x0000000000000000  x27: 0xe000000000000000
   x28: 0x0000000000000031   fp: 0x000000016bc1ee40   lr: 0x000000010433268c
    sp: 0x000000016bc1ede0   pc: 0x000000010433269c cpsr: 0x20001000
   far: 0x0000000000000004  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x104268000 -        0x10436bfff com.isaacmarovitz.Whisky (2.3.3) <f26e3642-a4ef-3ae8-9baf-c3eaad0de909> /Applications/Whisky.app/Contents/MacOS/Whisky
       0x10449c000 -        0x1044dffff org.sparkle-project.Sparkle (2.6.4) <0e273e3e-459c-3fa6-9a86-4754c5cc30ff> /Applications/Whisky.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x10fc14000 -        0x10fc1ffff libobjc-trampolines.dylib (*) <22d17f68-169f-35d5-8030-5e4cf575b238> /usr/lib/libobjc-trampolines.dylib
       0x111738000 -        0x111e97fff com.apple.AGXMetalG15X-M1 (320.23.2) <e2715720-d160-3997-8e2f-13dd7a5fc69e> /System/Library/Extensions/AGXMetalG15X_M1.bundle/Contents/MacOS/AGXMetalG15X_M1
       0x1807af000 -        0x1807e9ff7 libsystem_kernel.dylib (*) <2f22b6fb-7929-3452-af97-7b074cf9270f> /usr/lib/system/libsystem_kernel.dylib
       0x184211000 -        0x18424fffb com.apple.CoreServicesInternal (505) <e1ca3730-e218-31ee-a1f5-869a36da695c> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
       0x181a41000 -        0x182891fff com.apple.Foundation (6.9) <db5c2244-050f-35bf-9bfe-eb09be3f8a8c> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x25a0fb000 -        0x25a17afff libswift_Concurrency.dylib (*) <4282f9f2-abb1-3984-89f8-c153cbc0130b> /usr/lib/swift/libswift_Concurrency.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x180469000 -        0x1804eaddb dyld (*) <080914bd-cd81-3697-869a-d72be1cf17a1> /usr/lib/dyld
       0x1807ea000 -        0x1807f6fff libsystem_pthread.dylib (*) <59673c9d-4337-3728-8375-fd6cf6cdfbaa> /usr/lib/system/libsystem_pthread.dylib
       0x18085c000 -        0x180d51fff com.apple.CoreFoundation (6.9) <81bf5987-3619-3ded-8c67-353c067ba79a> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1843e1000 -        0x185904fff com.apple.AppKit (6.9) <ea4dbbf0-9bf4-35a6-b610-d22ca3bfd730> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=1.5G written=626K(0%) resident=626K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
CG image                            80K        4 
ColorSync                          544K       27 
CoreAnimation                      736K       43 
CoreGraphics                        32K        2 
CoreServices                       144K        1 
CoreUI image data                 1344K       11 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.5G       72 
MALLOC guard page                  384K       24 
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                        144K        9 
__AUTH                            2817K      350 
__AUTH_CONST                      38.8M      530 
__CTF                               824        1 
__DATA                            14.4M      511 
__DATA_CONST                      16.9M      535 
__DATA_DIRTY                      1359K      160 
__FONT_DATA                        2352        1 
__LINKEDIT                       583.8M        5 
__OBJC_RW                         2346K        1 
__TEXT                           680.6M      550 
__TPRO_CONST                       272K        2 
mapped file                      236.5M       39 
owned unmapped memory              688K        1 
page table in kernel               626K        1 
shared memory                      928K       15 
===========                     =======  ======= 
TOTAL                              3.1G     2910 

-----------
Full Report
-----------

{"app_name":"Whisky","timestamp":"2024-10-09 22:12:41.00 -0300","app_version":"2.3.3","slice_uuid":"f26e3642-a4ef-3ae8-9baf-c3eaad0de909","build_version":"41","platform":1,"bundleID":"com.isaacmarovitz.Whisky","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.0 (24A5298h)","roots_installed":0,"name":"Whisky","incident_id":"A290D21E-EE27-4261-B6E8-E878C11A2F75"}
{
  "uptime" : 98000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac15,9",
  "coalitionID" : 30108,
  "osVersion" : {
    "train" : "macOS 15.0",
    "build" : "24A5298h",
    "releaseType" : "User"
  },
  "captureTime" : "2024-10-09 22:12:41.0337 -0300",
  "codeSigningMonitor" : 1,
  "incident" : "A290D21E-EE27-4261-B6E8-E878C11A2F75",
  "pid" : 47115,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-10-09 22:12:40.7984 -0300",
  "procStartAbsTime" : 2352045558917,
  "procExitAbsTime" : 2352051182537,
  "procName" : "Whisky",
  "procPath" : "\/Applications\/Whisky.app\/Contents\/MacOS\/Whisky",
  "bundleInfo" : {"CFBundleShortVersionString":"2.3.3","CFBundleVersion":"41","CFBundleIdentifier":"com.isaacmarovitz.Whisky"},
  "storeInfo" : {"deviceIdentifierForVendor":"88474B8F-E89E-5866-B495-00925D34BD4F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.isaacmarovitz.Whisky",
  "crashReporterKey" : "027BF917-F246-3628-2416-A12E201C843E",
  "codeSigningID" : "com.isaacmarovitz.Whisky",
  "codeSigningTeamID" : "92S3SG4PTH",
  "codeSigningFlags" : 570507777,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"AQCA0gIAgNJDAoBSBACA0gUAgNKxPwCUYAQANtQCA5HIAQDwCIlH+Q==","atPC":"AAVAud9BAJT1AwCqwP4A+WACAJAAYDGRt+P8l+cDAKoIAACQCIEfkQ=="},
  "bootSessionUUID" : "2517CA69-ACA4-4814-9ECC-4BFD1608D56A",
  "sip" : "disabled",
  "vmRegionInfo" : "0x4 is not in any region.  Bytes before following region: 4364599292\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      104268000-10436c000    [ 1040K] r-x\/r-x SM=COW  \/Applications\/Whisky.app\/Contents\/MacOS\/Whisky",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000004","rawCodes":[1,4],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000004"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":47115},
  "vmregioninfo" : "0x4 is not in any region.  Bytes before following region: 4364599292\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      104268000-10436c000    [ 1040K] r-x\/r-x SM=COW  \/Applications\/Whisky.app\/Contents\/MacOS\/Whisky",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":1186854,"frames":[{"imageOffset":17780,"symbol":"getattrlistbulk","symbolLocation":8,"imageIndex":4},{"imageOffset":49740,"symbol":"NextEntryFromParent","symbolLocation":184,"imageIndex":5},{"imageOffset":49116,"symbol":"DirEnumRead","symbolLocation":412,"imageIndex":5},{"imageOffset":48572,"symbol":"_GetDirectoryURLs(_CFURLEnumerator*)","symbolLocation":1276,"imageIndex":5},{"imageOffset":42408,"symbol":"_URLEnumeratorGetNextURL","symbolLocation":140,"imageIndex":5},{"imageOffset":211860,"symbol":"-[NSFileManager contentsOfDirectoryAtURL:includingPropertiesForKeys:options:error:]","symbolLocation":208,"imageIndex":6},{"imageOffset":527432,"imageIndex":0},{"imageOffset":506704,"imageIndex":0},{"imageOffset":73249,"imageIndex":0},{"imageOffset":532565,"imageIndex":0},{"imageOffset":73249,"imageIndex":0},{"imageOffset":424101,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":7}],"threadState":{"x":[{"value":31},{"value":0},{"value":5864024576},{"value":18600},{"value":32},{"value":3823577194},{"value":105553132868528},{"value":6102272086},{"value":5863817728},{"value":0},{"value":387584},{"value":6266496},{"value":33266},{"value":4366271528},{"value":0},{"value":2043},{"value":461},{"value":8281014792},{"value":0},{"value":105553152134912},{"value":105553152134832},{"value":5863817728},{"value":6102276016},{"value":6102276012},{"value":6},{"value":105553132868528},{"value":6102276272},{"value":5274403120},{"value":1}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6511776332},"cpsr":{"value":1073745920},"fp":{"value":6102275984},"sp":{"value":6102275888},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6450525556},"far":{"value":0}}},{"triggered":true,"id":1186862,"threadState":{"x":[{"value":1},{"value":1},{"value":6447283048,"symbolLocation":0,"symbol":"dyld4::APIs::dyld_get_base_platform(unsigned int)"},{"value":8160279080,"symbolLocation":584,"symbol":"vtable for dyld4::APIs"},{"value":2},{"value":18},{"value":0},{"value":0},{"value":0},{"value":2214767945558130924},{"value":6102838636},{"value":1},{"value":7},{"value":5863744096},{"value":72057602183141689,"symbolLocation":72057594037927937,"symbol":"OBJC_CLASS_$_NSURL"},{"value":8145213752,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSURL"},{"value":15779487202559654440},{"value":568},{"value":0},{"value":5863738240},{"value":5863737856},{"value":5863738240},{"value":5863737664},{"value":14987979559889010705},{"value":8165183016,"symbolLocation":0,"symbol":"value witness table for URL"},{"value":4},{"value":0},{"value":16140901064495857664},{"value":49}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4365428364},"cpsr":{"value":536875008},"fp":{"value":6102838848},"sp":{"value":6102838752},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4365428380,"matchesCrashFrame":1},"far":{"value":4}},"frames":[{"imageOffset":829084,"imageIndex":0},{"imageOffset":44293,"imageIndex":0},{"imageOffset":67813,"imageIndex":0},{"imageOffset":522233,"imageIndex":0},{"imageOffset":73249,"imageIndex":0},{"imageOffset":424101,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":7}]},{"id":1186863,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}],"threadState":{"x":[{"value":6103412736},{"value":5379},{"value":6102876160},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6103412736},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6450757864},"far":{"value":0}}},{"id":1186868,"frames":[{"imageOffset":8424,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}],"threadState":{"x":[{"value":6103986176},{"value":24067},{"value":6103449600},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6103986176},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6450757864},"far":{"value":0}}},{"id":1186872,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":267194210451456},{"value":0},{"value":267194210451456},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":2},{"value":0},{"value":0},{"value":0},{"value":62211},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8281016696},{"value":0},{"value":4294967295},{"value":2},{"value":267194210451456},{"value":0},{"value":267194210451456},{"value":6104555624},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6450587088},"cpsr":{"value":4096},"fp":{"value":6104555472},"sp":{"value":6104555392},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6450511412},"far":{"value":0}},"frames":[{"imageOffset":3636,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":79312,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":4},{"imageOffset":39384,"symbol":"mach_msg_overwrite","symbolLocation":480,"imageIndex":4},{"imageOffset":4476,"symbol":"mach_msg","symbolLocation":24,"imageIndex":4},{"imageOffset":517948,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":11},{"imageOffset":511980,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":11},{"imageOffset":509108,"symbol":"CFRunLoopRunSpecific","symbolLocation":572,"imageIndex":11},{"imageOffset":1443064,"symbol":"_NSEventThread","symbolLocation":148,"imageIndex":12},{"imageOffset":29412,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":10},{"imageOffset":8444,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364599296,
    "CFBundleShortVersionString" : "2.3.3",
    "CFBundleIdentifier" : "com.isaacmarovitz.Whisky",
    "size" : 1064960,
    "uuid" : "f26e3642-a4ef-3ae8-9baf-c3eaad0de909",
    "path" : "\/Applications\/Whisky.app\/Contents\/MacOS\/Whisky",
    "name" : "Whisky",
    "CFBundleVersion" : "41"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4366909440,
    "CFBundleShortVersionString" : "2.6.4",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "0e273e3e-459c-3fa6-9a86-4754c5cc30ff",
    "path" : "\/Applications\/Whisky.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2039.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4559290368,
    "size" : 49152,
    "uuid" : "22d17f68-169f-35d5-8030-5e4cf575b238",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4587749376,
    "CFBundleShortVersionString" : "320.23.2",
    "CFBundleIdentifier" : "com.apple.AGXMetalG15X-M1",
    "size" : 7733248,
    "uuid" : "e2715720-d160-3997-8e2f-13dd7a5fc69e",
    "path" : "\/System\/Library\/Extensions\/AGXMetalG15X_M1.bundle\/Contents\/MacOS\/AGXMetalG15X_M1",
    "name" : "AGXMetalG15X_M1",
    "CFBundleVersion" : "320.23.2"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6450507776,
    "size" : 241656,
    "uuid" : "2f22b6fb-7929-3452-af97-7b074cf9270f",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6511726592,
    "CFBundleShortVersionString" : "505",
    "CFBundleIdentifier" : "com.apple.CoreServicesInternal",
    "size" : 258044,
    "uuid" : "e1ca3730-e218-31ee-a1f5-869a36da695c",
    "path" : "\/System\/Library\/PrivateFrameworks\/CoreServicesInternal.framework\/Versions\/A\/CoreServicesInternal",
    "name" : "CoreServicesInternal",
    "CFBundleVersion" : "505"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6469980160,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 15011840,
    "uuid" : "db5c2244-050f-35bf-9bfe-eb09be3f8a8c",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "3035.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 10100912128,
    "size" : 524288,
    "uuid" : "4282f9f2-abb1-3984-89f8-c153cbc0130b",
    "path" : "\/usr\/lib\/swift\/libswift_Concurrency.dylib",
    "name" : "libswift_Concurrency.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6447075328,
    "size" : 531932,
    "uuid" : "080914bd-cd81-3697-869a-d72be1cf17a1",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6450749440,
    "size" : 53248,
    "uuid" : "59673c9d-4337-3728-8375-fd6cf6cdfbaa",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6451216384,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5201920,
    "uuid" : "81bf5987-3619-3ded-8c67-353c067ba79a",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "3035.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6513627136,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 22167552,
    "uuid" : "ea4dbbf0-9bf4-35a6-b610-d22ca3bfd730",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2559.1.1"
  }
],
  "sharedCache" : {
  "base" : 6446268416,
  "size" : 4723015680,
  "uuid" : "8ecfde80-15a4-3d80-8d0b-642520616bbc"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=1.5G written=626K(0%) resident=626K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nCG image                            80K        4 \nColorSync                          544K       27 \nCoreAnimation                      736K       43 \nCoreGraphics                        32K        2 \nCoreServices                       144K        1 \nCoreUI image data                 1344K       11 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.5G       72 \nMALLOC guard page                  384K       24 \nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                        144K        9 \n__AUTH                            2817K      350 \n__AUTH_CONST                      38.8M      530 \n__CTF                               824        1 \n__DATA                            14.4M      511 \n__DATA_CONST                      16.9M      535 \n__DATA_DIRTY                      1359K      160 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       583.8M        5 \n__OBJC_RW                         2346K        1 \n__TEXT                           680.6M      550 \n__TPRO_CONST                       272K        2 \nmapped file                      236.5M       39 \nowned unmapped memory              688K        1 \npage table in kernel               626K        1 \nshared memory                      928K       15 \n===========                     =======  ======= \nTOTAL                              3.1G     2910 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "ae14b9110466399d5bd8566be39c01552689de0c",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "654439cdafbf5b61207873a9",
      "factorPackIds" : {

      },
      "deploymentId" : 250000003
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 250000007
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c47ab4cc-c9c3-4b5d-a87c-e2433ce02597",
      "experimentId" : "6639bc6ba73d460582162323",
      "deploymentId" : 400000006
    },
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
}
}

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by TheGodPancake** [comment]
I can confirm, I have experienced the same exact issue on my m3 Mac.

**Comment by TheGodPancake** [comment]
The fix for this issue is to get off of beta software and use the main release of Mac os. This fixed it for me

**Comment by cauediademi** [comment]
> The fix for this issue is to get off of beta software and use the main release of Mac os. This fixed it for me

Is easier to downgrade Whisky than my entire SO

**Comment by cauediademi** [comment]
Fixed, just updated to MacOS 15.1 and worked fine.
