### ISSUE TITLE
GPTK fails to install in whisky versions 1.1.1 and 2.1.0

### ISSUE THREAD

**Issue by zote364** [Whisky-App/Whisky#1171]
### Description

I deleted whisky 1.1.1 to find a newer version compatible with cs2, and when i tried to redownload this version of whisky, it asked me to redownload GPTK, the issue is that it will show that it finished downloading GPTK almost instantly but I either cannot create a bottle or cannot run any programs, same with version 2.1.0(I tried multiple times).

To be specific, version 1.1.1 can create a bottle, but requires restarting the app to see the interface for the bottle. the run button on the bottom right allowed me to choose which apps I want to run, but it doesnt run after the specific program is chosen, in this case steaminstaller.
for version 2.1.0, the app just freezes when i clicked “Create” in the “Create a new bottle” window

![Image](https://github.com/user-attachments/assets/856a4374-c21b-4c29-835a-d0b3c69ccb99)
![Image](https://github.com/user-attachments/assets/c4641cc2-1c49-45d6-a9a2-16f20c377272)

### Steps to reproduce

1. Download verison 1.1.1 or 2.1.0 from github releases
2. unpack the apps and drop the app into Applications
3. run the app and confirm GPTK install
4. It happens

### Expected behaviour

Cannot run any exe apps
Whisky freezes 
cannot install GPTK

### Logs

nothing in logs, i think the app just crashed

### What version of Whisky are you using?

<2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The layout and location of our GPTK packages have changed, these older versions of Whisky are no longer supported.
