### ISSUE TITLE
Whisky won't download

### ISSUE THREAD

**Issue by JohnBlank-rgb** [Whisky-App/Whisky#1196]
### Description

Hi, I just tried to download Whisky to Mac with sequoia 15.0.1 When I try to open it after bringing it to my Applications folder it says that it can not open the application because "it isn't supported on this mac". I do not know what to do here would appreciate some help!

### Steps to reproduce

download whisky on the latest version 2.3.3
bring it to applications on OS sequoia 15.0.1 
and then try to open it

### Expected behaviour

I expected it to open

### Logs

uhh i tried to download whisky so I am having an issue with downloading it.

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by victorsaccucci** [comment]
Hello, how are you?

To run the application on your Mac, please update Swift to version 6.0.2. You can do this directly through the App Store.

Also, make sure that you have SwiftLint installed.I had to install it in order to run Whisky.
