### ISSUE TITLE
Whisky 2.3.3 steam installation issue with macbook air M3 13'

### ISSUE THREAD

**Issue by roux75** [Whisky-App/Whisky#1199]
### Description

I'm on macbook air M3 13' 16g
os : Sequoia 15.1

### Steps to reproduce

When Whisky start to install Steam, the updater runs well. Then a steam message appears : steamwebhelper is no responding 
![Image](https://github.com/user-attachments/assets/6f1673b6-ecab-4316-a098-b8c2a7280512)

### Expected behaviour

Does Whisky 2.3.3 unable running steam app ??

### Logs

Whisky Version: 2.3.3
Date: 2024-11-06T11:29:51Z
macOS Version: 15.1.0

Bottle Name: steam
Bottle URL: /Users/romainconstant/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2EF08593-77DB-4B26-842F-641BD301B396

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/romainconstant/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2EF08593-77DB-4B26-842F-641BD301B396/drive_c/SteamSetup.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/romainconstant/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2EF08593-77DB-4B26-842F-641BD301B396";
}

msync: bootstrapped mach port on wine-1d6c9a-msync.
msync: up and running.
02c0:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
02f0:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0324:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
033c:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0364:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by Joffrey54** [comment]
duplicate #946 ?

**Comment by tht** [comment]
The initial issue on #946 seems to be an old one. In the last few hours people started to report the same issue we're reporting here. For me (and others too) the issue started when updating Steam, it worked before.

Not sure if OP had it working before but I assume it's two different issues most people seem to have the issue only since a few hours.

**Comment by aSushiLegend** [comment]
Same

**Comment by Joffrey54** [comment]
Hi, I solved it (temporarly)

Run your steam with:
`forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`

It wil downgrade.

And after, run it with:

`-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`

to block updates.

**Comment by dojinshi** [comment]
> Hi, I solved it (temporarly)
> 
> Run your steam with: `forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 
> It wil downgrade.
> 
> And after, run it with:
> 
> `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 
> to block updates.

How would one run steam with those options? Would it be under argument in the config?

**Comment by neighborhoodciv** [comment]
Here's what I did:

1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
6. This should force download an older version of Steam and then exit.
7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
8. Click on "Run..."

That should do it. It did for me.

**Comment by eivino1** [comment]
> I paste the first command in the argument field then I run steam in whisky and...same message appears...:(

They forgot to type the first - , the argument is:

-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam

**Comment by roux75** [comment]
Ok thanks for the details, but...
At part 5 I paste the command in the terminal and run it and this message com to me :

"The program could not be launched, or no program is associated with the specified file.

ShellExecuteEx failed: Environment variable not found."

:(

**Comment by SubsTokencoin** [comment]
any solution?

**Comment by along02** [comment]
> any solution?

Try this. https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741

**Comment by roux75** [comment]
Won't work for me...

**Comment by GarthSnyder** [comment]
Thanks for posting the downgrade procedure, @Joffrey54. This method worked for me.

**Comment by neighborhoodciv** [comment]
> Ok thanks for the details, but... At part 5 I paste the command in the terminal and run it and this message com to me :
> 
> "The program could not be launched, or no program is associated with the specified file.
> 
> ShellExecuteEx failed: Environment variable not found."
> 
> :(

The difference may be that for everyone else Steam was already installed (old bottle), while you're trying to install Steam in a fresh bottle.

Can you go to the folder `/Users/romainconstant/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2EF08593-77DB-4B26-842F-641BD301B396/drive_c/Program Files (x86)/Steam`? Are there any files in there? More specifically - is `steam.exe` in there?

**Comment by roux75** [comment]
I am sorry, I don't understand
When I clic to "show informations" on the steam.exe file, the path have no /com.isaacmarovitz.Whisky/

But when I copy the path and paste in the terminal the folder appears : cd "</Users/romainconstant/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2EF08593-77DB-4B26-842F-641BD301B396/drive_c/Program Files (x86)/Steam>"

And when I tap return, I have this message :
cd: no such file or directory: </Users/romainconstant/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2EF08593-77DB-4B26-842F-641BD301B396/drive_c/Program Files (x86)/Steam>

??

**Comment by roux75** [comment]
All my bottles are in Containers/Whisky/Bottles/

**Comment by roux75** [comment]
Very strange, when I create a new folder in container folder and rename it 'com.isaacmarovitz.Whisky', a message says that the folder already exist, but it won't display even with the option display hidden folder in on.

**Comment by ktmtvv** [comment]
it doesn't work since yesterday app updating :(( im so sad... I rlly bad at this coding stuff in Terminal and I don't understand any of explanations here... heeeeeeelp

**Comment by along02** [comment]
> it doesn't work since yesterday app updating :(( im so sad... Im rlly bad at this coding stuff in Terminal and I don't understand any explanation here... heeeeeeelp


This is the temporary fix.
https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741

Further instructions if you're still confused.
1. Pin the program Steam to Whisky if it isn't already (path is usually drive_c/Program Files (x86)/Steam/steam.exe) 
2. Right click the the pin and press Config
3. Enter `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam` into the arguments section
4. Once it installs, the next time you run Steam, have `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` in the arguments section next time

**Comment by ktmtvv** [comment]
> > it doesn't work since yesterday app updating :(( im so sad... Im rlly bad at this coding stuff in Terminal and I don't understand any explanation here... heeeeeeelp
> 
> This is the temporary fix. [#1199 (comment)](https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741)
> 
> Further instructions if you're still confused.
> 
> 1. Pin the program Steam to Whisky if it isn't already (path is usually drive_c/Program Files (x86)/Steam/steam.exe)
> 2. Right click the the pin and press Config
> 3. Enter `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam` into the arguments section
> 4. Once it installs, the next time you run Steam, have `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` in the arguments section next time

thank you for your help. When I right click the pin I don't have option to config only open, settings, unpin...I tried to add these words in terminal before but prob I did something wrong so now when I try to open Terminal it shows error:
Failed to start the program! Failed to open 4D6895D0-9875-4949-BC9E-04DC894E6A8C: No access rights to send Apple Events events (recipient: "Terminal").

![Image](https://github.com/user-attachments/assets/8259268b-e670-4413-b6ff-a068e8600edc)

**Comment by along02** [comment]
> > > it doesn't work since yesterday app updating :(( im so sad... Im rlly bad at this coding stuff in Terminal and I don't understand any explanation here... heeeeeeelp
> > 
> > 
> > This is the temporary fix. [#1199 (comment)](https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741)
> > Further instructions if you're still confused.
> > 
> > 1. Pin the program Steam to Whisky if it isn't already (path is usually drive_c/Program Files (x86)/Steam/steam.exe)
> > 2. Right click the the pin and press Config
> > 3. Enter `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam` into the arguments section
> > 4. Once it installs, the next time you run Steam, have `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` in the arguments section next time
> 
> thank you for your help. When I right click the pin I don't have option to config only open, settings, unpin...I tried to add these words in terminal before but prob I did something wrong so now when I try to open Terminal it shows error: Failed to start the program! Failed to open 4D6895D0-9875-4949-BC9E-04DC894E6A8C: No access rights to send Apple Events events (recipient: "Terminal").
> 
> ![Image](https://github.com/user-attachments/assets/8259268b-e670-4413-b6ff-a068e8600edc)

I believe Settings is the Config button. (It's the one with the wheel symbol).

**Comment by roux75** [comment]
> > it doesn't work since yesterday app updating :(( im so sad... Im rlly bad at this coding stuff in Terminal and I don't understand any explanation here... heeeeeeelp
> 
> This is the temporary fix. [#1199 (comment)](https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741)
> 
> Further instructions if you're still confused.
> 
>     1. Pin the program Steam to Whisky if it isn't already (path is usually drive_c/Program Files (x86)/Steam/steam.exe)
> 
>     2. Right click the the pin and press Config
> 
>     3. Enter `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam` into the arguments section
> 
>     4. Once it installs, the next time you run Steam, have `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` in the arguments section next time



Yes !!! working for me !
You are a genius !
Thanks a lot !!

**Comment by ktmtvv** [comment]
> > > > it doesn't work since yesterday app updating :(( im so sad... Im rlly bad at this coding stuff in Terminal and I don't understand any explanation here... heeeeeeelp
> > > 
> > > 
> > > This is the temporary fix. [#1199 (comment)](https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741)
> > > Further instructions if you're still confused.
> > > 
> > > 1. Pin the program Steam to Whisky if it isn't already (path is usually drive_c/Program Files (x86)/Steam/steam.exe)
> > > 2. Right click the the pin and press Config
> > > 3. Enter `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam` into the arguments section
> > > 4. Once it installs, the next time you run Steam, have `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` in the arguments section next time
> > 
> > 
> > thank you for your help. When I right click the pin I don't have option to config only open, settings, unpin...I tried to add these words in terminal before but prob I did something wrong so now when I try to open Terminal it shows error: Failed to start the program! Failed to open 4D6895D0-9875-4949-BC9E-04DC894E6A8C: No access rights to send Apple Events events (recipient: "Terminal").
> > ![Image](https://github.com/user-attachments/assets/8259268b-e670-4413-b6ff-a068e8600edc)
> 
> I believe Settings is the Config button. (It's the one with the wheel symbol).
> 
> ![Image](https://github.com/user-attachments/assets/96d5ee63-0fcd-4942-8286-3aab98261fc1)

wow, it works!! U ARE ABSOLUTELY GENIUS THANK U!!!
(yeah, im so stupid that I didn't know what config is huh)

**Comment by botsbesud** [comment]
How do u know if it installs? it doesnt seem to work?

**Comment by botsbesud** [comment]
> > > it doesn't work since yesterday app updating :(( im so sad... Im rlly bad at this coding stuff in Terminal and I don't understand any explanation here... heeeeeeelp
> > 
> > 
> > This is the temporary fix. [#1199 (comment)](https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741)
> > Further instructions if you're still confused.
> > ```
> > 1. Pin the program Steam to Whisky if it isn't already (path is usually drive_c/Program Files (x86)/Steam/steam.exe)
> > 
> > 2. Right click the the pin and press Config
> > 
> > 3. Enter `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam` into the arguments section
> > 
> > 4. Once it installs, the next time you run Steam, have `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` in the arguments section next time
> > ```
> 
> Yes !!! working for me ! You are a genius ! Thanks a lot !!

How do I know if it installs?

**Comment by along02** [comment]
> How do I know if it installs? bc it doesnt work for me. And do I run it after step 3 or delete the previous augment and add step 4 to it? does this count as installed?

An updating icon should show up when you enter step 3 and run it.  Once the updating icon is done and goes away for a while, you should be able to do step 4 (deleting the previous argument). You can "Kill All Bottles" under File if you want beforehand.

**Comment by hahayupgit** [comment]
can confirm that this is an issue being worked on. i haven't read the above thread but there are many users in the discord working through this if you want to pop in there and see what's worked for others

**Comment by botsbesud** [comment]
Thank you very much sir

**Comment by botsbesud** [comment]
> > How do I know if it installs? bc it doesnt work for me. And do I run it after step 3 or delete the previous augment and add step 4 to it? does this count as installed?
> 
> An updating icon should show up when you enter step 3 and run it. Once the updating icon is done and goes away for a while, you should be able to do step 4 (deleting the previous argument). You can "Kill All Bottles" under File if you want before you do step 4.

Thank you SO MUCH for your help! steam works for me now :)

**Comment by Guddler** [comment]
@roux75 which commit completes this issue please?

**Comment by fnsne** [comment]
@Guddler  I followed the steps on this comment and it works.
https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2461184145

**Comment by Guddler** [comment]
> [@Guddler](https://github.com/Guddler) I followed the steps on this comment and it works. [#1199 (comment)](https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2461184145)

Yes, I’m aware. I subscribed to this issue to know if and when it was resolved, hence asking where it had been resolved. Not asking about the temporary workaround.

But I now realise that the whole whisky app is just a front end and the resolution will need to happen in Wine somewhere so I may as well unsubscribe from this issue.

**Comment by oiworld8** [comment]
Is there any other solution coz it doesn't work for me and I've tried many times to downgrade Steam to an older version

**Comment by kumakas** [comment]
After adding the first command into the argument, I pressed the "Run..." button, and all I saw was a little loading icon next to the "Run..." button. Does that mean it's still updating? I used the corrected code btw.

**Comment by lksalvis** [comment]
I followed the exact procedure and it didn't work too... After I dg the stream and clicked run on whisky. The run button keeps loading and nothing happened after 10 mins

**Comment by zote364** [comment]
> Hi, I solved it (temporarly)
> 
> Run your steam with: `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 
> It wil downgrade.
> 
> And after, run it with:
> 
> `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 
> to block updates.
> 
> EDIT: Add missing "-" on forcesteamupdate arg

didnt work for me, followed all the steps and steam does exit but does not show a window after turning back on

**Comment by oleksandr-jr** [comment]
> Hi, I solved it (temporarly)
> 
> Run your steam with: `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 
> It wil downgrade.
> 
> And after, run it with:
> 
> `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 
> to block updates.
> 
> EDIT: Add missing "-" on forcesteamupdate arg

Worked for me. Make sure you kill steam before trying this.

**Comment by tacoe** [comment]
FWIW, this works in the sense that Steam launches, however navigating from Home to the Library makes Steam crash. 

Even if it works though, Valve ending 32-bit support seems bad news for Whiskey users: seems unlikely that an older Steam build will keep working for long.

**Comment by tacoe** [comment]
> > FWIW, this works in the sense that Steam launches, however navigating from Home to the Library makes Steam crash.
> > Even if it works though, Valve ending 32-bit support seems bad news for Whiskey users: seems unlikely that an older Steam build will keep working for long.
> 
> Is it possible for whisky to run 64 bit steam, as supposedly wine should have better compatibility with 64bit apps

Wait, after doing some searching it seems both me and you are not correctly informed. It seems the Windows version of Steam *only comes* in 32-bit, there simply is no 64-bit client on Windows.

Which begs the question, what change made Steam suddenly working in Whisky? Is a fix possible?

**Comment by arya-chak** [comment]
> Here's what I did:
> 
> 1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
> 2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
> 3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
> 4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
> 5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 6. This should force download an older version of Steam and then exit.
> 7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 8. Click on "Run..."
> 
> That should do it. It did for me.

After running step 5 I am getting this error:
zsh: command not found: wine

How do i fix this to proceed?

**Comment by touchedthecode** [comment]
@arya-chak Install wine. With homebrew simply run `brew install --cask wine-stable`. After that you can use the `wine` command.

**Comment by LookingForSolutionsRN** [comment]
Hey everyone! Is anyone willing to help me out with Porting Kit? I'm facing the same issue, but the challenge is that Porting Kit uses Windows CMD. This means I'll need to translate the prompts into CMD commands. Any guidance would be greatly appreciated!"

what I'm trying to do: 

"Now you should be in the Steam folder in the Whisky bottle; verify it by typing pwd, it should show a path similar to: /Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam
Paste this command in the terminal and run it: wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam
This should force download an older version of Steam and then exit.
Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: -noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl
Click on "Run...""

**Comment by enyineer** [comment]
> [@roux75](https://github.com/roux75) which commit completes this issue please?

I'd like to second this question. We might have problems as soon as Valve disables the downgraded client version. Any permanent fix available because it was closed?

**Comment by along02** [comment]
I believe there's already been a fix. Whisky should prompt an update to its wine. Once updated, get rid of the arguments (if you used them for the temporary fix) and it should be fine.

**Comment by zeha** [comment]
Still seems broken with 2.3.4 and a freshly downloaded WhiskyWine.

**Comment by aianov** [comment]
> Here's what I did:
> 
> 1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
> 2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
> 3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
> 4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
> 5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 6. This should force download an older version of Steam and then exit.
> 7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 8. Click on "Run..."
> 
> That should do it. It did for me.

worked, thanks bro <3

**Comment by aianov** [comment]
> Here's what I did:
> 
> 1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
> 2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
> 3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
> 4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
> 5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 6. This should force download an older version of Steam and then exit.
> 7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 8. Click on "Run..."
> 
> That should do it. It did for me.

hi again bro, i do everything here and now all my games in steam are running good but, the game feels so slow, game graphics good, fps is too, everything smooth, but i really feel strange, like im in slow motion idk. can someone explain me what happened and how to fix it, please!!!

**Comment by upl1nk-v01d** [comment]
> Hi, I solved it (temporarly)
> 
> Run your steam with: `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 
> It wil downgrade.
> 
> And after, run it with:
> 
> `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 
> to block updates.
> 
> EDIT: Add missing "-" on forcesteamupdate arg

I can confirm this worked out for me in MX Linux with Lutris!!:)

**Comment by ap-1** [comment]
> Here's what I did:
> 
> 1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
> 2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
> 3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
> 4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
> 5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 6. This should force download an older version of Steam and then exit.
> 7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 8. Click on "Run..."
> 
> That should do it. It did for me.

Step 8 doesn't do anything for me (Whisky grays out the Run button and Steam doesn't open)

**Comment by zyberzebra** [comment]
> all my games

Which games?

**Comment by sinedoOo** [comment]
For me it's still broken on Whisky 2.3.4 :/ Any permanent solutions without downgrading the Steam?

**Comment by boncodinsamantha** [comment]
> Here's what I did:
> 
> 1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
> 2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
> 3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
> 4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
> 5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 6. This should force download an older version of Steam and then exit.
> 7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 8. Click on "Run..."
> 
> That should do it. It did for me.

this worked for a moment. i was able to download and open a game, but when i restarted my macbook and tried to open steam via whisky, the steamwebhelper error showed up again.

**Comment by scorninpc** [comment]
no one solution works for me. so i just try every option, and sandingbox disabled works like a charm

**Comment by Petrus323** [comment]
Hi everyone, 

i tried this method showed above and didn't worked for me. After downgrading the Steam and trying to start it with the other arguments, this simply won't started.

But i found something interesting and somehow worked for me. I have a mac M1 pro with two accounts, my account has the english language and my son's account has the german language. On my son's account, it works perfectly!!!
I installed the Whisky and than the steam, both with the last update, and simply works!!!

**Comment by isabelfaulds** [comment]
I also had config args issues in whisky & Run taking forever. I ran the first command in whisky terminal for steamsetup.exe (dont think that's needed) and also for setup.exe in the new Programs 86 folder & then I could see the update running

![Image](https://github.com/user-attachments/assets/f2153bcc-f686-4ce2-b0e8-66ef9521158c)

I still had issues running steam in whisky with the new arg. I got wine from homebrew (maybe that was issue) & using in  wine terminal wine steam.exe -noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl worked. So yeah it's not whisky but it's running & downloaded games work!

![Image](https://github.com/user-attachments/assets/245fe1a6-ae58-4515-a8a3-c321a85bcbc3)

**Comment by itskando** [comment]
I don't know if this helps:

I only have the issue when macOS display mode is mirroring. (I did not need the downgrade fix.)

If I am using the laptop internal monitor or an external monitor without the internal monitor (clamshell mode — not available when using battery power), I do not have this issue. 

If I am using the laptop internal monitor and plug an external monitor HDMI cable in, steam will even close immediately.

**Comment by stschaef** [comment]
> I don't know if this helps:
> 
> I only have the issue when macOS display mode is mirroring. (I did not need the downgrade fix.)
> 
> If I am using the laptop internal monitor or an external monitor without the internal monitor (clamshell mode — not available when using battery power), I do not have this issue.
> 
> If I am using the laptop internal monitor and plug an external monitor HDMI cable in, steam will even close immediately.

Same

**Comment by 0xdnL** [comment]
Won't work if steam is started right after installing, but after fresh a install, downgrade and startup flags worked for me on: 
- Apple M2 Pro
- macOs Sequoia 15.3.1

Thanks everybody !

**Comment by yogithesymbian** [comment]
> -noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl

we need run with `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl` its always need like that ? or how ?

**Comment by wgtiii** [comment]
> Here's what I did:
> 
> 1. Find out where your Steam executable is located: in Whisky, right-click on your Steam icon and click `Show in Finder`. Then either right-click on the parent folder and select 'Copy "Steam" as pathname' or right-click on "Steam.exe" -> Get Info -> right-click on the "Where" field -> Copy as Pathname
> 2. In Whisky click on the "Terminal..." button - it should open a MacOS terminal
> 3. In the terminal write: `cd "<paste_here>"` (I think you get the idea)
> 4. Now you should be in the Steam folder in the Whisky bottle; verify it by typing `pwd`, it should show a path similar to: `/Users/<username>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<some_letters_and_numbers>/drive_c/Program Files (x86)/Steam`
> 5. Paste this command in the terminal and run it: `wine steam.exe forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 6. This should force download an older version of Steam and then exit.
> 7. Back in Whisky - right-click on Steam -> Config -> add the following to the "Arguments" field: `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 8. Click on "Run..."
> 
> That should do it. It did for me.

@neighborhoodciv is there a way to run step 7 in CLI? If so, how? now right clicking on Config freezes Whisky, so can't complete your process. Everything worked up to step 7.

**Comment by umurpza** [comment]
> Hi, I solved it (temporarly)
> 
> Run your steam with: `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> 
> It wil downgrade.
> 
> And after, run it with:
> 
> `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> 
> to block updates.
> 
> EDIT: Add missing "-" on forcesteamupdate arg

This archive link appears to be broken. Is there an updated version?

**Comment by AmitayAbudy** [comment]
The solution provided here didn't work for me. I downloaded Whisky today and tried installing steam. The installation went fine but trying to launch it leads to same thin that happened here. I tried the downgrade method with no success:(

**Comment by Nakilon** [comment]
> > Hi, I solved it (temporarly)
> > Run your steam with: `-forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam`
> > It wil downgrade.
> > And after, run it with:
> > `-noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl`
> > to block updates.
> > EDIT: Add missing "-" on forcesteamupdate arg
> 
> This archive link appears to be broken. Is there an updated version?

I think webarchive is nuking those installers, but you can find different links by searching webarchive for https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe

But I tried one from the official manual and one from the March 2024 obtained myself -- both give the same 3008 error for me.
