### ISSUE TITLE
Steamwebhelper fails to launch, cannot open steam.

### ISSUE THREAD

**Issue by mdkuni** [Whisky-App/Whisky#1202]
### Description

see title. recent steam update seems to have completely broken whisky, at least for me. none of the options listed below do anything to help.
![Image](https://github.com/user-attachments/assets/26185082-64a2-4a10-9011-5bb98786c117)

### Steps to reproduce

open whisky
launch steam
steam doesn't launch

### Expected behaviour

open whisky 
launch steam
steam launches

### Logs

Whisky Version: 2.3.3
Date: 2024-11-04T00:20:32Z
macOS Version: 14.7.0

Bottle Name: steam
Bottle URL: /Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DAE0C87C-39FF-4BE8-A7CE-DABD3BEC8CED

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: false
DXVK HUD: off

Arguments: start /unix /Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DAE0C87C-39FF-4BE8-A7CE-DABD3BEC8CED/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "GST_DEBUG" = 1;
    "LC_ALL" = "en_US";
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DAE0C87C-39FF-4BE8-A7CE-DABD3BEC8CED";
}

msync: bootstrapped mach port on wine-24cf931-msync.
msync: up and running.
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00cc:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\vgk": c0000142
0170:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0150:err:ole:com_get_class_object class {aa509086-5ca9-4c25-8f95-589d3c07b48a} not registered

Whisky Version: 2.3.3
Date: 2024-11-07T13:47:43Z
macOS Version: 14.7.0

Bottle Name: steam
Bottle URL: /Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DAE0C87C-39FF-4BE8-A7CE-DABD3BEC8CED

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: false
DXVK HUD: off

Arguments: start /unix /Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DAE0C87C-39FF-4BE8-A7CE-DABD3BEC8CED/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "GST_DEBUG" = 1;
    "LC_ALL" = "en_US";
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DAE0C87C-39FF-4BE8-A7CE-DABD3BEC8CED";
}

msync: bootstrapped mach port on wine-24cf931-msync.
msync: up and running.
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00c0:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\vgk": c0000142
01e0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
02e4:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
02e4:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0334:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
03f8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0430:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
0430:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0448:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
049c:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
04b4:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
04c4:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
04e4:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
04e4:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003

there are a bunch but they seem all similar.

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by PonomareVlad** [comment]
[Temporary solution from Discord](https://discord.com/channels/1115955071549702235/1224176817372659774/1303823720179040326)

**Comment by mdkuni** [comment]
> [Temporary solution from Discord](https://discord.com/channels/1115955071549702235/1224176817372659774/1303823720179040326)

thanks.

**Comment by Csierram96** [comment]
Whats the solution? The discord link doesnt open for me

**Comment by ryanholden8** [comment]
For those having a hard time opening the discord link. https://github.com/Whisky-App/Whisky/issues/1199#issuecomment-2460454741 describes how to downgrade Steam to work around the broken update

**Comment by itskando** [comment]
I don't know if this helps:

I only have the issue when macOS display mode is mirroring. (I did not need the downgrade fix.)

If I am using the laptop internal monitor or an external monitor without the internal monitor (clamshell mode — not available when using battery power), I do not have this issue. 

If I am using the laptop internal monitor and plug an external monitor HDMI cable in, steam will even close immediately.
