### ISSUE TITLE
Erro in download of games

### ISSUE THREAD

**Issue by guilhermelopesdev** [Whisky-App/Whisky#1204]
### Description

My Steam was showing an error when I opened Whiskey, but I managed to fix it using #1202. However, when I try to install Far Cry 5, it starts downloading, but after about 2 seconds, Steam freezes and won't open again. I'm downloading the game onto an external hard drive.

### Steps to reproduce

My Steam was showing an error when I opened Whiskey, but I managed to fix it using #1202. However, when I try to install Far Cry 5, it starts downloading, but after about 2 seconds, Steam freezes and won't open again. I'm downloading the game onto an external hard drive.

### Expected behaviour

That the game was downloaded normally and could be run

### Logs

At the time, I hadn’t grabbed the logs, and now Steam won’t open.

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This issue can sometimes occur when using MSync. Please switch from MSync to ESync or No Enhanced Sync in Bottle settings.

**Comment by siller174** [comment]
Thank you. It help
