### ISSUE TITLE
Whisky v2.2.4 can't download GPTK

### ISSUE THREAD

**Issue by timoxd7** [Whisky-App/Whisky#1205]
### Description

I still use Whisky v2.2.4 as it is the last version which opens Planet Coaster without a problem. However, i just tried to install it and it just skips the downloading of GPTK. After searching in the source code, the URL [https://data.getwhisky.app/Libraries.zip](https://data.getwhisky.app/Libraries.zip) is used to download the GPTK, which returns a 404. Is it possible to alter this URL?

### Steps to reproduce

1. Install Whisky 2.2.4
2. Try to install GPTK

### Expected behaviour

Installing older Whisky Versions still works

### Logs

```bash
---
```

### What version of Whisky are you using?

<2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by timoxd7** [comment]
If it is legally not possible anymore to host the file, where would one need to unpack the Library.zip(.tag.gz) if obtained elsewhere?

**Comment by IsaacMarovitz** [comment]
The URL has changed to `https://data.getwhisky.app/Wine/Libraries.tar.gz`. Older versions of Whisky are not supported and won't work as intended with newer versions of WhiskyWine.
