### ISSUE TITLE
Add to docs how to completely uninstall Whisky

### ISSUE THREAD

**Issue by superbonaci** [Whisky-App/Whisky#1206]
### Is your feature request related to a problem?

Removing the bottle and moving the app to Bin doesn't remove all other files created in the filesystem, like:

```
~/Library/Application Support/com.isaacmarovitz.Whisky
```

### Describe the solution you'd like

Describe all folders which should be deleted to remove completely Whisky.

### Anything else?

not needed

### Issue Language

- [x] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This exists already. https://docs.getwhisky.app/paths.html#uninstalling-whisky
