### ISSUE TITLE
[Feature]: double click/open with (feature for all exe files)

### ISSUE THREAD

**Issue by logiota** [Whisky-App/Whisky#148]
### Is your feature request related to a problem?

faster to use the CLI unless you can just double click exe files

### Describe the solution you'd like

add whisky to the open with and dragging to the dock support, especially since GPT supports opening files from anywhere...

### Anything else?

![Screenshot 2023-06-20 at 23 35 06](https://github.com/IsaacMarovitz/Whisky/assets/45556023/955bfd44-a210-4efd-9f8b-0b05f33638fc)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ArmasF31** [comment]
Good idea! I'd love to see that as well, no idea how hard it is to implement tho. Also, if you can open apps in whisky with a double click instead of click once for more details and then on start.

**Comment by ohaiibuzzle** [comment]
Keep in mind that even when double clicked on, Whisky still needs to know what bottle it should use to execute the app (or even make an entirely new one), so it's actually more complicated than just adding a handler

**Comment by ArmasF31** [comment]
> Keep in mind that when double clicked on, Whisky still needs to know what bottle it should use to execute the app (or even make an entirely new one), so it's actually more complicated than just adding a handler

Maybe it can just throw a popup like "hey what bottle do you want to use for this/do you want a new one?"

**Comment by ohaiibuzzle** [comment]
That's now more logic that have to be handled. In SwiftUI passing down data from AppDelegate to a subview that may be nested a few levels down to handle this is quite the pain if my memory is serving me right.
If this were to be implemented you'll probably have to wait at least until the core feature set is more stable within Whisky.

**Comment by logiota** [comment]
I would love to have a toggle in the settings to enable this for a specific bottle

**Comment by logiota** [comment]
the Crossover logic is that it executes in it's bottle if it is in a bottle, otherwise it is treated an an install, but to just execute it in a predefined bottle is much more convenient since you are not confined to your bottle and you can try different ones. I also have zero issues with any different bottle compatibility other than windows version, after running around 60 games in wine throughout the years. The need for different bottles seems to be going away with every new version.

**Comment by logiota** [comment]
> That's now more logic that have to be handled. In SwiftUI passing down data from AppDelegate to a subview that may be nested a few levels down to handle this is quite the pain if my memory is serving me right.
> If this were to be implemented you'll probably have to wait at least until the core feature set is more stable within Whisky.

I would see it as a huge win even if it had to be entered into a config file, or create an alias, any way to do it for less techie friends would be wonderful...

**Comment by IsaacMarovitz** [comment]
Added in 1.3.0
