### ISSUE TITLE
[Bug]: CJK Languages have missing fonts

### ISSUE THREAD

**Issue by lieric210** [Whisky-App/Whisky#191]
### Description

When my Ventura 13.4.1 or Sonoma 14 beta system language is set to Chinese, the login box pops up when running Battle.net crashes, and the following error is displayed. But when I set the system language to English, there is no problem.

<img width="522" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/132564320/9c1a10f4-0bdf-4759-8132-6eeb1f051306">

### Steps to reproduce

Set the system language to Chinese

### Expected behaviour

none

### Logs

```bash
none
```

### What version of Whisky are you using?

1.0.0

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mika412** [comment]
Can you check if the same happens when you run it through GPTK/Wine, not through Whisky? 
There is a high chance that this may be unrelated to Whisky.

**Comment by shouri10** [comment]
On Sonoma dev beta 2, I fixed the issue of steam not launching by adding the launch argument `LANG=en_US`. This is with my system language still set to Japanese. Perhaps the solution with Battle.net would be the same?

**Comment by lieric210** [comment]
I also solved the problem by changing the system text in the whiskey registry, it may be a font problem.

**Comment by lianxin255** [comment]
> 我还通过更改威士忌注册表中的系统文本解决了该问题，这可能是字体问题。
How do you do it? Would you mind explaining it?

**Comment by lianxin255** [comment]
> 我还通过更改威士忌注册表中的系统文本解决了该问题，这可能是字体问题。

How do you do it? Would you mind explaining it?

**Comment by IsaacMarovitz** [comment]
In Whisky 1.2.0+, the easiest way to do this is by doing the following:
- Press the `Winetricks...` button on your bottle
- Run the `cjkfonts` command
- Follow any on-screen prompts

**Comment by dyzdyz010** [comment]
> In Whisky 1.2.0+, the easiest way to do this is by doing the following:
> 
> * Press the `Winetricks...` button on your bottle
> * Run the `cjkfonts` command
> * Follow any on-screen prompts

I followed this but nothing happens:

<img width="697" alt="image" src="https://github.com/Whisky-App/Whisky/assets/1324420/f135ff18-66e6-4f9d-b82a-7ff53fa5d2e8">
