### ISSUE TITLE
[Feature]: Running the program in terminal

### ISSUE THREAD

**Issue by ostrolucky** [Whisky-App/Whisky#192]
### Is your feature request related to a problem?

Yes, when software that's running through whisky crashes, there is no troubleshooting info. This requires hunting down log files, which are at various locations.

### Describe the solution you'd like

Run game through terminal, so i can see stdout/stderr output, which usually contains errors.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is a worthwhile feature that I am considering adding

**Comment by IsaacMarovitz** [comment]
Added upstream

**Comment by DanMossa** [comment]
Is there an example of how this is done?

**Comment by IsaacMarovitz** [comment]
> Is there an example of how this is done? @IsaacMarovitz 

Hold shift when clicking the "Run" button this will open a Terminal window and write the command for you.

**Comment by DanMossa** [comment]
@IsaacMarovitz  I did that and I don't see a terminal appear
Does it matter which Shift button is being held? I only have a left shift.

**Comment by Dock1100** [comment]
doesn't work when running app from pin. fails with error "Failed to open program!" "Failed to open steam.exe: Expected end of line, etc. but found identifier."

**Comment by CharlonTank** [comment]
@Dock1100 I got the same problem, have you been able to find a workaround?

**Comment by its-felix** [comment]
I have the same problem, even when running a program that works without holding shift it fails to run when holding shift with the same error as @Dock1100 described

**Comment by Dock1100** [comment]
Unfortunately no.

**Comment by Ozie-hue** [comment]
@IsaacMarovitz any luck on this?
