### ISSUE TITLE
[Feature]: Add DXVK Config

### ISSUE THREAD

**Issue by akxks** [Whisky-App/Whisky#219]
### Is your feature request related to a problem?

Yes, when running certain games they show GPU error 

like "
Error! Graphics driver error, please check your graphics card settings and make sure it has the latest driver.

Error code: [5-0]"

### Describe the solution you'd like

If we add DXVK Config into Whisky Settings under DXVK On Button we can go and change GPU driver name etc.

### Anything else?

That's it 

### Issue Language

- [X] Yes my issue is written in English

**Comment by kode54** [comment]
But Whisky isn't using DXVK.

**Comment by IsaacMarovitz** [comment]
> Error! Graphics driver error, please check your graphics card settings and make sure it has the latest driver.

This sounds probably more like a D3DM issue than a DXVK one. Is this happening in DX9/10 games?

**Comment by vinhtq115** [comment]
Is it possible to make a `dxvk.conf` file and use it in Whisky? I am trying to spoof the GPU in order to bypass NVAPI error.

**Comment by IsaacMarovitz** [comment]
> Is it possible to make a dxvk.conf file and use it in Whisky?
Yes, you should be able to configure DXVK that way just fine. 

As this is not necessary for most users I'm going to close those request for now.
