### ISSUE TITLE
[Bug]: Rage Plugin Hook, GTA V. Process exited with a Mono runtime loaded.

### ISSUE THREAD

**Issue by TheCriticalGamer** [Whisky-App/Whisky#225]
### Description

I ran Rage Plugin Hook with terminal and it says Wine-Mono wasn't installed, so I installed it then I received this error  "0208:err:mscoree:expect_no_runtimes Process exited with a Mono runtime loaded."

I came across the forum mentioning wine tricks : https://forum.winehq.org/viewtopic.php?t=32302

But it requires wine tricks, so how am I supposed to use wine tricks, maybe Dev can help?

### Steps to reproduce

Download GTA V From steam, Once that is done, go to LCPDFR.com press on LSPDFR in the top right, scroll down, press Download 0.49, press download this file, the press, agree then select "lspdfr_049_8564_setup.exe".

Once that is done drag that into C:, then run that in whisky, then select programs in whisky, scroll down to ragepluginhook.exe, and hold shift and run.

### Expected behaviour

It launches a GUI menu of RPH.

### Logs

```bash
Last login: Sat Jul  8 15:55:16 on ttys000

DXVK_HUD=fps WINEDLLOVERRIDES=dxgi,d3d9,d3d10core,d3d11=n,b WINEDEBUG=fixme-all WINEESYNC=1 

WINEPREFIX=/Users/####/Library/Containers/com.isaacmarovitz.Whisky/Bottles/689FB10C-7712-4B16-8747-623AAA3A0D48 MTL_HUD_ENABLED=1 WINEBOOT_HIDE_DIALOG=1 

/Users/####/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wine64 start 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\RAGEPluginHook.exe' 
####@####-MacBook-Pro ~ % DXVK_HUD=fps WINEDLLOVERRIDES=dxgi,d3d9,d3d10core,d3d11=n,b 

WINEDEBUG=fixme-all WINEESYNC=1 

WINEPREFIX=/Users/####/Library/Containers/com.isaacmarovitz.Whisky/Bottles/689FB10C-7712-4B16-8747-623AAA3A0D48 MTL_HUD_ENABLED=1 WINEBOOT_HIDE_DIALOG=1 

/Users/####/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wine64 start 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\RAGEPluginHook.exe' 

####@#####-MacBook-Pro ~ % 0208:err:mscoree:expect_no_runtimes Process exited with a Mono runtime loaded.

####@#####-MacBook-Pro ~ %
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Stale
