### ISSUE TITLE
[Bug]: Watch Dogs 2 Issues

### ISSUE THREAD

**Issue by lolalagay** [Whisky-App/Whisky#234]
### Description

When Launching Watch Dogs 2 on Steam I get an Error about a missing AMD Driver 

`Unhandled exception: unimplemented function atiadlxx.dll.ADL2_Adapter_Crossfire_Caps called in 64-bit code (0x0000007b01376e).`

Also the Installing DirectX in Steam is going very Fast and every time. Seems like its not doing anything. 

### Steps to reproduce

Download Steam, Download Watch Dogs 2, Try running it 

### Expected behaviour

The Game should run, I did actually once get it to run on just Wine and Winetricks on Apple Silicon. (wasnt playable tho)

### Logs

```bash
Unhandled exception: unimplemented function atiadlxx.dll.ADL2_Adapter_Crossfire_Caps called in 64-bit code (0x0000007b01376e).
Register dump:
 rip:000000007b01376e rsp:000000000021e720 rbp:000000000021e980 eflags:00000202 (   - --  I   - - - )
 rax:000000000021e760 rbx:000000007b60eb1c rcx:000000000021e740 rdx:0000000000000001
 rsi:000000000021e830 rdi:000000000021e770  r8:0000000000000002  r9:000000000021e820 r10:00000000fffffffa
 r11:0000000000000001 r12:00000000063b7970 r13:000000000645f548 r14:000000000021ed80 r15:0000000000000000
Stack dump:
0x0000000021e720:  000000000021e740 0000000000000000
0x0000000021e730:  0000000000000000 0000000000000000
0x0000000021e740:  0000000180000100 0000000000000000
0x0000000021e750:  000000007b01376e 0000000300000002
0x0000000021e760:  000000037516c000 000000037516c5f5
0x0000000021e770:  0000000000000000 0000000000000000
0x0000000021e780:  0000000000000000 0000000000000000
0x0000000021e790:  0000000000dc2568 00000000000000ff
0x0000000021e7a0:  0000000000366510 00000003667d71f5
0x0000000021e7b0:  0000000000000000 0000000000000000
0x0000000021e7c0:  0000000000000000 0000000000000000
0x0000000021e7d0:  0000000000000000 00000003667e83d5
Backtrace:
=>0 0x0000007b01376e RaiseException+0x46(code=<internal error>, flags=<internal error>, count=<is not available>, args=<internal error>) [Z:\private\tmp\game-porting-toolkit-20230706-41656-1kti46h\wine\dlls\kernelbase\debug.c:302] in kernelbase (0x0000000021e980)
  1 0x00000375169f55 __wine_spec_unimplemented_stub+0x35(module=<internal error>, function=<internal error>) [Z:\private\tmp\game-porting-toolkit-20230706-41656-1kti46h\wine\dlls\winecrt0\stub.c:32] in atiadlxx (0x0000000021e980)
  2 0x0000037516147f ADL2_ADC_CurrentProfileFromDrv_Get+0x47f() in atiadlxx (0x0000000021e980)
0x0000007b01376e RaiseException+0x46 [Z:\private\tmp\game-porting-toolkit-20230706-41656-1kti46h\wine\dlls\kernelbase\debug.c:302] in kernelbase: nop	
Unable to access file 'Z:\private\tmp\game-porting-toolkit-20230706-41656-1kti46h\wine\dlls\kernelbase\debug.c'
Modules:
Module	Address					Debug info	Name (79 modules)
PE	0000000000ed0000-0000000000ee1000	Deferred        psapi
PE	0000000001790000-0000000001a64000	Deferred        d3d9
PE	0000000002b60000-000000000ec13000	Deferred        disrupt_64
PE	000000000ec20000-000000000efd6000	Deferred        d3dcompiler_46
PE	000000000efe0000-000000000f10c000	Deferred        gfsdk_ssao_d3d11.win64
PE	000000000f110000-000000000f375000	Deferred        gfsdk_shadowlib_dx11.win64
PE	000000000f380000-000000000f465000	Deferred        gfsdk_txaa.win64
PE	000000000f470000-000000000f490000	Deferred        amd_ags_x64
PE	000000000f490000-000000000f4f3000	Deferred        bink2w64
PE	000000000f500000-000000000f801000	Deferred        d3d11
PE	000000000f900000-000000000f951000	Deferred        dbdata
PE	000000000fa60000-000000000fe69000	Deferred        uplay_aux_r164
PE	00000000104d0000-0000000011ac0000	Deferred        steamclient64
PE	0000000011ac0000-0000000011d98000	Deferred        dbghelp
PE	0000000013ee0000-00000000144ec000	Deferred        uplay_r164
PE	00000000144f0000-0000000014db4000	Deferred        overlay64
PE	000000003b400000-000000003b43e000	Deferred        steam_api64
PE	000000006a3c0000-000000006a3c3000	Deferred        win32u
PE	000000006aa10000-000000006aa16000	Deferred        winemac
PE	000000006f010000-000000006f014000	Deferred        opengl32
PE	000000007b000000-000000007b558000	Dwarf-4-5       kernelbase
PE	000000007b600000-000000007b7a4000	Deferred        kernel32
PE	000000013f000000-000000013f197000	Deferred        tier0_s64
PE	000000013f600000-000000013f6b3000	Deferred        vstdlib_s64
PE	0000000140000000-0000000140086000	Deferred        watchdogs2
PE	0000000170000000-0000000170333000	Deferred        ntdll
PE	0000000180000000-000000018018a000	Deferred        gameoverlayrenderer64
PE	00000001c4ee0000-00000001c4fb3000	Deferred        winspool
PE	00000001c69e0000-00000001c7768000	Deferred        shell32
PE	00000001c8b40000-00000001c8bb8000	Deferred        msacm32
PE	00000001c8db0000-00000001c90c6000	Deferred        msvcrt
PE	00000001dd3f0000-00000001dd76b000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec356000	Deferred        ws2_32
PE	00000001f51e0000-00000001f5213000	Deferred        hid
PE	00000001fdfd0000-00000001fe096000	Deferred        wintrust
PE	0000000201cf0000-0000000201d99000	Deferred        secur32
PE	000000021a380000-000000021a3b6000	Deferred        xinput9_1_0
PE	000000021a7e0000-000000021a9c4000	Deferred        setupapi
PE	0000000228450000-00000002284c9000	Deferred        propsys
PE	0000000231ae0000-0000000231d70000	Deferred        rpcrt4
PE	000000023d820000-000000023deff000	Deferred        user32
PE	0000000240030000-00000002400bd000	Deferred        iphlpapi
PE	0000000242df0000-0000000242f26000	Deferred        xaudio2_7
PE	0000000243540000-0000000243827000	Deferred        gdiplus
PE	000000026b4c0000-000000026b756000	Deferred        gdi32
PE	00000002739c0000-0000000273ea5000	Deferred        oleaut32
PE	0000000274a50000-0000000274a7c000	Deferred        kerberos
PE	000000028dfa0000-000000028dfc0000	Deferred        nsi
PE	000000029cfc0000-000000029d00c000	Deferred        dnsapi
PE	00000002a4090000-00000002a40c1000	Deferred        wtsapi32
PE	00000002b17c0000-00000002b1867000	Deferred        msvcp110
PE	00000002bb750000-00000002bbca6000	Deferred        comctl32
PE	00000002bc640000-00000002bc67c000	Deferred        imagehlp
PE	00000002bcfe0000-00000002bcffc000	Deferred        mswsock
PE	00000002d4d40000-00000002d4d92000	Deferred        bcrypt
PE	00000002de970000-00000002dea2d000	Deferred        rsaenh
PE	00000002e3540000-00000002e3656000	Deferred        shlwapi
PE	00000002e8f10000-00000002e9495000	Deferred        ole32
PE	00000002f1fa0000-00000002f1fc0000	Deferred        version
PE	00000002f7230000-00000002f72f0000	Deferred        uxtheme
PE	0000000308050000-000000030816d000	Deferred        dinput8
PE	00000003126f0000-0000000312745000	Deferred        shcore
PE	0000000319900000-000000031999f000	Deferred        mfreadwrite
PE	000000031f800000-000000031fa46000	Deferred        comdlg32
PE	0000000327020000-00000003271af000	Deferred        combase
PE	000000032a700000-000000032a7c0000	Deferred        sechost
PE	0000000330260000-000000033038e000	Deferred        advapi32
PE	0000000335260000-0000000335297000	Deferred        rtworkq
PE	0000000346ba0000-0000000346bee000	Deferred        jsproxy
PE	0000000358120000-0000000358250000	Deferred        winhttp
PE	0000000361860000-00000003620fb000	Deferred        windowscodecs
PE	00000003667a0000-0000000366874000	Deferred        msvcr110
PE	0000000375160000-00000003751b4000	Dwarf-4         atiadlxx
PE	0000000388e20000-0000000388e4d000	Deferred        userenv
PE	00000003a19e0000-00000003a1a06000	Deferred        ncrypt
PE	00000003a6d40000-00000003a6f35000	Deferred        mfplat
PE	00000003af670000-00000003af9f8000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd66000	Deferred        imm32
PE	00000003b8f00000-00000003b90b9000	Deferred        winmm
Threads:
process  tid      prio    name (all IDs are in hex)
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000064    0     
	0000008c    0     
	000000a4    0     
	000000e0    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	000000b0    0     
0000005c winedevice.exe
	00000060    0     
	00000068    0     
	0000006c    0     
	00000070    0     
	00000074    0     
	00000078    0     
	0000007c    0     
	00000080    0     
00000084 plugplay.exe
	00000088    0     
	00000090    0     
	00000094    0     
	00000098    0     
	00000198    0     
	0000019c    0     
	00000270    0     
	00000274    0     
	000005a4    0     
	000005a8    0     
0000009c svchost.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     
000000c4 explorer.exe
	000000c8    0     
	000000cc    0     
	000000d0    0     
000000d8 rpcss.exe
	000000dc    0     
	000000e8    0     
	000000ec    0     
	000000f0    0     
	000000f4    0     
	000000f8    0     
	00000380    0     
00000180 steam.exe
	00000184    0     
	00000188    0     
	0000018c    0     
	00000190    0     
	00000194    0     
	000001a8    0     
	000001ac    0     
	000001b4    0     
	000001c8    0     
	000001cc    0     
	000001d4    0     
	000001dc    0     
	000001e0    2     
	000001e4    2     
	000001ec    0     
	000001f0    0     
	000001f4    0     
	000001f8    0     
	000001fc    0     
	00000200    0     
	0000020c    0     
	00000210    2     
	00000234    0     
	00000288    0     
	000002a8    0     
	000002ac    0     
	00000350    0     
	00000354    0     
	00000364    0     
	0000036c    0     
	00000374    0     
	00000378    0     
	00000388    0     
000001a0 steamwebhelper.exe
	000001a4    0     
	000001b8    0     
	000001bc    0     
	0000021c    0     
	00000220    0     
	00000228   -2     
	0000022c    0     
	00000230    0     
	00000238    0     
	0000023c    0     
	00000240    0     
	00000244    0     
	0000024c    0     
	00000254    0     
	00000258    1     
	0000025c    0     
	00000260    0     
	00000264    1     
	00000268    0     
	0000026c    0     
	00000278   -2     
	0000027c    0     
	00000294    0     
	00000298   -2     
	0000029c    0     
	000002b0    0     
	00000358    0     
000002a0 steamwebhelper.exe
	000002a4    0     
	000002bc    0     
	000002c0    0     
	000002c8   -2     
	000002cc    0     
	000002d0    0     
	000002d4    0     
	000002d8    0     
	0000034c    0     
000002b4 steamwebhelper.exe
	000002b8    0     
	000002f8    0     
	000002fc    0     
	00000304   -2     
	00000308    1     
	0000030c    0     
	00000310    0     
	00000314    0     
	00000318    1     
	0000031c    0     
	00000320    0     
	00000324    0     
	00000328    0     
	0000032c    0     
	00000330   -2     
	0000033c    0     
	00000340    0     
	00000344    0     
	0000037c    0     
	00000470    0     
	00000474    1     
	00000484    0     
000003e8 steamwebhelper.exe
	000003ec    0     
	000003f8    0     
	000003fc    0     
	00000404   -2     
	00000408    1     
	0000040c    0     
	00000410    0     
	00000414    0     
	00000418    1     
	0000041c    0     
	00000420    0     
	00000424    0     
	00000428    0     
	0000042c    0     
	00000430   -2     
	0000043c    0     
	00000480    0     
	00000490    0     
00000440 steamwebhelper.exe
	00000444    0     
	00000448    0     
	0000044c    0     
	00000450    0     
	00000454   -2     
	00000458    0     
	0000045c    0     
	00000460    0     
	00000468    0     
	0000046c    0     
	000007bc    0     
000004ec UbisoftGameLauncher.exe
	000004f0    0     
	000004fc    0     
	00000500    0     
	000007b8    0     
00000508 upc.exe
	0000050c    0     
	00000538    0     
	0000053c    0     
	00000540    0     
	00000544    0     
	00000548    0     
	0000054c    0     
	00000550    0     
	00000554    0     
	00000558    0     
	0000055c    0     
	00000560   -2     
	00000564    0     
	00000568    0     
	0000056c    0     
	00000570    0     
	00000574    0     
	00000578    0     
	0000057c    0     
	00000580    0     
	00000588    0     
	00000594    0     
	00000598    0     
	0000059c    0     
	000005a0    0     
	000005ac   -2     
	000005b0    0     
	000005b8    0     
	000005cc    0     
	000005d8    0     
	00000790    0     
	00000798    0     
	0000079c    0     
	000007ec   -2     
000005c4 UplayWebCore.exe
	000005c8    0     
	000005f4    0     
	000005f8    0     
	000005fc    0     
	00000600   -2     
	00000604    0     
	00000608    0     
000005d0 UplayWebCore.exe
	000005d4    0     
	00000610    0     
	00000614    0     
	00000618    0     
	0000061c   -2     
	00000620    0     
	00000628    0     
	0000062c    0     
	00000630    0     
000005dc UplayWebCore.exe
	000005e0    0     
	00000638    0     
	00000640    0     
	00000644    0     
	00000648   -2     
	0000064c    1     
	00000654    0     
	00000658    0     
	0000065c    0     
	00000680    1     
	00000684    0     
	000006b8    0     
	000006bc    0     
	000006c0    0     
	000006c4    0     
	000006c8   -2     
000005ec UplayWebCore.exe
	000005f0    0     
	0000068c    0     
	00000690    0     
	00000694    0     
	00000698   -2     
	000006a4    1     
	000006ac    0     
	000006b0    0     
	000006b4    0     
	000006e0    1     
	000006e4    0     
00000738 UplayWebCore.exe
	0000073c    1     
	00000740    0     
	00000748    0     
	0000074c    0     
	00000750   -2     
	00000758    1     
	0000075c    0     
	00000760    0     
	00000764    1     
000007d4 (D) C:\Program Files (x86)\Steam\steamapps\common\Watch_Dogs2\bin\WatchDogs2.exe
	000007d8    0 <== 
	000007f4    0     
	00000808    0     
000007e4 SplashScreen.exe
	000007e8    0     
00000800 conhost.exe
	00000804    0     
System information:
    Wine build: wine-7.7
    Platform: x86_64
    Version: Windows 8
    Host system: Darwin
    Host version: 22.5.0
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lolalagay** [comment]
As for the Windows 8 Version, Steam only starts when I change the Windows Version. I tested 7-10 and all had the same Issue.

**Comment by lolalagay** [comment]
https://github.com/IsaacMarovitz/Whisky/assets/77240684/85a8ad21-7cf7-443f-af62-e68afcd5ddae

M1 with Wineskin Winery ca. March 2023

**Comment by lolalagay** [comment]
It will disable itself and its not online playable but it will work. *tried on Linux and the other Installation
I am more than happy with Single Play got not friend anyway

**Comment by IsaacMarovitz** [comment]
Okay, I ran into the same problem on my machine. This is likely due to the fact that game-porting-toolkit presents as an AMD graphics card, and the game is trying to check if it supports CrossFire. The function it's trying to call, `ADL2_Adapter_Crossfire_Caps`, has been stubbed but not implemented in Apple's atiadlxx.dll implementation. I've sent a message to Nat from Apple to see if there's a way to resolve this. I imagine fixing this would require writing some sort of implementation for that function.

**Comment by lolalagay** [comment]
Can we not just tell the game to stop checking? with some kind of argument?

**Comment by IsaacMarovitz** [comment]
> Can we not just tell the game to stop checking? with some kind of argument?

I don't think so

**Comment by IsaacMarovitz** [comment]
@lolalagay I've made a patch to see if I can fix this. Should know in about an hour or so

**Comment by lolalagay** [comment]
Cant wait.

**Comment by IsaacMarovitz** [comment]
> Cant wait.

There's actually a workaround without the patch. Add an environment variable called `WINEDLLOVERRIDES` and set it equal to `atiadlxx=` and the game should launch

**Comment by lolalagay** [comment]
It did launch now but I got a new error. 

Unhandled exception: divide by zero in 64-bit code (0x007ffa26e43a4b).
Register dump:
 rip:00007ffa26e43a4b rsp:000000003c13f5f0 rbp:000000003c13f630 eflags:00000207 (   - --  I   - -P-C)
 rax:000000007fffffff rbx:0000000000000000 rcx:0000000000000010 rdx:0000000000000000
 rsi:0000000000000000 rdi:0000000000000000  r8:0000000000000078  r9:0000000000000041 r10:0000000000000001
 r11:0000000000000000 r12:00000001200e8000 r13:000000003c13f730 r14:000000003c13f6c0 r15:0000000000000017
Stack dump:
0x0000003c13f5f0:  0000000000000000 0000000000000000
0x0000003c13f600:  0000000000000000 0000001524984968
0x0000003c13f610:  0000000000000000 00000001200e8000
0x0000003c13f620:  00006000030137b0 000000003c13f748
0x0000003c13f630:  000000003c13f720 00007ffa26e3ad0e
0x0000003c13f640:  0000000000000000 0000000000000000
0x0000003c13f650:  0000000000000000 0000000000000078
0x0000003c13f660:  0000000000000041 0000000000000001
0x0000003c13f670:  0000000000000000 000000006b8f0a00
0x0000003c13f680:  0000000000000001 0000000068845a90
0x0000003c13f690:  00007ff833fdf7eb 000000007936bf51
0x0000003c13f6a0:  54f65c8ba8db00cc 54f65c8ba8db00cc
Backtrace:
=>0 0x007ffa26e43a4b (0x0000003c13f630)
0x007ffa26e43a4b: divl	%r11d,%eax
Modules:
Module	Address					Debug info	Name (85 modules)
PE	0000000000ed0000-0000000000ee1000	Deferred        psapi
PE	0000000001790000-0000000001a64000	Deferred        d3d9
PE	0000000002b60000-000000000ec13000	Deferred        disrupt_64
PE	000000000ec20000-000000000efd6000	Deferred        d3dcompiler_46
PE	000000000efe0000-000000000f10c000	Deferred        gfsdk_ssao_d3d11.win64
PE	000000000f110000-000000000f375000	Deferred        gfsdk_shadowlib_dx11.win64
PE	000000000f380000-000000000f465000	Deferred        gfsdk_txaa.win64
PE	000000000f470000-000000000f490000	Deferred        amd_ags_x64
PE	000000000f490000-000000000f4f3000	Deferred        bink2w64
PE	000000000f500000-000000000f801000	Deferred        d3d11
PE	000000000f900000-000000000f951000	Deferred        dbdata
PE	000000000fa60000-000000000fe69000	Deferred        uplay_aux_r164
PE	00000000104d0000-0000000011ac0000	Deferred        steamclient64
PE	0000000011ac0000-0000000011d98000	Deferred        dbghelp
PE	0000000013ee0000-00000000144ec000	Deferred        uplay_r164
PE	00000000144f0000-0000000014db4000	Deferred        overlay64
PE	0000000035d40000-0000000035f02000	Deferred        coreextension
PE	0000000037810000-000000003782a000	Deferred        anselsdk64
PE	0000000039e80000-0000000039eb6000	Deferred        libscepad
PE	000000003b400000-000000003b43e000	Deferred        steam_api64
PE	000000006c010000-000000006c013000	Deferred        win32u
PE	000000006e170000-000000006e176000	Deferred        winemac
PE	000000006fc60000-000000006fc64000	Deferred        opengl32
PE	000000007b000000-000000007b558000	Deferred        kernelbase
PE	000000007b600000-000000007b7a4000	Deferred        kernel32
PE	000000013f000000-000000013f197000	Deferred        tier0_s64
PE	000000013f600000-000000013f6b3000	Deferred        vstdlib_s64
PE	0000000140000000-0000000140086000	Deferred        watchdogs2
PE	0000000170000000-0000000170333000	Deferred        ntdll
PE	0000000180000000-000000018018a000	Deferred        gameoverlayrenderer64
PE	00000001c4ee0000-00000001c4fb3000	Deferred        winspool
PE	00000001c69e0000-00000001c7768000	Deferred        shell32
PE	00000001c8b40000-00000001c8bb8000	Deferred        msacm32
PE	00000001c8db0000-00000001c90c6000	Deferred        msvcrt
PE	00000001c92d0000-00000001c934e000	Deferred        winecoreaudio
PE	00000001dc080000-00000001dc101000	Deferred        cabinet
PE	00000001dd3f0000-00000001dd76b000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec356000	Deferred        ws2_32
PE	00000001f51e0000-00000001f5213000	Deferred        hid
PE	00000001fdfd0000-00000001fe096000	Deferred        wintrust
PE	0000000201cf0000-0000000201d99000	Deferred        secur32
PE	000000021a380000-000000021a3b6000	Deferred        xinput9_1_0
PE	000000021a7e0000-000000021a9c4000	Deferred        setupapi
PE	0000000228450000-00000002284c9000	Deferred        propsys
PE	0000000231ae0000-0000000231d70000	Deferred        rpcrt4
PE	000000023d820000-000000023deff000	Deferred        user32
PE	0000000240030000-00000002400bd000	Deferred        iphlpapi
PE	0000000242df0000-0000000242f26000	Deferred        xaudio2_7
PE	0000000243540000-0000000243827000	Deferred        gdiplus
PE	000000026b4c0000-000000026b756000	Deferred        gdi32
PE	00000002739c0000-0000000273ea5000	Deferred        oleaut32
PE	0000000274a50000-0000000274a7c000	Deferred        kerberos
PE	000000028dfa0000-000000028dfc0000	Deferred        nsi
PE	000000029cfc0000-000000029d00c000	Deferred        dnsapi
PE	00000002a4090000-00000002a40c1000	Deferred        wtsapi32
PE	00000002b17c0000-00000002b1867000	Deferred        msvcp110
PE	00000002bb750000-00000002bbca6000	Deferred        comctl32
PE	00000002bc640000-00000002bc67c000	Deferred        imagehlp
PE	00000002bcfe0000-00000002bcffc000	Deferred        mswsock
PE	00000002d4d40000-00000002d4d92000	Deferred        bcrypt
PE	00000002de970000-00000002dea2d000	Deferred        rsaenh
PE	00000002e3540000-00000002e3656000	Deferred        shlwapi
PE	00000002e8f10000-00000002e9495000	Deferred        ole32
PE	00000002f1fa0000-00000002f1fc0000	Deferred        version
PE	00000002f6140000-00000002f6275000	Deferred        xaudio2_8
PE	00000002f7230000-00000002f72f0000	Deferred        uxtheme
PE	0000000308050000-000000030816d000	Deferred        dinput8
PE	00000003126f0000-0000000312745000	Deferred        shcore
PE	0000000319900000-000000031999f000	Deferred        mfreadwrite
PE	000000031f800000-000000031fa46000	Deferred        comdlg32
PE	0000000327020000-00000003271af000	Deferred        combase
PE	000000032a700000-000000032a7c0000	Deferred        sechost
PE	0000000330260000-000000033038e000	Deferred        advapi32
PE	0000000335260000-0000000335297000	Deferred        rtworkq
PE	0000000336850000-00000003368f4000	Deferred        mmdevapi
PE	0000000346ba0000-0000000346bee000	Deferred        jsproxy
PE	0000000358120000-0000000358250000	Deferred        winhttp
PE	0000000361860000-00000003620fb000	Deferred        windowscodecs
PE	00000003667a0000-0000000366874000	Deferred        msvcr110
PE	0000000388e20000-0000000388e4d000	Deferred        userenv
PE	00000003a19e0000-00000003a1a06000	Deferred        ncrypt
PE	00000003a6d40000-00000003a6f35000	Deferred        mfplat
PE	00000003af670000-00000003af9f8000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd66000	Deferred        imm32
PE	00000003b8f00000-00000003b90b9000	Deferred        winmm
Threads:
process  tid      prio    name (all IDs are in hex)
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000064    0     
	0000008c    0     
	000000a4    0     
	000000f0    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	000000b0    0     
0000005c winedevice.exe
	00000060    0     
	00000068    0     
	0000006c    0     
	00000070    0     
	00000074    0     
	00000078    0     
	0000007c    0     
	00000080    0     
	0000092c    0     
	00000930    0     
00000084 plugplay.exe
	00000088    0     
	00000090    0     
	00000094    0     
	00000098    0     
	000001bc    0     
	000001c0    0     
	000003f0    0     
	000003f4    0     
	000004c8    0     
	000007bc    0     
	000007c0    0     
	00000924    0     
	00000928    0     
0000009c svchost.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     
000000d4 explorer.exe
	000000d8    0     
	000000dc    0     
	000000e0    0     
000000e8 rpcss.exe
	000000ec    0     
	000000f8    0     
	000000fc    0     
	00000100    0     
	00000104    0     
	00000108    0     
	000005d4    0     
	000005fc    0     
00000110 UbisoftGameLauncher.exe
	00000114    0     
	00000118    0     
	0000011c    0     
	000003c4    0     
00000120 upc.exe
	00000124    0     
	00000150    0     
	00000154    0     
	00000158    0     
	0000015c    0     
	00000160    0     
	00000164    0     
	00000168    0     
	0000016c    0     
	00000170    0     
	00000174    0     
	00000178   -2     
	0000017c    0     
	00000184    0     
	00000188    0     
	0000018c    0     
	00000190    0     
	00000194    0     
	00000198    0     
	000001a0    0     
	000001a4    0     
	000001b0    0     
	000001b4    0     
	000001b8    0     
	000001c4   -2     
	000001c8    0     
	000001d0    0     
	000001e4    0     
	000001f0    0     
	000003b0    0     
000001dc UplayWebCore.exe
	000001e0    0     
	0000020c    0     
	00000210    0     
	00000214    0     
	00000218   -2     
	0000021c    0     
000001e8 UplayWebCore.exe
	000001ec    0     
	00000228    0     
	0000022c    0     
	00000230    0     
	00000234   -2     
	0000023c    0     
	00000240    0     
	00000244    0     
000001f4 UplayWebCore.exe
	000001f8    0     
	00000254    0     
	00000258    0     
	0000025c    0     
	00000260   -2     
	00000268    1     
	0000026c    0     
	00000270    0     
	00000274    0     
	00000298    1     
	0000029c    0     
	000002d0    0     
	000002d4    0     
	000002d8    0     
	000002dc    0     
	000002e0   -2     
00000204 UplayWebCore.exe
	00000208    0     
	000002a4    0     
	000002a8    0     
	000002ac    0     
	000002b0   -2     
	000002b8    1     
	000002bc    0     
	000002c0    0     
	000002c4    0     
	000002e4    1     
	000002e8    0     
00000350 UplayWebCore.exe
	00000354    1     
	00000358    0     
	00000360    0     
	00000364    0     
	00000368   -2     
	00000370    1     
	00000374    0     
	00000378    0     
	0000037c    1     
000003c8 steam.exe
	000003cc    0     
	000003d0    0     
	000003d4    0     
	000003dc    0     
	000003e4    0     
	000003e8    0     
	000003ec    0     
	00000400    0     
	00000404    0     
	0000040c    0     
	00000420    0     
	00000424    0     
	0000042c    0     
	00000434    0     
	00000438    0     
	0000043c    2     
	00000440    2     
	00000448    0     
	0000044c    0     
	00000450    0     
	00000458    0     
	0000045c    0     
	00000460    0     
	00000470    0     
	00000474    2     
	000004bc    0     
	000004ec    0     
	000004f0    0     
	000004f4    0     
	000005c8    0     
	000005cc    0     
	000005e4    0     
	000005e8    0     
	000005f4    0     
	00000604    0     
	000007ac    0     
	00000914    0     
000003f8 steamwebhelper.exe
	000003fc    0     
	00000410    0     
	00000414    0     
	0000046c    0     
	00000478    0     
	00000480   -2     
	00000484    0     
	00000488    0     
	0000048c    0     
	00000490    0     
	00000494    0     
	00000498    0     
	0000049c    0     
	000004a8    0     
	000004ac    1     
	000004b0    0     
	000004b4    0     
	000004b8    1     
	000004c0    0     
	000004c4    0     
	000004d0   -2     
	000004d4    0     
	000004d8    0     
	000004e0    0     
	000004f8    0     
	000005d0    0     
	0000091c   -2     
	00000a80    0     
000004e4 steamwebhelper.exe
	000004e8    0     
	00000504    0     
	00000508    0     
	00000510   -2     
	00000514    0     
	00000518    0     
	0000051c    0     
	00000524    0     
	000005a4    0     
	00000a7c    0     
	00000a84    0     
000004fc steamwebhelper.exe
	00000500    0     
	00000538    0     
	0000053c    0     
	00000544   -2     
	00000548    1     
	0000054c    0     
	00000550    0     
	00000554    0     
	00000558    1     
	0000055c    0     
	00000560    0     
	00000564    0     
	00000568    0     
	0000056c    0     
	00000570   -2     
	00000574    0     
	00000588    0     
	0000058c    0     
	000005f8    0     
	00000738    0     
	0000073c    1     
	00000740    0     
	00000a4c    0     
00000680 steamwebhelper.exe
	00000684    0     
	00000690    0     
	00000694    0     
	0000069c   -2     
	000006a0    1     
	000006a4    0     
	000006a8    0     
	000006ac    0     
	000006b0    1     
	000006b4    0     
	000006b8    0     
	000006bc    0     
	000006c0    0     
	000006c4    0     
	000006c8   -2     
	0000074c    0     
00000708 steamwebhelper.exe
	0000070c    0     
	00000710    0     
	00000714    0     
	00000718    0     
	0000071c   -2     
	00000720    0     
	00000724    0     
	00000728    0     
	00000730    0     
	00000734    0     
00000794 (D) C:\Program Files (x86)\Steam\steamapps\common\Watch_Dogs2\bin\WatchDogs2.exe
	00000798    2     
	000007a8    0     
	000007b0  -15     
	000007b4   15     
	000007b8    0     
	000007c4    0     
	000007cc   -1     
	000007d0   -1     
	000007d4   -1     
	000007d8   -1     
	000007dc   -1     
	000007e0   -1     
	000007e4   -1     
	000007e8   -1     
	000007ec    0     
	000007f0    0     
	000007f4    0     
	000007f8    0     
	000007fc    0     
	00000800    0     
	00000804    0     
	00000808    2     
	0000080c    2     
	00000810    2     
	00000814    2     
	00000818    0     
	0000081c   -2     
	00000820    0     
	00000824    0     
	00000828    0     
	0000082c    0     
	00000830    0     
	00000834    0 <== 
	00000838    0     
	0000083c    0     
	00000840    0     
	00000844    0     
	00000848    0     
	0000084c    0     
	00000850    0     
	00000854    1     
	00000858    0     
	0000085c    0     
	00000860   15     
	00000864    0     
	00000868   15     
	0000086c    0     
	00000870    0     
	000008b8    1     
	000008bc    1     
	000008cc    0     
	00000934    0     
	00000938   15     
	000009d0    1     
	000009d8    0     
	000009dc   -1     
	000009e0   -1     
	000009e4    2     
00000abc conhost.exe
	00000ac0    0     
System information:
    Wine build: wine-7.7
    Platform: x86_64
    Version: Windows 10
    Host system: Darwin
    Host version: 22.5.0

**Comment by IsaacMarovitz** [comment]
Hmm weird, maybe just try again. Right now I'm mostly struggling with the game's window which seems to really dislike Wine...

**Comment by lolalagay** [comment]
just set it to windowed once and then back to fullscreen. And yes the game is really not nice on Windows or Linux either. I got it to run with some hickups and uhm idk how to explain this but the players texture is a bit uhm cursed. 
![image](https://github.com/IsaacMarovitz/Whisky/assets/77240684/e5812f52-59b8-423f-a86f-c8e5108cc84d)
Also sometimes half of the screen has some dark overlay.

**Comment by lolalagay** [comment]
Also funny side note. When launching WatchDogs2.exe steam does launch every time. If I launch Steam.exe it doesnt.

**Comment by lolalagay** [comment]
update: its just the player modell. Using the RC car thing. I can move freely away and see things

**Comment by lolalagay** [comment]
So far my findings are: 

the player itself is bad.
above medium the game will just crash.

**Comment by IsaacMarovitz** [comment]
@lolalagay Can you test to see if these issues have been resolved in GPTK beta 4?

**Comment by lolalagay** [comment]
will give it a try tonight

**Comment by IsaacMarovitz** [comment]
Stale

**Comment by ivictor777** [comment]
I have the same error when starting Far Cry 5

**Comment by thanhdatpd** [comment]
> I have the same error when starting Far Cry 5

me too
