### ISSUE TITLE
[Bug]:  Altium Designer 23 not launching: FormatMessage failed

### ISSUE THREAD

**Issue by Haakliv** [Whisky-App/Whisky#238]
### Description

When I try to run Altium Designer 23's executable X2.EXE (64-bit), it will not launch. Nothing happens, except that when I run it in the terminal, I get the error "ShellExecuteEx failed: 00c4:err:start:fatal_error FormatMessage failed".

I have also tried to install the Winetricks dotnet40, dotnet48, and msxml6 with no result.

### Steps to reproduce

1. Installing Altium Designer 23 through its offline installer.
2. Installing dotnet40, dotnet48, and msxml6 Winetricks (also tried without this with same result)
3. Running X2.EXE

### Expected behaviour

A splash screen appearing, and Altium launching.

### Logs

```bash
Whisky Version: 1.0.1
Date: 12/7/2023, 16:51:27
macOS Version: Version 14.0 (Build 23A5286g)
Bottle Name: my-game-prefix
Wine Version: 7.7.0
Wine Binary Version: 4
Windows Version: win10
Bottle URL: /Users/USERNAME/Library/Containers/com.isaacmarovitz.Whisky/Bottles/EDFD511E-A2F7-43D3-849B-0C10DBE7704B

Arguments: start C:\Program Files\Altium\AD23\X2.exe 

Launched Wine (4304)
esync: up and running.
preloader: Warning: failed to reserve range 0000001400000000-0000001402ab4000
wine: failed to start L"C:\\Program Files\\Altium\\AD23\\X2.EXE"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: 00bc:err:start:fatal_error FormatMessage failed
Process exited with code 1
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Wine AppDB report that mentions the workaround is on Wine 8, whereas GPTK is on Wine 7. I can't see any reports for Altium Design 23 on anything older than Wine 8.

**Comment by Haakliv** [comment]
I have now tried installing Altium through the CX 23 beta with the same result unfortunately. It will not launch and gives error code 11, which I believe is related to the Formatmessage error mentioned above.

**Comment by LucasPaivaSilva** [comment]
@Haakliv do you have updates on this? trying to run altium here and getting the same problem. Also tried on CX

**Comment by thuvasooriya** [comment]
@LucasPaivaSilva @Haakliv I've tried installing Altium Designer with CW23.6, Wineskin and tried different winetricks. All resulted in the same errors you mentioned above. Wish I found this discussion earlier to have avoided burning some days. I wonder why even with all these fixes Altium is refusing to run.
I still have a glimmer of hope that someone might find some solution or some update fixes it. If any of you guys find out please don't forget to update it here. You are the last two guys I found on the internet trying to run Altium via wine rather than using a VM. 🥂
