### ISSUE TITLE
[Feature]: Add info or hints

### ISSUE THREAD

**Issue by woile** [Whisky-App/Whisky#245]
### Is your feature request related to a problem?

I'm unaware when to enable/disable DXVK and the same for Metal 

### Describe the solution you'd like

I would like some hints, like an (i) icon next to the attribute explaining:
- what is it
- when is recommended to use
- what is the HUD for? and what are the settings?

I think adding this can help the users (like me) better diagnose whether a setting is required or not for a game.

Thanks!

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by metya** [comment]
Interesting point. 
And I'd like to know, do I need to install DXVK ыщmehow or not? Because there are many different DXVK versions and implementations, for example.

**Comment by IsaacMarovitz** [comment]
Superseded by #407
