### ISSUE TITLE
[Bug]: EA App

### ISSUE THREAD

**Issue by Crd5** [Whisky-App/Whisky#248]
### Description

I downloaded Star Wars Battlefront 2 via Steam but when I press the play button Steam tries to install EaApp but I get an exception.

### Steps to reproduce

When you try to launch ea game for the first time Steam will try to install EaApp

### Expected behaviour

Is there any way to install EaApp (or Origin)

### Logs

```bash
There are no logs
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by woile** [comment]
I publish #246 which is quite similar I think

**Comment by Crd5** [comment]
> I publish #246 which is quite similar I think

Yeah you're right. Thanks

**Comment by IsaacMarovitz** [comment]
EA App now works in WhiskyWine 2.1.1 with the `d3dcompiler_47` trick.

**Comment by Cl1pperT** [comment]
> EA App now works in WhiskyWine 2.1.1 with the `d3dcompiler_47` trick. 
What's this trick and how do you get it to install?

**Comment by alex-days14** [comment]
> EA App now works in WhiskyWine 2.1.1 with the `d3dcompiler_47` trick.

can yo explain how to use use that trick?

**Comment by Cl1pperT** [comment]
> > EA App now works in WhiskyWine 2.1.1 with the `d3dcompiler_47` trick.
> 
> 
> 
> can yo explain how to use use that trick?
> 
> 

I got it working last night to run battlefront. Turns out within the whiskyapp in the bottom right corner you can select winetricks -> then select DLLs column in the top middle -> scroll down -> D3dcompiler_47 -> run. It'll open the terminal and take a minute or so to complete the install automatically. Then simply restart whisky add a fresh windows version of the EA app to your bottle and you're good to go.

**Comment by groeneveld** [comment]
> > > EA App now works in WhiskyWine 2.1.1 with the `d3dcompiler_47` trick.
> > 
> > 
> > can yo explain how to use use that trick?
> 
> I got it working last night to run battlefront. Turns out within the whiskyapp in the bottom right corner you can select winetricks -> then select DLLs column in the top middle -> scroll down -> D3dcompiler_47 -> run. It'll open the terminal and take a minute or so to complete the install automatically. Then simply restart whisky add a fresh windows version of the EA app to your bottle and you're good to go.

This got EA App working, but it crashes every few minutes.

**Comment by luiseps** [comment]
The workarround doesn't work with the latest version
