### ISSUE TITLE
[Feature]: Keep D3D9 of WineD3D when Game Porting Toolkit is installed

### ISSUE THREAD

**Issue by metarutaiga** [Whisky-App/Whisky#269]
### Is your feature request related to a problem?

the D3D9 is not implemented in Game Porting Toolkit.

### Describe the solution you'd like

1.Keep original d3d9.dll in system32.
2.Make a button to swap WineD3D or DXVK or AGPT

### Anything else?

None

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Done upstream in WhiskyBuilder
