### ISSUE TITLE
[Bug]: Ubisoft Connect Won't Start

### ISSUE THREAD

**Issue by cirava** [Whisky-App/Whisky#273]
### Description

After updating to GPTK 1.03 i simply cannot get Ubisoft Connect to start. I've tried every combination of DXVK and ESync and nothing has worked, the most I've gotten is the outline of the Ubisoft window, but no actual graphics have shown after it installed.

### Steps to reproduce

1. Download the Ubisoft Connect installer
2. Run through the installer
3. Attempt to run it

### Expected behaviour

I would expect it to at least start up.

### Logs

```bash
The log was too long to put in the comment

https://drive.google.com/file/d/1F-E3mt_qqZrZQIC-dAsBKNFbC_NGVmP1/view?usp=sharing
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Defaalt** [comment]
The 1.1.0 version of Whisky didn't fix it either !

**Comment by NuclearKookaburra** [comment]
As a workaround, you can get the older version from the internet and downgrade the app using it. 

How to:
0. Delete currently installed Ubisoft Connect
1. Find Ubisoft connect 138.3.10824 somewhere
2. Install it (make sure to not launch it straight away)
3. Open `drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher`
4. Replace the number in the `version.txt` with `10906`. This is the latest version

Now try to run it again. The downgraded version should now start. As long as Ubisoft releases another update, the thing will brake again and you need to do the trick once more with the newer version.

**Comment by cirava** [comment]
Can confirm that this workaround does work, I just love how straightforward it is to trick it into thinking it's a newer version haha

**Comment by m-raven** [comment]
For reference, the proton project was able to fix it. At least they mention "Fixed Ubisoft Connect not working after its recent update." in their latest experimental change logs: https://github.com/ValveSoftware/Proton/wiki/Changelog

But not sure which of the commits solved it
https://github.com/ValveSoftware/Proton/commits/experimental_8.0

**Comment by fila612** [comment]
> 4\. 10906

10931 is currently the latest version :)

**Comment by Schlabbesaicher** [comment]
> > 4. 10906
> 
> 10931 is currently the latest version :)

10933 now👍

**Comment by odahcam** [comment]
Here it installed and launched successfully the first time, but never worked again. Same for you?

**Comment by SH160388** [comment]
Why this thread is closed. Today Ubisoft launches a new version and whisky use the same unfixed wine version. So for me today, there is a problem again and this conversation can help to fix it. I need the new version number for the txt file.

**Comment by siulca** [comment]
Ubisoft connect still doesn't work on the latest version.

**Comment by LoulergueC** [comment]
Now : 10956 👍

**Comment by Gernot** [comment]
Seems like this does not work anymore, it updates to 10899, which is lower, for some reason. If I write 10899 into `versions.txt` however it still updates to 10956. Super weird.

**Comment by osa911** [comment]
Now: 10965

**Comment by u-tung** [comment]
Now: 10975

**Comment by SushiDesigner** [comment]
Now: 10984

**Comment by s7v3n7** [comment]
Do you have to update the txt. everytime the launcher got updated?

**Comment by MarcelBochtler** [comment]
Now: 10999

> Do you have to update the txt. everytime the launcher got updated?

Even worse. You have to update the txt **before** Ubisoft Connect automatically updates to the new version.

**Comment by nich886** [comment]
This stuff isn't working, I have tried changing the versions and all sorts off things.

**Comment by mihama** [comment]
Thanks for the community diligently reporting new version numbers in this issue! 

I want to share another approach that has been working for me (launching Anno 1800) when the "update versions.txt" workaround wasn't available: 
1. launch your game from Whisky (using the shortcut directly to the game, not the general Ubisoft Connect application)
2. wait for the Ubisoft Connect launcher to load
3. if it is starting to download updates, immediately turn off internet connection on your computer (I just turn off wifi)
4. after a short while, the launcher will report connectivity issues. Click `Continue` (not "Try Again")
5. the launching of the game resumes, and you can turn on wifi/internet again

It does have the disadvantage that you need to keep your eyes open and quickly react in case the update process starts - but for me this has been working (incl. online connectivity within the game after the initial launcher stage is passed). 

I'm doing this on version 138.3.10824 that's also required for the "versions.txt" method, so the two approaches can be mixed or combined.

**Comment by gruffvaughan** [comment]
Why is this bug closed when it is still very much an issue? Is there a fix planned?

**Comment by gedik25** [comment]
The application was launched in the latest version on September 21

**Comment by gegy1** [comment]
No need for the version trick.
Just do the following:

Make a new bottel
Run wintricks and install dotnet48
Install ubisoftconnect (download from website)

Works for Anno1800 starting from steam. (Steam launching ubisoft connect)

###Additional note: I hate ubisoft connect###

**Comment by bordplate** [comment]
> No need for the version trick. Just do the following:
> 
> Make a new bottel Run wintricks and install dotnet48 Install ubisoftconnect (download from website)

This doesn't work for me with Ubisoft Connect that came with Trackmania 2020 installed from Steam.

**Comment by gegy1** [comment]
> This doesn't work for me with Ubisoft Connect that came with Trackmania 2020 installed from Steam.

1.) Just make a new Bottle
2.) Install dotnet48 using winetricks
3.) Download Ubisoft connect from the ubisoft website
4.) Install Ubisoft connect
5.) Start ubisoft connect
6.) Install steam
7.) Download your game within steam
Now when you launch your game, the installed ubisoft client should be used and you should be able to play the game

**Comment by bordplate** [comment]
I messed around after installing dotnet48. Tried to change compat mode to WinXP and it told me to download Uplay, which I tried and it couldn't connect properly after 2FA, but had me uninstall Ubisoft Connect. Then I changed compat mode to Win7, reinstalled Ubisoft Connect from the installer that comes with Steam Trackmania, and now it works.

**Comment by waldi** [comment]
@bordplate deleting 

> drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache

indeed worked for me too!
