### ISSUE TITLE
[Bug]: 1.1.0 but not found winetricks menu

### ISSUE THREAD

**Issue by meritozh** [Whisky-App/Whisky#280]
### Description

in release log, from 1.1.0, whisky support winetricks, but I cannot found it.

### Steps to reproduce

download 1.1.0, open it

### Expected behaviour

<img width="768" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/7543300/476c48ae-76e7-4ca1-a6f7-b863dcfeda2e">

### Logs

```bash
no need log
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by meritozh** [comment]
https://github.com/IsaacMarovitz/Whisky/blob/16bf11a610b44d1082131574768dd9fcab431b6a/Whisky/Utils/Winetricks.swift#L13

my winetricks installed in `/usr/local/Cellar/winetricks`. how about just `which winetricks`?

**Comment by IsaacMarovitz** [comment]
Because we want ARM winetricks

**Comment by meritozh** [comment]
@IsaacMarovitz I'm intel-mac user, is intel winetricks not work? or some other reason?

**Comment by IsaacMarovitz** [comment]
> my winetricks installed in `/usr/local/Cellar/winetricks`. how about just `which winetricks`?

It's installed at `/usr/local/Cellar/winetricks` not `/usr/local/bin/winetricks`?

**Comment by IsaacMarovitz** [comment]
The reason I can't use `where` is that it's a zsh builtin, and for some reason, zsh does not give me a valid output if I try to execute this builtin using `/bin/zsh -c where winetricks`

**Comment by IsaacMarovitz** [comment]
Trying to use `where` from Swift is a nightmare. I got it working, but it can't seem to actually find anything.

**Comment by meritozh** [comment]
@IsaacMarovitz  the package location is `/usr/local/Cellar/winetricks`, bin location is `/usr/local/bin/winetricks`.

I have two mac, m1 and intel, will make a pr with test this weekend.
