### ISSUE TITLE
[Bug]: failed to open steam with argument setting after changing system to original language 

### ISSUE THREAD

**Issue by rayray9999** [Whisky-App/Whisky#294]
### Description

Following #191 ，I can open steam and everything works well.
But when I set system language to Chinese, it doesn't work even If I set the argument of steam.exe with LANG=en_US.
Registry Editor and Wine cannot show words.
Try to edit FontSubstitutes and change MS Shell Dig to Tahoma in Registry Editor and didn't work.
It's still the same after I set whisky to English by language setting. 
<img width="471" alt="截圖 2023-08-09 上午8 07 55" src="https://github.com/IsaacMarovitz/Whisky/assets/42163865/c8aea06f-138c-47b5-803e-6c4d56630504">

I think this problem is because Wine just using system language setting so the possible solution is setting Wine's argument to LANG=en_US.
But I'm not sure where to add it.
 I added some of .exe's argument to en_US in "Programs" and nothing happened.

### Steps to reproduce

Set the system language to Chinese

### Expected behaviour

none

### Logs

```bash
none
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
In Whisky 1.2.0+, the easiest way to fix this is by doing the following:
- Press the `Winetricks...` button on your bottle
- Run the `cjkfonts` command
- Follow any on-screen prompts
