### ISSUE TITLE
[Feature]: Enable running .bat files

### ISSUE THREAD

**Issue by johancedaniel** [Whisky-App/Whisky#296]
### Is your feature request related to a problem?

In order for the Horizon Zero dawn fix to work, i need to run a .bat file

https://github.com/Gcenx/WineskinServer/issues/424

### Describe the solution you'd like

Whisky should enable running .bat files

### Anything else?

N/A

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You can manually apply that fix to the registry without the usage of a bat file

**Comment by IsaacMarovitz** [comment]
I have added HZD to the game support wiki

**Comment by johancedaniel** [comment]
what is the  game support wiki ?

> I have added HZD to the game support wiki

**Comment by johancedaniel** [comment]
> I have added HZD to the game support wiki

I know about this solution, but the problem is that it automatically reverts to the original values and therefore the game still has slowdown issues

**Comment by faisalsayed10** [comment]
+1 @johancedaniel, the registry automatically reverts to the original even after changing the values
