### ISSUE TITLE
[Bug]: Windows path-based launching is inconsistent

### ISSUE THREAD

**Issue by Jayian1890** [Whisky-App/Whisky#304]
### Description

When I install a game. It doesn't open or work the normal way. Clicking run from within the icon, or the play arrow on the icon. It will only open if I use the Run button from the main bottle window where I have to locate and select the executable.

### Steps to reproduce

1. Install game(ex. Northgard)
2. Attempt to run game using normal means(run or play via icon)

### Expected behaviour

Clicking the play icon or run button within the icon should properly open/execute the game.

### Logs

```bash
Whisky Version: 1.1.0
Date: 8/13/2023, 12:34:53 PM
macOS Version: Version 13.5 (Build 22G74)
Bottle Name: Windows 10
Wine Version: 7.7.0
Wine Binary Version: 5
Windows Version: win10
Bottle URL: /Users/jayian/Library/Containers/com.isaacmarovitz.Whisky/Bottles/96DCB2C5-643A-4606-9951-11B10F5A8E83

Arguments: start C:\GOG Games\Northgard\Northgard.exe 

Launched Wine (2817)
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/jayian/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
Process exited with code 0
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Jayian1890** [comment]
https://youtu.be/JaIGWO1zL1U

Video showing issue

**Comment by Crd5** [comment]
Try to run holding shift

**Comment by Jayian1890** [comment]
Found the line in question. 

File: Whisky/Utils/Wine.swift
Line: 240
Modification: 
`return try await run(["start", "/unix", program.url.windowsPath()] + arguments,
                             bottle: program.bottle,
                             environment: program.settings.environment)`

Adding the "/unix" argument to this method fixes the issue I've describe above.
Clicking play or run from the icon causes the application to run as it normally should without having to manually select it.

**Comment by Jayian1890** [comment]
submitted the following pull-request that appears to fix the issue. https://github.com/IsaacMarovitz/Whisky/pull/307

**Comment by IsaacMarovitz** [comment]
> In the first attempt, it doesn't seem to be including the working directory. This appears to be the reason why. Maybe I can look through the code and figure out a fix.

I wonder if the issue is caused by the space in the path. Have you tried renaming the "GOG Games" folder to "GOG" or something to see if that resolves the issue?

**Comment by Jayian1890** [comment]
> > In the first attempt, it doesn't seem to be including the working directory. This appears to be the reason why. Maybe I can look through the code and figure out a fix.
> 
> I wonder if the issue is caused by the space in the path. Have you tried renaming the "GOG Games" folder to "GOG" or something to see if that resolves the issue?

It does not, it does the exact same thing.

**Comment by OxayMint** [comment]
> https://youtu.be/JaIGWO1zL1U

bruh..
