### ISSUE TITLE
[Bug]: Steam FPS counter doesn't work

### ISSUE THREAD

**Issue by QFSW** [Whisky-App/Whisky#309]
### Description

I created a Steam bottle and I cannot get the built in steam fps counter to work even though the games themselves work fine

### Steps to reproduce

1. Create a Steam bottle
2. Install any game (I tried Devil May Cry 5, Pizza Tower and Risk of Rain 2)
3. Enable the FPS counter in the Steam settings
4. Boot the game
5. Observe no FPS counter

### Expected behaviour

That an FPS counter would be displayed in the corner

### Logs

```bash
-
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Crd5** [comment]
You can use metal hud
