### ISSUE TITLE
[Bug]: audio loss after short bluetooth disconnect

### ISSUE THREAD

**Issue by pallazola** [Whisky-App/Whisky#312]
### Description

I have a total loss of audio from game if AirPods momentarily switch to different device. I can't get any audio from my games after the bluetooth disconnect, even if I switch output to speakers. 

### Steps to reproduce

Disconnect bluetooth headphones, then there is no sound from any new selected outputs or reconnected headphones.

### Expected behaviour

I would like to be able to change audio output.

### Logs

```bash
none captured
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is an issue with Wine as a whole. Unfortunately there is nothing we can do to resolve this.

**Comment by shreyanshk** [comment]
@IsaacMarovitz , do you have any link related to this issue on the upstream bug reporting system? I'm also facing similar issues but I didn't find related bug reports. Perhaps I am missing something here. Thanks.
