### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joecoool** [Whisky-App/Whisky#313]
### Description

<img width="1440" alt="Screenshot 2023-08-15 at 10 22 07 AM" src="https://github.com/IsaacMarovitz/Whisky/assets/121753437/749b487d-b535-47bd-98f9-be4fb1eda6fa">
epic games won't finish first launch

### Steps to reproduce

install epic games 

### Expected behaviour

play games

### Logs

```bash
Whisky Version: 1.1.0
Date: 8/17/2023, 8:57:16 AM
macOS Version: Version 14.0 (Build 23A5312d)
Bottle Name: games
Wine Version: 7.7.0
Wine Binary Version: 5
Windows Version: win10
Bottle URL: /Users/joecoool/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5B2BEB73-4732-4E65-AE20-B4011A9006B0

Arguments: start C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe 

Launched Wine (49838)
Process exited with code 0
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is a known general issue with Wine, not rly much I can do about it.
