### ISSUE TITLE
[Feature]: App run in all accounts including guest account

### ISSUE THREAD

**Issue by bolandnick18** [Whisky-App/Whisky#320]
### Is your feature request related to a problem?

I have few account and guest account enabled on my Mac. Is any possible you can add multiple account support so I can run the windows games and apps on my others users account?

it's would required to add others features that's has been requested by other users
https://github.com/Whisky-App/Whisky/issues/148

and 

https://github.com/Whisky-App/Whisky/issues/107

### Describe the solution you'd like

I would like to run a windows app and game from others users account including guest account without display permission error

### Anything else?

https://discussions.apple.com/thread/6976256

also this will needed to be tested to make sure there permission error will not display in others users account like its did with play cover macOS

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
The thing is:
a. This would take re-architecturing how Whisky store its bottle and runtime
b. It requires you as the admin to be able to set correct permissions
c. Straight up won't work on Macs with FileVault.
