### ISSUE TITLE
[Bug]: Everytime Whisky is relaunched it keeps requesting for the GTPK DMG even though I had already put it.

### ISSUE THREAD

**Issue by aa830** [Whisky-App/Whisky#321]
### Description

N/A

### Steps to reproduce

N/A

### Expected behaviour

I expected it accepts the GTPK DMG once and never asks again.

### Logs

```bash
N/A
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by virusman** [comment]
Could be related to GPTK beta 4.

**Comment by ElectricS01** [comment]
This is due to GPTK beta 4 changing a file path, here is a temporary fix from @ohaiibuzzle `ditto '/Volumes/Game Porting Toolkit-1.0/redist/lib/' ~/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib` Make sure you keep GPTK mounted while you use it

**Comment by johancedaniel** [comment]
yes, this issue is regarding GPTK 1.04. How long would a fix take?

**Comment by ElectricS01** [comment]
> yes, this issue is regarding GPTK 1.04. How long would a fix take?

See #322

**Comment by aa830** [comment]
> This is due to GPTK beta 4 changing a file path, here is a temporary fix from @ohaiibuzzle `ditto '/Volumes/Game Porting Toolkit-1.0/redist/lib/' ~/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib` Make sure you keep GPTK mounted while you use it

Unfortunatley I do not have access to the DMG if anyone could help me (bcos of account restrictions)
