### ISSUE TITLE
[Bug]:  Mount for the Game porting toolkit 1 beta 4 no more working 

### ISSUE THREAD

**Issue by akeschmidi** [Whisky-App/Whisky#328]
### Description

I download the new version from the GPT beta 4 and after a boot the app asking for the mount  

### Steps to reproduce

Open Whisky in the newest version with beta 3 Version -> id works 
Replace with the new one beta 4 and reboot the app and the same question pop up 

### Expected behaviour

mounting word fine as in beat 3

### Logs

```bash
nothin
```

### What version of Whisky are you using?

1.1.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
We're running into some extremely inconsistent behavior between builds to builds using the same source code (somehow cloning `main` and recompiling got it to work, and even that can be broken if built enough times).
I am not even sure if there is a possible race condition (shouldn't be) or literally Xcode beta generating bad code somehow.

**Comment by ohaiibuzzle** [comment]
@akeschmidi Could you go into System Settings > Privacy & Security > Full Disk Access and add Whisky there?

**Comment by joelmgallant** [comment]
^ Jumping in here, I just tried the above - same issue -- GPTK fails to install silently.
Version 1.1.0 (17)
Removed & re-added Full Disk Access / restarted Whisky.

Actual error displayed when launching via console:
`Error Domain=NSCocoaErrorDomain Code=516 "The file “D3DMetal.framework” couldn’t be saved in the folder “lib” because a file with the same name already exists." UserInfo={NSFilePath=/Users/joelmgallant/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/D3DMetal.framework, NSUnderlyingError=0x600002fd74b0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
`

**Comment by akeschmidi** [comment]
unfortunately both ways have not solved the problem for me

**Comment by joelmgallant** [comment]
Cleaning up:
`rm -rf "~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/"`
and re-installing does not appear to help - the same errors recur on attempting GPTK install.

**Comment by ohaiibuzzle** [comment]
@joelmgallant That error is basically the symlink creation failing which usually is fine

The more interesting errors that is popping up is `ditto` failing to copy the framework altogether. I have observed this
The strange issue is that if you just clone the repo, and then build it with Xcode on your machine, it somehow work with no code changes

**Comment by ohaiibuzzle** [comment]
Here is literally `main` rebuilt with Xcode 15 beta 5 with zero code changes (I literally just hit Archive after setting my developer signatures)

[Whisky.dmg.zip](https://github.com/Whisky-App/Whisky/files/12422388/Whisky.dmg.zip)

**Comment by joelmgallant** [comment]
^^ confirmed, that *does* work on my end 🤔

**Comment by ohaiibuzzle** [comment]
Yeah, me and Issac have been basically headbanging at this on Discord for the last hour or so, because unless somehow the Xcode compiler optimized the code in such a manner where `hdiutil` manages to unmount the volume before `ditto` finishes, there is basically no other explaination

**Comment by mantralunar** [comment]
I don't know if this is any help but I ran into the same errors. Whisky appears to be looking for the libs in '/Volumes/Game Porting Toolkit-1.0/libs' however in the latest dmg the libs are actually located in'/Volumes/Game Porting **Toolkit-1.0/redist/libs**. I extracted the dmg and repacked using diskutil removing the redist directory and GPTK installation in Whisky now reporting as installed.

**Comment by ohaiibuzzle** [comment]
@mantralunar We had a **brief** release of 1.1.1 yesterday which was **supposed** to fix it

But we're noticing inconsistencies in the release code so we're pulling it to investigate
