### ISSUE TITLE
[Feature]: Create a Whisky bottle via CLI?

### ISSUE THREAD

**Issue by DanMossa** [Whisky-App/Whisky#331]
### Is your feature request related to a problem?

I want wondering if it would be possible to create a bottle via CLI?

The end goal is someone can download Whisky.
A script creates a bottle
The user opens Whisky and a bottle is there.

### Describe the solution you'd like

I'd love for there to be some sort of CLI I can use to create a Bottle that will appear in Whisky

### Anything else?

I'm okay if everything is the default settings.
Just want there to be a Bottle.
I'm okay if there also needs to be manual intervention when first installing Whisky and loading it.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I've started work on this in the latest commits. The plan is to support the following commands:

- Create (Create new bottle)
- Add (Add existing bottle)
- Export (Export existing bottle)
- Delete (Delete existing bottle)
- Remove (Remove existing bottle)
- Install (Install dependencies Wine/GPTK)
- Uninstall (Uninstall dependencies Wine/GPTK)

Currently, the plan is to use some XPC to communicate between the CLI tool and the Whisky.app, which would result in the Whisky.app being opened for the execution of commands. It is possible that I can make this tool standalone if people would prefer, but that would take a fair amount of restructuring of Whisky's source code into an external library that could then be used by the CLI tool and the app (I don't want to have duplicate code).

**Comment by DanMossa** [comment]
@IsaacMarovitz 
You're an actual wizard. This would be incredible!
