### ISSUE TITLE
[Bug]: Don't install GPTK beta 4

### ISSUE THREAD

**Issue by popcorn2d** [Whisky-App/Whisky#334]
### Description

The installation of the 4th version does not work, when you drag the image to the area where you need to drag it, nothing happens, everything is fine with the 3rd version

### Steps to reproduce

Download new version
Drag an image to an area

### Expected behaviour

install GPTK v4

### Logs

```bash
no logs
```

### What version of Whisky are you using?

1.1.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This has been resolved. Update to the re-release of 1.1.1
