### ISSUE TITLE
[Bug]: When I have uninstalled game on steam , the disk space it occupied failed to release

### ISSUE THREAD

**Issue by clearluyy** [Whisky-App/Whisky#337]
### Description

I downloaded elden ring by steam , but after I uninstalled it , I checked steam storage and it showed elden ring still occupied my disk space. However, on apple's native settings , my disk space dosen't have any problem .  This might be a wine problem .

### Steps to reproduce

1. open steam through whisky ,
2. download a game.
3. uninstall it
4. check steam storage page .
5. disk space it occupies dosen't release

### Expected behaviour

Provide some  ways that could fix this problem

### Logs

```bash
none
```

### What version of Whisky are you using?

1.1.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
There is not a lot we can do to improve this. This is mostly down to how APFS treats purgable space. You can try restarting, as that can free up caches and other such temporary files.

**Comment by clearluyy** [comment]
> There is not a lot we can do to improve this. This is mostly down to how APFS treats purgable space. You can try restarting, as that can free up caches and other such temporary files.

I have solved this problem .The game I uninstalled became cache flies, I found them in Finder and deleted. Thanks a lot!

**Comment by clearluyy** [comment]
> There is not a lot we can do to improve this. This is mostly down to how APFS treats purgable space. You can try restarting, as that can free up caches and other such temporary files.

I have solved this problem .The game I uninstalled became cache files, I found them in Finder and deleted. Thanks a lot!

**Comment by PlGGS** [comment]
> The game I uninstalled became cache files, I found them in Finder and deleted. Thanks a lot!

Where did you find them in Finder? I can't seem to find them cached in my Library directory

**Comment by clearluyy** [comment]
> > The game I uninstalled became cache files, I found them in Finder and deleted. Thanks a lot!
> 
> Where did you find them in Finder? I can't seem to find them cached in my Library directory
> 
> Edit: Fixed it by downloading a large file and then my os finally purged the data. I had restarted multiple times without it being purged before

the current version seems not to happen this situation. When uninstalled a game, just wait long enough to let mac clean cahes automatically.

**Comment by Rapsag1668** [comment]
Just to know how much time you waited please ?
