### ISSUE TITLE
[Feature]: Utilizing Sonoma's Game Mode

### ISSUE THREAD

**Issue by Ferbez** [Whisky-App/Whisky#341]
### Is your feature request related to a problem?

Wine doesn't trigger Sonoma's Game Mode. I've done a bit of testing and it looks like it triggers when an application with `LSApplicationCategoryType` set to `public.app-category.games` or similar (macOS allows specifying game genres, check [here](https://developer.apple.com/documentation/bundleresources/information_property_list/lsapplicationcategorytype)) in `Info.plist` launches in fullscreen mode (and it looks like it has to be native fullscreen - as seen in No Man's Sky). It doesn't matter whether game launches via Rosetta 2 or natively - Divinity: Original Sin 2 also triggers Game Mode when launched in windowed mode and then maximised to the fullscreen.

### Describe the solution you'd like

I've been playing around myself and haven't found a solution. Wine executables (`wine64`, `wine64-preloader` and `wineserver`) have `Info.plist` embedded, which don't have `LSApplicationCategoryType` set to `public.app-category.games`, but manually adding it still doesn't trigger Game Mode.

### Anything else?

Apple sadly doesn't have any kind of hints about how Game Mode is triggered. Probably Game Mode isn't triggered because there's a few background Wine processes? If only there'd be a command line argument for manually triggering Game Mode...

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Apple currently doesn't have an API for manually triggering game mode. They do have a utility in the Xcode 15 beta called `gamepolicyctl`, which can be used to trigger game mode manually, but the API behind this is currently private.

**Comment by Ferbez** [comment]
Fiddled around once more - it IS possible to trigger Game Mode with Wine. Game Mode only looks at specific `LSApplicationCategoryType` as described before. I've been able to trigger it building a separate Wine wrapper: separate .app with proper `LSApplicationCategoryType` in `Info.plist` and simple executable (compiled shell script with shc) which launches game of the choice. This still requires game to be able to work in maximizable windowed mode - in my example, Warframe works perfectly this way.
<br />
<img width="1440" alt="Снимок экрана 2023-08-31 в 22 07 23" src="https://github.com/Whisky-App/Whisky/assets/30198857/1ad9a261-1a0d-4edc-a156-c21b9897d9ad">
<br />
It is possible to force any game to work in this kind of windowed mode though - however, I've only tested it on Wreckfest and did it pretty dirty (just forced Wine to make all windows maximizable).

**Comment by hxhelm** [comment]
@Ferbez Do you have more detailed instructions for how you started the game using your shell script? Also, do you have to configure the maximizable windowed mode beforehand or does that trigger automatically when game mode is active?
I would also be interested if you found any improvments in Warframe specifically when using game mode.

**Comment by Ferbez** [comment]
@hxhelm I've described all conditions for Game Mode above - Wine must be bundled into .app (all wine executables must be located in /Contents/MacOS), which must have `LSApplicationCategoryType` set to `public.app-category.games` and game must run in maximizable windowed mode (that obviously doesn't trigger automatically, thankfully Warframe support it natively), though it is possible to force Wine to make any app maximizable. I'm not sure about performance improvements - I'm using base M1 MacBook Air and biggest issue for me is 8 GB of RAM and lack of active cooling
