### ISSUE TITLE
[Feature]: Cancel Button during OnBoarding

### ISSUE THREAD

**Issue by ultratiem** [Whisky-App/Whisky#346]
### Is your feature request related to a problem?

Yes. From UX, the UI needs to service an escape. Currently the only options are to proceed or shutdown the app.

### Describe the solution you'd like

A cancel button to enable users to simply opt out and return to the main screen.

### Anything else?

![Screenshot 2023-08-31 at 2 34 27 PM](https://github.com/Whisky-App/Whisky/assets/2991193/3cfd5179-878a-44c1-9b63-82a47d4f36ad)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
It's not so intuitive, but pressing "Next" here will accomplish that.

**Comment by ultratiem** [comment]
In that case a prime solution would be that if the user is all green, next reads cancel. If they are missing anything, then next is next and will take them thru the on-boarding.
