### ISSUE TITLE
[Bug]: application requires apple silicon [intel]

### ISSUE THREAD

**Issue by woile** [Whisky-App/Whisky#350]
### Description

I'm trying to run games through steam. 

I'm now trying to run "Hogwarts Legacy", which according to [this](https://www.applegamingwiki.com/wiki/Hogwarts_Legacy) should be playable. I've tried Doom and Mass Effect Andromeda with the same error.

But when I open the game using steam, either I see an error (see image) or it just stays in background with "running".

<img width="328" alt="Screenshot 2023-09-02 at 12 23 57" src="https://github.com/Whisky-App/Whisky/assets/2585816/ed653232-c158-421d-a5e9-edd82a9e0db7">

I'm running on an intel mac with sonora:

```
MacBook Pro
16-inch, 2019
i9
AMD Radeon Pro 5500M
14.0 Beta (23A5337a
```

Any thoughts on what might be the issue or how to configure properly? 

### Steps to reproduce

1. Install `steam.exe`
2. Log in
3. Choose "Hogwarts legacy" and install
4. Click on "Play game"

Observe that it says "running" or an error is thrown

### Expected behaviour

Game opens

### Logs

```bash
how? couldn't find any button for logs
```

### What version of Whisky are you using?

1.2.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by alexsch01** [comment]
If this is intended behavior I will need to update: https://github.com/Whisky-App/Whisky/pull/342

**Comment by alexsch01** [comment]
@IsaacMarovitz this is intended behavior now

**Comment by woile** [comment]
Oh that's sad, what's the reason for it not working? Is there anything we can do? I wouldn't mind testing and reporting back

**Comment by alexsch01** [comment]
@woile apple dropped support for ventura in GPTK in latest version and Whisky automatically installs the latest version now

**Comment by IsaacMarovitz** [comment]
The source you need is in the screenshot you attached to the issue. It specifically states it requires Apple Silicon.
