### ISSUE TITLE
[Feature]: Download base DirectX from Microsoft to install

### ISSUE THREAD

**Issue by Grien25** [Whisky-App/Whisky#356]
### Is your feature request related to a problem?

Hello

I was wondering if we could get an installation of Direct X working. I understand GPTK has directx inside of it, but their are some components it does not cover. 

### Describe the solution you'd like

If GPTK could implement those features and process the download, we cna get a proper version of the full directx working on whisky. It currently works on crossover, but I want to offer a free service to some of my mates who cant purchase crossover rn.

### Anything else?

Heres the link:

https://files.holarse-linuxgaming.de/mirrors/microsoft/directx_Jun2010_redist.exe

Thanks!

### Issue Language

- [X] Yes my issue is written in English

**Comment by sorae42** [comment]
DirectX library can be set in the Wine Configuration > Libraries.
Whiskey should include some essential libraries, just like CrossOver did.

**Comment by Grien25** [comment]
How do you set the library in wine config? any links?

**Comment by sorae42** [comment]
In the Bottle config.

<img width="1012" alt="Screenshot 2023-09-18 at 21 53 16" src="https://github.com/Whisky-App/Whisky/assets/34794115/c4432df4-5126-47f8-a618-68890f9f0368">

**Comment by sorae42** [comment]
Then you can add a "library override" here.
<img width="522" alt="Screenshot 2023-09-18 at 21 54 31" src="https://github.com/Whisky-App/Whisky/assets/34794115/cf9af8dd-c31e-4e6e-b7ce-d03e3906ca2e">

**Comment by sorae42** [comment]
You can use `winetricks` to install DirectX (only if they are not present in the Wine configuration).

**Comment by 12people** [comment]
@sorae42 What library should I override in wine configurations? How do I install directx with Winetricks if I need to?

**Comment by 12people** [comment]
@IsaacMarovitz 
I think what @Grien25 might have been referring to is that installing the [directx_Jun2010_redist.exe](https://files.holarse-linuxgaming.de/mirrors/microsoft/directx_Jun2010_redist.exe) package, which seems to be required for games like AoE II:DE, currently fails in Whisky with this message:

<img width="317" alt="Screenshot 2023-10-16 at 09 17 09" src="https://github.com/Whisky-App/Whisky/assets/7361228/4282cf87-92b1-4edc-b0c3-fd158192ca5b">

(To install, the exe has to unpack files into a folder first and then the unpacked `DXSETUP.exe` needs to be run.)

It does NOT fail when run inside of CrossOver, however.

I'm attaching the log files in case they are helpful:

[DirectX.log](https://github.com/Whisky-App/Whisky/files/12913344/DirectX.log)
[DXError.log](https://github.com/Whisky-App/Whisky/files/12913345/DXError.log)

**Comment by erthru** [comment]
@12people, same with me, i need to install the directx to play my childhood online game called dragon nest, tried in crossover and it’s working without any issue, want to use whiskey because its free, but stuck on installing the directx, the game force close when entering the town (crossover also has this issue but when i installed the directx the issue fixed)
