### ISSUE TITLE
[Feature]: Add option to choose wine version including the latest master

### ISSUE THREAD

**Issue by effolkronium** [Whisky-App/Whisky#357]
### Is your feature request related to a problem?

Including the latest built master from https://gitlab.winehq.org/wine/wine

### Describe the solution you'd like

Built custom wine versions from source directly from https://gitlab.winehq.org/wine/wine

### Anything else?

Select wine version in config menu. Load all version by parsing wine branches wine-X.XX

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
GPTK is based on CX 22 which is based on Wine 7. We cannot upgrade.
