### ISSUE TITLE
[Feature]: Programs and Games won’t run without .Net Framework 2.5 to 4.8.2

### ISSUE THREAD

**Issue by bolandnick18** [Whisky-App/Whisky#361]
### Is your feature request related to a problem?

I was wondering if we could get an installation of .Net Framework 2.5 to 4.8.2 working on Whisky

The reason I am asking because I know there are windows programs and games won’t run without it.

### Describe the solution you'd like

I was wondering if we could get an installation of .Net Framework 2.5 to 4.8.2 working on Whisky

The reason I am asking because I know there are windows programs and games won’t run without it.

### Anything else?

<img width="1100" alt="Screenshot 2023-09-06 at 3 37 54 PM" src="https://github.com/Whisky-App/Whisky/assets/40327737/1f146a7a-0767-405f-b045-e2a3ff3c9254">
<img width="561" alt="Screenshot 2023-09-06 at 3 42 30 PM" src="https://github.com/Whisky-App/Whisky/assets/40327737/76b1ac25-6bd7-4eb0-86b1-a32a2333a4b9">

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
.NET Framework 4.8 can be installed using the Winetricks command `dotnet48`
