### ISSUE TITLE
[Feature]: Programs and Games won’t run without Microsoft Webview2 runtime

### ISSUE THREAD

**Issue by bolandnick18** [Whisky-App/Whisky#362]
### Is your feature request related to a problem?

I was wondering if we could get an installation of Microsoft Webview2 runtime working on Whisky

The reason I am asking because I know there are some windows programs and games won’t run without it.

### Describe the solution you'd like

I was wondering if we could get an installation of Microsoft Webview2 runtime working on Whisky

The reason I am asking because I know there are some windows programs and games won’t run without it.

### Anything else?

https://developer.microsoft.com/en-us/microsoft-edge/webview2/

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
WebView2 can be downloaded here https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/fbf928f5-dd43-4f7f-94ed-75cc22fc8141/Microsoft.WebView2.FixedVersionRuntime.105.0.1343.25.x64.cab

**Comment by chulinx** [comment]
> WebView2 can be downloaded here https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/fbf928f5-dd43-4f7f-94ed-75cc22fc8141/Microsoft.WebView2.FixedVersionRuntime.105.0.1343.25.x64.cab

do u have some method to install cab file in whisky

**Comment by brewagebear** [comment]
@IsaacMarovitz I think I need to use cmd.exe to install the Cab file, is this possible?
