### ISSUE TITLE
Add Wiki to main repo + Add Baldur's Gate 3 Game support in wiki

### ISSUE THREAD

**Issue by pelmered** [Whisky-App/Whisky#371]
Unfortunately, GitHub does not support PRs for Wiki. Therefore it would be great if you could add the wiki as a folder in the main repo and the automatically publish that folder to the Wiki, for example with a GitHub action. That way you can have support for PRs for the Wiki as well and have the community contribute. 

I added Baldur's Gate 3 to the Game support page on the wiki here: https://github.com/pelmered/Whiskywiki/commit/4d8862809fe0c727ab139b6c0a7a039021679e8e
As you can see, this workflow is not that that great and I think the community can add a lot of value.

If you think this is a good idea, I can make an attempt to create a GitHub action for this.

**Comment by IsaacMarovitz** [comment]
BG3 has been released on Mac, so adding it to the wiki is no longer necessary. I'm fine with people opening issues to request new pages on the wiki.
