### ISSUE TITLE
[Bug]: Text error

### ISSUE THREAD

**Issue by lpgneg19** [Whisky-App/Whisky#374]
### Description

After three versions, this text is still wrong
<img width="1043" alt="截屏2023-09-12 10 03 03" src="https://github.com/Whisky-App/Whisky/assets/138191911/e6ef0bc2-330a-4c55-ab0d-80ce4a705914">

### Steps to reproduce

Displayed when the bottle is deleting

### Expected behaviour

Display correct copy

### Logs

```bash
none
```

### What version of Whisky are you using?

1.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fix pushed
