### ISSUE TITLE
[Feature]: Suggestions for polishing the Whisky.app installation experience for brand new users (who have never seen Whisky before)

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#375]
### Is your feature request related to a problem?

Thanks for making Whisky, the UI is looking very nice!

However: I downloaded and installed Whisky and tried to look at the experience from the point of view of a "normal" brand new user who has never *ever* seen Whisky / Wine / whatever before (and isn't an "enthusiast" yet). Then I decided to ***very*** pedantically write down ***everything*** I think could be improved.

Some of the following problems are pretty minor, but I think still worth fixing. I hope these will be helpful. Please let me know if you want a separate issue for each problem instead.

**(Steps to reproduce:)**

1. Temporarily move/relocate ("remove") ***everything*** previously installed by Whisky, to see what a brand new user would see (i.e. someone who has never seen Whisky before and is installing it for the very first time)
2. Download Whisky and install it (try to see everything from the point of view of a brand new user)

### Describe the solution you'd like

6 separate things, in chronological order (a new user downloads and installs Whisky for the very first time):

-----------
- [x] 1) The new user probably downloaded the .zip file to ~/Downloads. If the user accidentally tries to launch Whisky.app from ~/Downloads (before first knowing how to manually move it to `/Applications`, because this is not the standard way to install macOS applications), is it possible for Whisky to move `Whisky.app` to `/Applications` automatically? Something like https://github.com/potionfactory/LetsMove/ or similar?

-------------
- [ ] 2) Here's the first thing the brand new user sees after launching Whisky.app (screenshot below). There are approximately 8 billion people in the world who don't know what "GPTK" means, so this is a good opportunity to teach some slang / terminology (suggestion: "GPTK (Game Porting Toolkit) not installed" or something like that) 

edit: also add tooltips that further explain what Rosetta and GPTK do, copy the text from the respective installation dialogs

<img width="300" alt="GPTK not installed" src="https://github.com/Whisky-App/Whisky/assets/42669366/be96fac8-ff48-45ac-9ed6-a99af489922a">

-------------
- [ ] 3) also add an explanation for what "Rosetta" means: "Rosetta Intel translator installed", or "Rosetta Translation Environment installed" or something like that

-------------
- [x] 4) After that, most users will see the GPTK download screen (screen recording below). It's unnecessarily bouncy and flickery. Try aligning the text right and/or use a monospace font at least for the numbers, and don't update the text so often (and especially don't update the "n (I mean n-1, I mean n again) seconds remaining" number so often), so that the text doesn't bounce and flicker?

edit: Also, the downloading screen is a great opportunity to educate the new user (not sure what to say here, but I think `GPTK`,  `D3DMetal` and `Wine` should all be explained): _"GPTK (Game Porting Toolkit) provides D3DMetal, which improves support for DirectX 11-12 games. Wine allows Windows games and applications to run on your Mac."_ (please keep the help text on the screen (to give the user time to understand it), even after the installation is ready, until the user manually dismisses the dialog) (btw my example wording was originally influenced by the wording of the "Installing Rosetta" dialog, screen shot [here](https://github.com/Whisky-App/Whisky/assets/42669366/626e3c6f-2b9a-4ef5-993e-5cfeedd2e4fa))

https://github.com/Whisky-App/Whisky/assets/42669366/7f835d23-5f8c-4794-afa0-ea2f59f26436

-------------
- [x] 5) Next, the user sees the random word "Bottle" (screenshot). The user has to be able to guess that it's a pun involving Whisky (Wine) and bottles or something. Here's another opportunity to explain the slang word used here, and/or even better, use a more normal/standard word
<img width="313" alt="explain_what_bottle_means" src="https://github.com/Whisky-App/Whisky/assets/42669366/e8512391-f425-4f0d-9bf9-54f8575eb132">

-------------
- [x] 6) Next, while trying to make the new "bottle", the text in the dialog shows the "Bottle path" truncated in the middle (I see something something "C...isky"). At least show a tooltip when the mouse cursor is hovering over the the path, and/or find a way to show the whole path somehow (or hide the path for now, is it necessary for the path to be visible here)?

<img width="415" alt="at_least_add_a_tooltip" src="https://github.com/Whisky-App/Whisky/assets/42669366/a680af63-d815-43dd-aafc-9de80bf602b7">

### Anything else?

OK, I'm done here. Thanks for considering these!

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Issue 1 has been implemented for a while.

Issue 5, Bottle is the standard vocabulary in Wine managers.

Issue 6, your text is larger than normal (probably due an accessibility option), normally, the full path is visible.

**Comment by IsaacMarovitz** [comment]
Alright most of this has been completed and I'm less sure about the other suggestions so I'm gonna mark this as done
