### ISSUE TITLE
[Feature]: Hide the "default" iexplore.exe, wmplayer.exe and wordpad.exe programs from the list of installed programs by default

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#376]
### Is your feature request related to a problem?

The "Installed programs" list shows "`iexplore.exe`", "`wmplayer.exe`" and "`wordpad.exe`" (each one twice!), none of which are probably what the user was looking for.

They are just unnecessarily cluttering the view and hiding the "real" installed programs.

<img width="858" alt="unnecessary_programs_in_installed_programs_list" src="https://github.com/Whisky-App/Whisky/assets/42669366/ae230460-0994-437a-b0d4-3dfc507ee399">

### Describe the solution you'd like

Suggestion: hide the "default" programs (`iexplore.exe`, `wmplayer.exe` and `wordpad.exe`) from the list of installed programs by default.

Maybe they can still be accessible from a submenu ("Default Wine programs") or something like that, if somebody really wants to launch one of them for some reason, but please don't show them by default.

### Anything else?

Nope, thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Added a blocklist (empty by default), but you can add these programs
