### ISSUE TITLE
[Bug]: UI bug: unnecessary toolbar icon?

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#377]
### Description

Is this an unnecessary toolbar icon?

### Steps to reproduce

1. Click the >> icon

What was supposed to happen? Can the icon just be removed?

Here's a screen shot that shows what happened when I clicked the icon:
<img width="903" alt="unnecessary_icon" src="https://github.com/Whisky-App/Whisky/assets/42669366/98f44bfd-1513-42d8-94b3-6854fa189c57">

### Expected behaviour

I don't know what the button is supposed to do.

### Logs

```bash
UI bug, no Wine logs. (Or should I have used the "Feature" template instead?)
```

### What version of Whisky are you using?

1.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Not a bug, this is what SwiftUI does when you shrink the window. Expanding the window will remove that extra icon and move the original icon to it's place.

**Comment by IsaacMarovitz** [comment]
You need to make the sidebar wider
