### ISSUE TITLE
[Bug]: Not authorized to send Apple events to Terminal when use Winetrick

### ISSUE THREAD

**Issue by micturkey** [Whisky-App/Whisky#378]
### Description

I need Winetrick to install d3dx9, but it opens terminal and popups "Not authorized to send Apple events to Terminal".
<img width="372" alt="image" src="https://github.com/Whisky-App/Whisky/assets/1297392/470d7f01-0e7a-4896-9ea3-937515d1ef63">

I checked Automation in MacOS setting but no whisky appears there.
<img width="827" alt="image" src="https://github.com/Whisky-App/Whisky/assets/1297392/90713aac-be2f-4105-8943-8221521b8ffc">

I also tried resetting the Apple events permission's database using `tccutil reset AppleEvents` but it doesn't work as well.
### Steps to reproduce

Click winetrick, input 'd3dx9' or everything, then it popups.

### Expected behaviour

It should open terminal and input correct instructions.

### Logs

```bash
Maybe no need?
```

### What version of Whisky are you using?

1.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by the-eternel** [comment]
I had the same issue, but if you run the app through terminal (/Applications/Whisky.app/Contents/MacOS/Whisky), then you can run the winetricks

**Comment by micturkey** [comment]
> I had the same issue, but if you run the app through terminal (/Applications/Whisky.app/Contents/MacOS/Whisky), then you can run the winetricks

Thanks, I will try it

**Comment by IsaacMarovitz** [comment]
macOS is meant to prompt the user for the permissions when Whisky first tries to do this. Nothing I can really to resolve this on my end.

**Comment by amckinlay** [comment]
You can reset it `Preferences > Privacy & Security > Automation`.
<img width="827" alt="Screenshot 2024-03-15 at 12 10 04 AM" src="https://github.com/Whisky-App/Whisky/assets/1351003/57b2636a-4080-4bac-826b-c371209df7cc">
