### ISSUE TITLE
[Feature]: Make it easier to launch new programs/games (and add/launch Shortcut icons)

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#380]
### Is your feature request related to a problem?

Launching newly installed programs/games (and launching or *manually* adding Shortcut icons) is unnecessarily difficult/unintuitive, especially for brand new users (who have never seen the Whisky UI before and haven't already learned its current idiosyncrasies).

- The user has to figure out that you have to click the little green triangle of the Shortcut icon to actually launch the program (clicking the Shortcut icon itself weirdly does something completely different(**!**))

_edit: if the user wants to run a program that doesn't automatically have a Shortcut (doesn't add itself into the Start Menu), this is what the new user has to realize:_
- _First the user has to find (and open) the "Programs >" menu_
- _and then figure out that the "play button" (▶) (no tooltip) launches the program, but..._

(edited slightly) ...also, ***manually*** adding a Shortcut icon is unnecessarily difficult/unintuitive:
- The user has to know/guess that "Programs >" is where Shortcuts are added
- Then know/guess that the star (☆) icon (no tooltip) in "Programs >" must be clicked to add a `program.exe` Shortcut

### Describe the solution you'd like

Suggestions / ideas:

First of all, in the "Installed Programs" menu:
- add a tooltip to the (▶) in "Programs >" (the icon that launches `program.exe`)
- consider changing the default action for clicking the `program.exe` name in "Programs >" to -> "star" ⭐ the application (edit: and also add a tooltip when hovering over the `program.exe` name) instead of whatever happens now (info/config)
~~- - (...or maybe to launch it(?) when clicking the name?)~~
- - (...and add an icon, ⚙️ or something, (and a tooltip) to do what currently happens when clicking on the name of `program.exe`)

Make it easier to manually add a `program.exe` Shortcut icon to Whisky UI:
- show something (a green star, (edit: or maybe a small blue dot 🔵), or colorful help text "New programs installed" or whatever) in the UI next to "Programs >" to indicate there are newly added items in the "Installed Programs" list since last opening the menu
- add a tooltip to the "☆" star icon to explain what it does
- add a notification or whatever somewhere in the UI ("Shortcut added") when the "☆" star is clicked
- or at least scroll the list to the beginning so the user notices that the star icon changed when clicked (->⭐) (edit: this is relevant when the list of programs is very long)

Make Shortcut icons in Whisky UI more intuitive to launch:
(edited these: launch by double-clicking, to match normal macOS / Windows / Linux behavior)
- make **double-clicking** the icon launch the application
- make **single-clicking** the icon do nothing (just select it, try to mimic normal macOS Finder behavior)
- remove the "little green triangle" from the icon
- move the info/config/whatever (current default action for clicking a Shortcut icon) into the context menu
- - (and/or maybe show a different little icon, ⚙️ or something, but only if the Shortcut is currently selected, or something?)
- also maybe add a tooltip to Shortcut icons ("Double-click to launch/start/open the_name_of_the_program")

edit: this is only needed for programs that don't add a Start Menu item: _PS. Of course it would be great if Whisky also (at some point in the future) *automatically* "starred" (⭐) newly installed .exe files (yes, e.g. Steam also installs lots of superfluous stuff, but extra junk could be special cased / heuristically detected and avoided or whatever)_

### Anything else?

Nope, thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by luixo** [comment]
There is more to this issue: there is still no way (or not obvious for me) to add an arbitrary program (say, installer) to a list of installed apps in the bottle.
In my case installer requires specific wine env variables that can only be set if I open a cog icon in installed programs, but I can't get it there.
