### ISSUE TITLE
[Feature]: Make it easier to install Steam (automatically)

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#382]
### Is your feature request related to a problem?

I believe many/most Whisky users will want to install and run (the Windows version of) Steam.

Currently brand new users (who have never seen the Whisky UI before and haven't already learned its current idiosyncrasies) will have to figure out how to do that manually, i.e.:

- Know/guess that a "bottle" is an emulated Windows environment / container of some sort
- Know/guess that Steam currently requires a Windows 10 "bottle", and make a new win10 "Steam" bottle
- Figure out how to manually download (the Windows version of) the Steam installer
- Know how to install Steam inside that bottle (issue #381)
- Then figure out how to actually launch Steam (issue #380)

### Describe the solution you'd like

It would be exceptionally good "customer service" if Whisky had a way to automatically install Steam, or even offered to do it automatically for brand new users (to save their time)!

**Suggestion:**
After a new user has installed Whisky, currently Whisky shows this:
"Create your first bottle to get started
[+ Create Bottle]"

What if Whisky also had a [+ Install Steam] button, or automatically showed a dialog ("Would you like to install Steam (into a new Windows 10 bottle "Steam")?

And then automatically do these things (to save the user's time and effort):
- Create a new Windows 10 bottle "Steam" automatically
- Download the Windows version of the Steam installer (`https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe`)
- ...and run SteamSetup.exe inside the new bottle to install Steam

### Anything else?

Nope, thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The reason why I avoided implementing like this is cause it has potential to become incredibly complicated and bloated. Ideally, we would want to recreate a system similar to CrossOver's CrossTies, which automate the installing of programs, as well as providing dependencies, and workarounds.

It's definitely possible, but we do need to carefully draft and evaluate the best way to proceed with a system like this before trying.

**Comment by ohaiibuzzle** [comment]
@rxhfcy Issues being that it is also very easy to swing the issues in the other direction and have the user not knowing what they need to do if they want to, eg. having separate environments for games that needs different configurations (one retina mode, one normal).

I think the learning curve on Wine basics should still exist, this is how most prefix managers (eg. Bottles on Linux) works

**Comment by IsaacMarovitz** [comment]
In order not to overstep on CrossOver's turf, I've decided we're not going to be implementing something like this for now.

**Comment by d9j** [comment]
@rxhfcy then whisky project serves no purpose . if you are basically sold out to crossover!

**Comment by GabCoolDude** [comment]
@d9j Whisky is not sold out to CrossOver, It is a standalone open-source project.

The only thing that is affiliated with CrossOver is our use of cx-wine 7, which is a fork of wine that is used by CrossOver, and our affiliate link that we have setup with them in order to avoid hostilities with CrossOver.
