### ISSUE TITLE
[Feature]: Rename "Create Shortcut" button (because otherwise "Shortcut" means two different things)

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#383]
### Is your feature request related to a problem?

Currently "Shortcut" means two different things in the Whisky UI:
1) The shortcut icons in Whisky UI are called "Shortcuts" (right click an icon: "Delete Shortcut")

<img width="183" alt="Shortcut" src="https://github.com/Whisky-App/Whisky/assets/42669366/d4cd0fc9-8451-4d81-b426-ac9f67ac0d80">

2) Click "Programs >", find e.g. `steam.exe`, open the config/info screen, there's a "Create Shortcut" button
<img width="321" alt="Create Shortcut" src="https://github.com/Whisky-App/Whisky/assets/42669366/6fe795da-9042-4670-81de-89958ba94fb4">

### Describe the solution you'd like

Suggestion: rename the "Create Shortcut" button -> "Add Launcher to Applications folder" or whatever.

That way there'd be less confusion (what is a "Shortcut", exactly?), and the button would more clearly describe what it does.

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I did have this concern when naming this button. `Add Launcher to Applications folder` would be too long for the UI. I can think of something else.

**Comment by IsaacMarovitz** [comment]
Resolved
