### ISSUE TITLE
[Bug]: If the user manually adds a Shortcut before first exiting the new program, duplicate Shortcut possible

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#384]
### Description

If the user manually adds a Shortcut before first exiting the new program for the first time, Whisky automatically adds a Shortcut anyway. After that, there are suddenly ***two*** Shortcuts, probably very similar to each other (in my example below, "Steam" and "steam")

### Steps to reproduce

Using Steam as an example.

1. Install Steam into a new bottle "Steam", don't exit Steam yet
2. No Shortcut for Steam yet in the Whisky UI
3. Manually add a Shortcut ("star" ⭐ `steam.exe`)

What happens: now there are two Shortcuts for Steam: "Steam" and "steam"

### Expected behaviour

Expected: don't unexpectedly add the extra Shortcut
Or even better: automatically add the Shortcut even if the user hasn't exited the new program yet (edit: if the Whisky.app UI is currently active/selected).

I now know the technical reason why the duplicate appeared: Whisky automatically makes the Shortcut (I didn't know that, great job!) but ***only after*** the user ***exits*** Steam, ***or if the user manually adds a Shortcut (!)***

Suggestion:
- edit: Automatically scan for new .lnk files and automatically add any new Shortcut(s), even if the new steam.exe hasn't exited yet, ***if*** the user switches to the Whisky.app UI, and then periodically scan every 5 seconds or so ***while*** Whisky.app UI is currently active/selected ***until*** focus is switched away from Whisky again

edit: the rest of these were probably just me overthinking this, unnecessary if already scanning and automatically adding Shortcuts for newly installed programs when the Whisky UI is currently active/selected?
- ~~Maybe during the first time installing a program (before the user has exited it), periodically check for new .lnk files (ugly, I know, but maybe worth it? It can't be *that* expensive to look through a couple of files every 5 seconds or so for the first 5 minutes or whatever? (edit: until a Start Menu item has appeared, or could there be a corner case where a program first makes one Start Menu item, then waits for several seconds, then makes another one, etc?)~~
- ~~...or maybe if the user manually adds a Shortcut, assume that the user knows best and don't add any Shortcuts automatically~~
- ~~...or maybe add a simple heuristic: if the user adds a Shortcut that looks an awful lot like the Shortcut Whisky was about to make automatically, don't add it ("steam" and "Steam" are identical, if compared case-insensitively)~~

### Logs

```bash
UI bug, no logs
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fixed
