### ISSUE TITLE
[Bug]: Trackmania incorrectly reads Disk space

### ISSUE THREAD

**Issue by odahcam** [Whisky-App/Whisky#387]
### Description

First I'm sorry if this is duplicated, I'm new around and I didn't find anything related.

When launched the game reads there's only 5GB left of disk space, but there's 145GB.
<img width="933" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3942006/93f83748-8464-4ecf-be25-7cf332e56e83">

### Steps to reproduce

1. Create a Win7 bottle.
2. Install Ubisoft Play.
3. Install Trackmania (2020).
4. Open the game.

### Expected behaviour

The game should receive the correct value from the API that reads disk space. 

### Logs

```bash
I don't know where to get the logs for this kind of behaviour.
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by odahcam** [comment]
I don't know if that's relevant but I've installed Whisky using brew.

**Comment by IsaacMarovitz** [comment]
Trackmania is complaining about RAM here not Disk Space, either way I'm pretty sure you can just ignore this error.

**Comment by odahcam** [comment]
You know if there's something I could look into either in Whisky or Wine in order to fix that?

**Comment by Blendertom** [comment]
@odahcam this is not something that needs to be fixed. Mac will automatically clear as much Ram as needed while the game is running.

The only way possible for this error to not show is to close any other application using Activity Monitor so you have at least 5GB of ram available.
