### ISSUE TITLE
[Feature]: Rename "the other" Run... button ("..." means a dialog will open)

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#392]
### Is your feature request related to a problem?

The "other" `Run...` button should be renamed, because it doesn't follow normal UI guidelines.

Step to reproduce:

1) Click "Programs >", find e.g. `program.exe`, open the config/info screen, there's a `Run...` button (with an ellipsis/three dots/"...") that launches the `program.exe` in question. 

The problem: "..." [means](https://en.wikipedia.org/wiki/Ellipsis#Usage_in_computer_system_menus) a dialog box will open first.
(reusing the image from #383)
<img width="321" alt="Create Shortcut" src="https://github.com/Whisky-App/Whisky/assets/42669366/6fe795da-9042-4670-81de-89958ba94fb4">

### Describe the solution you'd like

Rename the button. Maybe `Launch` (without the "...", and avoid reusing the word "Run" which is already used in another button elsewhere in a slightly different context)?

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
From Apple's HIG:

> **Append a trailing ellipsis to the title when a push button opens another window, view, or app.** Throughout the system, an ellipsis in a control title signals that people can provide additional input. For example, the Edit buttons in the AutoFill pane of Safari Settings include ellipses because they open other views that let people modify autofill values.

This button opens another program which falls under those guidelines.
