### ISSUE TITLE
[Feature]: Right after launching Whisky, don't force the user to choose a "bottle"

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#395]
### Is your feature request related to a problem?

Currently, Right after launching Whisky, it always forces the user to choose a "bottle" (even if there's only one to choose from).

<img width="595" alt="Select a bottle" src="https://github.com/Whisky-App/Whisky/assets/42669366/d3a39404-78d5-4b0f-9092-5b8a524e6890">

### Describe the solution you'd like

Suggestions:

- Don't force the user to select a "bottle" when there's only one available
- If there are more than two available, remember which one was last selected when closing Whisky, and automatically choose that one again
- If the suggestions above are rejected for some reason, at least consider tweaking the text
- - "Select a bottle" -> "Select a bottle from the Sidebar"
- - (or if the Sidebar is hidden, -> "First show the Sidebar, then select a bottle")
- edit: ...or if all of the above is rejected, at least consider always showing the Sidebar on startup if the user has hidden it (I honestly think hiding the Sidebar is an unnecessary footgun that doesn't have any legitimate uses in the Whisky UI, and it only potentially confuses beginners who accidentally click it (and the button should be removed), but that's just, like, my opinion)

Screen shot: Sidebar accidentally hidden, only one "bottle" (unnecessarily makes beginners jump through hoops)
<img width="481" alt="Hidden Sidebar, one bottle" src="https://github.com/Whisky-App/Whisky/assets/42669366/7116823f-c9cd-41ca-b4ce-3fae3ab814f4">

### Anything else?

Nope, thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fixed
