### ISSUE TITLE
Do I need to be using Sonoma?[Bug]: 

### ISSUE THREAD

**Issue by Mrblutziii** [Whisky-App/Whisky#397]
### Description

Games I have attempted are not working and result in the game crashing, or giving errors. Are the issues I am facing have something to do with me being on Ventura instead of Sonoma?

### Steps to reproduce

Try and launch games while on the Ventura OS

### Expected behaviour

To play and launch games.

### Logs

```bash
N/A
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
New versions of Whisky shouldn't even open on Ventura. Yes, you need Sonoma.
