### ISSUE TITLE
[Bug]: Bottle name not updated after renaming it (only updated after relaunching Whisky)

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#398]
### Description

The Bottle name is not updated in the Sidebar after renaming the Bottle

https://github.com/Whisky-App/Whisky/assets/42669366/4ccf8e45-f05a-41e0-ac91-d7ed94edeb4a

### Steps to reproduce

1. Right click the Bottle name
2. Select "Rename"
3. Pick a different name
4. Look at the name (still the same)

### Expected behaviour

Expected: update the Bottle name immediately. Now it only updates after relaunching Whisky

### Logs

```bash
UI bug, no logs.
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Resolved
