### ISSUE TITLE
[Feature]: Winetricks... dialog is confusing

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#400]
### Is your feature request related to a problem?

The dialog after clicking the "Winetricks..." button is kind of confusing, especially for new users: currently it says "Run Winetricks command" and expects the (new) user to know what to blindly type here.

The "Run..." button can be pressed even if the text field is left blank (good) but the user has to guess/know this.

<img width="356" alt="Blindly_type_the_name_of_a_winetricks_command" src="https://github.com/Whisky-App/Whisky/assets/42669366/ac1755b9-4676-4a42-865d-1c8fbc8a35dd">

### Describe the solution you'd like

Suggestions:

Somehow better show/tell/indicate that the text field can be left blank and pressing Run... is OK (Open Winetricks dialog)

Also, maybe show a dropdown list of the most common/probably-what-the-user-wants winetricks commands?

PS. Of course, the Winetricks that opens is "the raw Winetricks experience" (a bit rough around the edges to put it mildly) which could be improved, but that might be outside the scope of this issue.

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by nilsnilsnils** [comment]
It would be nice to have an menu like wineskin have to easy install software.

https://github.com/Gcenx/WineskinServer

![Bildschirmfoto 2023-10-02 um 11 36 26](https://github.com/Whisky-App/Whisky/assets/5464118/7509e139-6783-4a6d-80e9-40878dcb6239)
