### ISSUE TITLE
[Feature]: Also list Start Menu items in "Installed Programs" list

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#401]
### Is your feature request related to a problem?

Whisky automatically adds a Shortcut item if there's a .lnk file in the Start Menu inside the Bottle. This is great.

However: if the user (accidentally?) removes the Shortcut, it's pretty difficult to get it back. The user has to manually find the correct `filename.exe` in the "Installed Programs" list (and after that, the Shortcut isn't as pretty as the automatically created one was: "steam" vs. "Steam")

### Describe the solution you'd like

Also list Start Menu items in the "Installed Programs" list (at the beginning of the list because they are probably what the user was looking for).

That way, the user can "star" ⭐ the item to restore it (if it was accidentally deleted before)

Suggestion:
something like this in "Installed Programs":
"⭐ Steam (Start Menu item)"
"     steam.exe"
etc.

(or if that's not feasible, at least consider adding some other way to restore deleted Shortcuts: a button or something to automatically add all Start Menu items as Shortcuts)

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Resolved
