### ISSUE TITLE
[Feature]: What to do with files left behind from (forgotten?) removed Bottles?

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#403]
### Is your feature request related to a problem?

It's possible to remove Bottles from the Whisky UI without actually deleting the files from the disk, but after that, there's no easy way to review removed (but not "deleted") Bottles.

The user can forget about the removed Bottle(s) completely and/or not realize that Bottles are ***surprisingly*** large, and "removed" Bottles can easily take up several (dozens of) gigabytes of valuable disk space without the user understanding that. This is a significant problem, especially because *many* Apple users have a hard disk that's already too small, because Apple likes to wildly overcharge for hard disk upgrades when buying, and deliberately makes upgrading impossible after buying.

Also, it's possible to make another new Bottle with the same name as a (forgotten?) removed Bottle, with no warning in the UI.

**Example scenario:**

1. Make a new Bottle "Steam"
2. Right click "Steam" in the Sidebar
3. Remove...
4. Don't click "Delete files from disk" (not actually deleting files is the default action, probably the right call)
5. Remove

(after some time, the user has already forgotten there's another removed "Steam" bottle left behind)

6. Add a new Bottle with the same name: "Steam"

Currently the UI does nothing (perfectly reasonable of course, but could probably be improved?)

### Describe the solution you'd like

1) In the scenario above, because there was already a removed Bottle by the same name, ask the user what to do:
- add the removed Bottle back to the Bottles list instead (undo removing it)
- permanently delete the removed Bottle from the disk (also show how many gigabytes would be freed), and add the new bottle instead
- leave the existing Bottle's files on the disk, don't delete its files (also show how many gigabytes the files are currently taking), and add the new bottle

2) What if the user has already completely forgotten about some or all of the Bottles removed before (and doesn't realize the fact that the abandoned "hidden" files will forever take gigabytes of valuable disk space)? What now? Can Whisky help the user automatically by detecting and indicating that there are N gigabytes of "wasted" space in removed Bottles hidden from the UI, especially if that has already been the case for M days (a month or so?)

3) Also, maybe add an easy way to view removed (but not deleted) Bottles.

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Tbh, this is kind of up to the user to handle on their own. I don't think we need to deal with this.
