### ISSUE TITLE
[Feature]: Disable ClearType font rendering by default?

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#404]
### Is your feature request related to a problem?

When installing Steam (very common), the user has to look at the weirdly colorful mess Windows affectionately calls "ClearType" fonts. Can ClearType be disabled by default, because macOS users are probably not used to seeing weirdly colorful text like that?

Closeup of weirdly colorful ClearType text:
![Closeup of weirdly colorful ClearType text](https://github.com/Whisky-App/Whisky/assets/42669366/cfb0b5b9-985b-48a8-9db6-55aca41c18e5)

<img width="506" alt="ClearType text" src="https://github.com/Whisky-App/Whisky/assets/42669366/4a34b872-d9d3-43a2-a17a-0233e2c1924a">

### Describe the solution you'd like

Disable ClearType, or at least only use Grayscale anti-aliasing, not the weirdly colorful messy stuff?

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is just sorta how Wine is, not much I can do about it.
