### ISSUE TITLE
[Feature]: More UI feedback

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#406]
### Is your feature request related to a problem?

(edit: actually, I somewhat changed my mind about what I originally wrote in this issue, and took the opportunity to morph the issue to have a more general name and added some more stuff)

### Describe the solution you'd like

More UI feedback:
- bottle info -> Path: "Show in Finder" context menu item instead (and/or also make the text selectable/copyable if that's feasible)
- same thing for `program.exe` / Shortcut info -> Path: "Show in Finder" context menu instead (and/or also make the text selectable/copyable if that's feasible)
- bottle info: make "Wine version" and "GPTK Version" text fields selectable/copiable
- bottle info: Windows version is listed in both info and config, why is it only possible to change the version from one place, but not the other? Allow changing the version from Bottle info too please?
- bottle info: add a new field "size on disk" (show how much the Bottle is currently using disk space (size on disk, not "size"))

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I think I'm going to remove the Info section, as most of the information is duplicate, global, or unhelpful. I will find somewhere else to put size on disk.

**Comment by IsaacMarovitz** [comment]
Info has been removed
