### ISSUE TITLE
[Feature]: Change the order of the text items and tweak the text a little bit?

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#408]
### Is your feature request related to a problem?

Should the order and names of these items be tweaked a little bit?

<img width="159" alt="Items" src="https://github.com/Whisky-App/Whisky/assets/42669366/aac52133-761b-4dcb-8a90-987270e11bc1">

### Describe the solution you'd like

Some possible suggestions:
- list "Programs" before "Config" to make it easier to notice for new users (also, Config and Info logically next to each other, kind of related/similar)?
- should it be made even more crystal clear that these items are not universal, but the contents are different for each Bottle -> by adding e.g. "Steam: " before each item?
- rename "Programs" -> "Installed Programs" or "Steam: Installed Programs" (already uses "Installed Programs" inside the menu)
- maybe rename "Info" -> "Information" or -> "Steam: Information"?
- maybe rename "Config" -> "Configuration or -> "Steam: Configuration"?

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Done
