### ISSUE TITLE
Compatibility with M1 Ventura

### ISSUE THREAD

**Issue by timsayshey** [Whisky-App/Whisky#412]
I have a Macbook Pro M1 with MacOS 13.5.2 (22G91) and the app won't open and says it's not compatible:
![image](https://github.com/Whisky-App/Whisky/assets/1148940/8067e047-823d-42d8-bbbb-0dba09d05ce0)

I also checked the github project and issues and couldn't find anyone else with this issue or a compatibility list.

**Comment by IsaacMarovitz** [comment]
<img width="419" alt="Screenshot 2023-09-17 at 22 44 12" src="https://github.com/Whisky-App/Whisky/assets/42140194/cc21f502-d75a-43a3-95c1-597a2bcbf93f">
