### ISSUE TITLE
[Feature]: Ability to change bottle locale directly in the app

### ISSUE THREAD

**Issue by sorae42** [Whisky-App/Whisky#413]
### Is your feature request related to a problem?

Some program won't install or run if not set to specific locale, especially old Japanese game where the game expects the system to be in Japanese (ja_JP).

### Describe the solution you'd like

Be able to change the locale directly instead of having to change the configuration file.

### Anything else?

Osaka Simulator's Installer ver. is an example of such problem.
https://archive.org/details/osakasimulatorfinal

### Issue Language

- [X] Yes my issue is written in English

**Comment by sorae42** [comment]
> <img alt="image" width="958" src="https://user-images.githubusercontent.com/2720676/273440873-da3fa196-33cf-4387-a2c8-7cc4a7a05338.png">
> Help needed!
> 
> In Parallels Desktop I can do this settings to make this prog show Chinese characters correctly, but cannot find a way to do it in Whisky.
> 
> Test file: [eyesmail.exe.gz](https://github.com/Whisky-App/Whisky/files/12840349/eyesmail.exe.gz)


https://github.com/Whisky-App/Whisky/assets/34794115/3159e954-8522-4125-be33-c699f77bccee

**Comment by Haoisin** [comment]
is that a 32 bit game? i thought Mac couldnt run that, even thru whisky?

**Comment by sorae42** [comment]
idk how it works but it works.
