### ISSUE TITLE
[Bug]: Civ VI crashes

### ISSUE THREAD

**Issue by yoondagoon** [Whisky-App/Whisky#414]
### Description

When I try to run Sid Meier's Civ VI from Steam via Whisky, I get this problem. 

The program t2gp.exe has encountered a serious problem and needs to close. 

We are sorry for the inconvenience.
This can be caused by a problem in the program or a deficiency in Wine. You may want to check
http://www.codeweavers.com/compatibility/ for tips about running this application.

### Steps to reproduce

Open Whisky
Open Steam
Download Sid Meier Civ VI
Start game

### Expected behaviour

I wanted to open Civ 6

### Logs

```bash
0x00000182ecdfc1 libcef+0x2ecdfc1: int	$3
Modules:
Module	Address					Debug info	Name (74 modules)
PE	0000000000450000-0000000000653000	Deferred        dxgi
PE	0000000001760000-00000000018ea000	Deferred        gameoverlayrenderer64
PE	00000000018f0000-0000000001901000	Deferred        psapi
PE	0000000010000000-0000000010002000	Deferred        usp10
PE	00000000688b0000-00000000688b3000	Deferred        win32u
PE	0000000068eb0000-0000000068eb4000	Deferred        opengl32
PE	000000006b1d0000-000000006b1d6000	Deferred        winemac
PE	000000007b000000-000000007b558000	Deferred        kernelbase
PE	000000007b600000-000000007b7a4000	Dwarf-4-5       kernel32
PE	0000000140000000-00000001404f6000	Export          t2gp
PE	0000000170000000-0000000170333000	Dwarf-4-5       ntdll
PE	0000000180000000-000000018a228000	Export          libcef
PE	00000001c4ee0000-00000001c4fb3000	Deferred        winspool
PE	00000001c69e0000-00000001c7768000	Deferred        shell32
PE	00000001c8b40000-00000001c8bb8000	Deferred        msacm32
PE	00000001c8db0000-00000001c90c6000	Deferred        msvcrt
PE	00000001c92d0000-00000001c934e000	Deferred        winecoreaudio
PE	00000001cfdf0000-00000001cfe56000	Deferred        dxva2
PE	00000001dd3f0000-00000001dd76c000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec356000	Deferred        ws2_32
PE	00000001f48d0000-00000001f48f8000	Deferred        wpc
PE	00000001f51e0000-00000001f5213000	Deferred        hid
PE	00000001fdfd0000-00000001fe096000	Deferred        wintrust
PE	0000000201cf0000-0000000201d99000	Deferred        secur32
PE	000000021a7e0000-000000021a9c4000	Deferred        setupapi
PE	000000021ff70000-0000000221564000	Deferred        wined3d
PE	0000000228450000-00000002284c9000	Deferred        propsys
PE	0000000231ae0000-0000000231d71000	Deferred        rpcrt4
PE	000000023d820000-000000023deff000	Deferred        user32
PE	0000000240030000-00000002400bd000	Deferred        iphlpapi
PE	000000024f470000-000000024f4d8000	Deferred        mpr
PE	00000002522e0000-00000002523cc000	Deferred        oleacc
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Civ VI has a Mac version on Steam.

**Comment by yoondagoon** [comment]
@IsaacMarovitz never runs on my M1 Pro

**Comment by yoondagoon** [comment]
I believe the version is optimised towards non-apple silicon macs and labeled as mac friendly, however I have seen some people play it with emulators and such. Anyway my main concern is - is this problem that I run into with wine going to happen with other games, if so I might as well fix it now, rather than waste my time downloading other games only to check.

**Comment by yoondagoon** [comment]
Fair enough - is there a thread on PayDay 2/3

**Comment by Crd5** [comment]
I play civ6 on m1 pro Mac. When I had epic games version (which doesn't allow to download Mac version) I used CX22 to play civ6. Main launcher doesn't run but launchpad works great. Run launchpad manually
