### ISSUE TITLE
[Bug]: text for "Programs" section is shifted in main UI

### ISSUE THREAD

**Issue by s0rd3s** [Whisky-App/Whisky#416]
### Description

You can clearly see that "Programs" in the UI of the program is shifted, relative to the buttons "Config" and "Info". Apparently this is due to the icon of the programs, which is not square.
<img width="389" alt="Снимок экрана 2023-09-19 в 18 18 02" src="https://github.com/Whisky-App/Whisky/assets/10173942/97a33b15-c9b2-4906-966a-8f48d1b6803b">

### Steps to reproduce

Open Whisky app.

### Expected behaviour

Everything should be straight.

### Logs

```bash
Logs are not required.
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Already resolved
