### ISSUE TITLE
[Feature]: Setting WINEDLLOVERIDES= 

### ISSUE THREAD

**Issue by DeanMaxwell** [Whisky-App/Whisky#418]
### Is your feature request related to a problem?

Would like to use some custom dll injection on games. 

### Describe the solution you'd like

A field to set Setting WINEDLLOVERIDES=

### Anything else?

I could have sworn this was in an early build, but maybe was replaced by winetricks? 

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This can be accomplished by clicking on a program and adding a field in the Environment Variables list

**Comment by maecc** [comment]
I'd also add, you can add some dll's under the winecfg in Bottle configuration.
