### ISSUE TITLE
[Feature]: isskin.dll error

### ISSUE THREAD

**Issue by IcrusaI** [Whisky-App/Whisky#419]
### Is your feature request related to a problem?

<img width="444" alt="image" src="https://github.com/Whisky-App/Whisky/assets/20923066/a0d6c397-6bdf-4e28-aae5-fc0aa81d1938">
Trying to install Heroes of Might and Magic V. This error appears

### Describe the solution you'd like

Installing game

### Anything else?

.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This should not be a feature request.

**Comment by moonsweel** [comment]
@IcrusaI try this https://github.com/Whisky-App/Whisky/issues/471
