### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cuga-rajal** [Whisky-App/Whisky#421]
### Description

I am using Whisky 1.1.1 on macOS Ventura 13.5.2. It works fine, no issues. I use it for a couple small Windows programs.

I went to download Whisky version 1.3.2 and the app says that it will not launch on my macOS version. Same for 1.3.1. The app icon has a diagonal line through it, which means the build does not support the OS version I'm running.

Could you please document what OS versions the app will run on.

I see that in this Github bug report page, there is a field for me to say what OS version I am running. It only gives the Sonoma (macOS 14) option. I am running 13.5.2. macOS 14 is not released yet. Are you building this app only for macOS14?  If so, could you please the required macOS versions clearly in the docs. If you intended for it to run on macOS 13 then you need to build it with MACOSX_DEPLOYMENT_TARGET=13.0.

Cuga

### Steps to reproduce

Download Whisky on a Mac running Ventura 13.5.2. Uncompress the zip file.

### Expected behaviour

Able to launch app, but cannot

### Logs

```bash
No logs to include since it is not launching.
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This information is easily accessible in the README

**Comment by ohaiibuzzle** [comment]
From `Whisky/README.md`:


# System Requirements
- CPU: Apple Silicon (M1/M2 and its variants)
- OS: macOS Sonoma 14.0 or later

Is this clear enough?

**Comment by cuga-rajal** [comment]
Sorry for the inconvenience. Thanks for the great software app. The switch to Sonoma-only before Sonoma is released was just very unexpected and unusual.

**Comment by IsaacMarovitz** [comment]
> The switch to Sonoma-only before Sonoma is released was just very unexpected and unusual.

We have no choice, GPTK beta 4+ only runs on Sonoma.
