### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Hardfg5000** [Whisky-App/Whisky#423]
### Description

Yesterday, I installed Steam then Beam.NG drive, played the game for a while. But, I tried it the next day and it just wouldn't boot and crashes with an error in the logs.

### Steps to reproduce

1. Install Steam, had no issues opening it 
2. Installed Beam.NG drive
3. Went to play it the next day
4. Nothing

### Expected behaviour

I expected to be able to open the game as I did yesterday and for it to function

### Logs

```bash
Whisky Version: 1.3.2
Date: 23/09/2023, 2:52:21
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: Beamng
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Volumes/Crossover/Whiskey/7A45D4F7-FD62-42F0-BC28-914DE507A9DF

Arguments: start /unix /Volumes/Crossover/Whiskey/7A45D4F7-FD62-42F0-BC28-914DE507A9DF/drive_c/Program Files (x86)/Steam/steam.exe 

Environment:
{
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
}

Launched Wine (1958)
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/myname/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
Process exited with code 0
```

### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by teunzwart** [comment]
I'm seeing the same thing on Whiskey 2.0.0. In a new bottle you can start Steam once (when installing), and you can install and play games. But closing and trying to reopen leads to a error loop.

P.S. This bug should probably be renamed to have an informative title.

**Comment by IsaacMarovitz** [comment]
Please try the latest version of Whisky. 1.3.2 is not supported.
