### ISSUE TITLE
[Feature]: metalfx support?

### ISSUE THREAD

**Issue by PgAtom05** [Whisky-App/Whisky#425]
### Is your feature request related to a problem?

so, the performance of course can be at times quite poor cause of all the translation happening in the background, and so, to solve this issue, since the traduction is to metal api

### Describe the solution you'd like

is there any way to implement metalfx to improve performances?

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is not possible
