### ISSUE TITLE
Rage Multiplayer crush

### ISSUE THREAD

**Issue by karengharibyan** [Whisky-App/Whisky#427]
Hey all ! i tried to run Rage multiplayer with Whisky-app , when i trying to open its throwing an  exception 

Unhandled exception: page fault on write access to 0x00000000b63cf5e0 in 64-bit code (0x00000148854ed3).
Register dump:
 rip:0000000148854ed3 rsp:00000000023cf5e0 rbp:00000001483ddeb7 eflags:00000247 (   - --  I  Z- -P-C)
 rax:ffffffffc32114b5 rbx:0000000148964b19 rcx:00000000b5000000 rdx:0000000064ad0000
 rsi:0000000000000000 rdi:000000000000ffff  r8:0000000148882002  r9:ffffffffe78cd9fe r10:80000000004f2f56
 r11:00000000023cf878 r12:0000000000000001 r13:0000000000aa3df0 r14:0000000000000018 r15:0000000000000009
Stack dump:
0x000000023cf5e0:  0000000000000000 0000000000000018
0x000000023cf5f0:  0000000000000007 0000000000000001
0x000000023cf600:  00000000023cf9a0 0000000000aa8090
0x000000023cf610:  0000000000aa8090 0000000000000007
0x000000023cf620:  000000000000001b 00000001483ddcd3
0x000000023cf630:  0000000000b90000 000000000000001b
0x000000023cf640:  0000000000b90000 0000000000aa8088
0x000000023cf650:  0000000000a80100 0000000000b90000
0x000000023cf660:  0000000000000012 0000000000000000
0x000000023cf670:  0000000000aa3df0 0000000000a80138
0x000000023cf680:  0000000000000202 00000000023cf9b0
0x000000023cf690:  000000014814483f 0000000000000014
Backtrace:
=>0 0x00000148854ed3 AmdPowerXpressRequestHighPerformance+0x7f777b() in ragemp_v (0x000001483ddeb7)
  1 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  2 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  3 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  4 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  5 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  6 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  7 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  8 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  9 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  10 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  11 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  12 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  13 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  14 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  15 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  16 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  17 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  18 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  19 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  20 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  21 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  22 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  23 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  24 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  25 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  26 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  27 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  28 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  29 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  30 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  31 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  32 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  33 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  34 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  35 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  36 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  37 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  38 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  39 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  40 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  41 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  42 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  43 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  44 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  45 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  46 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  47 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  48 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  49 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  50 0x0000014896957f AmdPowerXpressRequestHighPerformance+0x90be27() in ragemp_v (0x000000023cf9a0)
  51 0x0000014812687b AmdPowerXpressRequestHighPerformance+0xc9123() in ragemp_v (0x000000023cf9a0)
  52 0x0000014812397e AmdPowerXpressRequestHighPerformance+0xc6226() in ragemp_v (0000000000000000)
  53 0x000003af6d9caa _beginthreadex_trampoline+0x4a(arg=0000000000A8C980) [Z:\private\tmp\game-porting-toolkit-20230918-30770-150ob8e\wine\dlls\msvcrt\thread.c:199] in ucrtbase (0000000000000000)
  54 0x0000007b62a889 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [Z:\private\tmp\game-porting-toolkit-20230918-30770-150ob8e\wine\dlls\kernel32\thread.c:61] in kernel32 (0000000000000000)
  55 0x0000017005b3b8 __wine_pop_frame(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [Z:\private\tmp\game-porting-toolkit-20230918-30770-150ob8e\wine\include\wine\exception.h:275] in ntdll (0000000000000000)
  56 0x0000017005b3b8 RtlUserThreadStart+0x88(entry=[<register RSP not accessible in this frame>, arg=[<register RSP not accessible in this frame>) [Z:\private\tmp\game-porting-toolkit-20230918-30770-150ob8e\wine\dlls\ntdll\thread.c:240] in ntdll (0000000000000000)
0x00000148854ed3 ragemp_v+0x8854ed3: movq	%rcx,0xffffffffff000000(%rsp,%rcx,1)
Modules:
Module	Address					Debug info	Name (84 modules)
ELF	0000000000000000-000000000017c000	Deferred        <wine-loader>
PE	0000000000430000-00000000004d6000	Deferred        msvcp140
PE	00000000004e0000-00000000004f6000	Deferred        vcruntime140
PE	0000000002e40000-0000000003238000	Deferred        vk_swiftshader
PE	0000000003440000-0000000003517000	Deferred        vulkan-1
PE	0000000003520000-0000000003662000	Deferred        chrome_elf
PE	0000000003670000-00000000036ea000	Deferred        libegl
ELF	0000000068039000-000000006803d000	Deferred        <wine-loader>
PE	00000000680a5000-00000000680b1000	Deferred        libwine.1.0.dylib
PE	00000000680b9000-00000000680c2000	Deferred        libffi.8.dylib
ELF	00000000680da000-00000000681b6000	Deferred        ntdll.so
PE	000000006846f000-000000006848b000	Deferred        libd3dshared.dylib
ELF	0000000068599000-00000000685a9000	Deferred        ws2_32.so
ELF	00000000686b5000-00000000686c5000	Deferred        user32.so
ELF	00000000686cd000-00000000686e1000	Deferred        crypt32.so
ELF	00000000686ee000-0000000068706000	Deferred        bcrypt.so
PE	000000006871b000-000000006872f000	Deferred        libz.1.2.13.dylib
PE	000000006874a000-000000006875f000	Deferred        libbz2.1.0.8.dylib
PE	000000006877d000-0000000068789000	Deferred        libbrotlidec.1.0.9.dylib
ELF	000000006879a000-00000000687a6000	Deferred        kerberos.so
PE	00000000687a9000-00000000687d5000	Deferred        libpng16.16.dylib
PE	000000006883a000-000000006885c000	Deferred        libbrotlicommon.1.0.9.dylib
ELF	0000000068864000-0000000068874000	Deferred        dnsapi.so
ELF	000000006887f000-0000000068a87000	Deferred        win32u<elf>
  \-PE	0000000068890000-0000000068a43000	\               win32u
ELF	0000000068a87000-0000000068a9b000	Deferred        secur32.so
ELF	0000000068c6c000-0000000068c88000	Deferred        winecoreaudio.so
PE	0000000068cda000-0000000068d81000	Deferred        libfreetype.6.dylib
PE	000000006add5000-000000006ade4000	Deferred        libintl.8.dylib
PE	000000006adf8000-000000006ae08000	Deferred        libtasn1.6.dylib
PE	000000006ae2a000-000000006ae5c000	Deferred        libidn2.0.dylib
PE	000000006aecf000-000000006af2a000	Deferred        libnettle.8.6.dylib
PE	000000006af8d000-000000006b148000	Deferred        libgnutls.30.dylib
PE	000000006b33e000-000000006b4a0000	Deferred        libp11-kit.0.dylib
PE	000000006b617000-000000006b667000	Deferred        libhogweed.6.6.dylib
PE	000000006b7b7000-000000006b959000	Deferred        libunistring.5.dylib
PE	000000006b9ca000-000000006ba48000	Deferred        libgmp.10.dylib
PE	000000006baf1000-000000006bc02000	Deferred        libiconv.2.dylib
ELF	000000006bc3d000-000000006bd1d000	Deferred        winemac<elf>
  \-PE	000000006bc50000-000000006bce1000	\               winemac
PE	000000007b000000-000000007b558000	Deferred        kernelbase
PE	000000007b600000-000000007b7a4000	Dwarf-4-5       kernel32
PE	000000007d400000-000000007d405000	Deferred        wine64-preloader
PE	0000000140000000-0000000148e5b000	Export          ragemp_v
PE	0000000170000000-0000000170333000	Dwarf-4-5       ntdll
PE	0000000180000000-000000018009b000	Deferred        discord-rpc
PE	00000001c69e0000-00000001c7768000	Deferred        shell32
PE	00000001c8b40000-00000001c8bb8000	Deferred        msacm32
PE	00000001c8db0000-00000001c90c6000	Deferred        msvcrt
PE	00000001c92d0000-00000001c934e000	Deferred        winecoreaudio
PE	00000001dc810000-00000001dc831000	Deferred        schannel
PE	00000001dd3f0000-00000001dd76c000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec356000	Deferred        ws2_32
PE	0000000201cf0000-0000000201d99000	Deferred        secur32
PE	000000021a7e0000-000000021a9c4000	Deferred        setupapi
PE	0000000231ae0000-0000000231d71000	Deferred        rpcrt4
PE	000000023d820000-000000023deff000	Deferred        user32
PE	0000000240030000-00000002400bd000	Deferred        iphlpapi
PE	000000026b4c0000-000000026b756000	Deferred        gdi32
PE	00000002739c0000-0000000273ea5000	Deferred        oleaut32
PE	0000000274a50000-0000000274a7c000	Deferred        kerberos
PE	000000027ab80000-000000027ab91000	Deferred        cfgmgr32
PE	000000028dfa0000-000000028dfc0000	Deferred        nsi
PE	000000029cfc0000-000000029d00c000	Deferred        dnsapi
PE	00000002d4d40000-00000002d4d92000	Deferred        bcrypt
PE	00000002de970000-00000002dea2d000	Deferred        rsaenh
PE	00000002e3540000-00000002e3656000	Deferred        shlwapi
PE	00000002e8f10000-00000002e9495000	Deferred        ole32
PE	00000002e9930000-00000002e9942000	Deferred        bluetoothapis
PE	00000002edf00000-00000002ee103000	Deferred        dxgi
PE	00000002f1fa0000-00000002f1fc0000	Deferred        version
PE	00000002f7230000-00000002f72f0000	Deferred        uxtheme
PE	00000002f7f20000-00000002f7f2b000	Deferred        vcruntime140_1
PE	00000003126f0000-0000000312745000	Deferred        shcore
PE	0000000327020000-00000003271af000	Deferred        combase
PE	000000032a700000-000000032a7c1000	Deferred        sechost
PE	0000000330260000-000000033038e000	Deferred        advapi32
PE	0000000336850000-00000003368f4000	Deferred        mmdevapi
PE	00000003af670000-00000003af9f8000	Dwarf-4-5       ucrtbase
PE	00000003afd00000-00000003afd66000	Deferred        imm32
PE	00000003b8f00000-00000003b90b9000	Deferred        winmm
PE	00007ff80a7d8000-00007ff80a814000	Deferred        libsystem_kernel.dylib
PE	00007ff80a813000-00007ff80a81f000	Deferred        libsystem_pthread.dylib
PE	00007ff80a843000-00007ff80a84f000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000080    0     
	000000a4    0     
	000000bc    0     
	00000100    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	000000c8    0     
00000078 winedevice.exe
	0000007c    0     
	00000084    0     
	00000088    0     
	0000008c    0     
	00000090    0     
	00000094    0     
	00000098    0     
0000009c plugplay.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     
	000000b0    0     
000000b4 svchost.exe
	000000b8    0     
	000000c0    0     
	000000c4    0     
000000f8 rpcss.exe
	000000fc    0     
	00000104    0     
	00000108    0     
	0000010c    0     
	00000110    0     
	00000220    0     
0000020c explorer.exe
	00000210    0     
	00000218    0     
	0000021c    0     
000002bc (D) C:\RAGEMP\ragemp_v.exe
	000002c0    0     
	000002c4    0     
	000002c8    0     
	000002cc    0 <== 
	000002d4    0     
	000002e0    0     
	000002ec    0     
000002e4 conhost.exe
	000002e8    0     
System information:
    Wine build: wine-7.7
    Platform: x86_64
    Version: Windows 10
    Host system: Darwin
    Host version: 23.0.0

**Comment by IsaacMarovitz** [comment]
Please make issues with the correct template
