### ISSUE TITLE
[Feature]: .ink link support in favourites (starred apps)        Thanks for all the awesome work so far!!

### ISSUE THREAD

**Issue by logiota** [Whisky-App/Whisky#429]
### Is your feature request related to a problem?

I create steam shortcuts but it is almost impossible to open them

### Describe the solution you'd like

.ink link support in favourites (starred apps)

### Anything else?

![Screenshot 2023-09-25 at 16 29 32](https://github.com/Whisky-App/Whisky/assets/45556023/5fdcada6-8821-4a7c-a8ed-689338dd3a0e)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
LNKs will automatically appear as pinned programs in Whisky. If not, you can pin items manually from the program list.

**Comment by jnpdx** [comment]
In version 2.2.3, I have a Launch `Zork Grand Inquisitor.lnk` file, but it is not pinned, nor does it appear as selectable in the pinned file chooser. Is there anything I can do to make this runnable?

<img width="835" alt="Screenshot 2024-03-05 at 11 24 16 PM" src="https://github.com/Whisky-App/Whisky/assets/50815/f1272756-575d-45f3-8654-923e44e40f7f">

**Comment by newzealandpaul** [comment]
I have the same issue, .lnk cannot be pinned.
