### ISSUE TITLE
[Feature]: Don't unnecessarily waste the user's time when creating a new bottle

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#434]
### Is your feature request related to a problem?

Right after the user creates a new Bottle, there's currently a noticeable delay: the whole UI is disabled while the spinner spins until the Bottle is ready.

It's of course understandable that the Bottle doesn't just appear from thin air instantly, but there's no need to block *all* UI actions during the new Bottle creation.

### Describe the solution you'd like

Consider allowing the user to already click "`Run...`" and begin looking for the setup executable in the dialog, even while the Bottle is actually still being created in the background.

It always feels so laughably absurd when a human being (***extremely*** slow) has to wait for a computer (***extremely*** fast) to finish a task, and this should always be avoided if possible: allow the user to do something (**very** slowly) while the computer finishes the task (usually **very** quickly).

The computer might be done creating the Bottle before than the user finds the correct file anyway, so why make the user wait before allowing clicking "`Run...`"?

If, however, the user is done faster (I seriously doubt it but still, this is a possibility), just wait the couple of seconds it will take until the Bottle is actually ready, before actually continuing launching the .exe the user selected?

Here's a video that shows how the user has to unnecessarily wait for over 10 seconds before clicking the button is allowed:

https://github.com/Whisky-App/Whisky/assets/42669366/910b0891-3fd3-4110-9e8a-7cb36bd88a78

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The wait here is not unnecessary; running programs in a bottle that doesn't exist yet is impossible. The UI is not blocked during this time. You can use all of your other bottles just fine.

**Comment by SENNiiNHA** [comment]
Ain't better like this? Imo, when we talk about ux, i'd be pretty frustrated if some kind of feature shows up like it's ready and it ends up just ignoring my command/action.
And if we talk about inserting in some kind of queue to execute after it ends the bottle creation, is it even worth to implement this kind of logic just because of some seconds?
