### ISSUE TITLE
[Feature]: Is Whisky licensed technically correctly?

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#436]
### Is your feature request related to a problem?

This is not a fascinating subject, but it's a necessary evil I'm afraid. I'm not a lawyer, but I still think you should probably make sure Whisky is licensed technically correctly.

- [ ] First: is Whisky licensed under "GPL 3" or "GPL 3 or later"? (i.e. Do you blindly trust that FSF won't do anything silly in any later GPL versions?)

edit: ignore this because you seem to disagree ~~Side note: Do you strongly prefer GPL 3? Wouldn't it be more polite to release Whisky under the same license as Wine itself which it heavily relies on (LGPL 2.1 or later), so that Whisky or portions of code from it could theoretically be used under the Wine project umbrella at some point in the future (maybe unlikely but a nice gesture...)? Consider relicensing when it's still not too late (admittedly you should ask for permission from any earlier Whisky contributors though).~~

### Describe the solution you'd like

If you really prefer GPL 3, please at least do the following (and carefully read https://www.gnu.org/licenses/gpl-howto.html if I misunderstood or forgot something myself):

Carefully read and follow the instructions in the current LICENSE file where it for example says (from line 623 onward): 
"How to Apply These Terms to Your New Programs" <clip>
"To do so, attach the following notices to the program.  It is safest
to 
- [ ] ***attach them to the start of each source file*** [emphasis mine]
to most effectively state the exclusion of warranty;
and 
- [ ] ***each file should have at least the "copyright" line and a pointer to where the full notice is found*** [emphasis mine]."

please of course read the whole thing, I'm sure I forgot something.

### Anything else?

Nope.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
LGPL and GPL are compatible, Whisky's code base can be freely used by any program licensed under GPL (and its variants).

Whisky is specifically licensed under GPL 3.0
