### ISSUE TITLE
[Feature]: Reverse-Rosetta for Intel-based MacOS running Sonoma and support for Intel Macs on Game Porting Toolkit out-of-the-box.

### ISSUE THREAD

**Issue by shyamalschandra** [Whisky-App/Whisky#438]
### Is your feature request related to a problem?

The problem is that I cannot run the game porting toolkit on Intel Mac.

### Describe the solution you'd like

Reverse-Rosetta for Intel-based MacOS running Sonoma and support for Intel Macs on Game Porting Toolkit out-of-the-box.

I would like to run all M1 or M2 MacOS apps on the Intel Macs.

### Anything else?

Please let me know as soon as you achieve this ability.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The effort required would be gargantuan and incredibly out of scope for this project.
