### ISSUE TITLE
[Feature]: Custom Resolution

### ISSUE THREAD

**Issue by hardcod3dd** [Whisky-App/Whisky#444]
### Is your feature request related to a problem?

Im trying to run a game (metin2 private server) but the weird issue about this game is that if the desktop resolutions doesnt include 800x600 or other standard resolutions game window would not launch and stop itself.the error is called "create no appropiate device"

### Describe the solution you'd like

On windows devices its easy to fix if it ever happens. From intel graphics panel you can just add 800x600 resolution and it works.

### Anything else?

none

### Issue Language

- [X] Yes my issue is written in English

**Comment by mauriville** [comment]
hey @hardcod3dd , to fix this I used to use better display (an app that alows you to create custom resolutions) this worked with crossover, so probably can work with whisky

**Comment by IsaacMarovitz** [comment]
The solution for this varies wildly from program to program, so there's no one-size-fits-all solution.
