### ISSUE TITLE
[Problem]: Bottle disappears after hard drive remount

### ISSUE THREAD

**Issue by k-d-afk** [Whisky-App/Whisky#449]
### Is your feature request related to a problem?

I created a bottle on external hard drive and it worked OK. But after unplugging and plugging the hard drive again, my bottle is not there any more.

STEPS TO REPRODUCE:

Create bottle on external hard drive
Unplug the hard drive
Close Whisky
Plug the hard drive again
Launch Whisky
The bottle is not there :/

OR

Create bottle on external hard drive
Close Whisky
Unplug the hard drive
Launch Whisky
Close Whisky
Plug the hard drive again
Launch Whisky
The bottle is not there :/

### Describe the solution you'd like

I would like the bottle to stay there after plugging the hard drive back.

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by serista** [comment]
Are you sure it worked without replugging the external hard drive. It's my understanding that after it starts it keeps looking for bottles ONLY in default directory (~Library/Containers/Whisky/Bottles) that's why bottle "disappears". And there is currently no official way to set a default directory as far as I can see.

**Comment by kamdz01** [comment]
> Are you sure it worked without replugging the external hard drive if you restart Whisky? It's my understanding that after it starts it keeps looking for bottles ONLY in default directory (~Library/Containers/Whisky/Bottles) that's why bottle "disappears". And there is currently no official way to set a default directory as far as I can see.
> 
> PS: Actually it started to work properly after I created first bottle in the default folder, then I deleted it. Somehow there just was no Whisky folder in the .../Library/Containers until that.

Not true :) all bottle's home directories are stored in Whisky's database, but Whisky works in such a way, that if the path is no longer available during launch, it deletes the path from the database. See https://github.com/Whisky-App/Whisky/pull/455 for the fix for that problem :)
