### ISSUE TITLE
[Bug]: Bottle not saved after quit app (btw, love your app)

### ISSUE THREAD

**Issue by holyman2k** [Whisky-App/Whisky#450]
### Description

After the quit and restart the app, any saved bottle will disappear from the list.  
Bottle need to be imported on every restart.

### Steps to reproduce

1. install whisky
2. create a new bottle
3. quit app (cmd+q)
4. open the app
5. the created bottle is no longer in the list

### Expected behaviour

after restart the app, any previously created will apear in the list

### Logs

```bash
Whisky Version: 2.0.0
Date: 27/9/2023, 5:28:02 pm
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: Jagged Alliance 3
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/charliewu/Utilities/Bottles/AECFFACA-4F6D-4FD0-9723-8C68E5BE9337

Arguments: start /unix /Users/charliewu/Utilities/Bottles/AECFFACA-4F6D-4FD0-9723-8C68E5BE9337/drive_c/Jagged Alliance 3/JA3.exe 

Launched Wine (21695)
Process exited with code 0
```

### What version of Whisky are you using?

2.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by serista** [comment]
I think what's going in here is that upon start Whisky still looks for bottles only in default directory even though it now allows to create bottles elsewhere. Bottle you created is still there it's just that Whisky can't see it. It's an oversight of developer.

**Comment by IsaacMarovitz** [comment]
> PS: Actually it started to work properly after I created first bottle in the default folder, then I deleted it. Somehow there just was no Whisky folder in the .../Library/Containers until that.

Could be the list won't save correctly/it assumes the directory already exists. Nice catch.

**Comment by IsaacMarovitz** [comment]
Should be fixed upstream
