### ISSUE TITLE
[Bug]: Whisky won't run anything

### ISSUE THREAD

**Issue by chair-man-f** [Whisky-App/Whisky#451]
### Description

When I create a bottle, it disappears. So I import the bottle from the bottles folder. Then I try to run something, SteamSetup.exe and the little loading thing turns for a bit and then nothing happens

Game porting toolkit should be installed, because making a wine prefix works and Rosetta is installed with "softwareupdate --install-rosetta"

### Steps to reproduce

^

### Expected behaviour

Open steamsetup.exe and set up steam

### Logs

```bash
Whisky Version: 2.0.0
Date: 9/27/2023, 18:05:37
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: Steam
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/jackief./Library/Containers/com.isaacmarovitz.Whisky/Bottles/1614EA4B-4E1D-4E2F-A7D0-2276EC99B476

Arguments: start /unix /Users/jackief./Downloads/SteamSetup.exe 

Launched Wine (86488)
wine: could not load kernel32.dll, status c0000135
wine: could not open working directory L"Z:\\Users\\jackief\\Library\\Application Support\\com.isaacmarovitz.Whisky\\Libraries\\Wine\\bin\\", starting in the Windows directory.
wine: could not load kernel32.dll, status c0000135
Process exited with code 53
```

### What version of Whisky are you using?

2.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Similar issue to #359 it seems, your username ends in a `.` which is a special character and is causing problems here. In the short term, changing your home directory folder name to not end with a `.` should resolve it.

**Comment by chair-man-f** [comment]
How do I change it?? Wouldn't that mess up all my file paths
