### ISSUE TITLE
[Bug]: Steam won't open after startup

### ISSUE THREAD

**Issue by agent-carl** [Whisky-App/Whisky#454]
### Description

When I open Steam, under (Whisky), it shows up in the dock but nothing happens. 

### Steps to reproduce

just open Steam

### Expected behaviour

![Снимок экрана 2023-09-28 в 11 55 43](https://github.com/Whisky-App/Whisky/assets/57443863/d564a65c-405d-4e4b-a367-054f5904f788)

### Logs

```bash
where i can take the logs? :)
```

### What version of Whisky are you using?

2.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lightrow** [comment]
it doesn't work with dxvk

**Comment by allicebiyon** [comment]
Try changing your macOS language to English before installing Steam.

**Comment by zondug** [comment]
> Try changing your macOS language to English before installing Steam. (or modify System Preferences so that Whisky will run in English)

Changed language to English but not solved.

**Comment by crazecoder** [comment]
I solved it with change the language in the registry
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Nls\Language
change InstallLanguage and Default to your language code, example 0409(English) or 0804(Chinese)

**Comment by crazecoder** [comment]
> I solved it with change the language in the registry HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Nls\Language change InstallLanguage and Default to your language code, for example 0409(English) or 0804(Chinese)

Sadly, it doesn't work on 2.1.1

**Comment by IsaacMarovitz** [comment]
Locale settings can be changed in program config. You can also try installing fonts before installing Steam with Winetricks.

**Comment by crazecoder** [comment]
> 0804

You're right, I did ```cjkfonts``` before installing steam and now it works
