### ISSUE TITLE
[Help]: How to manually add a program (without install)

### ISSUE THREAD

**Issue by du-song** [Whisky-App/Whisky#459]
### Is your feature request related to a problem?

It seems unclear how one can add a program to the ui after copying it into the drive_c folder.

### Describe the solution you'd like

add a + button in installed programs to manually add an exe

### Anything else?

n/a

### Issue Language

- [X] Yes my issue is written in English

**Comment by kamdz01** [comment]
As a temporary solution I suggest copying the program into Program Files (or Program Files x86) folder. If the program has .exe extension, it should appear on the program list. Other extensions (like .msi, .bat) are not supported yet.

**Comment by Crd5** [comment]
If it's in "Program Files" or "Program Files x86" it will appear in program list. After that you can pin it
