### ISSUE TITLE
[Bug]: 0x80070490 - Element not found

### ISSUE THREAD

**Issue by viniborgas** [Whisky-App/Whisky#460]
### Description

Hi, I'm trying to install Power BI using Whisky, bit I keep getting an error message after trying to setup Microsoft .NET
Framework. The message says that the element 0x80070490 were not found.

### Steps to reproduce

pasted the Power BI .exe file on Program Files and tried to run it.

### Expected behaviour

Install Microsoft Power BI

### Logs

```bash
0x80070490 - Element not found
```

### What version of Whisky are you using?

2.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Considering that the compatibility is currently “Garbage” on WineDB I have not too much hope.

Issues being that MS’s own apps usually have some Win32 shenanigans thrown in (which makes them harder to run via WIne)

**Comment by MHNDhq** [comment]
Hi, vin. have you been able to run power bi desktop on Mac some other way? :'(
im running into same 0x80070490 .NET error
running on GPTK 1.3 and Whiskey 2.2.3

**Comment by abdelaziz-mahdy** [comment]
i ran it inside vmware fusion (which is free for personal use)
