### ISSUE TITLE
[Bug]: Steam is no longer supported on your operating system version?

### ISSUE THREAD

**Issue by bolandnick18** [Whisky-App/Whisky#461]
### Description

[Bug]: Steam is no longer supported on your operating system version?

here a screenshot
<img width="1280" alt="Screenshot 2023-09-30 at 1 49 30 PM" src="https://github.com/Whisky-App/Whisky/assets/40327737/a5cca401-45a4-4fe9-b624-b055004afe1a">

The bottle already been set to windows 10 as you can see in screenshot!

### Steps to reproduce

Not sure what happen here

### Expected behaviour

The program should run as normal without the error!

### Logs

```bash
Not sure where to found!
```

### What version of Whisky are you using?

2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Your build version has gone down too low. Edit to say `18362`

**Comment by bolandnick18** [comment]
still didn't work and I have set it to 18362

<img width="1280" alt="Screenshot 2023-09-30 at 2 02 35 PM" src="https://github.com/Whisky-App/Whisky/assets/40327737/7172d8a7-9c87-4888-9a19-a0f45ac53b56">

**Comment by IsaacMarovitz** [comment]
Try toggling the Windows version from Win10 to something else, then back to Win10

**Comment by bolandnick18** [comment]
Ok it’s working now
