### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by YangHHong** [Whisky-App/Whisky#464]
### Description

macbook pro 16 2019 
Whisky cannot install but can only install lower versions
Installing Steam shutdown program failed to start
<img width="246" alt="截屏2023-10-01 19 00 23" src="https://github.com/Whisky-App/Whisky/assets/59305607/92b23c56-9104-4a63-8e7b-69293763b198">

### Steps to reproduce

macbook pro 16 2019 
Whisky cannot install but can only install lower versions
Installing Steam shutdown program failed to start
<img width="246" alt="截屏2023-10-01 19 00 23" src="https://github.com/Whisky-App/Whisky/assets/59305607/92b23c56-9104-4a63-8e7b-69293763b198">

### Expected behaviour

macbook pro 16 2019 
Whisky cannot install but can only install lower versions
Installing Steam shutdown program failed to start
<img width="246" alt="截屏2023-10-01 19 00 23" src="https://github.com/Whisky-App/Whisky/assets/59305607/92b23c56-9104-4a63-8e7b-69293763b198">

### Logs

```bash
no
```

### What version of Whisky are you using?

<2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by GabCoolDude** [comment]
As the prompt said in the screenshot your provided, you need an M1 or higher macbook since whisky release 1.2.1.
