### ISSUE TITLE
[Bug]: Win32:WormX-gen

### ISSUE THREAD

**Issue by Drjacky** [Whisky-App/Whisky#465]
### Description

Avast detects a malware when I try to create a bottle!
<img width="600" alt="Screenshot 2023-10-01 at 12 25 31" src="https://github.com/Whisky-App/Whisky/assets/2296754/afa941f1-7927-4101-9490-d4c810fec55d">
<img width="610" alt="Screenshot 2023-10-01 at 12 25 47" src="https://github.com/Whisky-App/Whisky/assets/2296754/6c23d71d-506c-4dc0-96bd-8a7f7ed8e16f">

### Steps to reproduce

Have Avast Security installed.

### Expected behaviour

No virus detection

### Logs

```bash
N/A
```

### What version of Whisky are you using?

2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Okay I'm gonna break this down point by point.

One, to address the original concern, no, these DLLs are not malware. All the DLLs that come with Wine are open-source implementations, and it is incredibly easy to find this information.

Here are the DLLs in question [`msxml4.dll`](https://gitlab.winehq.org/wine/wine/-/tree/master/dlls/msxml4?ref_type=heads), and [`msxml6.dll`](https://gitlab.winehq.org/wine/wine/-/tree/master/dlls/msxml6?ref_type=heads).

Browse the source code to your heart's content.

Secondly, these antiviruses often work by simply browsing for suspicious file names. The contents of the DLL have not been checked, and this check is incredibly superficial, easy to bypass, and basically useless from a security standpoint. Not to mention that without Wine, it would be impossible to execute a DLL on macOS, so I'm not sure why the macOS version of this software is even flagging this on a completely incompatible system.

Lastly, the utility of an antivirus in the first place on macOS. Unless you are downloading extremely dodgy third-party applications or running programs with unchecked permissions, there is very little that a malicious program can accomplish on a Mac. Without the user manually downgrading the system security either by disabling SIP, AMFI, or running programs with `sudo`, yada yada, it's practically impossible for a program to do any sot of real damage.

Using an antivirus on Mac is, in my opinion, unnecessary and only serves to slow your computer down and scare you with false positives like the one shown here.

**Comment by ohaiibuzzle** [comment]
@Drjacky And if you aren’t convinced yet, here is a more technical explanation:

Mac antivirus programs typically falls into two types: Unnecessary and Adware. 
Amazingly, Avast managed to kill two birds with one stone and did both!

The “malware” it detects (WormX-gen) is a **generic** detection, hence the “gen” in the name. Now, I’m not going to talk about why a Win32 virus even matter on a Mac system, but, ignoring that, it manages to detect what is basically a re-implementation of a library as a virus, suggesting that this thing isn’t even smart enough to do heuristic and see just what kind of dll it is.

And let’s not talk about Avast’s free stuff being a walking billboard for their other products nowadays.

TL,DR: You don’t need it, and freaking out over this is stilly

**Comment by Drjacky** [comment]
Thanks for the explanation. That was helpful.
I do not agree with the part that Mac users don't need an antivirus.
Feel free to follow what these guys are doing:
https://objective-see.org/
https://www.clamav.net/ 

But yeah, I'm gonna add those files to the exception list to be ignored.

**Comment by ohaiibuzzle** [comment]
> I do not agree with the part that Mac users don't need an antivirus.

I don’t think you notice the nature of those tools:
- Objective-See’s tools are only there for you to **manually** inspect what applications are doing on your device, it doesn’t necessarily detect harmful stuff by itself
- ClamAV is just ClamAV, it's literally available everywhere (even embedded stuff tbh)

The reason why the Mac doesn’t need antivirus as such is that unlike Windows, macOS’s system files are immuatable (aka. you cannot even modify a single system file to persist your infection). All “malware” can do on Mac is at the user level: either adware annoying you or data stealers, which, if you have enough common sense to not just run random stuff, isn’t an issue, unlike Windows where a malicious ring 0 driver can literally read/write all of memory
