### ISSUE TITLE
I can not run CS2 with DXVK

### ISSUE THREAD

**Issue by suservu123** [Whisky-App/Whisky#469]
I have turn on DXVK anh DXVK Async but the game still open with GPTK. 
<img width="1308" alt="Screenshot 2023-10-02 at 13 56 15" src="https://github.com/Whisky-App/Whisky/assets/71489512/256522bb-bbbc-43d7-93da-6a0d1e32a787">
<img width="2056" alt="Screenshot 2023-10-02 at 13 56 01" src="https://github.com/Whisky-App/Whisky/assets/71489512/0eb39725-4dea-4573-87c5-aa044ce99187">

**Comment by Crd5** [comment]
Youre using DXVK but you enabled metal hud

**Comment by suservu123** [comment]
> Youre using DXVK but you enabled metal hud

MetalHUD just a tool let you see the performance of game while playing

**Comment by suservu123** [comment]
> Same issue for me, metal hud doesn't matter, for some reason games ran via steam don't pick dxvk, just default to gptk. If you run the same game outside of steam, directly - they run correctly with dxvk but for cs2 i.e. it doesn't let you play online this way.

Yeah i hope next update will fix this issue

**Comment by IsaacMarovitz** [comment]
> MetalHUD just a tool let you see the performance of game while playing

Yes but the version displayed here is GPTK's HUD

**Comment by IsaacMarovitz** [comment]
A workaround for this is to start Steam, and then start CS2 externally from Whisky with (with proper commands set in Whisky).

The problem is Steam has UI issues when running under DXVK, so it has DLL Overrides to overcome that. Unfortunately, these overrides are inherited by all processes started from Steam.

**Comment by kelvinthh** [comment]
> A workaround for this is to start Steam, and then start CS2 externally from Whisky with (with proper arguments set in Whisky).
> 
> The problem is Steam has UI issues when running under DXVK, so it has DLL Overrides to overcome that. Unfortunately, these overrides are inherited by all processes started from Steam.

With this work around I'm not able to connect to my own server, but if I launch via Steam I can, but the game will freeze and crash within minutes. I guess the launch externally method somehow messes up the anti-Cheat, it's reporting the connection to the server being insecure.

**Comment by tomas-hanzlik** [comment]
> A workaround for this is to start Steam, and then start CS2 externally from Whisky with (with proper arguments set in Whisky).

The game is fluent now but having the same issue as @kelvinthh 

I am unable to play only due to Anti-Cheat error
