### ISSUE TITLE
[Bug]: Cannot Import isskin.dll

### ISSUE THREAD

**Issue by moonsweel** [Whisky-App/Whisky#471]
### Description

Some games fail to install with the following error:
<img width="444" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3405348/4e716933-ae1d-4f5b-a75c-cc08cc6e04b1">

### Steps to reproduce

Just try to install a game.

### Expected behaviour

No error happens

### Logs

```bash
-
```

### What version of Whisky are you using?

2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by moonsweel** [comment]
I found the solution, you need to run winetricks with "vcrun6sp6" argument like so
<img width="655" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3405348/f0dab7da-f6f8-4cdc-adbb-712256136227">

If you get something like "winetricks is not found" in the terminal run after you hit "Run...", find the winetricks binary file, i.e. install it through homebrew, and copy the installed binary to the ""/Users/user/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/" dir.

**Comment by Rose937** [comment]
For those who are looking for how to install the component, click on the Winetricks button, the library and at the very bottom of this component

**Comment by blackseabreathe** [comment]
Thanks a lot

**Comment by Fakhriddin3040** [comment]
> I found the solution, you need to run winetricks with "vcrun6sp6" argument like so (type "vcrun6sp6" here)
> <img width="655" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3405348/f0dab7da-f6f8-4cdc-adbb-712256136227">
> 
> If you get something like "winetricks is not found" in the terminal that run after you hit "Run...", find the winetricks binary file, i.e. install it through homebrew, and copy the installed binary to the "/Users/user/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/" dir.

Hello. Can u help me too? I have the same issue but, I couldn't use the solution you provided. I cannot find "Run winetricks...".
