### ISSUE TITLE
[Bug]: Bottles renamed to "BOTTLE" and Installed Programs now empty

### ISSUE THREAD

**Issue by tarasis** [Whisky-App/Whisky#476]
### Description

After updating to 2.0.1 my bottles now have the Generic name "Bottle", and the list of installed programs is empty or only shows Steam.

How I was greeted after update

<img width="1012" alt="Screenshot 2023-10-05 at 00 06 36" src="https://github.com/Whisky-App/Whisky/assets/3006/d8babdc5-87c1-41e0-b692-3d74b1296187">

Showing the exes/link that should show up under installed programs. Opening it up, it only shows the usual IEEXPLORE, wmplayer, wordpad.

<img width="926" alt="Screenshot 2023-10-05 at 00 15 34" src="https://github.com/Whisky-App/Whisky/assets/3006/034cd403-f9f9-4bdd-893c-3fdc4eee5599">

### Steps to reproduce

Used 1.x version of Whisky
Created 3 bottles (two with direct GOG game installs, one with Steam and a game)
Quit
Updated to 2.0.1 bottles now renamed to BOTTLE
List of Installed Programs empty.

### Expected behaviour

That the bottles retain there name, and the installed programs shows the programs.

### Logs

```bash
Not applicable
```

### What version of Whisky are you using?

2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by mavethee** [comment]
Known issue after update to 2.x,
Bottles can be renamed and should work fine, if any shortcuts disappeared my suggestion is to re-add them manually or re-do the bottles and do not store games in them but rather in folders e.g. like Heroic does in `~/Games` to avoid issues with reinstalling them once bottle breaks after major update.
