### ISSUE TITLE
[Feature]: Add support to install the app to external drive.

### ISSUE THREAD

**Issue by Lucas04-nhr** [Whisky-App/Whisky#478]
### Is your feature request related to a problem?

No, my feature request is not related to a problem.

### Describe the solution you'd like

The built-in storage of my Mac is small, so I want to install the Whisky app and its bottle to an external disk. However, the only way to solve this problem is to add symlink via terminal. 
(See Discussion #477)

### Anything else?

There’s nothing else to explain.

### Issue Language

- [X] Yes my issue is written in English

**Comment by sorae42** [comment]
You should create a bottle in that external disk instead.

If you don't want to, you should modify the installation path when you install that program.
