### ISSUE TITLE
[Bug]: Retina toggle not shown in bottle settings

### ISSUE THREAD

**Issue by martimcfly** [Whisky-App/Whisky#485]
### Description

When setting up a new bottle using Windows 10 retina toggle is not shown in the bottle config. Instead, there is just a grayed-out string shown which says: "Keine Angabe".

### Steps to reproduce

Open Whiskey
Create a new bottle
Click on Bottle Config
Try to find Retina Mode

### Expected behaviour

I am expecting to see a toggle to turn on retina mode.
I am running whiskey on a m2 pro 14 inch base model with no external screen

### Logs

```bash
No Logs were provided.
```

### What version of Whisky are you using?

2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I've pushed another fix for this
