### ISSUE TITLE
[Feature]: Do not quit apps when closing Whisky window

### ISSUE THREAD

**Issue by sorae42** [Whisky-App/Whisky#489]
### Is your feature request related to a problem?

When you close the last Whisky window, the app will also quit all wine process.

### Describe the solution you'd like

Closing all window should not quit all Wine process nor quitting Whisky itself. (Treat Whisky as a document-like app)

### Anything else?

none

### Issue Language

- [X] Yes my issue is written in English

**Comment by himbeles** [comment]
Just a side-note: the current approach has the advantage that you don't need to manually kill potential wine-prelauncher "zombie" processes that remain after quitting wine apps.

**Comment by sorae42** [comment]
Using a task manager is more recommend actually. That's how people have been doing for years.

**Comment by eetgeenappels** [comment]
Maybe add an option to enable/disable this behaviour.
