### ISSUE TITLE
[Bug]: Unable to create a bottle

### ISSUE THREAD

**Issue by az1m00** [Whisky-App/Whisky#490]
### Description

Unable to create a bottle

### Steps to reproduce

I launch the whiskey, create a bottle, but the bottle disappears at the same moment and is not created

### Expected behaviour

I wanna play dark souls, but it not working, please help 

https://github.com/Whisky-App/Whisky/assets/147241976/0874a8c7-3689-4a3c-9b98-ade388615fcc

### Logs

```bash
in expected behavior
```

### What version of Whisky are you using?

2.0.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by AlisherAdylov** [comment]
Not all games run with Whisky

**Comment by Dynamix16383** [comment]
I have this problem too. I am using m1 pro (8 core CPU and 14 core GPU) and 16GB of RAM.
Log file as shown
[2023-10-08T08:59:58Z.log](https://github.com/Whisky-App/Whisky/files/12840245/2023-10-08T08.59.58Z.log)

**Comment by Dynamix16383** [comment]
Whisky Version: 2.0.2
Date: 2023/10/8 16:59:58
macOS Version: 版本14.0（版號23A344）
Bottle Name: test
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/sheungwaiip/Library/Containers/com.isaacmarovitz.Whisky/Bottles/AAA02C98-06A5-4D33-9ACB-8C2A075CD8E2

Arguments: winecfg -v win10 

Launched Wine (61019)
00fc: thread_get_state failed on Apple Silicon - faking zero debug registers
0024:err:environ:run_wineboot boot event wait timed out

**Comment by mavethee** [comment]
Show Wine -> Setup tab.

**Comment by xiexie1111** [comment]
我也有相同的問題，我也要是 macBook Pro 14吋M1Pro晶片 我下載的也是最新版的Whisky 和樓主有相同的情況無法建立bottle 希望你們可以快速處理這個問題，謝謝

**Comment by az1m00** [comment]
ive got a solution you need open terminal and put there ```softwareupdate --install-rosetta``` after press A @AlisherAdylov help me to found out

**Comment by gakkun0108** [comment]
I tried that command updatesoftware ~ then resolved the problem thank you 🥰

**Comment by Nikodemek131** [comment]
that still doesnt work for me

**Comment by Nikodemek131** [comment]
guys i found another solution
open whisky then click on whisky in the top left then click setup and uninstall whiskywine then reinstall it

**Comment by xiexie1111** [comment]
非常感谢，其实我已经解决了 不过这是个bug希望你们的工程师可以从根源解决



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: Nikodemek131 ***@***.***&gt;
Date: Mon,Feb 3,2025 9:19 PM
To: Whisky-App/Whisky ***@***.***&gt;
Cc: xiexie1111 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Whisky-App/Whisky] [Bug]: Unable to create a bottle (Issue #490)





 
guys i found another solution
 open whisky then click on whisky in the top left then click setup and uninstall whiskywine then reinstall it
