### ISSUE TITLE
[Огапсото]:

### ISSUE THREAD

**Issue by timka191010** [Whisky-App/Whisky#493]
### Description

 can not install the application

### Steps to reproduce

![IMG_8241](https://github.com/Whisky-App/Whisky/assets/130147481/448689b9-88a6-4de3-bd7a-62aec5af4cf9)

### Expected behaviour

please fix

### Logs

```bash
I don't have logs
```

### What version of Whisky are you using?

2.0.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by YRychkov** [comment]
What are the steps to reproduce the error? You just sent us a screenshot of an error message. I don't have this problem so it's quite difficult to help you.

**Comment by excellproj** [comment]
Учитывая, что ты фоткаешь экран, то не удивительно xD

**Comment by IsaacMarovitz** [comment]
The screenshot is bunk, and you've not provided any details, please remake this issue with sufficient information so we can help you.
