### ISSUE TITLE
[Feature]: a useful Wiki

### ISSUE THREAD

**Issue by yawnbox** [Whisky-App/Whisky#498]
### Is your feature request related to a problem?

The wiki is for people who know what they're doing.

```
[Installing your first program](https://github.com/Whisky-App/Whisky/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml&title=%5BFeature%5D%3A+#installing-your-first-program)

1. Click on the bottle you want to install your program into
2. Press the Run... button in the bottom right
3. Navigate to where you have your exe or msi file in Finder
4. Select the file and press Open
```

Where is the really important step 2.5?

1. When did I download an EXE or MSI?
2. Where did it go?
3. Why would I need to do this?
4. Where does the "drive_c" exist?
5. Do I need to put things in "dive_c" somewhere?
6. Like, what is going on here, and why don't you explain things better?

### Describe the solution you'd like

A complete guide for people who have never used this before.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by d12bb** [comment]
Also: New bottle for every game? New bottle for every game launcher (one for all Steam games etc.)? What's the difference to CrossOver (especially now they support AGPT too)?

**Comment by IsaacMarovitz** [comment]
I've updated [A Hitchhiker's Guide to Whisky](https://github.com/Whisky-App/Whisky/wiki/A-Hitchhiker's-Guide-to-Whisky). Let me know if you think it's still inadequate.
