### ISSUE TITLE
[错误]：无法成功建立bottle

### ISSUE THREAD

**Issue by xiexie1111** [Whisky-App/Whisky#499]
### Description

我使用的是MacBook Pro 14寸2021款M1 Pro芯片下载的最新版本whiskey 电脑系统已升级为Sonoma 帮我建立 bottle 时 软件会不起作用不会显示任何东西，希望你们可以尽快处理！

### Steps to reproduce

使用MacBook升级到最新Sonoma系统 系统下载最新whisky 2.0.2 系统语言为英语 不管如何操作whisky 都不会有反应 我已重置系统又尝试了一遍 还是无法正常创建

### Expected behaviour

可以成功建立bottle，并且可以正常使用可

### Logs

```bash
.
```

### What version of Whisky are you using?

2.0.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Issue is not in English.
