### ISSUE TITLE
[Bug]: Apps written in C# (for example: SDA) are not launching.

### ISSUE THREAD

**Issue by excellproj** [Whisky-App/Whisky#500]
### Description

Unable to launch applications written in C#. .NET Framework is installed. For example, I am trying to run the SDA (Steam Desktop Authenticator) application. After launching, nothing happens.

https://github.com/Whisky-App/Whisky/assets/5286593/eebd3138-85ae-4498-bdb4-9403309e3ae2

### Steps to reproduce

Watch the video

### Expected behaviour

I expect the application to start. For example, in Crossover, everything works fine.

### Logs

```bash
There is no information in the logs.
```

### What version of Whisky are you using?

2.0.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You will need to install the correct dotnet version using Winetricks

**Comment by IsaacMarovitz** [comment]
Running `dotnet472` on Winetricks should solve this

**Comment by excellproj** [comment]
> Running `dotnet472` on Winetricks should solve this

👆
