### ISSUE TITLE
[Bug]: Diablo 4 stuck in endless Updating / Play loop after msync update

### ISSUE THREAD

**Issue by dev-mush** [Whisky-App/Whisky#507]
### Description

After updating to the latest version of whisky that enables msync support and redownloading gptk as instructed, the battlenet launcher fails to run diablo 4

### Steps to reproduce

- Update to whisky latest `Version 2.1.0 (29)`
- Uninstall and redownload gptk
- Configure the bottle for diablo 4 as instructed [here](https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv) (except for the esync part which is now missing)
- Try launching the diablo 4 game by pressing play

### Expected behaviour

Diablo 4 starts as always, but it instead starts an "Updating" phase and then goes back to play.
(Disabling msync entirely causes the wine launcher to fail)

### Logs

```bash
Whisky Version: 2.1.0
Date: 12/10/2023, 17:00:00
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: Bottle
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/mush/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DF62AE9A-A411-4A83-BEFB-EB17C755D350

Arguments: start /unix /Users/mush/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DF62AE9A-A411-4A83-BEFB-EB17C755D350/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe 

Launched Wine (1638)
msync: bootstrapped mach port on wine-13914fd-msync.
msync: up and running.
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/mush/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00e0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
01f8: thread_get_state failed on Apple Silicon - faking zero debug registers
	VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_su0250: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] GPU device:
		model: Apple M2 Pro
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0003f0
		pipelineCacheUUID: DB8512A6-0E00-03F0-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 8
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
02fc: thread_get_state failed on Apple Silicon - faking zero debug registers
0320: thread_get_state failed on Apple Silicon - faking zero debug registers
040c: thread_get_state failed on Apple Silicon - faking zero debug registers
0438: thread_get_state failed on Apple Silicon - faking zero debug registers
05f0: thread_get_state failed on Apple Silicon - faking zero debug registers
05f8: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lilthundamane** [comment]
Hello, can you please tell how to get log? I want to report a bug, but no idea where logs are stored. Thanks

**Comment by bamesserly** [comment]
I think I'm in the same boat, but with Diablo II: Resurrected. Everything was working great in 2.0.2.

For me, I updated Whiskey to 2.1.0, (did not redownload GPTK), kept my bottle config as before (tried toggling msync to no avail), started bnet launcher, opened D2R, and D2R app opens as a black window (not full screen as usual), and hangs there indefinitely.

I tried reverting to 2.0.2 (drag whisky app to trash, DL 2.0.2 from releases), but am seeing the same symptom. Next steps I'll try: with 2.1.0 reinstalling gptk, importing a version of the bottle which I exported from 2.0.2, re-making the bottle, and finally a clean re-install of whisky and d2r (though without an uninstaller I'm going to have a hard time cleaning out all the old whisky files, maybe.) I'll also compare my logs with the one above to see if we might indeed be looking at the same issue.

**Comment by lilthundamane** [comment]
> I think I'm in the same boat, but with Diablo II: Resurrected. Everything was working great in 2.0.2.
Experiencing the same issue here. Everything was working fine, but after the update and redownloading GPTK, Diablo II Resurrected hangs on a windowed black screen indefinitely. I've tried adjusting all settings, but it hasn't resolved the problem.

**Comment by MaHaGoNet** [comment]
> I removed everything, including Application Support/ dirs and Library/Container/ stuff, 

Please tell me which Dirs I have to delete. I thought to have delete all, but still hanging in Update Loop at Diablo4. Reinstall Whisky, BattleNet, Diablo too. 

Whisky is install in programs at onBoard SSD, Bottle with D4 is installed at a TB3 NVME. Whisky 2.02 run fine.
System: Mac mini M1 16GB/512GB with Sonoma.

**Comment by Gubbledenut** [comment]
same issue here, I have gone back to ver 2.0.0 and turned on esync..all is working

**Comment by bartech0** [comment]
temporary solution to have version 2.1.0 and be able to play D4 or D2R:
- turn off MSync
- In Environment Variables add a key WINEESYNC with value set to 1, to enable back ESync and enjoy your game

<img width="167" alt="image" src="https://github.com/Whisky-App/Whisky/assets/38248837/377f92b1-6b82-4080-8a22-757f34c74e19">
<img width="736" alt="image" src="https://github.com/Whisky-App/Whisky/assets/38248837/af22c3c5-7e09-4879-a0e1-73ea1374f8de">

**Comment by Gubbledenut** [comment]
That works   on 2.1.0 now, Thank you

**Comment by kadorito** [comment]
I updated to 2.1 as well and Diablo IV is not lauching any more. I guess it's the same Esync issue since the option dissapeared

**Comment by azat-io** [comment]
@bartech2508 Looks like this solution not works for me:

<img width="344" alt="image" src="https://github.com/Whisky-App/Whisky/assets/5698350/ed06ba29-ce31-48f8-beed-00a77f2f4762">

Could you show me your bottle configuration?

**Comment by bartech2508** [comment]
> @bartech2508 Looks like this solution not works for me:
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/5698350/276325729-ed06ba29-ce31-48f8-beed-00a77f2f4762.png">
> 
> Could you show me your bottle configuration?


Hey, sorry but I'm using battlenet version, have no idea about steam, but I assume that's why you have an issue which I never saw before

**Comment by MaHaGoNet** [comment]
Hi
Let´s have a look at two workarounds in the past comments in this thread.

Workaround 1: https://github.com/Whisky-App/Whisky/issues/507#issuecomment-1761201492

Workaround 2: Myself has downgrade Whisky to V 2.0.2 (just download the old version on GitHub und install it). 

Don't forget the hint on download site to Wiki D4 and other games.

Greets

**Comment by georgebouz1** [comment]
does this works on immortal too?

**Comment by georgebouz1** [comment]
When I try to open Diablo Immortal I get an error which says a serious problem appeared and the game doesn't open

**Comment by Mac-Gamer** [comment]
> temporary solution to have version 2.1.0 and be able to play D4 or D2R:
> 
> * turn off MSync
> * In Environment Variables add a key WINEESYNC with value set to 1, to enable back ESync and enjoy your game
> 
> <img alt="image" width="167" src="https://user-images.githubusercontent.com/38248837/274859103-377f92b1-6b82-4080-8a22-757f34c74e19.png"> <img alt="image" width="736" src="https://user-images.githubusercontent.com/38248837/274859160-af22c3c5-7e09-4879-a0e1-73ea1374f8de.png">

Thank you very much, that trick worked for me

**Comment by Mhmnz** [comment]
> @bartech2508看起来这个解决方案不适合我：> @bartech2508看起来这个解决方案不适合我：>> <img alt="图像" width="344" src="https://user-images.githubusercontent.com/5698350/276325729-ed06ba29-ce31-48f8-beed-00a77f2f4762.png">> 你能给我看看你的瓶子配置吗？>> <img alt="图像" width="344" src="https://user-images.githubusercontent.com/5698350/276325729-ed06ba29-ce31-48f8-beed-00a77f2f4762.png">> 你能给我看看你的瓶子配置吗？第十个英文字母J  can you work? my steam is same to you

**Comment by stupidface89** [comment]
How you did add Diablo IV application in this list ? I try make same with Diablo II, but needed .exe file not on the list applications :(

**Comment by Mhmnz** [comment]
> How you did add Diablo IV application in this list ? I try make same with Diablo II, but needed .exe file not on the list applications :(

need  buy it....but it can not work by whisky

**Comment by stupidface89** [comment]
> > How you did add Diablo IV application in this list ? I try make same with Diablo II, but needed .exe file not on the list applications :(
> 
> need buy it....but it can not work by whisky

Come on, already bought

**Comment by bartech2508** [comment]
ok guys I see some confusion, even that something is obvious for men, might not be for the others, so I will make very detailed instruction, as a fix, for now:
Prerequisites:
1. Whisky in version 2.1.0
2. Diablo IV bought with installed battle.net
3. Everything else like on wiki page: https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
4. I'm assuming that Whisky is installed properly with gaming platform toolkit (GPTK), Whisky etc. I will not make a guide for it here, it's in project documentation.

All required settings of the bottle:
<img width="756" alt="image" src="https://github.com/Whisky-App/Whisky/assets/38248837/3f53467d-cd85-4ce9-9c99-540f3445af75">

On the list of installed programs you need to find Diablo IV.exe and add the environment variable by clicking the cogwheel:
<img width="753" alt="image" src="https://github.com/Whisky-App/Whisky/assets/38248837/dd783fba-1cfb-4219-a8e2-db6d76dcacaf">
<img width="760" alt="image" src="https://github.com/Whisky-App/Whisky/assets/38248837/cefa785e-9bce-4638-a565-89eba1fc4436">


For instruction step by step, go to wiki mentioned in point 3 in prerequisites. That's all.

**Comment by Mhmnz** [comment]
> 好吧，伙计们，我看到了一些困惑，即使对男人来说很明显，但对其他人来说可能不是，所以我现在会做出非常详细的指导，作为修复：先决条件：
> 
> 1. 2.1.0版本的威士忌
> 2. 暗黑破坏神IV通过安装battle.net购买
> 3. 维基页面上的其他一切：https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
> 4. 我假设威士忌与游戏平台工具包（GPTK）、威士忌等一起正确安装。我不会在这里为它做指南，它在项目文档中。
> 
> 瓶子的所有必要设置： <img alt="图像" width="756" src="https://user-images.githubusercontent.com/38248837/277229311-3f53467d-cd85-4ce9-9c99-540f3445af75.png">
> 
> 在已安装程序列表中，您需要找到Diablo IV.exe，并通过单击齿轮添加环境变量： <img alt="图像" width="753" src="https://user-images.githubusercontent.com/38248837/277229457-dd783fba-1cfb-4219-a8e2-db6d76dcacaf.png"> <img alt="图像" width="760" src="https://user-images.githubusercontent.com/38248837/277229477-cefa785e-9bce-4638-a565-89eba1fc4436.png">
> 
> 要逐步获得说明，请转到先决条件中第3点中提到的维基。仅此而已。

i

> ok guys I see some confusion, even that something is obvious for men, might not be for the others, so I will make very detailed instruction, as a fix, for now: Prerequisites:
> 
> 1. Whisky in version 2.1.0
> 2. Diablo IV bought with installed battle.net
> 3. Everything else like on wiki page: https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
> 4. I'm assuming that Whisky is installed properly with gaming platform toolkit (GPTK), Whisky etc. I will not make a guide for it here, it's in project documentation.
> 
> All required settings of the bottle: <img alt="image" width="756" src="https://user-images.githubusercontent.com/38248837/277229311-3f53467d-cd85-4ce9-9c99-540f3445af75.png">
> 
> On the list of installed programs you need to find Diablo IV.exe and add the environment variable by clicking the cogwheel: <img alt="image" width="753" src="https://user-images.githubusercontent.com/38248837/277229457-dd783fba-1cfb-4219-a8e2-db6d76dcacaf.png"> <img alt="image" width="760" src="https://user-images.githubusercontent.com/38248837/277229477-cefa785e-9bce-4638-a565-89eba1fc4436.png">
> 
> For instruction step by step, go to wiki mentioned in point 3 in prerequisites. That's all.

it is cool bro ,I play diablo4 at steam. how to do ?thx

**Comment by stupidface89** [comment]
> > ok guys I see some confusion, even that something is obvious for men, might not be for the others, so I will make very detailed instruction, as a fix, for now: Prerequisites:
> > 
> > 1. Whisky in version 2.1.0
> > 2. Diablo IV bought with installed battle.net
> > 3. Everything else like on wiki page: https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
> > 4. I'm assuming that Whisky is installed properly with gaming platform toolkit (GPTK), Whisky etc. I will not make a guide for it here, it's in project documentation.
> > 
> > All required settings of the bottle
> > On the list of installed programs you need to find Diablo IV.exe and add the environment variable by clicking the cogwheel
> > For instruction step by step, go to wiki mentioned in point 3 in prerequisites. That's all.
> 
> it is cool bro ,I play diablo4 at steam. how to do ?thx

Try next:
In root your Bottle folder, find folder Program Setting, create empty txt file with name "Diablo IV.exe.plist" (without quotes ofc.) and put inside next:


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>arguments</key>
	<string></string>
	<key>environment</key>
	<dict>
		<key>WINEESYNC</key>
		<string>1</string>
	</dict>
	<key>locale</key>
	<string></string>
</dict>
</plist>

**Comment by stupidface89** [comment]
> > > ok guys I see some confusion, even that something is obvious for men, might not be for the others, so I will make very detailed instruction, as a fix, for now: Prerequisites:
> > > 
> > > 1. Whisky in version 2.1.0
> > > 2. Diablo IV bought with installed battle.net
> > > 3. Everything else like on wiki page: https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
> > > 4. I'm assuming that Whisky is installed properly with gaming platform toolkit (GPTK), Whisky etc. I will not make a guide for it here, it's in project documentation.
> > > 
> > > All required settings of the bottle
> > > On the list of installed programs you need to find Diablo IV.exe and add the environment variable by clicking the cogwheel
> > > For instruction step by step, go to wiki mentioned in point 3 in prerequisites. That's all.
> > 
> > 
> > it is cool bro ,I play diablo4 at steam. how to do ?thx
> 
> Try next: In root your Bottle folder, find folder Program Setting, create empty txt file with name "Diablo IV.exe.plist" (without quotes ofc.) and put inside next:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>arguments</key>
	<string></string>
	<key>environment</key>
	<dict>
		<key>WINEESYNC</key>
		<string>1</string>
	</dict>
	<key>locale</key>
	<string></string>
</dict>
</plist>
`

**Comment by Mhmnz** [comment]
> > > ok guys I see some confusion, even that something is obvious for men, might not be for the others, so I will make very detailed instruction, as a fix, for now: Prerequisites:
> > > 
> > > 1. Whisky in version 2.1.0
> > > 2. Diablo IV bought with installed battle.net
> > > 3. Everything else like on wiki page: https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
> > > 4. I'm assuming that Whisky is installed properly with gaming platform toolkit (GPTK), Whisky etc. I will not make a guide for it here, it's in project documentation.
> > > 
> > > All required settings of the bottle
> > > On the list of installed programs you need to find Diablo IV.exe and add the environment variable by clicking the cogwheel
> > > For instruction step by step, go to wiki mentioned in point 3 in prerequisites. That's all.
> > 
> > 
> > it is cool bro ,I play diablo4 at steam. how to do ?thx
> 
> Try next: In root your Bottle folder, find folder Program Setting, create empty txt file with name "Diablo IV.exe.plist" (without quotes ofc.) and put inside next:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>arguments</key>
> 	<string></string>
> 	<key>environment</key>
> 	<dict>
> 		<key>WINEESYNC</key>
> 		<string>1</string>
> 	</dict>
> 	<key>locale</key>
> 	<string></string>
> </dict>
> </plist>
> ```

very very ty bro, but I do not understand root, I can not find it ,where to creat txt,please tell me by pictures ty again

**Comment by Mhmnz** [comment]
> > > ok guys I see some confusion, even that something is obvious for men, might not be for the others, so I will make very detailed instruction, as a fix, for now: Prerequisites:
> > > 
> > > 1. Whisky in version 2.1.0
> > > 2. Diablo IV bought with installed battle.net
> > > 3. Everything else like on wiki page: https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv
> > > 4. I'm assuming that Whisky is installed properly with gaming platform toolkit (GPTK), Whisky etc. I will not make a guide for it here, it's in project documentation.
> > > 
> > > All required settings of the bottle
> > > On the list of installed programs you need to find Diablo IV.exe and add the environment variable by clicking the cogwheel
> > > For instruction step by step, go to wiki mentioned in point 3 in prerequisites. That's all.
> > 
> > 
> > it is cool bro ,I play diablo4 at steam. how to do ?thx
> 
> Try next: In root your Bottle folder, find folder Program Setting, create empty txt file with name "Diablo IV.exe.plist" (without quotes ofc.) and put inside next:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>arguments</key>
> 	<string></string>
> 	<key>environment</key>
> 	<dict>
> 		<key>WINEESYNC</key>
> 		<string>1</string>
> 	</dict>
> 	<key>locale</key>
> 	<string></string>
> </dict>
> </plist>
> ```

ty bro,I am hopeless. I followed your method and what others said was useless

**Comment by Qonstrukt** [comment]
Might be great to have a toggle per app between no-sync/esync/msync, because it can really differ per app what works best.
The only downside being that wineserver can run with only one active option at a time.

I also saw that the msync implementation got a some updates in the last couple of days, so it would be good to try and stay up to date with that as well.

**Comment by IsaacMarovitz** [comment]
To all those experiencing issues, please try again in the latest GPTK build with the latest MSync commits (1.0.0+2) and let me know if the issue still occurs.

**Comment by Gubbledenut** [comment]
No sorry, i turned on msync, removed the wineesync variable, restarted whisky, same issue, won't launch game, opens battlenet again.
running latest loaded GPTK from suggestion in whisky.
turned off msnyc put back wineesync variable working again

**Comment by cuba** [comment]
For me, clicking on the cog and adding WINEESYNC didn't work. 

But this worked:
1. Click on Open C: Drive
2. Go to Program Settings
3. Find and edit (or create) Diablo IV.exe.plist
4. Make sure you have the following
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>arguments</key>
	<string></string>
	<key>environment</key>
	<dict>
		<key>WINEESYNC</key>
		<string>1</string>
	</dict>
	<key>locale</key>
	<string></string>
</dict>
</plist>
```

**Comment by Mhmnz** [comment]
> To all those experiencing issues, please try again in the latest GPTK build with the latest MSync commits (1.0.0+2) and let me know if the issue still occurs.

hi bro can you fix Diablo4 at steam? it do not work through steam thx!

**Comment by dclive** [comment]
I'm not getting anywhere with D4 BN version. 

I installed Whisky 2.1, installed BN, Win10 version 19042.  MSync off.  Async off.  

Going to B.N or D4 or D4-Launcher and keying Config/EnvVar of "WINEESYNC" "1" results in "Failed to open program!" errors....

If I remove the "1" next to WINEESYNC, it tries to endlessly update. 

If I make my Diableo IV EXE PLIST look like this: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>arguments</key>
	<string></string>
	<key>environment</key>
	<dict>
		<key>WINEESYNC</key>
		<string>1</string>
	</dict>
	<key>locale</key>
	<string></string>
</dict>
</plist>
```
...then BN opens but the app just wants to endlessly update. 

Any ideas on a fix?

**Comment by dclive** [comment]
Still dead in the water here.  

Sonoma 14.1, Whisky 2.1.1, and the following settings: 

![image](https://github.com/Whisky-App/Whisky/assets/4536776/d9f0f186-6df3-4e59-9904-a3d5e7e155a5)
![image](https://github.com/Whisky-App/Whisky/assets/4536776/55cf3289-1ebf-41aa-954c-7fb3dadec74f)
![image](https://github.com/Whisky-App/Whisky/assets/4536776/6c9fd883-32fa-410f-90fc-7b065d5104ff)
![image](https://github.com/Whisky-App/Whisky/assets/4536776/2c950b95-b4d1-4169-9b5d-e3ffe8fe8cc8)

And when I run Diablo IV, all I get is this: 

![image](https://github.com/Whisky-App/Whisky/assets/4536776/170a71e9-eca1-4faf-86e2-682b7d17c5f0)

This happens immediately.  

My Program Settings / Diablo IV.exe.plist settings are: 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>arguments</key>
	<string></string>
	<key>environment</key>
	<dict>
		<key>WINEESYNC</key>
		<string>1</string>
	</dict>
	<key>locale</key>
	<string></string>
</dict>
</plist>


Any ideas?

**Comment by IsaacMarovitz** [comment]
Superceeded by #554

**Comment by dclive** [comment]
Moving to 2.13 and then flipping the toggle from msync to esync fixed my Diablo issues; I made no other changes - D4 (BN) immediately opened and ran.  Thank you!
