### ISSUE TITLE
[Feature]: Swap the position of loading/modifying progress view and other content view.

### ISSUE THREAD

**Issue by kolyneh** [Whisky-App/Whisky#509]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Unlike the system's Settings app, Whisky show loading/modifying progress view right after the other content.
There position should be swapped to avoid view flicker when view state changes.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Can you provide an example?

**Comment by kolyneh** [comment]
Here :
![Screenshot 2023-10-14 at 14 21 25](https://github.com/Whisky-App/Whisky/assets/13062910/8b99f165-0c04-45f8-a6b8-5e0862f6b1a6)

![Screenshot 2023-10-14 at 14 22 40](https://github.com/Whisky-App/Whisky/assets/13062910/ddd805c2-f7c0-4bb4-9df7-7698e7ba4300)

For Whisky flicker:
![2023-10-14 14-42-48](https://github.com/Whisky-App/Whisky/assets/13062910/76a801d0-a564-4b59-89bc-85494587139a)

**Comment by kolyneh** [comment]
Thanks for your update!

But with that updated animation, we have another flicker issue:
![2023-10-30 15-02-56](https://github.com/Whisky-App/Whisky/assets/13062910/c6f64777-10a7-46c9-8174-a922b1fc59a3)

See the `Windows Version ` and `DPI Scaling` slightly changed their position when load end.
Maybe it's because of the different height of `content` child views in `SettingItemView`.
