### ISSUE TITLE
[Bug]: Wine 7.7 can't recognise the available space correctly

### ISSUE THREAD

**Issue by ddouble** [Whisky-App/Whisky#510]
### Description

I put the bottle to an 4TB external drive, the drive has 2247GB space available, but I couldn't install game in steam, it reported there's no enough space. The wine reported only 47GB space available when I used the cmd.exe and 'dir c:' command to view the available space. 

Then I installed wine 8.0.1 by brew, it can recognise the available space correctly.
Whisky is currently based on wine 7.7,  hope for moving to wine 8 or any further version which has solved the problem if it's not difficult. 

### Steps to reproduce

1. need a 4TB external disk to reproduce the issue
1. create a new bottle in the 4TB external disk
1. run `dir c:` by `cmd.exe` in the new bottle
1. you can see the available space in the last lines
1. also you can install steam, you can see the available space in settings->storage of steam

### Expected behaviour

wine report the correct space to application

### Logs

```bash
how to get the logs?
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Have you tried using winecfg to mount a directory on the external drive as an extra drive in Wine?

**Comment by ddouble** [comment]
Just tested, cmd.exe can'be recognise the available space correctly for the mounted directory on external drive.  
Also I tried to copy more files to make the available space 1.4TB, then the cmd.exe can recognise it correctly,  then removed those files to make the available space 2.2TB, it can't recognise it correctly again.

**Comment by IsaacMarovitz** [comment]
This is a known issue, but unfortunately, there isn't a whole lot we can do to resolve this.

**Comment by EuroBlue** [comment]
Wow cool almost a year later and im faced with slap on my face
