### ISSUE TITLE
[Bug]: SCORN Game is not working

### ISSUE THREAD

**Issue by Gunmetalblue** [Whisky-App/Whisky#511]
### Is your feature request related to a problem?

Starts just with a black screen and nothing happens

### Describe the solution you'd like

Dunno, i am an ordinary user

### Anything else?

https://store.steampowered.com/app/698670/Scorn/

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Please use the bug template for problems
