### ISSUE TITLE
[Feature]: Game Porting Tool Kit v1.0

### ISSUE THREAD

**Issue by altynbek07** [Whisky-App/Whisky#512]
### Is your feature request related to a problem?

Today has been released GPTK v1.0. How we can integrate in Whisky?
How to update current bottles to  GPTK v1.0?

### Describe the solution you'd like

Link: https://developer.apple.com/download/all/?q=game%20porting%20toolkit

### Anything else?

Integrate for CrossOver: https://www.youtube.com/watch?v=e9mDwm9bQww

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
It is already integrated if your installed GPTK is up to date
