### ISSUE TITLE
[Bug]: Bottle name, and apps icon not available any more after 2.1 update

### ISSUE THREAD

**Issue by kadorito** [Whisky-App/Whisky#514]
### Description

I was running 2.0.2 and I updated to 2.1 today. Several issues to report
My bottle lost its name, it became "Bottle" (I can rename it back of course). But more importantly, the apps icons from my existing bottle are not there any more. If I'm running them manually, they would not come back.

### Steps to reproduce

Update whisky to 2.1

### Expected behaviour

Everything runs as before

### Logs

```bash
Not sure its wine related (well I'm pretty sure it's not)
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Gubbledenut** [comment]
from the correct bottle, select run, from the list, pin the applications you want to show up...then right click on the diablo 4 app icon and add the environmental variable WINEESYNC 1 fix from previous post..it works

**Comment by kadorito** [comment]
Seems like a working workaround thanks ! I guess we need the esync button to come back maybe
