### ISSUE TITLE
[Feature]: Ability to choose default path for creating bottles

### ISSUE THREAD

**Issue by vinhtq115** [Whisky-App/Whisky#517]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I usually create a new bottle on my external SSD instead of MBP's internal SSD in order to preserve the lifetime of the drive. It would be convenient to change the default path where new bottles are created instead of having to browse to the external drive every time.

For example: Whisky -> Setup -> Default bottle path.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Added in https://github.com/Whisky-App/Whisky/commit/e038cad2c80cce0b00f735e51a3194f5860391d1
