### ISSUE TITLE
[Bug]: Permanent lag while steam downloading

### ISSUE THREAD

**Issue by PavelShulya** [Whisky-App/Whisky#520]
### Description

I've permanent lags when downloading game in steam, probably after 5-10 minutes from start. Also i dont know if i'll have it when i start playing cuz it cannot download the game.

### Steps to reproduce

Open steam.exe - log in - starting download - 5-10 mins everything works well then its just not responding. Only fore shutdown helps but after 3-4 tries mac starting warm

### Expected behaviour

How to fix this issue? I cannot use the software while its happens

### Logs

```bash
idk where to find it
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
5-10 minutes is basically around the point where most apps and games begins their decompressing phase, higher than normal CPU usage is expected at this period. Not a bug imo

**Comment by PavelShulya** [comment]
> 5-10 minutes is basically around the point where most apps and games begins their decompressing phase, higher than normal CPU usage is expected at this period. Not a bug imo
> 
> And even if it is, it's a Wine bug, not Whisky.

And how should I use the software if I cannot just download the game without hundreds of shutdowns and restarting Mac. No matter is this a bug or something, I just want to solve it :)

**Comment by tvrrp** [comment]
@PavelShulya turn off MSync in bottle configuration

**Comment by PavelShulya** [comment]
> @PavelShulya turn off MSync in bottle configuration

And finally it works! 😄
