### ISSUE TITLE
[Feature]: Run app directly without prompt when there is only one bottle.

### ISSUE THREAD

**Issue by kolyneh** [Whisky-App/Whisky#522]
### Is your feature request related to a problem?

No need to prompt user to select bottle when there is only one bottle.

### Describe the solution you'd like

When user run exe/msi from Finder (by double click or Open as Whisky) and there is only one bottle, just use it to run the app without prompting the bottle selection modal.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Simple, because now we have to implement a usage case for that one specific usage, which doesn't always makes sense, given that the point of Wine is to have multiple bottles so you can have different configs for apps

**Comment by kolyneh** [comment]
That's great if when can have different configs for bottle - app bindings.

**Comment by IsaacMarovitz** [comment]
That seems reasonable

**Comment by IsaacMarovitz** [comment]
https://github.com/Whisky-App/Whisky/commit/04d189435915c11ffb8f25f677db046ca3b4a4bf

**Comment by kolyneh** [comment]
@IsaacMarovitz Hi it's working, but will still show modal then dismiss suddenly.
And this is for while Whisky running case.

But for Whisky closed case, when user run `exe/msi` from Finder, we can:
- There is only one bottle: Just run it.
- There are more than one bottles: Prompt  user to select one.
