### ISSUE TITLE
[Bug]: Bottle selection dialog will not show up when running exe/msi from Finder while Whisky is closed.

### ISSUE THREAD

**Issue by kolyneh** [Whisky-App/Whisky#523]
### Description

Currently the bottle selection dialog will show up when running exe/msi from Finder while Whisky is open.
But while Whisky is closed, running ext/msi from Finder will only start Whisky and nothing else.

### Steps to reproduce

1. Close Whisky.
2. Run exe/msi from Finder by double click or Open as Whisky.
3. Whisky will start but the exe/msi will not run.

### Expected behaviour

Bottle selection dialog will show up when running exe/msi from Finder even when Whisky is closed.

### Logs

```bash
No
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Should be fixed by https://github.com/Whisky-App/Whisky/commit/199871b897041b59a88791021c170d2058af5477
