### ISSUE TITLE
[Bug]: Cannot open Diablo IV installed via Steam

### ISSUE THREAD

**Issue by azat-io** [Whisky-App/Whisky#536]
### Description

Here is my settings.

<img width="1003" alt="image" src="https://github.com/Whisky-App/Whisky/assets/5698350/915f8ccd-40b8-4344-8fc9-a7d9976cd07e">

I'm trying to launch Diablo IV, Steam says the game is running, but nothing actually happens:

<img width="779" alt="image" src="https://github.com/Whisky-App/Whisky/assets/5698350/b22145d5-63e2-4878-8d69-fe6a379837f9">

### Steps to reproduce

1. Install Diablo IV from Steam
2. Update bottle settings
3. Press "Play" button

### Expected behaviour

The game is launching.

### Logs

I'm not sure that's what's needed:

```
Whisky Version: 2.1.0
Date: 18/10/2023, 3:01:25 AM
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: Bottle
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/azat/Library/Containers/com.isaacmarovitz.Whisky/Bottles/E31756B8-DA6B-4297-AF01-8DF6A9B01C6E

Arguments: start /unix /Users/azat/Library/Containers/com.isaacmarovitz.Whisky/Bottles/E31756B8-DA6B-4297-AF01-8DF6A9B01C6E/drive_c/Program Files (x86)/Steam/steam.exe 

Environment:
{
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
}

Launched Wine (1725)

(wine:1770): GStreamer-CRITICAL **: 03:01:32.441: _gst_util_uint64_scale: assertion 'denom != 0' failed
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
	0158:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Oct 2023 20:00:00 UTC"
0158:err:wininet:HTTP_ParseDate unexpected date format L"Tue, 17 Oct 2023 20:00:00 UTC"
0144: thread_get_state failed on Apple Silicon - faking zero debug registers
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
05a4:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
05b4:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
05b4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
00c0: thread_get_state failed on Apple Silicon - faking zero debug registers
Process exited with code 0

```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by romanhaa** [comment]
I may be experiencing the same thing although I installed D4 through the Battle.net Laucher. I click "Play" and nothing happens. I also tried with the "DXVK" option enabled but that gave me the "No GPU" error.

**Comment by azat-io** [comment]
It's probably related: https://github.com/Whisky-App/Whisky/issues/507

**Comment by peakercope** [comment]
I've tried to run Diablo 4 using gameportingtoolkit directly and got the same error.
Nothing happens if run from steam.
and
"Cedar must be running to play this game" if run directly Diablo IV.exe

**Comment by arog00** [comment]
Same issue here, getting "cedar" error
Steam is working fine, unable to actually open the diablo4 app though.

**Comment by Mhmnz** [comment]
> Same issue here, getting "cedar" error Steam is working fine, unable to actually open the diablo4 app though.

the same one can you work it?

**Comment by arog00** [comment]
> > Same issue here, getting "cedar" error Steam is working fine, unable to actually open the diablo4 app though.
> 
> the same one can you work it?

Now i'm having an issue where steam only loads the main page- the library page isn't working at all. (the whisky bottle crashes when i switch to the library page in Steam). When i try to run the DiabloIV.exe from the whisky main page i get the error "Cedar must be running to play this game"

**Comment by ThibautHerent** [comment]
The issue is still there with version 2.1.1

**Comment by IsaacMarovitz** [comment]
I unfortunately don't have the game on Steam, so I'm unable to test this properly.

**Comment by Juhuameimei** [comment]
Have you solved this problem now?

**Comment by IsaacMarovitz** [comment]
No, Steam Diablo IV can be played in CX 23.

**Comment by Juhuameimei** [comment]
> 不，Steam版《暗黑破坏神IV》可以在CX 23中游玩。

23.6 not work,  must 23.7

**Comment by IsaacMarovitz** [comment]
> 23.6 not work, must 23.7

Yes it works in 23.7+

**Comment by arog00** [comment]
> > 23.6 not work, must 23.7
> 
> Yes it works in 23.7+

23.7 is not released publicly, so currently the Steam version of D4 doesn't work at all.

**Comment by vegetabo** [comment]
> > 不，Steam版《暗黑破坏神IV》可以在CX 23中游玩。
> 
> 23.6 not work, must 23.7

What software are you talking about?  what is CX?  thanks

**Comment by arog00** [comment]
> > > 不，Steam版《暗黑破坏神IV》可以在CX 23中游玩。
> > 
> > 
> > 23.6 not work, must 23.7
> 
> What software are you talking about? what is CX? thanks

Crossover. https://www.codeweavers.com/crossover/download

**Comment by Juhuameimei** [comment]
> > 23.6 不工作，必须 23.7
> 
> 是的，它适用于 23.7+

I tried，it doesn't work in crossover23.7

**Comment by HiberP** [comment]
Delet 'dstorage.dll', the path is program files(x86)/steam/steamapps/common/Diablo IV

**Comment by Mhmnz** [comment]
> Delet 'dstorage.dll', the path is program files(x86)/steam/steamapps/common/Diablo IV

you are the god! it work I can play at steam! ty bro!!!  kiss you!

**Comment by qq424712730** [comment]
> > Delet 'dstorage.dll', the path is program files(x86)/steam/steamapps/common/Diablo IV
> 
> you are the god! it work I can play at steam! ty bro!!! kiss you!

hi  you use which software whisky or crossover?

**Comment by AliG1030** [comment]
Hey guyz i was having the same exact issues, main difference is that with the last version of whisky, i tried the same configuration of the bottle, deleted the file in the steam folder. And still can't launch the game ... If anyone has an idea, i really would like to start my DB4 fiest campaign '^^
