### ISSUE TITLE
[Bug]: Can not install GPTK

### ISSUE THREAD

**Issue by kle-wang** [Whisky-App/Whisky#538]
### Description

I lanuched the whisky but it can not download gptk
i am in China. And i am using clash in my mac
so anyway to use proxy in whisky?
did it have proxy config?
<img width="882" alt="image" src="https://github.com/Whisky-App/Whisky/assets/61112265/adaa468a-ad09-4faf-8bf0-85aa5798fba4">

### Steps to reproduce

lanuch the app
and the Internet is good

### Expected behaviour

i can use proxy to download gptk
my clash is global mode
but whisky can not connect to the internet(clash log do not have anything about whisky)

### Logs

```bash
none
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mabbs** [comment]
I tried v2rayU and this proxy can be used normally, so this program can definitely use proxies, you should check your proxy configuration.

**Comment by IsaacMarovitz** [comment]
We may want to invest in a hosting server that is more easily accessible from China in the future, but for now I'm marking this as resolved.
