### ISSUE TITLE
[Bug]: Mac M1 Pro get errors: Your CPU does not meet the minimum specs for Diablo IV

### ISSUE THREAD

**Issue by zhouweiming** [Whisky-App/Whisky#542]
### Description

I used version 2.1.0 of whisky to install the game today. There was no problem installing the Blizzard client, but when I clicked to install Diablo IV, the following prompt appeared.
<img width="1180" alt="image" src="https://github.com/Whisky-App/Whisky/assets/4847735/91c53dfa-2fdd-4363-9a9b-8d60882e2be6">
<img width="1327" alt="image" src="https://github.com/Whisky-App/Whisky/assets/4847735/8688a058-f39c-4b95-b16f-d9403c18ae44">
### Steps to reproduce

+ install whisky
<img width="857" alt="image" src="https://github.com/Whisky-App/Whisky/assets/4847735/b8d6c4d5-6e53-490f-95a7-fbb8f88bef26">

+ add windows 10 bottle and set version 19042

+ setup Blizzard client and login

+ click install Diablo IV and get the warn note

+ I has tried to click "continue anyway" to install game, but not start success when install complete.

### Expected behaviour

Game can been installed sucessful whithout the error note

### Logs

```bash
1. When I click "Winetricks", get some warn messages in terminal:

➜   PATH="/Users/zhouweiming/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/zhouweiming/Library/Containers/com.isaacmarovitz.Whisky/Bottles/CA52C3D3-FEAD-4FB7-8B2C-15854B2248F3" "/Users/zhouweiming/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" 
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212 - sha256sum: 524c3cd602ef222da3dc644a0a741edd8bca6dfb72ba3c63998a76b82f9e77b2 with wine-7.7 and WINEARCH=win64
Running on OSX, but DISPLAY is not set...probably using Mac Driver.
No arguments given, so tried to start GUI, but neither zenity
nor kdialog were found. Please install one of them if you want
a graphical interface, or run with --help for more options.
```

2. My cpu info:
```
(base) curvature-platform[ruanzhu_momo] % sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Apple M1 Pro
(base) curvature-platform[ruanzhu_momo] % sysctl hw.physicalcpu
hw.physicalcpu: 10
(base) curvature-platform[ruanzhu_momo] % sysctl hw.logicalcpu
hw.logicalcpu: 10
```
```


### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You should be able to just press "Continue Anyway" and bypass this.

**Comment by vegetabo** [comment]
I've encountered the same issue; there's no response after clicking "play."
