### ISSUE TITLE
[Bug]: Honkai Starrail doesn't go beyond launcher

### ISSUE THREAD

**Issue by theqa-ninja** [Whisky-App/Whisky#552]
### Description

Trying to get Honkai Star Rail to run, the launcher will do the download / update, but when I hit `Launch` nothing ever shows up, however it's still in the dock under `win64-preloader`

I already tried uninstalling and reinstalling the GPTK 

### Steps to reproduce

1. download the PC client from https://hsr.hoyoverse.com/en-us/
2. spun up whiskey
3. made a new bottle
4. pointed it to the StarRail_setup_xxxxxx.exe file that I downloaded
5. wait for the update to finish
6. hit "launch"
nothing happens

### Expected behaviour

Expect the game to launch

### Logs

When I launch via launcher.exe
```bash
Whisky Version: 2.1.0
Date: 10/23/2023, 02:34:37
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: hokai
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/moi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/57417440-23DB-494D-9737-D54760858BE5

Arguments: reg query HKCU\Software\Wine\Mac Driver -v RetinaMode 

Launched Wine (14556)
0078:err:module:open_builtin_so_file failed to load .so lib "/Users/moi/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0078:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
reg: Unable to find the specified registry key
Process exited with code 1
```

When I launch StarRail.exe via the `Installed Programs` run
```
Whisky Version: 2.1.0
Date: 10/23/2023, 02:42:30
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: hokai
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/moi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/57417440-23DB-494D-9737-D54760858BE5

Arguments: start /unix /Users/moi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/57417440-23DB-494D-9737-D54760858BE5/drive_c/Program Files/Star Rail/Games/StarRail.exe 

Launched Wine (14936)
wineserver: using server-side synchronization.
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/moi/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
wine: could not open working directory L"unix\\Users\\moi\\Library\\Application Support\\com.isaacmarovitz.Whisky\\Libraries\\Wine\\bin\\", starting in the Windows directory.
Process exited with code 0
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by theqa-ninja** [comment]
forgot to mention, I also tried uninstalling GPTK and installing the new version, no dice :(

**Comment by IsaacMarovitz** [comment]
Star Rail and other Hoyoverse games require anti-cheat bypasses to get in-game. If you want to play the Windows version on Mac, there are better and easier ways to do it.

**Comment by theqa-ninja** [comment]
never knew that, thanks for the info!
