### ISSUE TITLE
[Feature]: Update Diablo IV Wiki Instructions

### ISSUE THREAD

**Issue by arcataroger** [Whisky-App/Whisky#554]
### Is your feature request related to a problem?

#224 and #507 both seem to be related to ESYNC and MSYNC settings in Whisky 2.1.0. They can be fixed with the workaround described in https://github.com/Whisky-App/Whisky/issues/507#issuecomment-1761201492 (basically, disabling MSYNC and manually reenabling ESYNC using `WINEESYNC`=1 in the env vars for `Diablo IV.exe`).

Can we update the wiki to say this? Sorry, Github wouldn't let me edit the Wiki or PR against it.

(Edit: Previously, this issue erroneously mentioned #536 as related. After investigation, these instructions do NOT apply to the Steam version. 536 will need separate fixes.)

### Describe the solution you'd like

Update the [Game Support wiki Diablo IV section ](https://github.com/Whisky-App/Whisky/wiki/Game-Support#diablo-iv) with clearer instructions (below). 

### Diablo IV - Battle.net Only (does not work for Steam version)

Updated Oct 23, 2023.
Tested on Whisky version 2.1.0, macOS Sonoma 14.0

This is for the Battle.net version only. The Steam version of Diablo IV currently will not work with these instructions.

1. Create a new Windows 10 bottle
2. Go to Bottle Configuration
4. Change Build Version by manually typing in `19042`. **Make sure to press enter to submit the change.**
5. Disable MSync.
6. Download and install Battle.net
   - Download the [Battle.net client for Windows](https://download.battle.net/en-us/?platform=windows) (in macOS) and save it somewhere in your macOS file system, like ~/Downloads
   - Back in your Whisky bottle, click the "Open C: Drive" button. This will open the virtual filesystem for your bottle
   - Drag and drop the Battle.net installer from your macOS download location into the C: drive and run it to install Battle.net in your bottle.
9. Once Battle.net is installed, run it. On the login screen, press the cog icon in the top right. Click on Advanced, and **disable** `Use browser hardware acceleration`.
   - If you forget to do this and accidentally log in, Battle.net will show up as a black screen. You can change this setting by right-clicking the Battle.net icon in your macOS notifications area (upper right part of your screen, near the clock) and going to settings there. 
![image](https://github.com/Whisky-App/Whisky/assets/11964962/a1c5dce3-df38-4737-a7a6-d1d6dd27d5c0)

10. Install Diablo IV
11. Try launching Diablo IV by clicking `Play` in Battle.net It will mostly likely fail after pretending to update for a few seconds. **This is OK and expected.** We will fix it.
13. Go back to Whisky. Click on`File` > `Kill All Bottles`
14. Looking at your Diablo 4 bottle again, click on `Installed Programs`. Find `Diablo IV.exe` in the list. Click its cog icon to the right, next to the play button. 
![image](https://github.com/Whisky-App/Whisky/assets/11964962/4aae88cb-e34b-4512-bf48-4dc0ba3d9a66)
16. In the Config screen, add a new Environment Variable with `WINEESYNC` on the left and `1` on the right. Push enter after typing 1 to make sure it saves.
![image](https://github.com/Whisky-App/Whisky/assets/11964962/552a43b5-39f7-4a2d-8a30-7b9f6fde6d0b). 
17. Now you can hit `Run`. Battle.net should re-open, you can click `Play`, and hopefully Diablo IV will run.

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mhmnz** [comment]
ty bro, but I play diablo4 at steam. I use whisky 1.1.1 2.0.0 2.1 2.0.2 but it do not work ,can you fix diablo4 at steam? ty again

**Comment by arcataroger** [comment]
> ty bro, but I play diablo4 at steam. I use whisky 1.1.1 2.0.0 2.1 2.0.2 but it do not work ,can you fix diablo4 at steam? ty again

Sorry @Mhmnz, I don't have the Steam version so I can't help you figure this out :( I am not the developer of this app either.

Maybe you can find the Diablo IV executable in your Steam folder and try to apply the same workaround and see if that works. If that doesn't, sorry, I don't know what to do.

**Comment by arog00** [comment]
These steps do not resolve the issue of running Diablo 4 through steam- even with all of the settings it gives the error "cedar must be running to play this game"

**Comment by arcataroger** [comment]
> These steps do not resolve the issue of running Diablo 4 through steam- even with all of the settings it gives the error "cedar must be running to play this game"

Thanks for the confirmation. If the app owner updates the instructions, I hope they make it clear it's for the Battle.net version only.

Sorry, I'd experiment more if I had a Steam copy too, but I don't want to buy the game again...

**Comment by ThibautHerent** [comment]
This steps are still needed for Bnet version on v2.1.1

**Comment by IsaacMarovitz** [comment]
@arcataroger Thank you for collating these instructions. I think I'd rather fix the problem causing MSync to have issues with Diablo IV or introduce a toggle to switch between MSync and ESync in Whisky. These instructions are pretty technical for the average user to follow.

**Comment by arcataroger** [comment]
> @arcataroger Thank you for collating these instructions. I think I'd rather fix the problem causing MSync to have issues with Diablo IV or introduce a toggle to switch between MSync and ESync in Whisky. These instructions are pretty technical for the average user to follow.

Sure, if that's possible, even better!

**Comment by dclive** [comment]
Still dead in the water here. 

BN D4.  Whisky 2.11.  

Config: 
![image](https://github.com/Whisky-App/Whisky/assets/4536776/f5cc73c5-e87f-4864-ba72-1e77d617647e)

App config: 
![image](https://github.com/Whisky-App/Whisky/assets/4536776/73aa8f3c-e257-4b1e-aeac-62474fba88ec)

In the .plist: 
![image](https://github.com/Whisky-App/Whisky/assets/4536776/3c7a0b9d-3a53-4be6-9168-b8182fd62216)


I just get endless updates presented in BN for D4.  D4 never loads.

**Comment by arcataroger** [comment]
> I just get endless updates presented in BN for D4. D4 never loads.

Have you tried killing all the bottles and then launching the `Diablo IV.exe` directly (instead of the BN launcher?

**Comment by dclive** [comment]
![image](https://github.com/Whisky-App/Whisky/assets/4536776/effe0b0a-8fda-4b18-be57-43fcad02378a)

That is what I am doing.  BN still loads every time, tries to update, then is back to the rum prompt.

**Comment by arcataroger** [comment]
> ![image](https://user-images.githubusercontent.com/4536776/279525872-effe0b0a-8fda-4b18-be57-43fcad02378a.png)
> 
> That is what I am doing. BN still loads every time, tries to update, then is back to the rum prompt.

Sorry, I am not sure what causes that :(

I think it happened to me early on too and I had to destroy the bottle and reinstall everything from scratch. It's just a pain all around :(

I don't think I'll try to use GPT/Whisky again after this. It's been such a nightmare... hopefully the game just comes out on Geforce Now at some point.

**Comment by budachst** [comment]
Well…I just installed Diabolo IV yesterday - hadn't played it since the original Dabolo. And yes, the instructions are somewhat involved, but in the end, I was able to run Diabolo IV smoothly on my MBP M1max - such a great game!

**Comment by dclive** [comment]
Moving to 2.13 and then flipping the toggle from msync to esync fixed my Diablo issues from 2.11; I made no other changes - D4 (BN) immediately opened and ran. Thank you!

**Comment by gaffer43** [comment]
Did I miss something? In Whisky, The only programs that appear under installed programs are: iexplore, wordpad, wmplayer. Do I have to install D4 on the local drive?

**Comment by arcataroger** [comment]
> Did I miss something? In Whisky, The only programs that appear under installed programs are: iexplore, wordpad, wmplayer. Do I have to install D4 on the local drive?

Yes, you have to install the Windows version of Battle.net inside the bottle, then use that to install D4 on the same virtual drive. (See Steps 7-8 in the instructions at the top)

Once you install it and try to run D4 for the first time, you should see it in the installs programs list in subsequent runs. Or you can also manually navigate to it. It's installed somewhere like `/Users/YOUR_USER/Library/Containers/com.isaacmarovitz.Whisky/Bottles/BOTTLE_ID/drive_c/Program Files (x86)/Diablo IV/Diablo IV Launcher.exe`

**Comment by gaffer43** [comment]
> > Did I miss something? In Whisky, The only programs that appear under installed programs are: iexplore, wordpad, wmplayer. Do I have to install D4 on the local drive?
> 
> Yes, you have to install the Windows version of Battle.net inside the bottle, then use that to install D4 on the same virtual drive. (See Steps 7-8 in the instructions at the top)
> 
> Once you install it and try to run D4 for the first time, you should see it in the installed programs list in subsequent runs. If you don't, you can also try to manually navigate to it. It's installed somewhere like `/Users/YOUR_USER/Library/Containers/com.isaacmarovitz.Whisky/Bottles/BOTTLE_ID/drive_c/Program Files (x86)/Diablo IV/Diablo IV Launcher.exe`
> 
> But you can also try what @dclive suggested and just change the bottle settings to ESYNC, without setting it individually for the D4 exectuable.

I had already downloaded D4 on previous attempts. This time, I created the bottle on my removable drive, copied the downloaded D4 folder INTO Program Files, then the D4 exe file appeared in the Whisky list. From there, it was easy to follow the directions and run the game. Thanks for all the help!

**Comment by capJavert** [comment]
I still get update loop when clicking play on `2.1.3`, I set Esync and everything else mentioned but with no success, using `2.0.1` still to make it work.

**Comment by mpede** [comment]
Hola, just sharing feedback that I used the instructions in the Wiki for installing BN, running it and installing D4 worked well & out of the box (disable hardware acceleration was necessary tho) but D4 will not start at first :-( then I found this issue, changed MSync to ESync, added WINEESYNC=1 as described here and it works. Not too good performance on a fully specced M2 Air with default resolution, graphic settings on Low, but good enough for inventory management (I must try lower res, maybe better then). Thanks for the help!

Whisky 2.2.1 (34)
D4 1.2.2.47240 (18066505-18066504)

**Comment by arcataroger** [comment]
FYI, if anyone's still interested in trying to play this on a Mac, Diablo IV is FINALLY available on GeForce Now (both via Steam and Battle.net): https://blogs.nvidia.com/blog/geforce-now-thursday-battlenet-march-games-list/

Playing on an ultrawide 3440x1440, I get a solid ~120 FPS with graphics on Ultra and DLSS on. It is a much, much better experience than trying to run it on the Mac itself. Everything looks and runs beautifully.
