### ISSUE TITLE
[Bug]: Cannot install dotnot 48 using winetricks

### ISSUE THREAD

**Issue by Junyi-99** [Whisky-App/Whisky#558]
### Description

cannot install `dotnet48` using `winetricks`

### Steps to reproduce

<img width="683" alt="image" src="https://github.com/Whisky-App/Whisky/assets/14367694/f897d35c-645f-4126-a867-bfdbad192aa5">

Press "Run"

### Expected behaviour

Expecting a successful installation.

### Logs

```bash
Last login: Thu Oct 26 00:18:23 on ttys002
PATH="/Users/junyi/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/junyi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/9D98FCBF-55DC-4455-960F-364381A0E61D" "/Users/junyi/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" dotnet48
(base) ➜  ~ PATH="/Users/junyi/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/junyi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/9D98FCBF-55DC-4455-960F-364381A0E61D" "/Users/junyi/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" dotnet48
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: .
..
.DS_Store
Program Files
Program Files (x86)
ProgramData
users
windows

Registry info:
/Users/junyi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/9D98FCBF-55DC-4455-960F-364381A0E61D/system.reg:#arch=win64
/Users/junyi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/9D98FCBF-55DC-4455-960F-364381A0E61D/user.reg:#arch=win64
/Users/junyi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/9D98FCBF-55DC-4455-960F-364381A0E61D/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine64 cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
(base) ➜  ~ 
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Junyi-99** [comment]
I think I found the bug. It's a bug inside the `winetricks`

After modifying the script, I can now install `dotnet48`

**Comment by Junyi-99** [comment]
Weird, I set the environment variable by adding `export` to `.zshrc`, shut down all the terminals, and then fixed the problem?

I don't know if this is the right solution or not, but it seems to have helped me out!

**Comment by Junyi-99** [comment]
No, my solution is not right.

The correct way is to `Kill All Bottles` first, then installing `dotnet48` through `winetricks`

**Comment by eyabs** [comment]
I had a similar issue installing dotnet48, but the error was regarding openssl. Incase anyone lands here from google, I was able to resolve it by reinstalling wget with brew.

**Comment by Junyi-99** [comment]
> I had a similar issue installing dotnet48, but the error was regarding openssl. Incase anyone lands here from google, I was able to resolve it by reinstalling wget with brew.

Thanks for the solution, but I think this issue should be cloused

**Comment by davisoares454** [comment]
> No, my solution is not right.
> 
> The correct way is to `Kill All Bottles` first, then installing `dotnet48` through `winetricks`

For those who don't know (like I did), to kill all bottles you should execute your **wineserver** binary, this is how I used:

```
$HOME/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wineserver -k
```

This is where my wineserver was located, usually it is on the same directory as wine64.

After killing the bottles, you can open Whisky again and just execute the Winetricks (don't open any program from the bottle yet).
