### ISSUE TITLE
[Bug]: PUBG - Failed to initialize BattleEye Service: Driver Load Error (6) 

### ISSUE THREAD

**Issue by canberkkurtulmus** [Whisky-App/Whisky#559]
### Description

I wanted to play PUBG but when I started the game this issue came. 
<img width="485" alt="Screenshot 2023-10-25 at 22 32 23" src="https://github.com/Whisky-App/Whisky/assets/76259559/82c6d6c7-b0ba-48b8-9fe1-f448d270d861">

### Steps to reproduce

Just downloaded the game from Steam and that's it, clicked the start game button inside Steam.

### Expected behaviour

Should open the game.

### Logs

```bash
Whisky Version: 2.1.0
Date: 10/25/2023, 22:42:11
macOS Version: Version 14.0 (Build 23A344)
Bottle Name: Bottle
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/canberkkurtulmus/Library/Containers/com.isaacmarovitz.Whisky/Bottles/31CF7020-1B54-46F3-8EE1-D076F828F0A7

Arguments: start /unix /Users/canberkkurtulmus/Library/Containers/com.isaacmarovitz.Whisky/Bottles/31CF7020-1B54-46F3-8EE1-D076F828F0A7/drive_c/Program Files (x86)/Steam/steamapps/common/PUBG/TslGame/Binaries/Win64/ExecPubg.exe 

Launched Wine (12590)
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Kernel level drivers like BattleEye do not work under Wine.
