### ISSUE TITLE
[Bug]: Antivirus shows whisky as worm virus

### ISSUE THREAD

**Issue by Dnblgn07** [Whisky-App/Whisky#565]
### Description

needs an update about it especially avast sees it as virus

### Steps to reproduce

go to avast or other antivirus make detailed scan it sees a lot of virus

### Expected behaviour

Not sees as virus

### Logs

```bash
dont have
```

### What version of Whisky are you using?

2.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by GabCoolDude** [comment]
Uninstall your shitty antivirus

**Comment by GabCoolDude** [comment]
Okay I'm gonna break this down point by point.

One, to address the original concern, no, these DLLs are not malware. All the DLLs that come with Wine are open-source implementations, and it is incredibly easy to find this information.

Here are the DLLs in question [msxml4.dll](https://gitlab.winehq.org/wine/wine/-/tree/master/dlls/msxml4?ref_type=heads), and [msxml6.dll](https://gitlab.winehq.org/wine/wine/-/tree/master/dlls/msxml6?ref_type=heads).

Browse the source code to your heart's content.

Secondly, these antiviruses often work by simply browsing for suspicious file names. The contents of the DLL have not been checked, and this check is incredibly superficial, easy to bypass, and basically useless from a security standpoint. Not to mention that without Wine, it would be impossible to execute a DLL on macOS, so I'm not sure why the macOS version of this software is even flagging this on a completely incompatible system.

Lastly, the utility of an antivirus in the first place on macOS. Unless you are downloading extremely dodgy third-party applications or running programs with unchecked permissions, there is very little that a malicious program can accomplish on a Mac. Without the user manually downgrading the system security either by disabling SIP, AMFI, or running programs with sudo, yada yada, it's practically impossible for a program to do any sot of real damage.

Using an antivirus on Mac is, in my opinion, unnecessary and only serves to slow your computer down and scare you with false positives like the one shown here.

**Comment by GabCoolDude** [comment]
And if you aren’t convinced yet, here is a more technical explanation:

Mac antivirus programs typically falls into two types: Unnecessary and Adware.
Amazingly, Avast managed to kill two birds with one stone and did both!

The “malware” it detects (WormX-gen) is a generic detection, hence the “gen” in the name. Now, I’m not going to talk about why a Win32 virus even matter on a Mac system, but, ignoring that, it manages to detect what is basically a re-implementation of a library as a virus, suggesting that this thing isn’t even smart enough to do heuristic and see just what kind of dll it is.

And let’s not talk about Avast’s free stuff being a walking billboard for their other products nowadays.

The Mac itself already denies apps that are known to be malicious through Gatekeeper, and system modifications are impossible unless both SIP and AMFI are turned off

TL,DR: You don’t need it, and freaking out over this is stilly
