### ISSUE TITLE
[Bug]: Unable to run Cities: Skylines II

### ISSUE THREAD

**Issue by Junyi-99** [Whisky-App/Whisky#573]
### Description

This issue is used to solve any problems related to `Cities: Skylines II`

So far, we haven't managed to get the game running.

### Here are some useful discussions in case of you met some errors during installation.

- [x] Install Steam
- [x] Install Paradox Launcher
    [Failed to install `Paradox Launcher` ?](https://github.com/orgs/Whisky-App/discussions/556)
    [Cannot install `dotnet48` ?](https://github.com/Whisky-App/Whisky/issues/558#issuecomment-1780344013)
    Errors regarding `openssl` ? [#558](https://github.com/Whisky-App/Whisky/issues/558#issuecomment-1783242032) [#562](https://github.com/orgs/Whisky-App/discussions/562)
- [ ] Running Game (failed because `Unity Crash`)
    [#556 (something was related to volumetrics?)](https://github.com/orgs/Whisky-App/discussions/556#discussioncomment-7392766)
    > Under CrossOver 23.6, the game still isn't playable
    [#560 (cohtml_unity3dplugin)](https://github.com/orgs/Whisky-App/discussions/560)

    [#561 (page fault on read access)](https://github.com/Whisky-App/Whisky/issues/561)

### What version of Whisky are you using?

2.1.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

### Last Update of this issue:

03 Nov, 2023

**Comment by lightblair** [comment]
enabling dxvk lets me get to the loading screen - but no further

**Comment by IsaacMarovitz** [comment]
The game currently isn't playable in Whisky or CrossOver 23.6. CrossOver doesn't experience a Unity crash, but it seems to have issues with C:S 2's networking (it uses raw sockets which require "admin" level permissions).

**Comment by chrisvander** [comment]
Raw sockets? Interesting. How are the permission requirements enforced? Is there a way to introduce a "sudo" or is it something that Wine doesn't support

**Comment by chrisvander** [comment]
> The only way to play this on-device for now is in Parallels, but the FPS is too low to be considered "playable".

Yeah, definitely want to get it as close to the metal as possible. Heavy game.

**Comment by IsaacMarovitz** [comment]
> Raw sockets? Interesting. How are the permission requirements enforced? Is there a way to introduce a "sudo" or is it something that Wine doesn't support

It's a consequence of how Wine translates C:S 2's networking; it becomes a socket of type `SOCK_RAW` which requires elevated privileges on POSIX systems. There's some discussion of this problem in a [Linux environment](https://forum.winehq.org/viewtopic.php?t=30704) although I'm not sure how it translates in terms of macOS in Whisky or CrossOver.

On Windows and Parallels, I believe this manifests as a dialogue of this style:
![image](https://github.com/Whisky-App/Whisky/assets/42140194/7c897f70-2e01-4fb7-9bfc-1724863a3c91)
