### ISSUE TITLE
[Bug]: steam constantly opens despite I close it

### ISSUE THREAD

**Issue by Dnblgn07** [Whisky-App/Whisky#587]
### Description

Once I start steam on whisky and close again it reopens it 

### Steps to reproduce

Open steam close it I dont know what to write

### Expected behaviour

To not open again

### Logs

```bash
Dont have it
```

### What version of Whisky are you using?

2.1.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You can force Wind processes to close with Shift + CMD + K in Whisky.

**Comment by Dnblgn07** [comment]
> You can force Wine processes to close with Shift + CMD + K in Whisky.

Thank you
