### ISSUE TITLE
Games don’t start

### ISSUE THREAD

**Issue by kesa11** [Whisky-App/Whisky#596]
The problem with the Honkai Star Rail game. The game is installed, but I can't start it. The menu starts, I click on the start game button and nothing happens. I don't understand what needs to be done. And there is also a problem, I can't install another Genshin Impact game. I made a new bottle, the installer starts to run. And then it shows that "there is not enough disk space". How to increase the disk space?

**Comment by cuba** [comment]
There is no special disk space allocation for wine, you just need to free some space on your macOS disk.
System Settings -> General -> Storage

**Comment by carlosjunod** [comment]
same problem here!
I do have 208 GB space free on my HD but steams says no enough space:

any ideas?

![space](https://github.com/Whisky-App/Whisky/assets/7373811/f5814bc4-017c-475e-9444-d217ace5d8e5)
![steam](https://github.com/Whisky-App/Whisky/assets/7373811/5048cc2e-6939-49eb-82e3-a9d4be653910)

**Comment by wangxy98c** [comment]
yes,I have the same issue as well. I want to know how to change the properties setting.

**Comment by mkhotib20** [comment]
i have same issue, do you guys found any solution ??
