### ISSUE TITLE
[Feature]: Optimized game profiles?

### ISSUE THREAD

**Issue by arcataroger** [Whisky-App/Whisky#599]
### Is your feature request related to a problem?

Currently, it's quite a hassle to get any game up and running, requiring a search through the community wiki, open Github issues, reddit and other forums, etc. And it's still a largely hit-or-miss process that makes it significantly difficult to play.

There is a large learning curve and a lot of conflicting third-party information.

### Describe the solution you'd like

Would it be possible to create a crowdsourced database of game profiles (similar to Steam Controller settings), with bottles/executables preset to settings recommended by the community (maybe by a vote system, or a simple # of downloads)?

When you create a new bottle, for example, instead of just having the Windows version, you could choose from a drop-down of pre-optimized games. That would set all the bottle, wine, registry, etc. settings for you, and pin any relevant executables (and their arguments/env vars) too.

In this way, we'd slowly start to grow a collection of "known to work" games with their proper configs out-of-the-box.

### Anything else?

Crossover and Wine have similar compatibility lists:

https://www.codeweavers.com/compatibility

https://appdb.winehq.org/

But having a GUI like this is a great opportunity to implement those lists & setup instructions directly into the installation flow, for a simpler UX and easier gaming.

### Issue Language

- [X] Yes my issue is written in English

**Comment by c01nd01r** [comment]
In the world of Wine Linux, there is https://lutris.net/. With this program, you can run scripts for installation and configuration.
For example, script for install Cyberpunk 2077: https://lutris.net/games/install/24989/view

**Comment by IsaacMarovitz** [comment]
This is specifically not planned due to maintainability issues and in order to not undercut CrossOver. If that's the experience you're looking for, use CrossOver.
