### ISSUE TITLE
[Bug]: Unable to use DXVK when game is launched with Steam, how to turn off D3DMetal

### ISSUE THREAD

**Issue by thenamangoyal** [Whisky-App/Whisky#600]
### Description

On MacOS Sonoma, DXVK is not working when game is launched with Steam since it uses D3DMetal from GPTK.

Also Whisky DXVK performance is slower than Crossover DXVK.

E.g. missing menu items is due to not using DXVK.

<img width="1512" alt="Screenshot 2023-11-04 at 11 47 35 AM" src="https://github.com/Whisky-App/Whisky/assets/22537996/9adc23b9-f2ab-4fe3-82ef-5adacb61e00f">

### Steps to reproduce

Install a Age of Empires II: De from Steam. Even with DXVK turned on from Bottle Configuration, the game doesn't use DXVK.

https://github.com/Whisky-App/Whisky/issues/469#issuecomment-1751156690

The game can't be directly launched externally alone from Whisky as it needs to be launched from Steam. Though its possible to open steam, then launch the game externally but thats too slow of a process and it leads to much worse performance compared to Crossover in the same settings. 

Also the DXVK Hud doesn't appear as pointed in previous issue.

Additionally if we remove the `WINEDLLOVERRIDES="dxgi,d3d9,d3d10core,d3d11=b"` parameters from the steam config, the game launches fine with DXVK. But then steam is a blank window.

<img width="333" alt="Screenshot 2023-11-04 at 12 31 20 PM" src="https://github.com/Whisky-App/Whisky/assets/22537996/ad7398eb-dfcb-422e-8976-0c3c0713f90f">

### Performance Difference
When using DXVK - launching Steam and then game using Steam. It seems it defaults to D3DMetal (in Metal HUD it shows D3D11).
<img width="1512" alt="Whisky DXVK using Steam" src="https://github.com/Whisky-App/Whisky/assets/22537996/54f07111-0098-4c3d-bfff-2c58961e6ad5">

When using DXVK - launching Steam and then the game externally. DXVK HUD now appears but performance is too low. 
<img width="1512" alt="Whisky DXVK" src="https://github.com/Whisky-App/Whisky/assets/22537996/04f902dc-0987-4479-91d0-86d9bf462e55">

Crossover with DXVK - notice the DXVK HUD, performance is much better than Whisky DXVK
<img width="1512" alt="Crossover DXVK" src="https://github.com/Whisky-App/Whisky/assets/22537996/cb2cf885-af7a-45bf-af78-81c5c02f040e">

### Expected behaviour

Crossover is able to handle this which has a cxbottle.conf which sets "WINED3DMETAL" = "0" which turns of D3DMetal.

There should be option to switch between DXVK and D3DMetal or use steam in DXVK without those parameters.

### Logs

```bash
-
```

### What version of Whisky are you using?

2.1.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lolo782374** [comment]
Were you able to find a solution? I am having a similar issue when trying to run GTA5 with DXVK, I can see it is running in d3dmetal from the metal HUD. DXVK works fine with crossover but whiskey still runs in d3dmetal. I have found that running games directly and not through steam works but is not much help with gta.

**Comment by sheutran** [comment]
Hello,
I am facing an issue when trying to run Fallout 76 with the same config. Game launches and immediately crashes. Winedbg report log indicates similar things than what you describe. I cannot try to run the game separately either :/
I tried removing envirronment variable WINEDLLOVERRIDES to try DXVK but then, steam never launches.
I am a bit confused regarding where to find hints right now

Whisky Version 2.2.3 (36)
Winedbg: System information:
    Wine build: wine-7.7
    Platform: x86_64
    Version: Windows 8.1
    Host system: Darwin
    Host version: 23.2.0

**Comment by AndreyDero** [comment]
> Hello, I am facing an issue when trying to run Fallout 76 with the same config. Game launches and immediately crashes. Winedbg report log indicates similar things than what you describe. I cannot try to run the game separately either :/ I tried removing envirronment variable WINEDLLOVERRIDES to try DXVK but then, steam never launches. I am a bit confused regarding where to find hints right now
> 
> Whisky Version 2.2.3 (36) Winedbg: System information: Wine build: wine-7.7 Platform: x86_64 Version: Windows 10* Host system: Darwin Host version: 23.2.0
> 
> *: I tried Windows 10, 8.1, 7

1. Install the interface language ENG on your macbook
2. install Steam (it doesn’t matter what language you use during installation)
3. In Whiskey Bottel itself (steam.exe) - force it to start with ENG

<img width="895" alt="image" src="https://github.com/Whisky-App/Whisky/assets/48225002/3d56a22f-a19c-4ff2-b95e-8ffe08336a74">

Now everything is ready - you can launch it and your Steam will open.
P.S. Opening time is about 20 seconds - sometimes 30 seconds

<img width="1292" alt="image" src="https://github.com/Whisky-App/Whisky/assets/48225002/994337b4-23b7-4bec-a1a9-de93379c762d">

**Comment by thenamangoyal** [comment]
> Install the interface language ENG on your macbook

@AndreyDero What is interface language pack?

**Comment by thenamangoyal** [comment]
This seems to be solved in the v2.3.2 when using WhiskyWine and making a new bottle with DXVK turned on.
<img width="1296" alt="Screenshot 2024-04-14 at 5 33 19 AM" src="https://github.com/Whisky-App/Whisky/assets/22537996/aa47fe44-1f06-40f7-bc0a-ff3f2f02e93d">
