### ISSUE TITLE
Impossible to pass Skyrim SE installation

### ISSUE THREAD

**Issue by tozzig** [Whisky-App/Whisky#603]
Hello there!
I am trying to run Steam version of Skyrim on my Mac (M2 Pro, MacOS 14.1)
I am trying to follow this guide: 
https://github.com/Whisky-App/Whisky/wiki/Game-Support#skyrim-se

During the step with Winetricks command I see the following logs and nothing gets installed. 

```
PATH="/Users/tozzig1408/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/tozzig1408/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C1BCF224-828B-4695-BA92-ACBF8E175268" "/Users/tozzig1408/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" dotnet48 vcrun2019 dxvk1103 d3dx11_43 d3dcompiler_43 d3dcompiler_47 faudio
tozzig1408@MacBook-Pro-Anton ~ % PATH="/Users/tozzig1408/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/tozzig1408/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C1BCF224-828B-4695-BA92-ACBF8E175268" "/Users/tozzig1408/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" dotnet48 vcrun2019 dxvk1103 d3dx11_43 d3dcompiler_43 d3dcompiler_47 faudio
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: .
..
Program Files
Program Files (x86)
ProgramData
users
windows

Registry info:
/Users/tozzig1408/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C1BCF224-828B-4695-BA92-ACBF8E175268/system.reg:#arch=win64
/Users/tozzig1408/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C1BCF224-828B-4695-BA92-ACBF8E175268/user.reg:#arch=win64
/Users/tozzig1408/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C1BCF224-828B-4695-BA92-ACBF8E175268/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine64 cmd.exe /c echo '%AppData%' returned empty string, error message "" 
```

**Comment by shdwlkr** [comment]
hey there!
same problem here:

`PATH="/Users/shdwlkr/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/shdwlkr/Library/Containers/com.isaacmarovitz.Whisky/Bottles/99B834BE-148A-48B1-97E4-FA018B56B291" "/Users/shdwlkr/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" dotnet48 vcrun2019 dxvk1103 d3dx11_43 d3dcompiler_43 d3dcompiler_47 faudio
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: .
..
.DS_Store
Games
Program Files
Program Files (x86)
ProgramData
users
windows

Registry info:
/Users/shdwlkr/Library/Containers/com.isaacmarovitz.Whisky/Bottles/99B834BE-148A-48B1-97E4-FA018B56B291/system.reg:#arch=win64
/Users/shdwlkr/Library/Containers/com.isaacmarovitz.Whisky/Bottles/99B834BE-148A-48B1-97E4-FA018B56B291/user.reg:#arch=win64
/Users/shdwlkr/Library/Containers/com.isaacmarovitz.Whisky/Bottles/99B834BE-148A-48B1-97E4-FA018B56B291/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine64 cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
`

**Comment by Notacod3r** [comment]
> hey there! had the same problem, File > Kill All Bottles helped solve it

Did this work? I have the same problem. How exactly do I go about this? While the console message appears, I kill the bottle? Won't that cancel the installation?
