### ISSUE TITLE
Arkham Origins Does Not Start - Failed to Create Crash Dump Error 87

### ISSUE THREAD

**Issue by AP4536** [Whisky-App/Whisky#612]
Hi y'all, I am encountering an error that I am hoping I could get some help with. So I am running the latest version of Whisky on a Macbook Pro 2022, with an M2, running Sonoma 14.1. I am attempting to play Batman Arkham Origins through steam. I installed the game with no problem, but when I go to run it, a error appears stating "Failed to Create Crash Dump Error 87", which causes the game to stop running immediately. How can I solve this? I am truly grateful for any and all help!

On a side note, Whisky as an app adds functionality that I never thought possible for Macbooks, so hats off to the team who created this and continues to update it, this is incredible work!

**Comment by meta-ryan** [comment]
find a solution?
