### ISSUE TITLE
[Bug]: Insane amount of memory usage

### ISSUE THREAD

**Issue by EmilianoTalamo** [Whisky-App/Whisky#623]
### Description

My Whisky instance appears to be memory leaking randomly. The OS will show a popup asking to force quit applications because Whisky is asking the system an absurd amount of memory (~100gb).

<img width="665" alt="image" src="https://github.com/Whisky-App/Whisky/assets/12476222/86b38557-2965-4457-bc2a-e23d38ca6886">

<img width="539" alt="image" src="https://github.com/Whisky-App/Whisky/assets/12476222/28236883-35bd-4808-b084-e6fb11638577">

Process-wise, Whisky is idling in the background, and I have only one bottle instance that's running the Steam client.

<img width="1012" alt="image" src="https://github.com/Whisky-App/Whisky/assets/12476222/d1d4aae9-4a8f-4624-9f84-b86b98b92f44">

### Steps to reproduce

Not sure what's precisely causing these memory leaks, but for me it's just a matter of:

* Open Whisky
* Wait

### Expected behaviour

~100mb of memory usage, as it appears to be using on startup.

### Logs

```bash
None. Can I get logs or debugging information about this somehow?
```

### What version of Whisky are you using?

2.1.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by xzzngdsr** [comment]
but 
![Uploading image.png…]()

**Comment by IsaacMarovitz** [comment]
I've not heard of this issue occurring past Release 2.1.1. Do you have Xcode? If you can reproduce this issue could you check it with instruments?

**Comment by bolandnick18** [comment]
I am noticed this as well

**Comment by Cappy** [comment]
Got the same issue on my MacBook Pro M1 Pro.
Whisky 2.1.2 (31)
![telegram-cloud-photo-size-2-5400239145391084193-y](https://github.com/Whisky-App/Whisky/assets/1041113/585d72d1-fbaa-453a-87bd-0e34a3b3ef0c)

**Comment by IsaacMarovitz** [comment]
Reporting that you're experiencing this issue won't help. Please provide detailed reproduction steps. I have not experienced this issue personally.

**Comment by bejeweledjamie** [comment]
i just had this happen to me as well. 40GB being used, made me force quit whisky. if it happens again ill screenshot. idk how to get logs lol but if someone sends me a link on how to do it, i got you!

**Comment by IsaacMarovitz** [comment]
Resolved in recent commits
