### ISSUE TITLE
[Bug]: New Bottles Aren't Created / Disappear

### ISSUE THREAD

**Issue by edlorenz7** [Whisky-App/Whisky#627]
### Description
Note - I do NOT have a period in my Mac user name.

Fresh install MacOS Sonoma. M3 Mac.  

Installed Whisky 2.1.3 - it downloaded all the prereqs.  

When I click "New bottle" and create it, nothing happens in the GUI.  The bottle file is created behind in the filesystem but is missing.

I can manually import the bottle to force it to show, but then none of the commands work (for example, can't open C: drive, can't run any files)

### Steps to reproduce

1. Install Whisky 2.1.3
2. Create new Win10 bottle

### Expected behaviour

Bottle is shown in the list, and run commands work.

### Logs

```bash
Whisky Version: 2.1.3
Date: 2023-11-19T04:05:23Z
macOS Version: 14.1.1

Bottle Name: newSteam
Bottle URL: /Users/edlorenz/Documents/NewBottles/92ACFA28-B4AF-4308-B80C-D54A0C057743

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: winecfg -v win10
```

### What version of Whisky are you using?

2.1.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by edlorenz7** [comment]
Have tried (unsuccessfully):

- deleting all files and app, redownloading and starting fresh
- enabling full disk access (as suggested in another issue)
- using both default AND custom paths for bottles
- manually importing bottle files into Whisky

nothing works :(

**Comment by vladyer** [comment]
Been running into the same issue, but was able to find a workaround
1. Create a new bottle with Win 8.1 instead of Windows 10
2. Go to bottle configuration and switch to Window 10

The bottle will remain on the list and won't disappear after the restart. Hope it helps until it's fixed

**Comment by edlorenz7** [comment]
Thanks for the reply. No help, sadly. When I create one with Win 8.1, still same behavior. I create it and it disappears.

I did try and import the bottle (which worked) and then switch it back to Win10.  It just hangs at this screen - maybe this is informative.

<img width="660" alt="Screenshot 2023-11-19 at 14 42 54" src="https://github.com/Whisky-App/Whisky/assets/1566507/4c114291-8a04-4e3e-8b89-3fa00e6eb24c">

**Comment by dguenther** [comment]
This may be a separate issue, but I encountered the same problem on a fresh install of Sonoma. For me what fixed it was:

1. Open the `Whisky > Setup... ` menu.
1. "Rosetta" was marked red, despite installing it when opening Whisky for the first time.
1. Open Terminal and run `softwareupdate --install-rosetta --agree-to-license`. It may display "Package Authoring Error", this seems to be fine, but it should display "Install of Rosetta 2 finished successfully".

After closing/reopening Whisky, the next bottle I made worked properly.

**Comment by edlorenz7** [comment]
THAT WAS IT!! Thank you very much. I suppose the bug is Whisky not recognizing or reporting that Rosetta either wasn't installed or didn't install properly. 

Closing issue and will open a new one that focuses on the rosetta install issue

**Comment by Roboralted** [comment]
Can you elaborate on these instructions, having the same problem with whisky
