### ISSUE TITLE
[Bug]:  Failed to create bottle: progress disappeared

### ISSUE THREAD

**Issue by x1a00** [Whisky-App/Whisky#633]
### Description

please see the log. Every progress disappeared after a few seconds with no warning at all

### Steps to reproduce

just clean installed whisky app and created the first bottle

### Expected behaviour

bottle created 

### Logs

```bash
Launched Wine (12379)
msync: bootstrapped mach port on wine-c81a10-msync.
msync: up and running.
wine: could not load kernel32.dll, status c0000135
wine: could not open working directory L"Z:\\Users\\l.x\\Library\\Application Support\\com.isaacmarovitz.Whisky\\Libraries\\Wine\\bin\\", starting in the Windows directory.
wine: could not load kernel32.dll, status c0000135
Process exited with code 53
```

### What version of Whisky are you using?

2.1.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Likely resolved in newer versions
