### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IlYAN-FISHERMAN** [Whisky-App/Whisky#635]
### Description

Hello guys, i have a problem when i want Install a game on steam with wisky, When I start the download, the download starts, it crashes after a few minutes (the download rate drops to 0 and stays like that)

### Steps to reproduce

- install steam windows with whisky
- start to install a game

### Expected behaviour

install the game

### Logs

```bash
.
```

### What version of Whisky are you using?

2.1.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by AP4536** [comment]
Hey,

I run into this issue frequently, but I have a fix. Close steam and then start it again from Whisky, the download speed will go back up beyond 0

**Comment by justin-himself** [comment]
This is issue did not go away. I'm using 2.2.1 and the download halts after 5-10 minutes and stay that way, until I close and reopen steam.

**Comment by Vermyndax** [comment]
Setting my bottle to ESync seems to make this go away for me as well.

**Comment by GordonBeeming** [comment]
Switching to ESync from MSync seems to (no hangs for a while) have fixed it for me as well 🙂
