### ISSUE TITLE
[Bug]: Staticky sound with Steam games (Half Life, Oblivion, Skyrim)

### ISSUE THREAD

**Issue by Howlinmoon** [Whisky-App/Whisky#637]
### Description

Hi,
I have been attempting to play Half Life via Whisky after getting to successfully download from my Steam account.
The game seems to be running fine - except for one major issue, the sound is staticky / choppy.
This is using a Mac Mini M2 Pro with 32GB of RAM and Whisky version 2.1.3 (brew installed)
I was wondering if anyone had any suggestions on how to fix the static. I see there are various settings in the bottle configuration, but I didn't want to make things worse by mucking with them.

It seems to be with all Steam games - since I also tried installing Oblivion and Skyrim - both which appeared to run fine - except for the staticky audio issue.

I have tried the idea of a Windows 7 based bottle, but that gives me the same results, with the warning that steam support for Windows 7 ends in 40 days - i.e. 1/1/2025 - so that would have only been a very short term solution at best.

thanks for any suggestions on how to address this.

### Steps to reproduce

Fresh install of Whisky via brew on MacOS Sonoma 14.1.1

brew install --cask whisky

Download the windows Steam installer

Creat a Windows 10 Whisky bottle

Click "Run"

Select the windows Steam installer

Once Steam has been installed and is running, select Half Life and download it.

When Half Life is finished downloading - try running it - the sound issue should be heard almost immediately.

### Expected behaviour

Ideally, sound w/out static

### Logs

```bash
If I knew how to get the requested logs, I would/will provide them.
```

### What version of Whisky are you using?

<2.2.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by nicolinuxfr** [comment]
Same issue for me with Half-Life. It's a Whisky 2.2 regression it seems, it was fine with the previous version. I will downgrade the app for now.

**Comment by Howlinmoon** [comment]
> Same issue for me with Half-Life. It's a Whisky 2.2 regression it seems, it was fine with the previous version. I will downgrade the app for now.
> 
> EDIT : unfortunately, the bug seems to remain on 2.1.3… 😢

Sorry you downgraded to 2.1.3 - that was the version I was reporting it on.
I removed the reference to 2.2 if that was confusing.
I was referring to the version selector when posting the bug.
I am glad to see I'm not the only one seeing (hearing actually) this issue.

**Comment by cgarst** [comment]
Might be a duplicate #445 - seems like a broader issue with some older games

**Comment by nicolinuxfr** [comment]
> Sorry you downgraded to 2.1.3 - that was the version I was reporting it on.

No problem, so I tried 2.1.2 and even 2.1.1 and it is not better. I'm not sure if it's Whisky's fault then, since the game has been updated a couple times since I last tried it (monday evening). 

> Might be a duplicate https://github.com/Whisky-App/Whisky/issues/445 - seems like a broader issue with some older games

It was working perfectly fine at the beginning of this week, so I'm not sure.

**Comment by thekamilpro** [comment]
Could this be also related to HOMM3 - the game runs, but sound is clunky? #252

**Comment by sashok1337** [comment]
I ran into the same problem in Worms Armageddon (via Steam)

**Comment by EmilianoTalamo** [comment]
Most sound issues from old games are fixed by installing dsound and flagging it as native.

**Comment by Howlinmoon** [comment]
> Most sound issues from old games are fixed by installing dsound and flagging it as native.

OK - I did some googling and I failed to find anything useful when searching for "macos whisky dsound"
Just what is dsound and where do I get it so I can try your solution?
A google search on "macos dsound" just resulted in this: https://www.soundonsound.com/techniques/d-sound-pro-35-beta and I suspect this is not the dsound you're referring to :-)

**Comment by EmilianoTalamo** [comment]
>  where do I get it so I can try your solution?

It's available on winetricks. Then you override it with Winecfg.

For future reference, you install Windows libraries and dlls within Wine, not through your OS.

**Comment by thekamilpro** [comment]
> > where do I get it so I can try your solution?
> 
> It's available on winetricks. Then you override it with Winecfg.
> 
> For future reference, you install Windows libraries and dlls within Wine, not through your OS.

Thank you it just worked!

**Comment by Howlinmoon** [comment]
> > where do I get it so I can try your solution?
> 
> It's available on winetricks. Then you override it with Winecfg.
> 
> For future reference, you install Windows libraries and dlls within Wine, not through your OS.

Worked perfectly!

**Comment by glenmeredith68** [comment]
Downloaded whiskey today to play half-life too! 

Winetricks tells me 'wine server not found!' when I run the command 'winetricks dsound' in the terminal.  

@Howlinmoon or @thekamilpro can you describe to me how you carried out the line 

"It's available on winetricks. Then you override it with Winecfg.'
?

Seems like I'm missing something here.

**Comment by mrkody** [comment]
File > Kill All Bottles helped solve it

**Comment by sashok1337** [comment]
I finally managed to play Worms Armageddon with normal sound!
Huge thanks to everyone in this thread, but I want to point out that this is very difficult to do without detailed instructions! 
(like @glenmeredith68 mentioned)

So here are the steps you need to take to get it working:
1. In your terminal run `brew install cabextract`
2. Open `Whisky`
3. Run `File > Kill All Bottles` (at the top left of your screen)
4. At the bottom of the Whisky window you will find the `Winetricks...` button, click it
5. Go to DLLs tab, find `dsound`, choose it and press `RUN`
6. Run the game!

**Comment by Notacod3r** [comment]
I still get the staticky sound even with dsound. Someone mentioned to flag it as native and override it with Winecfg, how do I do that?

**Comment by phamthohongduong** [comment]
> > I finally managed to play Worms Armageddon with normal sound! Huge thanks to everyone in this thread, but I want to point out that this is very difficult to do without detailed instructions! (like @glenmeredith68 mentioned)
> > So here are the steps you need to take to get it working:
> > 
> > 1. In your terminal run `brew install cabextract`
> > 2. Open `Whisky`
> > 3. Run `File > Kill All Bottles` (at the top left of your screen)
> > 4. At the bottom of the Whisky window you will find the `Winetricks...` button, click it
> > 5. Go to DLLs tab, find `dsound`, choose it and press `RUN`
> > 6. Run the game!
> 
> в skyrim на заставке звук есть, а в самой игре нет((
> 
> Skyrim has sound on the splash screen, but not in the game itself((

I tried this method in Heroic Launcher, now the game is just stuck at black screen on launch... :(

**Comment by cffranco26** [comment]
> Most sound issues from old games are fixed by installing dsound and flagging it as native.

this solution work for me with NFSMW 2005
<img width="738" alt="Screenshot 2024-07-15 at 12 36 27" src="https://github.com/user-attachments/assets/6799ab59-e67d-4745-b6be-c3c788c2c3cb">

**Comment by LuizSSB** [comment]
For reference (and SEO for those wanting some help), Falcom games also seem to suffer from this sound issue, and the `dsound` winetrick apparently solves it for them.

I've done some _very_ basic testing with the following games, and it worked for all of them:
- Gurumin
- Ys Oath in Felghana
- Ys Ark of Naptishim
- Ys Seven (the opening cutscene has a bullet-being-fired-like sound effect that's too loud and keeps being repeated ad nauseum, but it seems to go away after that)

I imagine it would also work for other games like the Zweis and Xanadus

**Comment by kurkaspars** [comment]
> Most sound issues from old games are fixed by installing dsound and flagging it as native.

Like others have noted, it is not clear what is meant by "flagging it as native", any help would be appreciated.

**Comment by okschlatter** [comment]
> > Most sound issues from old games are fixed by installing dsound and flagging it as native.
> 
> Like others have noted, it is not clear what is meant by "flagging it as native", any help would be appreciated.

Writing a basic guide on how to do this because I wasn't sure what it meant at first either, but I figured it out pretty quickly.

Go to the "Bottle Configuration" screen and then click "Open Wine Configuration" (bottom right corner). Click on the Libraries tab, and in the "New override for library:" menu, select "dsound" then click the "Add" button. Now you can select it in the list under "Existing overrides:" and click the "Edit..." button. Choose either the "Native" or "Native then Builtin" option. Click "OK" then "Apply" to apply the changes. Now close the "Wine configuration" window now and playtest the game you were having audio issues with.

![Image](https://github.com/user-attachments/assets/7780b56c-409e-4234-bb2f-56b0986ef3b0)

**Comment by younesbram** [comment]
dsound fixed the sound for  iji (gamemaker game from 2008)
fixed tf2 sound being distorted
fixed morrowind sound distroted but morrowind still crashes

thanks tho
