### ISSUE TITLE
[Feature]: Setup EXE support.

### ISSUE THREAD

**Issue by JesusLuvsYooh** [Whisky-App/Whisky#650]
### Is your feature request related to a problem?

Setup EXE's do not run, they show the box, then close.  
<img width="296" alt="Screenshot 2023-11-27 at 11 42 16" src="https://github.com/Whisky-App/Whisky/assets/57072365/a11a594c-1627-4d9f-a83c-c7beb525374f">

### Describe the solution you'd like

1: Support for setup exe or
2: Tutorial if command line args, or certain wine tricks are needed.

### Anything else?

That's all, thanks! Great work.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is incredibly nonspecific, the issue here is likely with that specific exe, not with setup exes as a whole.

**Comment by JesusLuvsYooh** [comment]
> This is incredibly nonspecific, the issue here is likely with that specific exe, not with setup exes as a whole.

Are you sure, just tried the xbox pc gamepass installer and that does not work either.
Anything that seems to be an 'installer' does not run, but direct .exe's do.
Am I missing something here?  Any trick or args needed?
