### ISSUE TITLE
Epic games type launcher

### ISSUE THREAD

**Issue by RealMimoi** [Whisky-App/Whisky#653]
### Description

I don't know how to download the Epic Games Launcher for Windows on a mac but I saw that you could just use the Heroic Games Launcher and run it on Whisky. I downloaded the launcher (v2.10.0) for windows and it doesn't work. What do I do?

### Steps to reproduce

download the latest version of the launcher (v2.10.0) for windows and run it on Whisky

Then this should happens:
![Screenshot 2023-11-27 at 6 11 21 PM](https://github.com/Whisky-App/Whisky/assets/152229121/00186340-3e83-4e08-ba99-33e948287e3b)

bottle configs:

![Screenshot 2023-11-27 at 6 19 08 PM](https://github.com/Whisky-App/Whisky/assets/152229121/f0bdeb62-ce91-4809-8ff2-18b55666ee35)

### Expected behaviour

It should be about to open and download/launch games like Fortnite, Rocket League, Fall Guys and more.

### Logs

```bash
idk what to put here...
```

### What version of Whisky are you using?

2.2.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You are meant to use Heroic for macOS, not Heroic for Windows.

**Comment by philippesic** [comment]
What's the process for playing Epic Games through Whiskey? After installing Windows version of game through MacOS Heroic, running the game through Whiskey?
<img width="657" alt="Screenshot 2024-03-14 at 7 42 08 PM" src="https://github.com/Whisky-App/Whisky/assets/116986036/90eb84d3-56f4-4e57-b01c-4fc923bd0604">

Installing online games like Fortnite through Heroic show an anticheat denial error:
<img width="1080" alt="Screenshot 2024-03-14 at 7 42 57 PM" src="https://github.com/Whisky-App/Whisky/assets/116986036/3f2e8140-19af-4eb6-80e3-106f49aaa14b">

**Comment by philippesic** [comment]
After Installing and running FortniteLauncher.exe, there is no launch and no errors. Any fixes?

**Comment by philippesic** [comment]
Attempted running straight through Heroic Wine but its nearly impossible to connect to game servers
