### ISSUE TITLE
[Bug]: Cannot install GPTK

### ISSUE THREAD

**Issue by BokBoy** [Whisky-App/Whisky#654]
### Description

This is just an outline of the issue, I did fix it.
Trying to install Whisky 2.2.0 doesn't let you install GPTK if not already installed.
Downgrading to Whisky 2.1.0 (I heard about the issue on 2.1.3) lets you install, and then you can upgrade to 2.2.0.
One of the issues I'm getting, creating another one after this.

### Steps to reproduce

Download Whisky 2.2.0 (either from homebrew or just from releases) without GPTK installed. When trying to install, it stays at 0mb out of 0mb when trying to install.

### Expected behaviour

Expected to install (like on 2.1.0) and let me work it.

### Logs

```bash
No logs, does not involve WINE but GPTK installer.
```

### What version of Whisky are you using?

2.2.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is a networking issue on your end

**Comment by BokBoy** [comment]
> This is a networking issue on your end

No definitely not, please read. 
I mentioned **downgrading** to 2.1.0 let me install.

**Comment by swartout** [comment]
Getting the same issue, M2, network connection is not the problem.

**Comment by BokBoy** [comment]
#706 and state
No one will listen to this one
