### ISSUE TITLE
Wiki Says Elite Dangerous is NOT working[Bug]: 

### ISSUE THREAD

**Issue by ChinaBackGo** [Whisky-App/Whisky#663]
### Description

Elite Dangerous works in Whisky. The issue appears to be with the launcher hanging on startup or difficult dependencies to get working with winetricks.

However using the https://github.com/rfvgyhn/min-ed-launcher to bypass Frontier's launcher it's possible to get Elite Running.

### Steps to reproduce

Note: tested on M1 Max via Steam
1. install Whisky (I've tested with 2.2.1)
2. Create a win10 bottle
3. Install Steam
4. Install Elite Dangerous via steam
5. Install [min-ed-launcher](https://github.com/rfvgyhn/min-ed-launcher) (note you must have already linked accounts)
6. Follow the Steam min-ed-launcher setup instructions (use /edo for odyssey, /ed4 for horizon)
7. Modify the gamesettings.json in (users/crossover/AppData/Local/min-ed-launcher) add the line:
  "gameStartDelay": 5,
Note: I do not know why the above is needed, perhaps there is a race condition between the launcher and startup process. I found the Launcher would hang but a 5 second delay allows consistent startup.

M1 Max I'm getting 60 fps outside stations, 45 fps inside, high quality settings. I've played around 2 hours, between stations, landing on planets - no issues or crashes.
Gamepad works (disable steam input)
Resolution is low on retina display (I could not get it to work with retina display toggled, it just shows 1/4 of the screen)

<img width="1512" alt="Screenshot 2023-11-30 at 10 34 10 AM" src="https://github.com/Whisky-App/Whisky/assets/7291102/aeec7236-9657-4d52-a3c6-c6f12ef2fe3a">
<img width="1512" alt="Screenshot 2023-11-30 at 10 33 11 AM" src="https://github.com/Whisky-App/Whisky/assets/7291102/880d920e-3907-4b83-891d-30e82fb734dd">

 

### Expected behaviour

You can play Elite!

### Logs

```bash
n/a
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by akxks** [comment]
How do you "LINK" accounts ?

**Comment by akxks** [comment]
Managed to start the game up but how to set the resolution ? I changed the Config but every time it resets to 1512x982

**Comment by ChinaBackGo** [comment]
Hey - I know you got it working, but in case anyone else asks -the account linking is done via frontier or steam. I did it previously with steam so nothing to do if you previously got it working on another platform. I think you'd only have to do this if it's the 1st time launching the game.

Resolution is bugged for me as well, but I haven't spent much time looking into it as the game is pretty playable on laptop screen. 

Retina option in whisky will work, but will zoom on 1/4 of the screen so there's some issue it's not recognizing the display properly. using a 2nd monitor also fails.

I'd guess it's a common issue but haven't had time to check proton/wine forums yet.
