### ISSUE TITLE
[Bug]: Watch Dogs, Watch Dogs 2, Watch Dogs Legion. Installs, will not run

### ISSUE THREAD

**Issue by storlay** [Whisky-App/Whisky#669]
### Description

Steam says that the game is running, but in fact it is not. After 2 hours of waiting, the game still didn't start. No error messages appeared.

### Steps to reproduce

Making a bottle
Installing Steam
Installing the game on Steam

### Expected behaviour

Correct launch of the game

### Logs

```bash
-
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by edgar5055** [comment]
https://github.com/Whisky-App/Whisky/issues/234 

I used the solutions provided in the comments and they worked for me, if you have any problems with ubisoft, please open the link below. I hope it helps)

https://github.com/Whisky-App/Whisky/issues/502

**Comment by storlay** [comment]
`[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (162)                                                               
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (166)                               -- Starting Ubisoft Game Launcher --
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (173)                               Platform: PC.                   
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (181)                               Exe version: 148.2.10984        
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (182)                               Installed version: 10984        
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (183)                               Built: Dec  4 2023.             
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (188)                               OS: Microsoft Windows Server 2008 R2, 64-bit  Service Pack 1 (build 7601)
[ 1600]  2023-12-13 00:13:41      [ 1836]      INFO       HubUtils.cpp (193)                               CPU: VirtualApple @ 2.50GHz     
[ 1600]  2023-12-13 00:13:43      [ 1836]      INFO       HubUtils.cpp (198)                               GPU: NVIDIA GeForce 8800 GTX    
[ 1600]  2023-12-13 00:13:43      [ 1836]      INFO       HubUtils.cpp (203)                               RAM: 8191 MB                    
[ 1600]  2023-12-13 00:13:43      [ 1836]      INFO       HubUtils.cpp (211)                               Timezone: UTC-03:00             
[ 1600]  2023-12-13 00:13:43      [ 1836]      INFO       HubUtils.cpp (230)                               Command line:                   
[ 1600]  2023-12-13 00:13:47      [   32]      INFO       BusSettings.cpp (111)                            Failed to disable start on Windows start.
[ 1600]  2023-12-13 00:13:47      [ 1836]      INFO       Hub.cpp (107)                                    Environment is PROD.            
[ 1600]  2023-12-13 00:13:47      [  188]      INFO       ConnectView.cpp (162)                            Using CEF with native rendering 
[ 1600]  2023-12-13 00:13:53      [  188]      INFO       StartView.cpp (921)                                                              
[ 1600]  2023-12-13 00:13:55      [  180]      INFO       AccountOnlineLogin.cpp (384)                     Login Type: ticket, platform: Uplay.
[ 1600]  2023-12-13 00:13:57      [  180]      INFO       AccountStartupLogin.cpp (293)                    User: bb0ec3e9-2a74-4f2c-b8bc-5fa8de980f97
[ 1600]  2023-12-13 00:13:58      [  188]      ERROR      TaskBarJumpListView.cpp (168)                    Jump list: cannot link the list to our app ID
[ 1600]  2023-12-13 00:14:08      [ 2124]      ERROR      RecentlyMetPlayersGet.cpp (57)                   Failed to get friend suggestions.
[ 1600]  2023-12-13 00:14:37      [ 2124]      INFO       GameStartPipe.cpp (82)                           Accepted connection.            
[ 1600]  2023-12-13 00:14:37      [ 2124]      INFO       GameStartPipe.cpp (83)                           Starting game session.          
[ 1600]  2023-12-13 00:14:39      [  188]      INFO       StartView.cpp (921)                                                              
[ 1600]  2023-12-13 00:14:45      [ 2124]      INFO       ApiProcessConnection.cpp (124)                   Game with process id 276 connected.
[ 1600]  2023-12-13 00:14:45      [ 2124]      INFO       ApiProcessConnection.cpp (136)                   Game with process id 276 has been started with product id 541 (branch: 'default').
[ 1600]  2023-12-13 00:14:45      [ 2124]      INFO       UplayGameConnectionHandler.cpp (401)             Game with process id 276 connected (API version: 1.0.0).
[ 1600]  2023-12-13 00:15:12      [ 2124]      INFO       ApiProcessConnection.cpp (292)                   Game with process id 276 disconnected.
[ 1600]  2023-12-13 00:15:12      [ 2124]      INFO       UplayGameConnectionHandler.cpp (349)             Game with process id 276 disconnected.
`

Thank you! I followed the advice from #502, but it only partially solved my problem.
An "unknown error" occurs when launching Watch Dogs.
