### ISSUE TITLE
[Bug]: Doesn't work on Intel Mac's

### ISSUE THREAD

**Issue by TheKnarf** [Whisky-App/Whisky#681]
### Description

![Screenshot 2023-12-05 at 12 33 05](https://github.com/Whisky-App/Whisky/assets/213777/c2d92c03-01c1-4ef2-ada4-91b90f5df734)

Seems to not work on Intel Mac's...

### Steps to reproduce

- Download from the website
- Try to launch the app (on an MacBook with Intel processor)

### Expected behaviour

Preferably to work

### Logs

```bash
N/A
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Not a bug, Apple Silicon is required.

**Comment by QuigonJohnn** [comment]
How do I safely remove the bottles and any other configuration that was create when it could be run on Intel Macs?

I've reinstalled an older version to at least see the bottles and where they are stored. Is deleting them from the UI enough?

Is there any residual non-functional GPTK data I need to be worried about?
