### ISSUE TITLE
Error 0x3 no dbdata generation was possible

### ISSUE THREAD

**Issue by rastaman111** [Whisky-App/Whisky#683]
I get this error "Error 0x3 no dbdata generation was possible" when starting the game Hogward Legacy

I installed visual studio c++ 2006-2020

I understand that this error is due to DirectX

What version of Whisky are you using?

2.2.1

What version of macOS are you using?

Sonoma (macOS 14)

**Comment by IsaacMarovitz** [comment]
Issue exclusive to the cracked version of the game
