### ISSUE TITLE
[Bug]: Steam downloads time out

### ISSUE THREAD

**Issue by antwacky** [Whisky-App/Whisky#693]
### Description

Mac: Apple M1 Max
OS: 14.0 (23A344)
Whisky: Version 2.2.1 (34)

Steam launches perfectly, it seems to have internet access as login works and everything else (library, friends, store).

Downloads never go above 0 bps, and eventually fail with 'CONNECTION TIME OUT' or 'NO INTERNET CONNECTION'.

Any ideas?

### Steps to reproduce

Install Whisky on the given OS, then install Steam inside a bottle. Login and try to download a game.

### Expected behaviour

The game downloads should start.

### Logs

```bash
Whisky Version: 2.2.1
Date: 2023-12-09T11:36:08Z
macOS Version: 14.0.0

Bottle Name: Steam
Bottle URL: /Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/AF8164DD-1B74-4408-8238-929A73343470

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: reg add HKCU\Control Panel\Desktop -v LogPixels -t REG_DWORD -d 0 -f

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/me/Library/Containers/com.isaacmarovitz.Whisky/Bottles/AF8164DD-1B74-4408-8238-929A73343470";
}

reg: The operation completed successfully
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by antwacky** [comment]
Disabling IPV6 got it working :D

**Comment by nobodyawesomer** [comment]
I have this same problem. How did you disable IPv6? I can't find anything in the Wine Control Panel or Registry.

**Comment by antwacky** [comment]
Disable IPV6 in your MacOS network settings.

**Comment by hat-dogs** [comment]
> I have this same problem. How did you disable IPv6? I can't find anything in the Wine Control Panel or Registry.

Go to system settings, search "IPv6", click the dropdown for "Configure IPv6", select "Link-Local Only"
