### ISSUE TITLE
[Bug]: "drive_c"-folder only contains "windows"-folder

### ISSUE THREAD

**Issue by gaudiman** [Whisky-App/Whisky#703]
### Description

Hello,

Im having a problem with Whisky:

The installation seemed like it went fine, until I tried to open a bottle. Everytime I opened up a bottle, the "drive_c"-folder only contained the "windows"-folder, which only contained the folders "system32" & "syswow64", these folders contain nothing. This occures for every bottle opened.

I suspect that it has something to do with my current installation of Parallels, but Im not sure either.

I hope you can help me with this frustrating problem.

### Steps to reproduce

1. Install Whisky
2. Open up a bottle

### Expected behaviour

"drive_c", which contains all necessary folders like "Program Files", "Program Files (x86)", "Program Data", "users" and "windows".

### Logs

```bash
-
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by gaudiman** [comment]
<img width="972" alt="Screenshot_2023-12-13_at_00 29 20" src="https://github.com/Whisky-App/Whisky/assets/151548174/3eeb7c24-0812-41a1-bb33-6cab2a574e97">
<img width="961" alt="Screenshot_2023-12-13_at_00 29 27" src="https://github.com/Whisky-App/Whisky/assets/151548174/0d5b7dbe-30a6-41c7-8c2a-180801d032d4">

**Comment by BokBoy** [comment]
> I suspect that it has something to do with my current installation of Parallels, but Im not sure either

Parallels does not use Wine or GPTK so it shouldn't have an effect.

How did you download Wine?? From whisky or other sources??
Try another way of getting wine and see if that works

**Comment by IsaacMarovitz** [comment]
This may be because your home folder ends with a `.`, which has historically caused Wine some issues. I suggest renaming your home folder to remove this character.

**Comment by sayheyakanksha** [comment]
> This may be because your home folder ends with a `.`, which has historically caused Wine some issues. I suggest renaming your home folder to remove this character.

I faced the exact same issue and this was definitely the reason for it. Tried it with another account without the fullstop and it worked. Thank you!
