### ISSUE TITLE
[Bug]: Apex Legends launches, but kicks you off because of the anticheat

### ISSUE THREAD

**Issue by savdav96** [Whisky-App/Whisky#705]
### Description

When launching Apex Legends through Steam, the game successfully reaches the main menu. However, it prevents progression to the actual gameplay, citing the absence of the Anti-Cheat system. I've attempted to start Easy Anti Cheat (included with the game) and tried patching/repairing the game. This issue seems to be related to permissions, as forums on Wine for Linux recommend running the program as an administrator to resolve the problem.

### Steps to reproduce

1. Install Steam for Windows
2. Download Apex Legends from Steam
3. Launch it
4. Start a gameplay

### Expected behaviour

The games proceeds to the gameplay

### Logs

```bash
No logs are provided, as I removed the game. I will update the issue when possible.
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Aem1024** [comment]
Easy Anti Cheat is incompatible with wine on macOS.

**Comment by BokBoy** [comment]
Anticheat cannot be ported, as far as I know.

**Comment by IsaacMarovitz** [comment]
There's no way around this; games with kernel-level anti-cheat will not work in Wine.
