### ISSUE TITLE
[Bug]: Not working with Ventura

### ISSUE THREAD

**Issue by Behinder** [Whisky-App/Whisky#708]
### Description

Cannot launch it in Ventura

### Steps to reproduce

N/a

### Expected behaviour

normal launch

### Logs

```bash
Cannot provide logs
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is not a bug, we require macOS Sonoma as GPTK only works on Sonoma and newer.

**Comment by Behinder** [comment]
That's bug and lazy programmers because you used Swift UI and WhiskyKit
uses some code declarations that works only in Sonoma.
If Crossover is able to work on Ventura that Whiskey should do.
This is very bad practice to support only unstable systems, Apple is doing
worse and worse OS and no serious developer supports GPTK.

czw., 14 gru 2023 o 19:31 Isaac Marovitz ***@***.***>
napisał(a):

**Comment by IsaacMarovitz** [comment]
How is that "lazy programming"? We use Sonoma APIs because we only support Sonoma. The entire point of Whisky is making GPTK easy to use.

**Comment by ohaiibuzzle** [comment]
> lazy programmers

Go ahead. Fork the tree at an earlier point where we have not make it mandatory to use Sonoma, then maintain it yourself.
The source code is available, so if you are "not lazy", do it yourself. We have better things and ideas to work on.
