### ISSUE TITLE
Why are you sharing source code project in Xcode if you want people to contribute?

### ISSUE THREAD

**Issue by Behinder** [Whisky-App/Whisky#709]
### Description

I cannot compile it without either resetting completely signing certificates or creating my own on developer portal.
Lot of people don't have Developer Account so their contrubutions will be pointless.

### Steps to reproduce

n/a

### Expected behaviour

n/a

### Logs

```bash
n/a
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Aem1024** [comment]
...just don't commit the Xcode changes..?

**Comment by ohaiibuzzle** [comment]
> I cannot compile it without either resetting completely signing certificates or creating my own on developer portal.
Lot of people don't have Developer Account so their contrubutions will be pointless.

Excuse me are you telling me you’re smart enough to go onto GitHub and to complain about this non-existence this issue, yet not enough to figure out 6 clicks are all you need to sign locally, and `git add` allows you to specify what to commit?

![at least read the docs](https://github.com/Whisky-App/Whisky/assets/23693150/f600d2d0-804e-41cf-8eeb-1e04eb6e29a2)
