### ISSUE TITLE
[Bug]: Failed to resolve your host

### ISSUE THREAD

**Issue by tcurdt** [Whisky-App/Whisky#710]
### Description

Fresh install of Whisky. Installed various programs. None start.
All fail with `002c:err:winediag:getaddrinfo Failed to resolve your host name IP`

### Steps to reproduce

Not sure it really is easy to reproduce. Here is what I did:

1. `brew install whisky`
2. Install Esltcam 12.
3. Run and nothing happens. (Not even an error message?!)
4. Checked the logs.

### Expected behaviour

The app should start.

### Logs

```bash
Whisky Version: 2.2.1
Date: 2023-12-15T01:54:09Z
macOS Version: 14.1.1

Bottle Name: Esltcam
Bottle URL: /Users/tcurdt/Library/Containers/com.isaacmarovitz.Whisky/Bottles/A7A16056-D89C-4E86-89D8-C4B7FFC8402B

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/tcurdt/Library/Containers/com.isaacmarovitz.Whisky/Bottles/A7A16056-D89C-4E86-89D8-C4B7FFC8402B/drive_c/Program Files (x86)/Estlcam12/Estlcam12_CAM.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/tcurdt/Library/Containers/com.isaacmarovitz.Whisky/Bottles/A7A16056-D89C-4E86-89D8-C4B7FFC8402B";
}

msync: bootstrapped mach port on wine-5bf2d0c-msync.
msync: up and running.
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
```
```


### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Is this the application?
You need to first run this package to install [Mono](https://github.com/madewokherd/wine-mono/releases/tag/wine-mono-7.2.0). It has nothing to do with your hostname 

<img width="1680" alt="image" src="https://github.com/Whisky-App/Whisky/assets/23693150/c6bf4e1a-4cad-43f1-b096-96a339915899">

**Comment by tcurdt** [comment]
That's the one.
But how does Mono relate to the error message `002c:err:winediag:getaddrinfo Failed to resolve your host name IP`? 

And I just realized: That's x86 and I am on arm.
It seems still to work (through Rosetta I guess).
