### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by BokBoy** [Whisky-App/Whisky#721]
Description

This is just an outline of the issue, I did fix it.
Trying to install Whisky 2.2.0 doesn't let you install GPTK if not already installed.
Downgrading to Whisky 2.1.0 (I heard about the issue on 2.1.3) lets you install, and then you can upgrade to 2.2.0.
One of the issues I'm getting, creating another one after this.

Steps to reproduce

Download Whisky 2.2.0 (either from homebrew or just from releases) without GPTK installed. When trying to install, it stays at 0mb out of 0mb when trying to install.

Expected behaviour

Expected to install (like on 2.1.0) and let me work it.

Logs

No logs, does not involve WINE but GPTK installer.
What version of Whisky are you using?

2.2.0

What version of macOS are you using?

Sonoma (macOS 14)

Issue Language

 Yes my issue is written in English

_Originally posted by @BokBoy in https://github.com/Whisky-App/Whisky/issues/706#issuecomment-1855167821_

#706, I'm trying to tell something and stop ignoring me.

**Comment by IsaacMarovitz** [comment]
Like I have stated numerous times, this is a networking issue on your end. The issues were closed for a reason. This does not properly follow formatting and is now boarding on spam. Something on your network is preventing a secure connection to Cloudflare's servers. This is not something I can fix.

Please do not reopen this issue again.
