### ISSUE TITLE
[Bug]: Cannot start Space Engine - OpenGL error

### ISSUE THREAD

**Issue by romann-broque** [Whisky-App/Whisky#726]
### Description

Hello guys ! I'm on Mac M1 and I just purchased Space Engine.
But when I launch it with Whisky, it freezes and returns a critical error.

<img width="634" alt="Screenshot 2023-12-22 at 15 05 00" src="https://github.com/Whisky-App/Whisky/assets/58867296/423500ad-a0b3-43bc-b40c-7804518c23c5">

I'm hopeless, but I'm waiting for someone who has an idea or a solution...
It could be great to finally play Space Engine on Mac.
Thanks in advance ! :D

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
macOS only has rudimentary OpenGL 4.1 support, and Space Engine seems to require 4.4. You can try to bypass this warning, but there's no guarantee the features it needs will be supported.
