### ISSUE TITLE
[Feature]: Disable Hot Corners

### ISSUE THREAD

**Issue by aseniah** [Whisky-App/Whisky#731]
### Is your feature request related to a problem?

I have a hot corner set to turn off my display / lock the screen. While playing GTA V, it would occasionally trigger as I drag my mouse in that direction.

### Describe the solution you'd like

It'd be nice if Hot Corners could be disabled somehow while running a full screen game (if possible).

### Anything else?

I found some discussion around this issue with Crossover [here](https://www.codeweavers.com/support/forums/general/?t=27;mhl=239217;msg=239217).

One suggestion in that thread is to add a key press to the Hot Corner which I may do in the mean time.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
There is no API to do this, if you can find a way to lock your mouse to center of the screen while playing GTA, that would resolve the issue.

**Comment by aseniah** [comment]
Thanks for taking a look at my request. I'll stick with the Hot Corner + Key Press solution.

**Comment by adamesque** [comment]
Just adding on here: if you go Bottle Configuration -> Open Wine Configuration -> Graphics, you'll find a checkbox for "Automatically capture the mouse in full-screen windows". When I checked that, and then quit everything, relaunched my game, and selected a full-screen graphics mode, my mouse no longer triggered hot corners, revealed my dock, etc.

The only minor downside is that the mouse was well and truly captured; I couldn't switch back to my desktop or break out of the game at all except by quitting it.

<img width="424" alt="Screenshot 2024-03-17 at 2 08 12 PM" src="https://github.com/Whisky-App/Whisky/assets/134433/e95608ac-80c6-4696-861c-52246632c166">

Surely there are better Mac OS APIs for capturing the mouse in fullscreen windows, but this worked for me!
