### ISSUE TITLE
[Bug]: NFS MW 2005 crashes immediately

### ISSUE THREAD

**Issue by vodemn** [Whisky-App/Whisky#735]
### Description

After pressing _Run_ button the thumbnail of the game appears in the dock and disappears immediately. Though loader next to the _Run_ button continues to spin. Waiting for it to "load" doesn't help.

I think there can be something with the game itself, I remember games on Windows missing some dlls or some other files. Is there a way to get Windows logs when running the app thought Whisky?

### Steps to reproduce

Install NFS MW through whisky. Run the game.

### Expected behaviour

Should run the game

### Logs

```bash
Whisky Version: 2.2.2
Date: 2023-12-27T09:37:18Z
macOS Version: 14.0.0

Bottle Name: NFS
Bottle URL: /Users/vodemn/Library/Containers/com.isaacmarovitz.Whisky/Bottles/B9ABEA6D-6E24-4515-805D-E594C6A747F8

Wine Version: 7.7.0
Windows Version: win7
Enhanced Sync: none

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/vodemn/Library/Containers/com.isaacmarovitz.Whisky/Bottles/B9ABEA6D-6E24-4515-805D-E594C6A747F8/drive_c/Program Files (x86)/EA GAMES/Need for Speed Most Wanted/speed.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "LC_ALL" = "ru_RU.UTF-8";
    WINEDEBUG = "fixme-all";
    WINEPREFIX = "/Users/vodemn/Library/Containers/com.isaacmarovitz.Whisky/Bottles/B9ABEA6D-6E24-4515-805D-E594C6A747F8";
}
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by techvlad** [comment]
Same problem. However, when I connect my macbook (pro m1 max) to the monitor, the game starts.

@vodemn try connect macbook to monitor and run game

**Comment by vodemn** [comment]
@techvlad connecting 2nd monitor didn't help

**Comment by Rakesh-HR** [comment]
@techvlad, same here, connecting to a second monitor didn't help. I am using a M2 mac.

**Comment by DanikKul** [comment]
try to execute winetricks -> libraries -> d3dx9 and dinput8

**Comment by Rakesh-HR** [comment]
Just tried that, its still not working. 
Also, Is there a way to check the logs?

**Comment by vodemn** [comment]
> try to execute winetricks -> libraries -> d3dx9 and dinput8

That fixed it for me! Thanks! Works with and without an external monitor.

**Comment by cheburashkalev** [comment]
Unhandled page fault on read access to 00000000 at address 006E6D5F (thread 0024)

Don't work for me
