### ISSUE TITLE
[Bug]: Batman Arkham knight resolution option

### ISSUE THREAD

**Issue by WellingtonNico** [Whisky-App/Whisky#736]
Hello guys, congratulations for you work!

I'm trying to run this game but it does now give me more resolution options, I'm stuck at 900x600, my device is a MacBook Pro m3 pro 18gb

**Comment by IsaacMarovitz** [comment]
See https://www.pcgamingwiki.com/wiki/Batman:_Arkham_Knight for configuration file locations. Try forcing the resolution from there. If that doesn't work, enable Retina Mode in bottle settings, which should unlock higher resolutions.
