### ISSUE TITLE
[Feature]: Have an option to Turn on .NET 

### ISSUE THREAD

**Issue by CookieyedCodes** [Whisky-App/Whisky#744]
### Is your feature request related to a problem?

![image](https://github.com/Whisky-App/Whisky/assets/20846898/76ab0a1f-f45c-4dec-8c66-8cf320fe6946)

### Describe the solution you'd like

I have 8.0 .NET installed under whisky, but I still can't install the affinity suite, can anyone provide clarity on how to get it installed or make whisky compatible in this regard, I think it would make older games compatible too so it would be appricated:)

### Anything else?

Let me know your thoughts :)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The app is requesting .NET 3.5, not .NET 8.0. They are not interchangeable like that. You can use Winetricks to install .NET 3.5 in your bottle.

**Comment by CookieyedCodes** [comment]
@IsaacMarovitz ah fair enough, is that under the DLLs? (Could you add a search function under the wine tricks to make it easier) & what about the windows features app where is that? Apologies if I'm being a bit dumb 😅
