### ISSUE TITLE
[Feature]: Implement GStreamer (so no Media Foundation DLLs are needed)

### ISSUE THREAD

**Issue by bfeeder** [Whisky-App/Whisky#746]
Please implement GStreamer instead of using old wine-crossover dylib libraries. Absence of this library and Wine’s natural absence of MF codecs are making some games unplayable.

When playing some specific games (Unreal Engine) like FNAF Security Breach, The Poppy Playtime, required videos aren’t played and those games cannot continue.

This gets fixed by installing Media Foundation DLLs. I used this library to install Media Foundation and this fixed my problem https://github.com/HoodedDeath/mf-fix.

Please implement GStreamer so no other fixes are required. For example, CrossOver 23.5+ make use of GStreamer.

**Comment by darlanvsvs** [comment]
> Please implement GStreamer instead of using old wine-crossover dylib libraries. Absence of this library and Wine’s natural absence of MF codecs are making some games unplayable.
> 
> When playing some specific games (Unreal Engine) like FNAF Security Breach, The Poppy Playtime, required videos aren’t played and those games cannot continue.
> 
> This gets fixed by installing Media Foundation DLLs. I used this library to install Media Foundation and this fixed my problem https://github.com/HoodedDeath/mf-fix.
> 
> Please implement GStreamer so no other fixes are required. For example, CrossOver 23.5+ make use of GStreamer.

I am not very techy could you make a guide to fix it?

**Comment by Grindisgood** [comment]
Is this planned to be implemented somewhere in the future?
In some Games, such as Star Wars: Fallen Order (Origin, D3DMetal), the voices of the characters are missing. I have been told that the GStreamer implementation will fix this...

**Comment by IsaacMarovitz** [comment]
This was added in Whisky 2.3.0
