### ISSUE TITLE
[Bug]: Cannot install whisky using homebrew. It thinks I'm running an intel processor.

### ISSUE THREAD

**Issue by g-evan-c** [Whisky-App/Whisky#751]
### Description

I tried to install Whisky using homebrew, but for some reason it seems to think I am running an Intel hardware architechture, as opposed to ARM64. I'm running on a fairly new computer, with the M3 Pro chip. 

I am not sure if I should put this here or under homebrew, so I put it here first.

### Steps to reproduce

I do not know how to reproduce the issue. It may be due to me entering a Rosetta environment earlier, however I have restarted the computer, and run the "arch" command to check what architechture It is running. It has told me arm64.

### Expected behaviour

I expected homebrew to just install Whisky as normal.

### Logs

```bash
No wine process was launched.
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You need to reinstall ARM homebrew, right now you're running the x86 version.
