### ISSUE TITLE
[Bug]: Genshin Impact 4.3 Boot Problem

### ISSUE THREAD

**Issue by MarkYu1995** [Whisky-App/Whisky#755]
### Description

Genshin Impact cannot boot successfully after Ver. 4.3 update. 
![Genshin Impact 4 3  failed to Launch ](https://github.com/Whisky-App/Whisky/assets/139697419/c50bd9a7-2117-4e8b-85b9-3ad142bfc828)

### Steps to reproduce

1, Launch Whisky 2.2.2
2, Select Bottle
3, Double click Launcher (Genshin Impact)
4, In Genshin Launcher, 
![Genshin Impact 4 3  failed to Launch ](https://github.com/Whisky-App/Whisky/assets/139697419/00f43c0c-8978-4770-adc4-417eaac0c186)
click "Start Game"
Output: Program error window ()

### Expected behaviour

When I click "Start" in the launcher, I can dive into the game directly with no error (Just like how it works in previous Genshin Impact Version)

### Logs

```bash
Cannot show LOGs cause it crashed immediately when we click "More details"
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Tony---Zhang** [comment]
I met the same problem too.

```
Whisky Version: 2.2.2
Date: 2024-01-03T12:25:59Z
macOS Version: 14.1.0

Bottle Name: mac
Bottle URL: /Users/zhangshuai/Library/Containers/com.isaacmarovitz.Whisky/Bottles/168A001C-8FDB-4437-A191-C6FA33E167E8

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/zhangshuai/Library/Containers/com.isaacmarovitz.Whisky/Bottles/168A001C-8FDB-4437-A191-C6FA33E167E8/drive_c/Program Files/Genshin Impact/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/zhangshuai/Library/Containers/com.isaacmarovitz.Whisky/Bottles/168A001C-8FDB-4437-A191-C6FA33E167E8";
}

msync: bootstrapped mach port on wine-424369-msync.
msync: up and running.
0174:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
```

My mac is Apple M2 Max and OS is 14.1

**Comment by IsaacMarovitz** [comment]
This is a bug in Rosetta.

Duplicated #718
