### ISSUE TITLE
[Bug]: It is not supported on my Mac

### ISSUE THREAD

**Issue by Jqvmsx** [Whisky-App/Whisky#764]
### Description

When I click on the app, it says that the application is not supported on my mac.

### Steps to reproduce

<img width="260" alt="Screenshot 2024-01-08 at 17 46 30" src="https://github.com/Whisky-App/Whisky/assets/155982783/214bb3aa-bb73-4b55-8154-f73e0ade2b3f">

### Expected behaviour

I thought that it would open the app so I could play a game but it didnt work

### Logs

```bash
It just became an error and is not letting me open the app
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lpgneg19** [comment]
Intel Mac？

**Comment by IsaacMarovitz** [comment]
Whisky is on supported on Apple Silicon Macs running macOS Sonoma or newer.

**Comment by hdinjos** [comment]
How to support Intel/x86 processors?
I use an Intel processor

**Comment by lpgneg19** [comment]
> How to support Intel/x86 processors? I use an Intel processor

Apple restricts only Apple Silicon to support GPTK, so whisky doesn't support Intel Macs either.
