### ISSUE TITLE
[Bug]: Foundation require OpenGL

### ISSUE THREAD

**Issue by gritsp** [Whisky-App/Whisky#785]
### Description

Foundation require OpenGL
![image](https://github.com/Whisky-App/Whisky/assets/39861809/41b4ffe9-deda-48d8-b11e-f4d53db18764)

### Steps to reproduce

Just open game on stream

### Expected behaviour

It should run game but not working

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-01-20T18:38:02Z
macOS Version: 14.2.1

Bottle Name: test
Bottle URL: /Users/3lackcat/Library/Containers/com.isaacmarovitz.Whisky/Bottles/01AE9DAE-D3E3-4893-9A04-D8549E2E2986

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Users/3lackcat/Library/Containers/com.isaacmarovitz.Whisky/Bottles/01AE9DAE-D3E3-4893-9A04-D8549E2E2986/drive_c/Program Files (x86)/Steam/bin/gldriverquery64.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/3lackcat/Library/Containers/com.isaacmarovitz.Whisky/Bottles/01AE9DAE-D3E3-4893-9A04-D8549E2E2986";
}
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by eetgeenappels** [comment]
Macos supports up to OpenGL 4.1. Thats why it doesn't run

**Comment by gritsp** [comment]
That mean I can't play this game. right?

**Comment by IsaacMarovitz** [comment]
Yes, macOS does not support the OpenGL features required. Whisky works best with DirectX12 titles.
