### ISSUE TITLE
[Bug]: Steam.exe won't run when clicking 'Run'

### ISSUE THREAD

**Issue by JonasHuygh** [Whisky-App/Whisky#788]
### Description

Hello, 

I think this issue/bug might have already been raised but I have not found out from anywhere how to exactly fix this issue and would be grateful for explained help.

My end goal is to try and play Lethal Company using Whisky but after installing Whisky and creating a bottle, and then trying to run the steam.exe file, it doesn't seem to do anything at all. So whenever I click on the 'Run' button on the bottom right, head to my downloads folder and then try to open the steam.exe, it shows a loading icon on the bottom right for like 5-6 seconds and then nothing happens. Can someone please tell me how to fix this?

### Steps to reproduce

1. Open Whisky
2. Create a bottle
3. Try and open Steam.exe with no success

### Expected behaviour

I expect the steam.exe file to load in which should prompt a download screen as seen on various Youtube videos and tutorials.

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-01-21T20:44:00Z
macOS Version: 14.2.1

Bottle Name: macgame
Bottle URL: /Users/jonash./Library/Containers/com.isaacmarovitz.Whisky/Bottles/865B1ECC-E27E-4E51-B584-168C42944421

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/jonash./Downloads/SteamSetup.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/jonash./Library/Containers/com.isaacmarovitz.Whisky/Bottles/865B1ECC-E27E-4E51-B584-168C42944421";
}

wine: could not load kernel32.dll, status c0000135
wine: could not open working directory L"Z:\\Users\\jonash\\Library\\Application Support\\com.isaacmarovitz.Whisky\\Libraries\\Wine\\bin\\", starting in the Windows directory.
wine: could not load kernel32.dll, status c0000135
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Xe4ro** [comment]
I have the same problem, tried to create bottles on different drives but the problem stays the same. 

For me the Build Version of Windows 10 also doesn't appear (the same circle thing) and the bottle contains only the folders dosdevices & drive_c (with drive_c only having a windows folder)

**Comment by theqa-ninja** [comment]
I have an existing steam whisky that works, looks like main difference is that I'm being a bum no updating my macOS though....

```
Whisky Version: 2.2.3
Date: 2024-01-24T19:45:09Z
macOS Version: 14.0.0

Bottle Name: Steam
Bottle URL: /Users/moi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/82F73C64-82B2-4FE3-8572-85DC11C2EE57

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/moi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/82F73C64-82B2-4FE3-8572-85DC11C2EE57/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/moi/Library/Containers/com.isaacmarovitz.Whisky/Bottles/82F73C64-82B2-4FE3-8572-85DC11C2EE57";
}

msync: bootstrapped mach port on wine-2f7bb4-msync.
msync: up and running.
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8:err:winediag:wined3d_adapter_create Using the Vulkan renderer for d3d10/11 applications.
0154: thread_get_state failed on Apple Silicon - faking zero debug registers
0188: thread_get_state failed on Apple Silicon - faking zero debug registers
0130:err:ole:com_get_class_object class {aa509086-5ca9-4c25-8f95-589d3c07b48a} not registered
0148: thread_get_state failed on Apple Silicon - faking zero debug registers
02e0: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
0274:err:wininet:HTTP_ParseRfc1123Date unexpected time zone L"UTC"
0274:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Jan 2024 19:09:00 UTC"
03e0: thread_get_state failed on Apple Silicon - faking zero debug registers
0450: thread_get_state failed on Apple Silicon - faking zero debug registers
049c: thread_get_state failed on Apple Silicon - faking zero debug registers
04a0: thread_get_state failed on Apple Silicon - faking zero debug registers
04cc: thread_get_state failed on Apple Silicon - faking zero debug registers
```

**Comment by hat-dogs** [comment]
I had the same issue. I found a workaround: you may see the bottle you want in the drop down menu before clicking run, but just open up the drop down and re-click the bottle you'd like to install steam on, and the run button works.

**Comment by electrovir** [comment]
I have an existing install, haven't updated macOS or Whisky recently and it suddenly stopped working within the past couple days.

**Comment by electrovir** [comment]
I was able to get mine working by creating a new bottle and installing steam fresh within that bottle.

**Comment by Lynden-Sylvester** [comment]
I am also encountering this issue

I'm running:

Whiskey v1.3.2

MacOS 14.1

**Comment by EMP-Playz** [comment]
I have the issue as well and the discord for support is dead :L

**Comment by IsaacMarovitz** [comment]
This issue has grown nebulous in scope. If you're having specific issues with the latest versions of Whisky and WhiskyWine, then feel free to make a new one.

**Comment by farrukitojajajaj** [comment]
For everyone that can't run steam because the botton won't work:

All you have to do is uninstall complete Whisky app from ur Mac and also Steam. After that install whisky and the steam.exe and do the process, it should work.

To uninstall correctly both apps use: AppCleaner that will eliminate all the files related to these apps.
