### ISSUE TITLE
[Bug]: Genshin Impact window not showing

### ISSUE THREAD

**Issue by JustSk1es** [Whisky-App/Whisky#794]
### Description

I recently just got Whisky and I found out I could play Genshin Impact on my mac using Whisky, I am able to open the installer and download the game files, however when launching the game no game window appears or any sign that the game is running except for when I go into the launcher and click "Clear Downloaded Resources" or try to uninstall by running the uninstaller via Whisky. I tried searching tutorials online to help solve my issue but I basically did the same steps as what the video says. Am I doing something wrong? I am also using a M1 MacBook Air 2020 (idk whether relevant to my problem or not)
<img width="285" alt="image" src="https://github.com/Whisky-App/Whisky/assets/94462130/90c8efe2-fb62-47b2-9bc2-56b48abc8dbd">
<img width="789" alt="image" src="https://github.com/Whisky-App/Whisky/assets/94462130/e2d2caf2-10c7-4229-a863-6ee9ff17eafe">

### Steps to reproduce

I downloaded the official installer for the launcher from the official English website file name: GenshinImpact_install_ua_ae79a5896942.exe and ran it using Whisky, once the launcher is opened I downloaded the game which had no issues and then I pressed launch game.

### Expected behaviour

The game window does not show up even though I left my computer on for a couple of minutes hoping that the game might boot up and the game launcher window minimises to the system tray 

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-01-24T15:53:25Z
macOS Version: 14.3.0

Bottle Name: GenshinImpact
Bottle URL: /Users/stanleyjebaretnam/Library/Containers/com.isaacmarovitz.Whisky/Bottles/0957F80F-4637-4CAD-819F-CBDBDA163D17

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

Arguments: start /unix /Users/stanleyjebaretnam/Downloads/GenshinImpact_install_ua_ae79a5896942.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/stanleyjebaretnam/Library/Containers/com.isaacmarovitz.Whisky/Bottles/0957F80F-4637-4CAD-819F-CBDBDA163D17";
}

0238:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Genshin is currently unplayable due to a bug in Rosetta.

**Comment by AnotiaWang** [comment]
The bug in Rosetta seems to be fixed in macOS 4.4 Beta (23E5180j), and GI can launch without issue.

<img width="1470" alt="截屏2024-02-02 11 56 11" src="https://github.com/Whisky-App/Whisky/assets/62269186/cfea0bc7-6a89-44b6-a662-35c0bf0cc68a">

**Comment by IsaacMarovitz** [comment]
It is fixed yes

**Comment by bobjoerules** [comment]
I has the same issue for me as well
