### ISSUE TITLE
[Bug]: Epic Games Launcher fails to load

### ISSUE THREAD

**Issue by wannafedor4** [Whisky-App/Whisky#800]
### Description

The epic games launcher fails when opening after installing.
The launcher fails after trying to self-update.

### Steps to reproduce

1. Download and run the Epic Games Launcher
2. Run 'EpicGamesLauncher' from the pinned apps list
3. Observe

### Expected behaviour

The launcher should open and ask for account information

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-01-27T02:40:18Z
macOS Version: 14.2.1

Bottle Name: Games
Bottle URL: /Users/<nice try but no>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/FF0C8F77-97F7-4810-B920-610F54A5E9AF

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/<nice try but no>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/FF0C8F77-97F7-4810-B920-610F54A5E9AF/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/<nice try buckaroo>/Library/Containers/com.isaacmarovitz.Whisky/Bottles/FF0C8F77-97F7-4810-B920-610F54A5E9AF";
}

msync: bootstrapped mach port on wine-17e8be-msync.
msync: up and running.
00d0: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Epic Games Launcher does not work under Wine. Please use [Heroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher).
