### ISSUE TITLE
[Bug]: Rockstar Games Launcher “Failed to Initiate”

### ISSUE THREAD

**Issue by Scooooodoo** [Whisky-App/Whisky#803]
### Description

After an update with the Rockstar games launcher, GTA 5 does not launch anymore. This error seems to not affect native windows, but It does affect Wisky.

### Steps to reproduce

Install the rockstar games launcher, or GTA V.

### Expected behaviour

Rockstar Games Launcher successfully launches. 

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-01-30T23:10:39Z
macOS Version: 14.3.0

Bottle Name: rockstar
Bottle URL: /Users/User1/Library/Containers/com.isaacmarovitz.Whisky/Bottles/684473A9-FB52-4344-B71E-C9A205864C48

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/User1/Library/Containers/com.isaacmarovitz.Whisky/Bottles/684473A9-FB52-4344-B71E-C9A205864C48/drive_c/Program Files/Rockstar Games/Launcher/LauncherPatcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/User1/Library/Containers/com.isaacmarovitz.Whisky/Bottles/684473A9-FB52-4344-B71E-C9A205864C48";
}
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Scooooodoo** [comment]
By the way, this might have to do with the end of support for windows 7 and 8

**Comment by pilisir** [comment]
Same here, but I found a workaround.
Keep Steam on, open Rockstar launcher via Whisky.
Login and scan games first, and clicking PLAY ON STEAM to play GTA V from Rockstar launcher would be fine.

**Comment by JSP100** [comment]
I've encountered the same issue too, and here is the log file of the Rockstar Game Launcher.
[launcher.log](https://github.com/Whisky-App/Whisky/files/14109099/launcher.log)

**Comment by Jerry22-ff** [comment]
> Same here, but I found a workaround. Keep Steam on, open Rockstar launcher via Whisky. Login and scan games first, and clicking PLAY ON STEAM to play GTA V from Rockstar launcher would be fine.

Can't open rockstar games launcher... already tried to delete the steam and rockstar game launcher and redownload it, still doesn't work for me :<

**Comment by pilisir** [comment]
> > Same here, but I found a workaround. Keep Steam on, open Rockstar launcher via Whisky. Login and scan games first, and clicking PLAY ON STEAM to play GTA V from Rockstar launcher would be fine.
> 
> Can't open rockstar games launcher... already tried to delete the steam and rockstar game launcher and redownload it, still doesn't work for me :<

My is LauncherPatcher.exe, I also heard about to enable DXVK help, but I keep it off and game still works.

**Comment by alflee0505** [comment]
Me too here , I used Heroic to run GTAV by Whisky but It just won't open saying GTAV doesn't support Windows7,8 anymore

**Comment by teksta7** [comment]
Can confirm that the workaround works although I did launch the Rockstar Games Launcher with the Launcher.exe file and that would only work if the bottle had DXVK enabled (the same error would come up if DXVK wasn't enabled so I'm thinking the culprit ties in with this somehow that's backed up by Windows 7/8 support for the launcher ending). By doing those steps I can launch GTA V. I also encountered the same error in Crossover too but haven't had chance to recreate the workaround in Crossover so can't confirm if that works there
![Whisky 1](https://github.com/Whisky-App/Whisky/assets/6579334/ce849697-b4f4-492c-8f96-ce5dd30c0e15)
![Whisky 2](https://github.com/Whisky-App/Whisky/assets/6579334/97abfe95-d601-4788-a2ee-5571e01e0375)

**Comment by Scooooodoo** [comment]
This workaround does work. Thanks.

**Comment by Jerry22-ff** [comment]
omg THANK YOU SO MUCH  DUDE

**Comment by master010lolol** [comment]
teksta7, you are literally the life saver, THANK YOU SO MUCCHCHCHCHHCHCHC

**Comment by PascalCrd** [comment]
For me it kinda "works" with DXVK but the graphics are insanely bad, green windows without MSAA and with that turned on it looks like a Family Guy Scene. Is there any possible way to solve this too?

**Comment by c9dn** [comment]
@teksta7 I have the same chip MacBook as you and It's not working for me? Can someone help. When I open the launcherPatcher, It just shows a loading screen. I've copied your settings as shown in the SS.

**Comment by cgcomito** [comment]
This workaround was functional yesterday and today it stopped working and it freezes on the Rockstar Logo.  No idea what changed.  Please help.  I want to play GTA

**Comment by c9dn** [comment]
I guess I'm just unlucky lmao. I'm probably gonna use VMware Fusion + CrystalFetch until it's fixed. Can someone @ me when it is pls??

**Comment by pilisir** [comment]
> I guess I'm just unlucky lmao. I'm probably gonna use VMware Fusion + CrystalFetch until it's fixed. Can someone @ me when it is pls??

Wineskin with engine WS11WineCX64Bit22.1.1-16 works fine and launch via Steam play button directly, but may encounter some graphic problems in game.

**Comment by c9dn** [comment]
How do I actually use that?

**Comment by pilisir** [comment]
Wineskin is another project, follow this [page](https://github.com/Gcenx/WineskinServer).

**Comment by c9dn** [comment]
I've notice multiple comments on other platforms about a new bug released some hours ago that broke this. Can we reopen this bug ?

**Comment by c9dn** [comment]
> Wineskin is another project, follow this [page](https://github.com/Gcenx/WineskinServer).

So that means I won't need to use whiskey?

**Comment by c9dn** [comment]
Once I've installed the engine, what's the next step?

**Comment by c9dn** [comment]
> > I guess I'm just unlucky lmao. I'm probably gonna use VMware Fusion + CrystalFetch until it's fixed. Can someone @ me when it is pls??
> 
> Wineskin with engine WS11WineCX64Bit22.1.1-16 works fine and launch via Steam play button directly, but may encounter some graphic problems in game.

This will work a temporary solution, but will whiskey need to get patched for this somehow?

**Comment by teksta7** [comment]
Yeah can confirm that there was a update to GTA V (198mb on Steam) and the Rockstar launcher which seems to result in not being able to launch the game through Steam or through the launcher either as it either gets stuck on the Rockstar logo OR the splash screen/logo for the launcher loads, disappears and then nothing occurs. Wonder if we can dig into the logs to see what's going on but I agree that the bug needs to reopen on the back of these updates

**Comment by c9dn** [comment]
> Yeah can confirm that there was a update to GTA V (198mb on Steam) and the Rockstar launcher which seems to result in not being able to launch the game through Steam or through the launcher either as it either gets stuck on the Rockstar logo OR the splash screen/logo for the launcher loads, disappears and then nothing occurs. Wonder if we can dig into the logs to see what's going on but I agree that the bug needs to reopen on the back of these updates

Is there anyway to go back to the previous version of gta in steam?

**Comment by c9dn** [comment]
> Yeah can confirm that there was a update to GTA V (198mb on Steam) and the Rockstar launcher which seems to result in not being able to launch the game through Steam or through the launcher either as it either gets stuck on the Rockstar logo OR the splash screen/logo for the launcher loads, disappears and then nothing occurs. Wonder if we can dig into the logs to see what's going on but I agree that the bug needs to reopen on the back of these updates

Do we know when this may be done, the graphics and lag on wineskin are terrible.

**Comment by Code7lol** [comment]
How do we download "Whisky"? I want to play GTAV but it keeps saying "Rockstar Games Launcher has failed to initialize." like dude. I just wanna play a game!

**Comment by c9dn** [comment]
Yep. I recommend just getting crossover. It's maintained by a company, and its not open source so fixes are made fast.

**Comment by Code7lol** [comment]
> Yep. I recommend just getting crossover. It's maintained by a company, and its not open source so fixes are made fast.

But how

**Comment by c9dn** [comment]
> > Yep. I recommend just getting crossover. It's maintained by a company, and its not open source so fixes are made fast.
> 
> But how

Download crossover from their website. Download steam, and from there download GTA, it works fine.

**Comment by Code7lol** [comment]
> > > Yep. I recommend just getting crossover. It's maintained by a company, and its not open source so fixes are made fast.
> > 
> > 
> > But how
> 
> Download crossover from their website. Download steam, and from there download GTA, it works fine.

I have gtav downloaded on steam. I can get crossover in a couple mins.

**Comment by c9dn** [comment]
> > > > Yep. I recommend just getting crossover. It's maintained by a company, and its not open source so fixes are made fast.
> > > 
> > > 
> > > But how
> > 
> > 
> > Download crossover from their website. Download steam, and from there download GTA, it works fine.
> 
> I have gtav downloaded on steam. I can get crossover in a couple mins.

Gta needs to be downloaded on the crossover bottle(which is a virtual windows enviremnt)

**Comment by Code7lol** [comment]
c9, can I get your snap or smth? It would be way mroe effecient, or Discord, idc

**Comment by Code7lol** [comment]
> > > > > Yep. I recommend just getting crossover. It's maintained by a company, and its not open source so fixes are made fast.
> > > > 
> > > > 
> > > > But how
> > > 
> > > 
> > > Download crossover from their website. Download steam, and from there download GTA, it works fine.
> > 
> > 
> > I have gtav downloaded on steam. I can get crossover in a couple mins.
> 
> Gta needs to be downloaded on the crossover bottle(which is a virtual windows enviremnt)

Can I get yo discord?

**Comment by c9dn** [comment]
sure. @c9dn

**Comment by Code7lol** [comment]
> sure. @c9dn

so where is yo Discord. Just add me. code_.7

**Comment by danml0** [comment]
> Yeah can confirm that there was a update to GTA V (198mb on Steam) and the Rockstar launcher which seems to result in not being able to launch the game through Steam or through the launcher either as it either gets stuck on the Rockstar logo OR the splash screen/logo for the launcher loads, disappears and then nothing occurs. Wonder if we can dig into the logs to see what's going on but I agree that the bug needs to reopen on the back of these updates

True. I briefly looked into the launcher.log I immediately noticed that the launcher somehow sees the system as a Windows XP Pro wrongly. Also in another logfile I found the Rockstar Launcher having issues to connect or to use a service

**Comment by c9dn** [comment]
yep, at this point crossover is the best solution.

**Comment by killa123sa** [comment]
hello, i am trying to play gta V on whisky but it won't let me open.
can someone please try to help me because my friends are playing without me...
MacBook Pro 16 m2 pro 14.3.1 (23D60)
<img width="1728" alt="Bildschirmfoto 2024-03-01 um 21 32 12" src="https://github.com/Whisky-App/Whisky/assets/161887894/00bd30ec-ee0e-40a6-a44b-a5455ff7b2be">
<img width="1728" alt="Bildschirmfoto 2024-03-01 um 21 31 55" src="https://github.com/Whisky-App/Whisky/assets/161887894/e03a26b6-1de0-4794-894b-fce84ce995d5">

**Comment by gamehunter1** [comment]
> hello, i am trying to play gta V on whisky but it won't let me open. can someone please try to help me because my friends are playing without me... MacBook Pro 16 m2 pro 14.3.1 (23D60) <img alt="Bildschirmfoto 2024-03-01 um 21 32 12" width="1728" src="https://private-user-images.githubusercontent.com/161887894/309384612-00bd30ec-ee0e-40a6-a44b-a5455ff7b2be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzE0MTAsIm5iZiI6MTcxMDkzMTExMCwicGF0aCI6Ii8xNjE4ODc4OTQvMzA5Mzg0NjEyLTAwYmQzMGVjLWVlMGUtNDBhNi1hNDRiLWE1NDU1ZmY3YjJiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMDM4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzQxMjVkNTY4MDc0MzIyMmQwNmQ4YWI5YTY0YWVlMWRiY2MxNDM5ZjFhMmQxMjk5Njg2ZTAyODRmZTc1YjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.deZiD4Y3xEsSHCifcxqkD16C9kA3VhKRxEfwWqKgpA0"> <img alt="Bildschirmfoto 2024-03-01 um 21 31 55" width="1728" src="https://private-user-images.githubusercontent.com/161887894/309384618-e03a26b6-1de0-4794-894b-fce84ce995d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzE0MTAsIm5iZiI6MTcxMDkzMTExMCwicGF0aCI6Ii8xNjE4ODc4OTQvMzA5Mzg0NjE4LWUwM2EyNmI2LTFkZTAtNDc5NC04OTRiLWZjZTg0Y2U5OTVkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMDM4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjU4YmUzN2M0ZTA1YmEzZDljYjhjM2Y1MWY2NWUyYTYwM2Q1OGVjMTAyMzc2YmIyOTg4NjYyODIwMTRjODQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j1ic76Q8pLC-QZ4-7Qtf71DTAvK4u-04VLf1TWA6tZI">

hey...you found any solution to this?

**Comment by KingNoosh** [comment]
LauncherPatcher.exe hangs for me, nothing discerning in the logs for me either.

When launching GTA V via steam with LauncherPatcher that also is stuck hanging.

Launching Launcher.exe|LauncherPatcher.exe then Steam then GTA V also hangs.

**Comment by KingNoosh** [comment]
Ah, apologies, issue already reported here https://github.com/Whisky-App/Whisky/issues/835

**Comment by c9dn** [comment]
Do you know if this would work on steam. Most users do use steam.

**Comment by TrulyInfinite** [comment]
> Do you know if this would work on steam. Most users do use steam.

It most probably will. As it’s the issue with the launcher and not the platforms. Worth the try. 

Also, do update the Whisky to latest version as the latest version fixes the ‘Stuck on Rockstar Logo’ issue which was a nightmare in the previous versions.

**Comment by KingNoosh** [comment]
> @KingNoosh @gamehunter1 @killa123sa check out the macgaming reddit forum. One of the latest posts someone asked this very question and I posted the answer in the comments.

Why not just paste the answer here? Or even link it?

Spam bot behaviour tbh

**Comment by BigByronRay** [comment]
> > @KingNoosh @gamehunter1 @killa123sa check out the macgaming reddit forum. One of the latest posts someone asked this very question and I posted the answer in the comments.
> 
> Why not just paste the answer here? Or even link it?
> 
> Spam bot behaviour tbh

I just came across this post here about a day after answering the same question on reddit and thought you might like the fix (my comment was quite long so thought it would be easier to redirect you to reddit)... I'll post here though for you as it seems going to reddit is too complicated for you.

"
I solved this problem few days ago. (Don’t listen to everyone saying you need to pirate it, or that the performance is bad. I run through steam on an M1 and get a good 60fps on high settings)

I run this using Whisky, but it will be the same if you’re using crossover. 

You need to launch GTA V through the Rockstar Games Launcher.

The bottle that you have your Rockstar Games Launcher & Steam installed in needs to have DXVK enabled. After you enable this, find the launcherpatcher.exe file and run. It will enable you to launch it sign in as normal.

From inside the Rockstar Games Launcher you can launch GTA V which will automatically launch it from Steam. 

Feel free to send me a message if you have any more questions.

Edit: all online functionality works great too
"

https://www.reddit.com/r/macgaming/s/GTRIyjGnG0

**Comment by azsoftware** [comment]
I have a bug with transparent weapons using DXVK. Is it possible to fix?

**Comment by batuhandursun** [comment]
> I found a solution to the following message.
> 
> <img alt="Screenshot 2024-04-16 at 11 09 12 PM" width="271" src="https://private-user-images.githubusercontent.com/40712315/322953400-eb41bc4e-9335-47a7-b741-43730d899b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzIyMjgsIm5iZiI6MTcxNDMzMTkyOCwicGF0aCI6Ii80MDcxMjMxNS8zMjI5NTM0MDAtZWI0MWJjNGUtOTMzNS00N2E3LWI3NDEtNDM3MzBkODk5YjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5MTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODVlNDg5MzBlMjE0OWJiYmE3MTYwMzFjMjAyMjlkMzkxNjBmNWE3NGY1ZDllZjExNTVhZjRkZGM5NDVkMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cpRHKUsMOWxeU5PJVS8iTOOfmQ-qC1l_fsoEILWi5xY">
> DO NOT PRESS OK
> 
> First open Rockstar Games Launcher MANUALLY using Whisky. After it loads, then press ok in the dialogue box.
> 
> If it's your first time launching the game, it will take some time to load, but the GTA V will boot up.
> 
> As of me, I installed rockstar games launcher using the exe from rockstar game. And also I installed prerequisites manually (.NET and direct x)
> 
> .NET 4.0 => https://appdb.winehq.org/objectManager.php?sClass=version&iId=17886 .NET 4.8 => https://appdb.winehq.org/objectManager.php?sClass=version&iId=38203
> 
> Also, Remember to enable DXVK and after this process, change to windows 10 from winecfg.
> 
> **Edit:** I am using Heroic Launcher as I have GTA V in Epic Games

But how do I connect the Rockstar games on whiskey with the gta 5 on heroic games launcher. When I click on play on heroic games it tries to download rockstar games again because it doesn't see the rockstar games that I just downloaded on whiskey bottle?

**Comment by batuhandursun** [comment]
<img width="1266" alt="Screenshot 2024-04-29 at 08 59 37" src="https://github.com/Whisky-App/Whisky/assets/150933757/9711f368-ab89-4dbf-bc97-1e4c8b02806c">
I installed rockstar games manually to a bottle on Whiskey. I have heroic games downloaded on Mac. When I run "PlayGta" file manually with Whiskey while rockstar launcher running (on whiskey), it shows this. I think the program locations are wrong but I couldn't figure it out. Where should I install my heroic games launcher, rockstar games etc.?

**Comment by batuhandursun** [comment]
> > <img alt="Screenshot 2024-04-29 at 08 59 37" width="1266" src="https://private-user-images.githubusercontent.com/150933757/326341678-9711f368-ab89-4dbf-bc97-1e4c8b02806c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTEyMjMsIm5iZiI6MTcxNDM5MDkyMywicGF0aCI6Ii8xNTA5MzM3NTcvMzI2MzQxNjc4LTk3MTFmMzY4LWFiODktNGRiZi1iYzk3LTFlNGM4YjAyODA2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxMTQyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2VkMzdlN2YxYjVjZmU0M2ViNDM4YzBmYjRhMGNiZTY1ZTIxOTE2YTc1MWMxMDc5NmEwNGFhODY1NTRkNzQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VNiw7-XcqnRHph6PZsK2HG-ZH2ExRpp6Qrjkq17pCQ0"> I installed rockstar games manually to a bottle on Whiskey. I have heroic games downloaded on Mac. When I run "PlayGta" file manually with Whiskey while rockstar launcher running (on whiskey), it shows this. I think the program locations are wrong but I couldn't figure it out. Where should I install my heroic games launcher, rockstar games etc.?
> 
> Do not launch GTAV directly from the launcher.
> 
> Press play on Heroic Launcher. And when 'Play' changes to 'Launching', immediately run the Rockstar Games Launcher from Whisky. Further process will happen automatically. 1st launch will take time so just wait patiently if it seems nothing is happening.

I did what you said. It has been an hour, my fan is spinning,  in the Activity Monitor “Whisky” energy impact is around 6.974,8. Neither rockstar games launcher nor gta5 appeared on the screen. Should I continue waiting, is that normal or something is wrong?

**Comment by tuksnesis** [comment]
Anyone using the non-steam non-epic version of GTA V? I can open the launcher fine. When I press play. It shows loading, then exit game, stays like that for around 1-2 minutes and shows exiting game.

**Comment by leolrg** [comment]
I don't see LauncherPatcher.exe or Launcher.exe, I only see Rockstar-Game-Launcher.exe, x86/x64Launcher.exe, GTAV.exe, running any of which will result in the error "There is no windows program configured to open this file"

**Comment by BardaktakiAdam** [comment]
Is there any news for GTA 5 Enhanced on Epic games?

**Comment by slavikme** [comment]
Have the same issue with Rockstar Game Launcher on my MacBook Pro 16 M3
![Image](https://github.com/user-attachments/assets/09bf61fc-80ae-4502-8884-0e5b2fb4fbd1)

This error occurs when running from Steam
![Image](https://github.com/user-attachments/assets/e5ceb41a-aae3-4910-b6a3-609037441ab5)

This error occurs when running directly using the `launcherpatcher.exe` file
![Image](https://github.com/user-attachments/assets/01618dbf-b629-459a-8942-8570f65842b5)

This is my Bottle configuration
<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/14088a67-6609-4208-bc2e-d3dd22936581" />

Using Whisky Version 2.3.5 (43)
![Image](https://github.com/user-attachments/assets/f41ea762-39dc-4116-8cbe-006dc234a4e3)

Does anyone have the same (or similar) setup and is able to play the game?
