### ISSUE TITLE
[Bug]: After new update "Party Animals" in Steam, the game cannot be launch now

### ISSUE THREAD

**Issue by notting-hill** [Whisky-App/Whisky#808]
### Description

The game used to play recently with no issue but after latest update the game seems to be error after open.

### Steps to reproduce

1. Update Steam to be latest 
2. Update Game to be latest.
3. Run Game

### Expected behaviour

After launch Game. The blank crash window get open 

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-02-03T03:18:39Z
macOS Version: 14.4.0

Bottle Name: Steam
Bottle URL: /Volumes/MACEXT/Games/Whisky/39266C6A-0513-4ADD-A100-11ED9A3BF0FB

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Volumes/MACEXT/Games/Whisky/39266C6A-0513-4ADD-A100-11ED9A3BF0FB/drive_c/Program Files (x86)/Steam/steamapps/common/Party Animals/PartyAnimals.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Volumes/MACEXT/Games/Whisky/39266C6A-0513-4ADD-A100-11ED9A3BF0FB";
}




{"bug_type":"284","timestamp":"2024-02-03 10:18:48.00 +0700","os_version":"macOS 14.4 (23E5180j)","roots_installed":0,"incident_id":"740E5E06-CD36-4F9B-A76B-2DD1DD0F395A"}
{
  "roots_installed" : 0,
  "bug_type" : "284",
  "process_name" : "wine64-preloader",
  "registers" : {},
  "timestamp" : 1706930328,
  "analysis" : {"fw_power_state":0,"fw_ta_substate":{"slot0":0,"slot1":0},"fw_power_boost_controller":0,"guilty_dm":2,"fw_power_controller_in_charge":0,"fw_cl_state":{"slot0":0,"slot1":0,"slot2":0},"fw_perf_state_lo":8,"fw_ta_state":{"slot0":0,"slot1":0},"signature":578,"fw_power_substate":0,"command_buffer_trace_id":1026805507,"fw_perf_state_select":0,"restart_reason":4,"fw_3d_state":{"slot0":1,"slot1":0,"slot2":0},"fw_gpc_perf_state":8,"fw_perf_state_hi":8,"fw_power_limit_controller":12,"restart_reason_desc":"firmware-detected lockup (pid=7184)"}
}
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by notting-hill** [comment]
I can see the info from https://steamdb.info/app/1260320/depots/
Is the shared install with Steamworks (VC 2022 Redist) required?
I've updated but the problem persists.

**Comment by notting-hill** [comment]
<img width="1124" alt="Party Animals 2024-02-03 10 58 28" src="https://github.com/Whisky-App/Whisky/assets/25293127/e750c3ab-1dc4-4949-b3bd-5d6c0ebb9346">
I tried to rollback the Game version but problem still

**Comment by notting-hill** [comment]
> I am getting the same problem... My guess is the **Sonoma 14.4 beta 1**.. Didn't find any reports about it yet...
> 
> But you're the first one having the same display behaviour...

yes it could be. I updated my macbook with the latest beta update. but not all the games got this problem. My "chicken horse run" working just fine

**Comment by lucaskatayama** [comment]
Yeah... I can confirm that is related... I have problems with Sekiro and Palworld.  I did a full reinstallation of Sonoma 14.3... Lost all my data... And now it is working normal..

**Comment by PeronGH** [comment]
I tested macOS 14.4 Beta 2 and this bug is still not fixed. I'm wondering if there is any workaround.

**Comment by notting-hill** [comment]
new update to macos today. Sonoma Beta 14.4 beta 4
I can play Party Animals again. :)

Issue Gone
