### ISSUE TITLE
[Bug]: Every text

### ISSUE THREAD

**Issue by MaW-cmkbk** [Whisky-App/Whisky#812]
### Description

Strange bug after update on every mac M1 and M3 same

![Snímek obrazovky 2024-02-05 v 7 55 50](https://github.com/Whisky-App/Whisky/assets/86100645/c92dece6-690f-4f0e-8cd8-350d8597a791)

### Steps to reproduce

just update to latest

### Expected behaviour

hide that text before dot :)

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-02-05T06:50:28Z
macOS Version: 14.3.0

Bottle Name: DiabloIV
Bottle URL: /Volumes/M2-SSD/Games/bottle/0B4A50B2-2811-443D-8D4D-461A8F9E3189

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: esync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Volumes/M2-SSD/Games/bottle/0B4A50B2-2811-443D-8D4D-461A8F9E3189/drive_c/Program Files (x86)/Games/Diablo IV/Diablo IV Launcher.exe

Environment:
{
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEPREFIX = "/Volumes/M2-SSD/Games/bottle/0B4A50B2-2811-443D-8D4D-461A8F9E3189";
}

esync: up and running.
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00ec: thread_get_state failed on Apple Silicon - faking zero debug registers
018c: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This would be a localization bug, what is your System Language set to?

**Comment by MaW-cmkbk** [comment]
> This would be a localization bug, what is your System Language set to?

Czech on first place English on 2nd

**Comment by MaW-cmkbk** [comment]
If you want the strings no problem I can fill it for you.
