### ISSUE TITLE
[Feature]: Option to Disable GPTK And Use DXVK Only

### ISSUE THREAD

**Issue by PeronGH** [Whisky-App/Whisky#817]
### Is your feature request related to a problem?

The macOS 14.4 Beta makes some games like Palworld unplayable. Maybe forcing DXVK can fix this.

### Describe the solution you'd like

An option to disable GPTK and uses DXVK only.

### Anything else?

None

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The issue with Palworld is likely a problem with Rosetta, as it has received some improvements in the 14.4 Beta. DXVK would not fix that. 

Also, this feature is essentially already implemented, enabling DXVK will use it over D3DM.
