### ISSUE TITLE
[Bug]: Horizon Zero Dawn™ Complete Edition runs at half speed

### ISSUE THREAD

**Issue by Hulkstern** [Whisky-App/Whisky#818]
### Description

# Primary Issue
Horizon Zero Dawn launches and doesn't seem to present any obvious issues. The opening cinematic plays fine (only plays if  you have no saves present). Only once you load a save, start a new game, or run the benchmark will you see that the game is running at half speed. Audio still plays at the correct speed and will trigger at the correct points but will quickly de-sync if it has any notable length as all animations, physics, and movement runs at half speed.

[Here is a video showing the issue in question](https://cdn.barehost.tech/onAppleSilicon/Horizon/).
The behavior is fairly obvious at **5:35**
Additionally you can see my graphical settings at **0:50** (both the display and graphics section)

## Secondary Issue (Related)
Additionally the performance that is observed does not seem to be inline with the relative performance I've observed on windows (I.E. when considering this game and the others I have been able to get working on whisky and their performance compared to running them on my windows desktop, Horizon Zero Dawn seems to perform much worse than expected).
Also, render scaling seems to not have much of an effect.

## Summary
Game sim speed seems to be running at half real time or 0.5x slower than it should be. Performance also does not fall in line with what I expect considering the relative performance of my laptop

This issue may be outside the scope of the whisky project, so I understand if nothing can be really done. Though if that is the case, I'd greatly appreciate being pointed towards any resources so that I may be able to further diagnose/resolve this issue.

### System Information
2021 Macbook Pro 16"
M1 Pro w/ 16GB RAM
MacOS Sonoma 14.3 (23D56)

### Steps to reproduce

1. Install whisky
2. Open/install prerequisites for whisky
3. Install steam client
4. Install Horizon Zero Dawn Complete Edition through steam
5. Launch Horizon Zero Dawn, and either run benchmark or play game to observe behavior

### Expected behaviour

Game to not run at 0.5x simulation/animation/game world speed.

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-02-07T19:31:40Z
macOS Version: 14.3.0

Bottle Name: gayming
Bottle URL: /Volumes/SabrentJump/Whisky Data/gayming/C3F6E4DF-E37C-4151-87CA-DBB1C5D80F24

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

Arguments: start /unix /Volumes/SabrentJump/Whisky Data/gayming/C3F6E4DF-E37C-4151-87CA-DBB1C5D80F24/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
    WINEMSYNC = 1;
    WINEPREFIX = "/Volumes/SabrentJump/Whisky Data/gayming/C3F6E4DF-E37C-4151-87CA-DBB1C5D80F24";
}

msync: bootstrapped mach port on wine-26-msync.
msync: up and running.
0118:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00bc: thread_get_state failed on Apple Silicon - faking zero debug registers
0210:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
[mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
[mvk-info] GPU device:
		model: Apple M1 Pro
		type: Integrated
		vendorID: 0x106b
		deviceID: 0xe0203ef
		pipelineCacheUUID: DB8512A6-0E02-03EF-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 3.0
		GPU Family Apple 7
		GPU Family Apple 6
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
00bc: thread_get_state failed on Apple Silicon - faking zero debug registers
00bc: thread_get_state failed on Apple Silicon - faking zero debug registers
00bc: thread_get_state failed on Apple Silicon - faking zero debug registers
0308: thread_get_state failed on Apple Silicon - faking zero debug registers
03e8: thread_get_state failed on Apple Silicon - faking zero debug registers
0268:err:module:import_dll Library mfplat.dll (which is needed by L"C:\\windows\\system32\\MF.dll") not found
0268:err:module:import_dll Library mfplat.dll (which is needed by L"C:\\windows\\system32\\MFReadWrite.dll") not found
0428: thread_get_state failed on Apple Silicon - faking zero debug registers
0450:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Feb 2024 10:30:00 UTC"
00bc: thread_get_state failed on Apple Silicon - faking zero debug registers
03e4:err:wininet:HTTP_ParseRfc1123Date unexpected time zone L"UTC"
03e4:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Feb 2024 04:32:00 UTC"
03e4:err:wininet:HTTP_ParseDate unexpected date format L"Wed, 07 Feb 2024 04:32:00 UTC"
0ae0: thread_get_state failed on Apple Silicon - faking zero debug registers
03e4:err:wininet:HTTP_ParseRfc1123Date unexpected time zone L"UTC"
03e4:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Feb 2024 13:14:00 UTC"
03e4:err:wininet:HTTP_ParseDate unexpected date format L"Wed, 07 Feb 2024 13:14:00 UTC"
0b10: thread_get_state failed on Apple Silicon - faking zero debug registers
0b2c: thread_get_state failed on Apple Silicon - faking zero debug registers
002c:err:module:import_dll Library mfplat.dll (which is needed by L"C:\\windows\\system32\\xaudio2_7.dll") not found
0140: thread_get_state failed on Apple Silicon - faking zero debug registers
0140: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by satchnut** [comment]
I am also experiencing this with Turbo Overkill (game/physics runs at 1/2 speed). Wiki does not mention this issue. Strangely, issue does not exist while using Heroic + Whiskey wine.
