### ISSUE TITLE
[Bug]: Rainbow Six doesn’t run (The procedure entry point DSDKMTQueryAdapterInto could not be located in the dynamic link library GDI32, dil)

### ISSUE THREAD

**Issue by dolphinahhhhh** [Whisky-App/Whisky#831]
### Description

![image](https://github.com/Whisky-App/Whisky/assets/160530689/c41349b9-2236-4719-a231-b4577c52210f)
This error message pop up while launching the r6

### Steps to reproduce

Launch steam -> launch RainbowSix -> error

### Expected behaviour

expect to launch the game

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-02-19T18:06:16Z
macOS Version: 14.3.0

Bottle Name: 2
Bottle URL: /Users/dolphin/Library/Containers/com.isaacmarovitz.Whisky/Bottles/6D7401CA-6B8B-429C-9087-C284A9D8B835

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/dolphin/Library/Containers/com.isaacmarovitz.Whisky/Bottles/6D7401CA-6B8B-429C-9087-C284A9D8B835/drive_c/Program Files (x86)/Ubisoft/Steam/steamapps/common/Tom Clancy's Rainbow Six Siege - Test Server/RainbowSix.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/dolphin/Library/Containers/com.isaacmarovitz.Whisky/Bottles/6D7401CA-6B8B-429C-9087-C284A9D8B835";
}

msync: bootstrapped mach port on wine-2105dec-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Willyam2194** [comment]
any updates on how to fix it?

**Comment by IsaacMarovitz** [comment]
Rainbow Six Siege has Battle-Eye anticheat. It will not work under wine.

**Comment by gmcmullengrc** [comment]
This error occurs before Battle-Eye is loaded. It can even be disabled by typing "/Belaunch -be" into the launch options, so this error does not have to do with the anticheat. This issue shouldn't have been closed

**Comment by gmcmullengrc** [comment]
@IsaacMarovitz

**Comment by Settiwie** [comment]
It is a kernel error. Since Rainbow six siege communicates with the the CPU on 64x or some shit, the kernel language cannot be translated properly. I do not think this can be fixed, other than Ubisoft bringing a real port to mac os.

**Comment by Ronny26** [comment]
Was this ever resolved? I am still getting the same error.

**Comment by Settiwie** [comment]
> Was this ever resolved? I am still getting the same error.

Nope, because it is a conflict with the processor. Apple chips are just not designed to run rainbow. But the rainbow six siege team will switch to another engine soon, so maybe we will be able to play rainbow with whiskey but I doubt it. The anti-cheat probably detects that it’s a virtual machine and will terminate the process before rainbow even launches.
