### ISSUE TITLE
[Feature]: Update Wine to 9.2

### ISSUE THREAD

**Issue by bolandnick18** [Whisky-App/Whisky#841]
### Is your feature request related to a problem?

I am not sure why this app is using the outdated version of wine 7 and I am wonder if you can please update to wine 9.2. its has address some of the issues compared to wine 7.x

here more info:
#https://gitlab.winehq.org/wine/wine/-/releases/wine-9.2

### Describe the solution you'd like

Please update wine 9.2

### Anything else?

no more comments

### Issue Language

- [X] Yes my issue is written in English

**Comment by JSP100** [comment]
Well, my guess is that Apple uses Wine 7.x to build their Game Porting Toolkit, so as Whisky.  (is that the case?)

**Comment by blackxfiied** [comment]
@JSP100 yeah
so it's not really as simple as just updating

**Comment by Mateus109** [comment]
Didn't the Whisky devs say they wouldn't support Wine 8 or 9 because that would take business away from Crossover?  If you what Wine 8+, buy Crossover.  Think of Whisky as a free version of Crossover, with limited features.

**Comment by bolandnick18** [comment]
crossover software is two pricing for me

**Comment by bmx666** [comment]
> Didn't the Whisky devs say they wouldn't support Wine 8 or 9 because that would take business away from Crossover? If you what Wine 8+, buy Crossover. Think of Whisky as a free version of Crossover, with limited features. Actually, now that Crossover is officially on Wine 9, maybe the Whisky devs will update to Wine 8.

wine 7 is no longer supported by `winetricks`:

> warning: Your version of wine 7.7 is no longer supported upstream. You should upgrade to 8.x

**Comment by d9j** [comment]
this project policy is non compete agreement with crosssover. wellcome to fork the project and update wine dependency . i personally tried to upgrade wine by compelling  wine from source. however i had no success launching games due to unclear crashing errors.

**Comment by IsaacMarovitz** [comment]
It is not enough to simply use Wine from source. CrossOver works because they have many in-house fixes that allow applications like Steam to work out of the box. Unless we develop those kinds of fixes ourselves, updating to Wine 9 would probably break more than it would fix.

**Comment by 100tomer** [comment]
So we should expect to always stay on wine 7.7?

**Comment by hahayupgit** [comment]
> So we should expect to always stay on wine 7.7?

Pretty much

**Comment by d9j** [comment]
lol. i gave up and move to windows laptop. couldnt be happier. free from apple breaking updates bulsh!t and need to pay crossover to get sh!t running
