### ISSUE TITLE
[Bug]:  Whiskey Memory Leak

### ISSUE THREAD

**Issue by devium335** [Whisky-App/Whisky#856]
### Description

Whisky while idling taking up 56 gb

### Steps to reproduce

1. Launch Whisky
2. Wait

### Expected behaviour

Using less memory than that

### Logs

```bash
None
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by GabCoolDude** [comment]
Do this : 

![image](https://github.com/Whisky-App/Whisky/assets/123309403/7278d25b-2ae1-4b48-90c6-54de7cde3e35)
