### ISSUE TITLE
[Bug]: Genshin doesn't start...

### ISSUE THREAD

**Issue by Wazakana** [Whisky-App/Whisky#858]
### Description

I downloaded whisky and installed Genshin impact. Installation was successful and I could start the launcher, but when I click "Start the Game", the launcher disappears and nothing happens. 
I checked the log, but there seems no clue to solve this problem.
Anyone knows how to fix this problem?

### Steps to reproduce

1. Install Whisky
2. Create New Bottle(windows10)
3. Click "Run" and choose Genshin impact  installer, which downloaded from the official website.
5. Install Genshin
6. Run launcher.exe
7. Click "Start the game" button.

### Expected behaviour

I was expecting Genshin impact's window to appear...

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-03-05T13:54:00Z
macOS Version: 14.3.1

Bottle Name: Genshin
Bottle URL: /Users/Wazakana/Library/Containers/com.isaacmarovitz.Whisky/Bottles/4A6F58E9-DB12-4E26-A5F4-4D191E0B6BD3

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Users/Wazakana/Library/Containers/com.isaacmarovitz.Whisky/Bottles/4A6F58E9-DB12-4E26-A5F4-4D191E0B6BD3/drive_c/Program Files/Genshin Impact/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/Wazakana/Library/Containers/com.isaacmarovitz.Whisky/Bottles/4A6F58E9-DB12-4E26-A5F4-4D191E0B6BD3";
}

info:  Apple M2:
info:      Memory Type[2]: Property Flags = 0xb
info:    OpenXR
info:      Memory Type[1]: Property Flags = 0xf
info:      Memory Type[2]: Property Flags = 0xb
warn:  D3D9: VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT -> VK_FORMAT_B4G4R4A4_UNORM_PACK16
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by GuryYu** [comment]
Upgrade system to 14.4 will fix it.

**Comment by Wazakana** [comment]
> Upgrade system to 14.4 will fix it.

Oh! Thank you! It worked!!
But now I have another problem. When I try to login, I can't see the identification puzzle...
Is this related to Whisky?
<img width="1440" alt="スクリーンショット 2024-03-10 6 42 55" src="https://github.com/Whisky-App/Whisky/assets/162332618/360f7150-564c-46fd-9c96-7e5cc0fd5735">

**Comment by nsfxdyj** [comment]
same problem

**Comment by nsfxdyj** [comment]
> > Upgrade system to 14.4 will fix it.
> 
> Oh! Thank you! It worked!! But now I have another problem. When I try to login, I can't see the identification puzzle... Is this related to Whisky? <img alt="スクリーンショット 2024-03-10 6 42 55" width="1440" src="https://private-user-images.githubusercontent.com/162332618/311470293-360f7150-564c-46fd-9c96-7e5cc0fd5735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDk1MTUsIm5iZiI6MTcxMDA0OTIxNSwicGF0aCI6Ii8xNjIzMzI2MTgvMzExNDcwMjkzLTM2MGY3MTUwLTU2NGMtNDZmZC05Yzk2LTdlNWNjMGZkNTczNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2MxMGIyZThiYWI2MmYwMDI1MGVlNDg3ODViMTIyNDE3NThlMTRiMmY5MWFmZTNkYmY2NTg4OTUwZjA4MGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OIrXbN4xtfSWaModTJ2OeGc1IB9JXYbE-Im4zNuXi10">

and genshin cannot close login certification now

**Comment by pilisir** [comment]
Try source-han-sans fonts.

Download and Install fonts for your macOS.
[Language Specific OTFs Japanese (日本語)](https://github.com/adobe-fonts/source-han-sans/releases/download/2.004R/SourceHanSansJ.zip)

Launch Whisky and open Registry Editor, press control + F to search "fontsub", modify both "MS Shell Dlg" and "MS Shell Dlg 2" to "源ノ角ゴシック".

---
Idea from a YouTube video with [same problem](https://youtu.be/0hgZFFKS_1A) in chinese fonts.

**Comment by nsfxdyj** [comment]
my problem solved.thanks
