### ISSUE TITLE
XBOX Elite V2 controller not showing in Wine Control Panel [Bug]: 

### ISSUE THREAD

**Issue by ChinaBackGo** [Whisky-App/Whisky#871]
### Description

A normal xbox controller works fine after connecting to macbook pro M1 and then viewing in the wine control panel -> Game Controllers. I can set override test input, etc. However, after successfully pairing an Xbox Elite V2 controller, I cannot get it to show up in the wine control panel. Steam/Games will not detect the controller either.

### Steps to reproduce

1. Pair Elite Series V2 controller with macbook.
2. Open Whisky/Install a bottle
3. Open Bottle Configuration
4. Open "Open Control Panel"
5. Open "Game Controllers"
6. Observe no controllers listed

### Expected behaviour

Can view and configure connected controller

### Logs

```bash
Whisky Version: 2.2.3
Date: 2024-03-16T18:52:16Z
macOS Version: 14.2.1

Bottle Name: Steam
Bottle URL: /Users/XXXX/Library/Containers/com.isaacmarovitz.Whisky/Bottles/1800CF4B-C288-4484-8094-3CF60E96DBE7

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: reg add HKCU\Control Panel\Desktop -v LogPixels -t REG_DWORD -d 0 -f

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/XXXX/Library/Containers/com.isaacmarovitz.Whisky/Bottles/1800CF4B-C288-4484-8094-3CF60E96DBE7";
}

msync: bootstrapped mach port on wine-228ae44-msync.
msync: up and running.
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
reg: The operation completed successfully
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ChinaBackGo** [comment]
Solved.

1. Go to System Settings ->  Input Monitoring
2. Enable Whisky (will prompt for password)
3. Make sure to power cycle the controller, reconnect via bluetooth
4. restart Whisky
5. Xbox Elite V2 controller now appears in Control Panel/Game Controllers as expected.

Note: This seems like a weird fix.

**Comment by abnerfreitas** [comment]
This bug is back again on new update, and now it doesnt recognizes even with this method
