### ISSUE TITLE
[Bug]:  Cannot start exe without re-selecting the bottle.

### ISSUE THREAD

**Issue by paseri3739** [Whisky-App/Whisky#873]
### Description

When double-clicking to launch the exe, if you click run with a bottle already selected, it will not launch, but if you re-select the same bottle yourself, it will launch.

### Steps to reproduce

1. double click exe in finder
2. click run button with default selected bottle

### Expected behaviour

run with default bottle

### Logs

```bash
None
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Should be resolved as of 2.2.4
