### ISSUE TITLE
[Feature]: Possibility for AVX support, maybe?

### ISSUE THREAD

**Issue by PythonBlue** [Whisky-App/Whisky#877]
### Is your feature request related to a problem?

Several newer programs and games don't work on Apple Silicon due to certain Intel-specific instructions, the most notorious being AVX and AVX2.

### Describe the solution you'd like

Not sure if this is a fix, or even if this is feasible on this team's end, but I discovered a separate GitHub project that claims to make it possible to port AVX instructions relatively trivially to Apple Silicon using NEON. My guess is that the best way to implement would involve rewriting Wine itself a bit, since the AVX errors I've even witnessed for myself seem specific to Wine, as opposed to Whisky or even Crossover. Either way, I feel this is worth at least looking into for those more technically saavy than I am.

### Anything else?

https://github.com/simd-everywhere/simde - The GitHub project I mentioned

### Issue Language

- [X] Yes my issue is written in English

**Comment by duckie** [comment]
GPTK 2.0 added support for AVX2. Why would whisky not do so too ?
