### ISSUE TITLE
[Bug]: Can not create new bottle

### ISSUE THREAD

**Issue by Bobby5291** [Whisky-App/Whisky#893]
### Description

I try creating a new bottle and it does nto create but the bottle folder does. I deleted the bottle URL as I do not want to give my pc name away

### Steps to reproduce

creating a bottle

### Expected behaviour

for the bottle to appear in the ui

### Logs

```bash
Whisky Version: 2.2.4
Date: 2024-04-01T16:26:05Z
macOS Version: 14.2.1

Bottle Name: steam
Bottle URL: 

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: winecfg -v win10

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = 
}
```

### What version of Whisky are you using?

2.2.4

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Bobby5291** [comment]
> Does your macOS username contain any special characters like `.`?

no just containes personal info

**Comment by Bobby5291** [comment]
fixed after i reinstalled gptk

**Comment by Nikodemek131** [comment]
how do you reinstall gptk give the download link
or the manual download through the terminal
