### ISSUE TITLE
[Bug]: Keeps asking to update to GPTK 1.4.0+0

### ISSUE THREAD

**Issue by avidrissman** [Whisky-App/Whisky#896]
### Description

When I launch Whisky, I get a dialog:

> New Version of GPTK Available
>
> You are running GPTK 1.3.0+0, but 1.4.0+0 is available. Would you like to update?

So I click [Update]. It updates and installs.

As soon as I quit and relaunch Whisky I get the dialog again. And again. It’s always asking me to update to 1.4.0+0.

### Steps to reproduce

1. Launch Whisky
2. Install GPTK.
3. Quit and relaunch Whisky.

### Expected behaviour

It should update to 1.4.0+0, and then stop asking me to install it.

### Logs

```bash
not applicable; this is the Whisky app itself, not a bottle.
```

### What version of Whisky are you using?

2.2.4

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The issue is happening on my machine, too. A temporary solution would be to manually edit the following file:

Find: `~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/GPTKVersion.plist`
Change
```
<key>minor</key>
<integer>3</integer>
```

to 

```
<key>minor</key>
<integer>4</integer>
```
