### ISSUE TITLE
[Bug]: Joypad no more working with version 2.3.0

### ISSUE THREAD

**Issue by avv3lenato** [Whisky-App/Whisky#912]
### Description

Every joypad I tested (Stadia, PS4, Xbox) Bluetooth or wired, totally stopped working as I updated to 2.3.0.

### Steps to reproduce

Updated to 2.3.0 and installed the new WhiskyWine. Everything work fine but no more joypad support.
Downgraded to 2.2.4 and still no joypad support; had to unistall and reinstall GPTK with this version and joypad are back!

### Expected behaviour

Something is wrong with the new WhiskyWine package.

### Logs

```bash
Whisky Version: 2.3.0
Date: 2024-04-09T07:35:10Z
macOS Version: 14.4.1

Bottle Name: Tomb Raider I-III Remastered
Bottle URL: /Volumes/2TB SSD/Whisky/FEBDF8AB-1CB3-4B03-A104-F904A247095D

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Volumes/2TB SSD/Whisky/FEBDF8AB-1CB3-4B03-A104-F904A247095D/drive_c/GOG Games/Tomb Raider I-III Remastered/tomb123.exe -novsync

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Volumes/2TB SSD/Whisky/FEBDF8AB-1CB3-4B03-A104-F904A247095D";
}

msync: bootstrapped mach port on wine-1f3d-msync.
msync: up and running.
0100:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
wine: configuration in L"/Volumes/2TB SSD/Whisky/FEBDF8AB-1CB3-4B03-A104-F904A247095D" has been updated.
```

### What version of Whisky are you using?

2.3.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Korolev-Oleg** [comment]
Same issue
Only vibration works in steam gamepad settings

**Comment by Korolev-Oleg** [comment]
bottle reinstalling fix it

**Comment by snougo** [comment]
same issue with 2.3.0

**Comment by IsaacMarovitz** [comment]
Bug in WhiskyWine updater might make it not prompt you but you can manually uninstall and reinstall to get the fix.
