### ISSUE TITLE
[Question] Should bottles be recreated after whisky upgraded?

### ISSUE THREAD

**Issue by lazywhite** [Whisky-App/Whisky#913]
whisky 2.3.0 released with new wine version, should bottles be recreated?

**Comment by IsaacMarovitz** [comment]
Most of the time, it shouldn't be necessary. If you're running into problems, it can be a useful debugging step. If you install your Steam library into an "external" library, you can keep your games decoupled from your bottles, which makes recreating bottles much less painful.
