### ISSUE TITLE
[Bug]: PS5 controller is not working after upgrade to 2.3.0

### ISSUE THREAD

**Issue by lazywhite** [Whisky-App/Whisky#914]
### Description

PS5 controller works very well with 2.2.4, but after upgrade to 2.3.0, all games can't recognize it

### Steps to reproduce

PS5 controller with bluetooth connection

### Expected behaviour

PS5 controller

### Logs

```bash
no
```

### What version of Whisky are you using?

2.3.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Please update to Whisky 2.3.1 and WhiskyWine 2.0.0+1

**Comment by mbac** [comment]
Hi,

I'm on 2.3.2 with the latest WhiskyWine at the time of this writing—DS5 controller is not recognized by any app when set up as "Connected" in Whisky's controller config; when I switch the DS5 to "Connected (xinput device)", Steam sees it as an Xbox controller but it still doesn't work at all in Elden Ring (I don't have another game to try).

**Comment by lazywhite** [comment]
> Hi,
> 
> I'm on 2.3.2 with the latest WhiskyWine at the time of this writing—DS5 controller is not recognized by any app when set up as "Connected" in Whisky's controller config; when I switch the DS5 to "Connected (xinput device)", Steam sees it as an Xbox controller but it still doesn't work at all in Elden Ring (I don't have another game to try).

DS5 is working perfectly with latest whisky 2.3.2, maybe is a problem of your mac version? I am using 14.4.1
