### ISSUE TITLE
[Bug]: always has high CPU  usage

### ISSUE THREAD

**Issue by makaspacex** [Whisky-App/Whisky#917]
### Description

I did nothing except start a winbox, and then whiskey kept occupying a high amount of CPU.

### Steps to reproduce

download winbox from https://mikrotik.com/download, then start it in win10 vm.

### Expected behaviour

<img width="274" alt="image" src="https://github.com/Whisky-App/Whisky/assets/16874796/583e6e9d-635e-44ab-a3f3-5b52967f3db5">

### Logs

```bash
Whisky Version: 2.3.1
Date: 2024-04-10T07:07:29Z
macOS Version: 14.4.1

Bottle Name: win10
Bottle URL: /Users/makaflow/Library/Containers/com.isaacmarovitz.Whisky/Bottles/B1DE9813-1F23-40F7-944A-926772A01EAE

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: esync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/makaflow/Library/Containers/com.isaacmarovitz.Whisky/Bottles/B1DE9813-1F23-40F7-944A-926772A01EAE/drive_c/Program Files/winbox64.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEPREFIX = "/Users/makaflow/Library/Containers/com.isaacmarovitz.Whisky/Bottles/B1DE9813-1F23-40F7-944A-926772A01EAE";
}

esync: up and running.
```

### What version of Whisky are you using?

2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by andryunin** [comment]
I can confirm that. Actually, it occurs with any app I attempt to run.

Here are the steps to reproduce:

1. Create an empty bottle.
2. Launch notepad.exe from the Windows directory.

Result: Whisky process consumes 100% of the CPU."

Whisky 2.2.3 (36), macOS Sonoma 14.4.1.

**Comment by makaspacex** [comment]
> I can confirm that. Actually, it occurs with any app I attempt to run.
> 
> Here are the steps to reproduce:
> 
> 1. Create an empty bottle.
> 2. Launch notepad.exe from the Windows directory.
> 
> Result: Whisky process consumes 100% of the CPU."
> 
> Whisky 2.2.3 (36), macOS Sonoma 14.4.1.
> 
> **UPD:** when I close app, CPU usage drops back to normal close to zero values

Yes, but I don't know if this is a feature or a bug.

**Comment by killsecurly** [comment]
> Yes, but I don't know if this is a feature or a bug.

Probably it's required. Since Wine and GPTK is changing Windows instruction sets to MacOS equivalents, that might make CPU usage high.

What CPU do you have for your Mac? I am on the latest version of Whiskey, and uses ~40% CPU on PC Building Sim 2. (For reference, I play on a Macbook Air M1)

**Comment by IsaacMarovitz** [comment]
Wine is expensive.

**Comment by andryunin** [comment]
@IsaacMarovitz Just discovered: when I close Whisky window (notepad.exe is still running), CPU usage drops to normal. So, I think its a bug.

**Comment by IsaacMarovitz** [comment]
I think its more an issue of how Activity Monitor is attributing the CPU usage to child processes.

**Comment by tdrkDev** [comment]
+1 here. CPU temperature drops almost instantly from 103℃ to 60℃ after closing Whisky window. Only Steam window is being open after that. Apple M1, 14.4.1

**Comment by killsecurly** [comment]
> @IsaacMarovitz +1 here. CPU temperature drops almost instantly from 103℃ to 60℃ after closing Whisky window. Only Steam window is being open after that. Apple M1, 14.4.1

I only hit 60c on Whisky with BeamNG, maybe it's only you?

**Comment by victorpavlenko** [comment]
Same with 2.3.3 
200% CPU usage M3 Pro

**Comment by hahayupgit** [comment]
to everyone who this has been affecting, could you check if the overall CPU usage goes down as whisky is closed? the whisky frontend shouldn't be contributing that much to cpu usage, and i suspect this is likely an activity reporting error like isaac said

that being said i'll test this myself as well

**Comment by killsecurly** [comment]
> to everyone who this has been affecting, could you check if the overall CPU usage goes down as whisky is closed? the whisky frontend shouldn't be contributing that much to cpu usage, and i suspect this is likely an activity reporting error like isaac said
> 
> that being said i'll test this myself as well

5 to 15% CPU at desktop.

**Comment by killsecurly** [comment]
> @hahayupgit <img alt="Screenshot at Sep 27 19-03-33" width="645" src="https://private-user-images.githubusercontent.com/5157416/371620167-1dba02b2-229d-4447-8bbf-5be481452c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDgwMDIsIm5iZiI6MTcyNzgwNzcwMiwicGF0aCI6Ii81MTU3NDE2LzM3MTYyMDE2Ny0xZGJhMDJiMi0yMjlkLTQ0NDctOGJiZi01YmU0ODE0NTJjODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDFUMTgzNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM3NWY0ZGFlN2U2YWZkODZlZWJmZTg3ZDg3YzIzMGYwZThiMTY2ODA0ZTNhZjEzNjdkMjVjNTkyYzNiMzFjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qmSGBuU3lsUiStU13GfnLmKOyXCubwHqKaiXlkolhh4">
> 
> when I close Whiski, for game, nothing change, same 70, but whiski itself, as you can see eat my 100%

I've seen Whisky translating X86_64 to ARM, not the process wine64_preloader.
