### ISSUE TITLE
[Feature]: Winetricks doesn't show anything.

### ISSUE THREAD

**Issue by jjoon0928** [Whisky-App/Whisky#918]
### Is your feature request related to a problem?

Hi. I downloaded Whisky and made a bottle to use Window Steam.
I am a Korean so I have to download fonts through Winetricks but it doesn't show anything
<img width="901" alt="스크린샷 2024-04-10 오후 8 23 31" src="https://github.com/Whisky-App/Whisky/assets/57268828/6e6b40de-96d7-4e1f-8575-d9295db1f1fd">

### Describe the solution you'd like

.

### Anything else?

.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Can you check if this file exists? `~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/verbs.txt`

**Comment by jjoon0928** [comment]
> Can you check if this file exists? `~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/verbs.txt`
There isn't the file you mentioned. Where can I download it?

**Comment by IsaacMarovitz** [comment]
> There isn't the file you mentioned. Where can I download it?

I recommend going to Setup, and uninstalling and reinstalling WhiskyWine
