### ISSUE TITLE
[Bug]: AntiCheat Easy in game Hell Let Loose

### ISSUE THREAD

**Issue by CodersMateusz** [Whisky-App/Whisky#921]
### Description

I'm trying to play game Hell Let Loose via Whisky on MacBook pro (M2 chip).
Steam and game installed correctly, but when i try to  enter server after sometime it shows bug that anticheat blocked me and kicked me back to main menu.
Is there any way to fix the issue?

### Steps to reproduce

1. Install Hell Let Loose Game.
2. Enter the game.
3. Try to join server and start the game.

### Expected behaviour

Possibility to join server.

### Logs

```bash
Whisky Version: 2.2.4
Date: 2024-04-11T18:37:24Z
macOS Version: 14.4.0

Bottle Name: Steam
Bottle URL: /Users/mateuszskiera/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DB60C415-E95C-40D5-AC41-BFFB34D664FB

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: winecfg -v win10

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/mateuszskiera/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DB60C415-E95C-40D5-AC41-BFFB34D664FB";
}

msync: bootstrapped mach port on wine-18688d3-msync.
msync: up and running.
00dc:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
wine: configuration in L"/Users/mateuszskiera/Library/Containers/com.isaacmarovitz.Whisky/Bottles/DB60C415-E95C-40D5-AC41-BFFB34D664FB" has been updated.
```

### What version of Whisky are you using?

2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by hahayupgit** [comment]
Unfortunately, this is not something Whisky developers can fix. This is up to the Easy AntiCheat and Hell Let Loose developers.
