### ISSUE TITLE
[Feature]: Allow users to use the app without having WhiskyWine installed

### ISSUE THREAD

**Issue by ultratiem** [Whisky-App/Whisky#937]
### Is your feature request related to a problem?

The problem surfaces when you launch Whisky and Uninstall WhiskyWine. The only option is quit or next. The former shuts down Whisky and the latter simply reinstalls it. On next subsequent launch, the modal window is forced onto the user making it impossible to even navigate Whisky without the backend.

![Screenshot 2024-04-15 at 6 56 30 PM](https://github.com/Whisky-App/Whisky/assets/2991193/eeecf20e-6eb1-4166-a3e5-0529cb7c4f4e)

### Describe the solution you'd like

Two solutions:

Don't force the modal window on relaunch. The user can navigate to the Setup menu option and install it manually.

Change the quit button to cancel. This way a user can dismiss the modal window and still make changes to the WINE environment and other house cleaning.

### Anything else?

I recognize this may be really edgy-casey, but it's just good UX form to quit your app for simply missing a dependency. I understand GPTK important to actually run Windows apps, but has little effect on the UI.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
WhiskyWine is essential to using Whisky, including several bottle configuration options. Allowing the use of the app without this central dependency would just create opportunities for confusion; locking you out of the UI is very much by design.

**Comment by ultratiem** [comment]
"WhiskyWine is essential to using Whisky, including several bottle configuration options." I didn't know it was vital for some configs. Given that, why even give the option to uninstall it? Or even have the user expressly install it for that matter?

Seems like the best UX course would be to install it automatically and instead of listing the uninstall option in the modal window of Setup, list the option to update.

![update](https://github.com/Whisky-App/Whisky/assets/2991193/76957bda-fa4f-4b93-9352-f8435cd71f75)
