### ISSUE TITLE
[Bug]: non-linear mouse input on some games

### ISSUE THREAD

**Issue by jeanravin** [Whisky-App/Whisky#939]
### Description

I have some mouse acceleration issues on some of my games. Of course I've checked that no mouse smoothing is enabled. And played them outside macos without issue.

Buggy :
- quake [remastered] (game and menu)
- quake 2 [remastered] (game and menu)
- dusk HD (only in game)

Working : 
- deadlink
- wrath
- sprawl
- control
- forgive me father 2

### Steps to reproduce

- turning off macos system mouse acceleration
- launching a game (mostly on Steam)

### Expected behaviour

linear (non-accelerated) mouse movement

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-04-16T23:29:50Z
macOS Version: 14.4.1

Bottle Name: steam
Bottle URL: /Volumes/Amusement/bouteilles whisky/9812EA83-321B-46AD-AF0F-812EC542F7D9

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

Arguments: start /unix /Volumes/Amusement/bouteilles whisky/9812EA83-321B-46AD-AF0F-812EC542F7D9/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Volumes/Amusement/bouteilles whisky/9812EA83-321B-46AD-AF0F-812EC542F7D9";
}

msync: bootstrapped mach port on wine-ae509-msync.
msync: up and running.
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
2024-04-17 01:30:02.798 wine64-preloader[6648:469836] *** WARNING: Method convertPointFromBase: in class NSView is deprecated on 10.7 and later. It should not be used in new applications. 
047c:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Apr 2024 17:54:00 UTC"
047c:err:wininet:HTTP_ParseDate unexpected date format L"Sun, 14 Apr 2024 17:54:00 UTC"
```

### What version of Whisky are you using?

2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by hahayupgit** [comment]
Mouse acceleration is *very* janky on macOS. The solution to it that I've used is to keep all macOS settings at a default and to use [linearmouse](https://linearmouse.app/). It's a great, robust, 100% free app that can disable acceleration and allow the mouse to actually move fast when acceleration is disabled, and provide many more tweaks at a per-device level (if you have multiple mice or use trackpads and mice).

Unfortunately if you aren't up for using that I won't be of much help, but if you do end up giving it a try let me know how it goes!

**Comment by jeanravin** [comment]
Like I said, I've already disabled mouse acceleration in System settings (this is apparently new to Sonoma), does this differ from that ? I guess not.

And I have no acceleration issues on the **working** list…
