### ISSUE TITLE
[Bug]: Fallout 4 does not start

### ISSUE THREAD

**Issue by Polyfish0** [Whisky-App/Whisky#940]
### Description

When I want to start Fallout 4, only the Launcher works. I can change any setting inside the Launcher. But when I click "Play" I just get a short black screen and then it crashes. It is not important if I start the game over Steam or directly.

That are my DLC's
<img width="872" alt="image" src="https://github.com/Whisky-App/Whisky/assets/38872139/eed82648-faa2-454c-8197-751a285ceeda">

### Steps to reproduce

1. Download Fallout 4 over Steam
2. Start Fallout 4
3. Go into the Settings and set the aspect ratio to 16:10 and click on Ultra (Preset)
4. Click Save
5. Click Play

### Expected behaviour

The game starts

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-04-17T10:26:35Z
macOS Version: 14.4.1

Bottle Name: Steam
Bottle URL: /Users/mika/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5D502705-0414-4A6E-B328-AC0A8E177A70

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: full

Arguments: start /unix /Users/mika/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5D502705-0414-4A6E-B328-AC0A8E177A70/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 4/Fallout4.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "DXVK_HUD" = full;
    "GST_DEBUG" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/mika/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5D502705-0414-4A6E-B328-AC0A8E177A70";
}
```

### What version of Whisky are you using?

2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Polyfish0** [comment]
I have a MacBook Pro (M2 Pro)

When I remove the DLLOVERRIDES for Steam and change my Windows version in wine to 8 I get this log

Whisky Version: 2.3.2
Date: 2024-04-17T10:35:10Z
macOS Version: 14.4.1

Bottle Name: Steam
Bottle URL: /Users/mika/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5D502705-0414-4A6E-B328-AC0A8E177A70

Wine Version: 7.7.0
Windows Version: win8
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: full

Arguments: start /unix /Users/mika/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5D502705-0414-4A6E-B328-AC0A8E177A70/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 4/Fallout4.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "DXVK_HUD" = full;
    "GST_DEBUG" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/mika/Library/Containers/com.isaacmarovitz.Whisky/Bottles/5D502705-0414-4A6E-B328-AC0A8E177A70";
}

msync: bootstrapped mach port on wine-e7a1f5-msync.
msync: up and running.
0188:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
info:      Size: 16384 MiB
info:  Built-in extension providers:
info:      Flags: 0x1
info:    Device name:     : Apple M2 Pro
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    tessellationShader                     : 1
info:    shaderCullDistance                     : 0
info:    shaderFloat64                          : 0
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:  DXVK: v1.10.3-20230507-async (macOS)
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_KHR_swapchain
info:    memoryPriority                         : 0
0638:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

**Comment by IsaacMarovitz** [comment]
Fallout 4 is working as of the Next Gen update: https://docs.getwhisky.app/game-support/fallout-4.html
