### ISSUE TITLE
Downloading WhiskeyWine

### ISSUE THREAD

**Issue by yiminglaa** [Whisky-App/Whisky#943]
### Description

So i recently started using whiskey and it was working fine until a couple days ago when I opened it and it suddenly required me to download WhiskeyWine as part of the dependencies setup. I tried downloading it but halfway through the download just stopped and wouldn't keep downloading. I've tried multiple times and it still didn't work. 

### Steps to reproduce

All i did was open the whiskey app and a popup would appear saying dependencies setup and that WhiskeyWine was not installed. 

### Expected behaviour

I have no idea why the app suddenly required me to download WhiskeyWine as before I could use whiskey without it. 

### Logs

```bash
Whisky Version: 2.2.4
Date: 2024-04-14T09:41:51Z
macOS Version: 14.4.1

Bottle Name: Stem
Bottle URL: /Users/yiminghe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/D5A11B0A-A068-4BFC-8AB4-EACB0D11C41B

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: winecfg -v win10

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/yiminghe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/D5A11B0A-A068-4BFC-8AB4-EACB0D11C41B";
}

msync: bootstrapped mach port on wine-2a4af43-msync.
msync: up and running.
00dc:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
wine: configuration in L"/Users/yiminghe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/D5A11B0A-A068-4BFC-8AB4-EACB0D11C41B" has been updated.
```

### What version of Whisky are you using?

<2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ana-fox** [comment]
have the same issue

**Comment by air-hedgehog** [comment]
Disabling Apple private relay might work.
