### ISSUE TITLE
[Bug]: Deleted Win64 by accident and something else I forgot

### ISSUE THREAD

**Issue by imfinnacook2134** [Whisky-App/Whisky#948]
### Description

Basically I had everything working perfectly, but steam would not close. Every time I closed it, it would pop up around 20 seconds later. Eventually, I just deleted win64 so it would stop launching and decided that I wouldn't need this application anymore so i deleted whisky. I then decided I want to redownload whisky. When I downloaded it, it didn't show me that I need to download gptk or rosetta and just brought me straight to the create bottle page. The bottle I had saved as steam was already there but I could not launch it because I do not have the "win64" file. I then deleted the bottle and tried to create another one, but when I created it, it instantly closes itself and brings me back to "create new bottle".

### Steps to reproduce

Deleted win 64 and something else that runs it

### Expected behaviour

I expect that it works

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-04-20T17:00:54Z
macOS Version: 14.3.0

Bottle Name: Steam
Bottle URL: /Users/sigma/Library/Containers/com.isaacmarovitz.Whisky/Bottles/797678AF-CF92-4976-8AAC-79B8DE8A380E

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: winecfg -v win10

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/sigma/Library/Containers/com.isaacmarovitz.Whisky/Bottles/797678AF-CF92-4976-8AAC-79B8DE8A380E";
}

msync: bootstrapped mach port on wine-5506e78-msync.
msync: up and running.
00dc:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
00dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
wine: configuration in L"/Users/sigma/Library/Containers/com.isaacmarovitz.Whisky/Bottles/797678AF-CF92-4976-8AAC-79B8DE8A380E" has been updated.
```

### What version of Whisky are you using?

2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
User error not a Whisky bug. User was helped on Discord.

**Comment by T0KINA** [comment]
Umm where is the discord and where is the problem on it??

**Comment by Anuj-cmd108** [comment]
I have the same issue ,how can I rectify it

**Comment by Colton131214** [comment]
> I have the same issue ,how can I rectify it

Did you ever find a solution?

**Comment by Anuj-cmd108** [comment]
> > I have the same issue ,how can I rectify it
> 
> Did you ever find a solution?

You can re install it by clicking the apple logo after opening whisky
