### ISSUE TITLE
[Bug]: Warcraft Reforged black screen / stuck on initial loading screen

### ISSUE THREAD

**Issue by DroofZA** [Whisky-App/Whisky#95]
### Description

I get stuck at the following screen when running Warcraft Reforged via Battle.net 
<img width="528" alt="Screenshot 2023-06-13 at 10 03 09 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/20288750/bfe6e7e0-a6f1-4dee-816a-bea3b516f0e3">

### Steps to reproduce

1. Install Whisky.dmg
2. Create bottle
3. Install BNET
4. Install Warcraft Reforged via BNET
5. Run War3 -> Freeze

NOTE: _resolved the black screen with -`windowmode windowed` BNET argument, `seenintromovie=1` in Documents/Warcraft/War3Preferences.txt file, but it will not progress past the "Lion Gate" screen
<img width="494" alt="Screenshot 2023-06-15 at 6 33 07 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/20288750/ed38aa27-7d80-4543-b7ad-381f6711e1b8">

### Expected behaviour

Game should run

### What version of Whisky are you using?

latest

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by DroofZA** [comment]
resolved the black screen with `-windowmode windowed` argument, but it will not progress past the "Lion Gate" screen, possible network issue.

**Comment by IsaacMarovitz** [comment]
Stale
