### ISSUE TITLE
[Bug]:Battleye Service Error  

### ISSUE THREAD

**Issue by mohdizhan7** [Whisky-App/Whisky#962]
### Description

While trying to open PUBG Battlegrounds, i am getting the below error 

<img width="602" alt="Note to self - 2024-04-29 12_37_23" src="https://github.com/Whisky-App/Whisky/assets/58340944/34c0871e-e531-4a88-9ce9-f6f22ce06418">

### Steps to reproduce

Launch PUBG from Steam

### Expected behaviour

The game should launch 

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-04-29T07:10:26Z
macOS Version: 14.5.0

Bottle Name: Steam
Bottle URL: /Users/mohdizhan/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2CC48118-8F8A-4476-9308-5E66CB95F703

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/mohdizhan/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2CC48118-8F8A-4476-9308-5E66CB95F703/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/mohdizhan/Library/Containers/com.isaacmarovitz.Whisky/Bottles/2CC48118-8F8A-4476-9308-5E66CB95F703";
}
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Battleye and other kernel-level anti-cheats do not work in Wine.
