### ISSUE TITLE
[Feature]: Xbox App compatibility

### ISSUE THREAD

**Issue by mohdizhan7** [Whisky-App/Whisky#963]
### Is your feature request related to a problem?

Would be helpful if the system was capable of running Xbox App

### Describe the solution you'd like

WIth the XBox App users will be able to also ulitize thier gamepass features while others will benifit from the low cost for playing the AAA titles instead of purchasing on steam 

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Wine does not support UWP apps.
