### ISSUE TITLE
[Bug]: Whisky does not run anything

### ISSUE THREAD

**Issue by Shuyinsama** [Whisky-App/Whisky#978]
### Description

Whisky won't run any .exe file (in this case steam but I tries other ones too). The app just shows a loading spinner next to run and then nothing.

I've given Whisky Full disk access. I tried a new user.

I've installed Whisky using Homebrew and in the new user just from the website.

### Steps to reproduce

1. Download Whisky
2. Open Whisky
3. Create Bottle (Windows 10)
4. Add SteamSetup.exe to the c drive
5. Click "Run"
6. Open SteamSetup.exe
7. Nothing

### Expected behaviour

Steam setup to start

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-05-10T14:56:25Z
macOS Version: 14.4.1

Bottle Name: Steam
Bottle URL: /Users/patrick/Library/Containers/com.isaacmarovitz.Whisky/Bottles/576338DE-E042-4E36-8D79-DFB2CE697A1A

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/patrick/Library/Containers/com.isaacmarovitz.Whisky/Bottles/576338DE-E042-4E36-8D79-DFB2CE697A1A/drive_c/SteamSetup.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/patrick/Library/Containers/com.isaacmarovitz.Whisky/Bottles/576338DE-E042-4E36-8D79-DFB2CE697A1A";
}

msync: bootstrapped mach port on wine-ba80a7-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I notice that you're running `SteamSetup.exe` from the root of `drive_c`. Can you try starting it from a normal macOS folder like `~/Downloads`

**Comment by Shuyinsama** [comment]
It seems this was a firewall and Bitdefender issue. I had previously allowed whisky and was under the impression it was turned off. It seems like it does some silent stuff in the background.

Apologies  for the issue! It has been resolved!
