### ISSUE TITLE
[Feature]: Use updated CrossOver

### ISSUE THREAD

**Issue by 101arrowz** [Whisky-App/Whisky#981]
### Is your feature request related to a problem?

Newer versions of CrossOver have various bugfixes for popular software and support D3DMetal through custom hooks rather than Apple's patches to the original CrossOver. It should not be too difficult to use a build of a newer version of CrossOver within Whisky in order to take advantage of the various bugfixes that have been added. Additionally, you'd be able to use Wine 9.0's WoW64 integration rather than CodeWeavers' custom LLVM patch to support 32-bit binaries, and even support macOS Intel by purely using DXVK.

### Describe the solution you'd like

You could use a similar technique to build Whisky Wine as in [CXBuilder](https://github.com/101arrowz/cxbuilder), or just use that script directly.

### Anything else?

From my own (not very scientific) testing, the Wine from CrossOver 24 with D3DMetal performs upwards of 20% better in games than Whisky for the admittedly few titles I tested; this might be due to the improved D3DMetal integration if I had to guess?

If Whisky is meant to only use the Game Porting Toolkit, or if there's some objection to using the newest version of CrossOver, then I suppose this issue isn't applicable.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Whisky is not CrossOver; we use our own fork of Wine that, yes, is initially derived from CrossOver's version of Wine. Just repacking CrossOver's Wine would be detrimental to their business model and, therefore, detrimental to the Mac gaming community as a whole.

**Comment by 101arrowz** [comment]
I agree that it's probably a bad idea to undermine CrossOver's business model, but as you recognize, this project already does so to a large extent: the only difference is how up-to-date the CrossOver binaries being used are. I understand that it's best to keep at least some differentiation though.

CrossOver's business model seems to depend solely on its users' lack of technical knowledge to build their open source releases from source. Such is the way of the GPL, I suppose.

**Comment by CamilleScholtz** [comment]
I mean doesn't crossover in turn build upon wine, which has an explicitly FOSS license, namely LGPL? Is this truely some moral argument or is there some monetary incentive going on here?
