### ISSUE TITLE
[Bug]: Whisky asks me to update to 2.2.0+0 when it thinks it's at 2.1.3+1 but about window says it's 2.3.2 ?!

### ISSUE THREAD

**Issue by that-ben** [Whisky-App/Whisky#994]
### Description

Auto-update popup today shows:
<img width="264" alt="Screenshot 2024-05-21 at 11 45 29 AM" src="https://github.com/Whisky-App/Whisky/assets/13210399/6ef4bda5-4b15-4648-83ff-efff57f1d02b">

About window today shows:
<img width="288" alt="Screenshot 2024-05-21 at 11 45 40 AM" src="https://github.com/Whisky-App/Whisky/assets/13210399/fb5bfbe3-4268-43ea-8847-a5761b7a8428">

GitHub today shows:
<img width="1069" alt="Screenshot 2024-05-21 at 11 47 42 AM" src="https://github.com/Whisky-App/Whisky/assets/13210399/216e311b-0f8c-4942-a4ca-ee1a51313912">

WTF?

### Steps to reproduce

To reproduce, launch Whisky today.

### Expected behaviour

There hasn't been an update over a month, so expected behavior should be: nothing.

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-05-17T14:50:20Z
macOS Version: 14.4.1

Bottle Name: W10
Bottle URL: /Users/ben/Library/Containers/com.isaacmarovitz.Whisky/Bottles/64C69A8D-8E64-4D2F-A9CE-A96B4530B455

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: none

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/ben/Library/Containers/com.isaacmarovitz.Whisky/Bottles/64C69A8D-8E64-4D2F-A9CE-A96B4530B455/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "GST_DEBUG" = 1;
    "LC_ALL" = "en_US";
    WINEDEBUG = "fixme-all";
    WINEPREFIX = "/Users/ben/Library/Containers/com.isaacmarovitz.Whisky/Bottles/64C69A8D-8E64-4D2F-A9CE-A96B4530B455";
}

wineserver: using server-side synchronization.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Whisky*Wine* is a separate and separately updated component of Whisky.

**Comment by that-ben** [comment]
Oh, wow, I didn't even notice that in my own screenshots! Thanks for pointing that out!
